### ISSUE TITLE
CMTCONFIG and AnalysisBase_PLATFORM wrong variables for x86_64-centos7-gcc62-opt

### ISSUE THREAD

**Issue by matthewfeickert** [UCATLAS/xAODAnaHelpers#1008]
I have a pretty minor bug. I'm trying to run my install script (which [follows the docs](http://xaodanahelpers.readthedocs.io/en/master/Installing.html))
```bash
# baseDir is set up here, but isn't relevant
mkdir src run build
cd src
git clone https://github.com/UCATLAS/xAODAnaHelpers
git clone ssh://git@gitlab.cern.ch:7999/johnda/StudyTrigTracks.git
asetup AnalysisBase,21.2.0,here
cd ../build
cmake ../src
make > xAH_CMake_out.txt 2>&1
echo "Build has finished at "$(tail -n 1 ${baseDir}/build/xAH_CMake_out.txt | sed 's/].*$/]/')" complete"
cd ..
source build/${CMTCONFIG}/setup.sh
```
on my local [Tier-3 "running on a RHEL7 compatible OS"](http://www.smu.edu/Academics/CSC/Documentation) (platform `x86_64-centos7-gcc62-opt`) --- [HTCondor isn't available on LXPLUS yet with a Rel21](https://github.com/UCATLAS/xAODAnaHelpers/issues/724#issuecomment-324707894) version of `xAH_run`, so I want to try with SLURM at my Tier-3.

However, it seems that here `${CMTCONFIG}` and `${AnalysisBase_PLATFORM}` don't get the correct variable which represents the architecture of the system. They get `x86_64-slc6-gcc62-opt` instead of `x86_64-centos7-gcc62-opt`.

This isn't that big of a deal (I know what the platform should be) but it means that I can't just run my setup environment scrip that uses `asetup --restore` to resetup the environment I need (and I'm trying to write something that will be used by more than just me).

I'm having trouble finding where `${CMTCONFIG}` is actually getting set along the way with CMake. Can someone point me to where that is so I can poke at it, or tell me why the platform isn't getting picked up properly?

**Comment by kratsg** [comment]
Oh, this is definitely an interesting bug. Can you run something like this for me `printenv | grep "x86_64-centos7-gcc62-opt"` to see which environment variable might contain it?

You will need to report this bug to:
- hn-atlas-PATHelp
- hn-atlas-offlineSWHelp
- Asoka De Silva, Attila Krasz.

**Comment by matthewfeickert** [comment]
@kratsg 

```bash
$ printenv | grep "x86_64-centos7-gcc62-opt"
# returns no results
$ printenv | grep "centos7"
BINARY_TAG=x86_64-centos7-gcc49-opt
$ grep -r "BINARY_TAG" .
./src/.asetup.save:BINARY_TAG = x86_64-centos7-gcc49-opt
```

Which is what I assume(?) corresponds to "platform name" during the `cmake ../src` step:
```bash
### cmake ../src
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/sw/lcg/releases/gcc/6.2.0/x86_64-slc6/bin/gcc
-- Check for working C compiler: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/sw/lcg/releases/gcc/6.2.0/x86_64-slc6/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/sw/lcg/releases/gcc/6.2.0/x86_64-slc6/bin/g++
-- Check for working CXX compiler: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/sw/lcg/releases/gcc/6.2.0/x86_64-slc6/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found AnalysisBase: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.0/InstallArea/x86_64-slc6-gcc62-opt (version: 21.2.0)
-- Found AnalysisBaseExternals: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.0/InstallArea/x86_64-slc6-gcc62-opt (version: 21.2.0)
-- Setting ATLAS specific build flags
-- checker_gccplugins library not found
-- Package(s) in AnalysisBaseExternals: 12
-- Using the LCG modules without setting up a release
-- Package(s) in AnalysisBase: 136
-- Configuring ATLAS project with name "WorkDir" and version "21.2.0"
-- Using build type: RelWithDebInfo
-- Using platform name: x86_64-centos7-gcc62-opt
-- Unit tests will be built by default
-- Found 2 package(s)
-- Using the LCG modules without setting up a release
-- Considering package 1 / 2
-- No package filtering rules read
-- Configuring the build of package: StudyTrigTracks
-- Found ROOT: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.0/InstallArea/x86_64-slc6-gcc62-opt/include (found version "6.08/06") 
-- Found ROOT: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.0/InstallArea/x86_64-slc6-gcc62-opt/include (found version "6.08/06") 
-- No package filtering rules read
-- Configuring the build of package: xAODAnaHelpers
-- Found ROOT: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.0/InstallArea/x86_64-slc6-gcc62-opt/include (found version "6.08/06") 
-- Found ROOT: /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.0/InstallArea/x86_64-slc6-gcc62-opt/include (found version "6.08/06") 
-- Number of packages configured: 2
-- Using the LCG modules without setting up a release
-- Including the packages from project AnalysisBase - 21.2.0...
-- Including the packages from project AnalysisBaseExternals - 21.2.0...
-- Using the LCG modules without setting up a release
-- Generated file: /users/mfeickert/testarea/test-2017-08-24/build/x86_64-centos7-gcc62-opt/packages.txt
-- Generated file: /users/mfeickert/testarea/test-2017-08-24/build/x86_64-centos7-gcc62-opt/compilers.txt
-- Generated file: /users/mfeickert/testarea/test-2017-08-24/build/x86_64-centos7-gcc62-opt/ReleaseData
-- Generating external environment configuration
-- Using the LCG modules without setting up a release
-- Writing runtime environment to file: /users/mfeickert/testarea/test-2017-08-24/build/x86_64-centos7-gcc62-opt/env_setup.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /users/mfeickert/testarea/test-2017-08-24/build
```


@kratsg In terms of reporting the bug, I should just reference this Issue and mention that `${CMTCONFIG}` isn't getting set correctly?

**Comment by kratsg** [comment]
Hrmm, yeah. I think so. My guess is they'll respond that "CMTCONFIG" shouldn't be relied on anymore (it's on its way out) but it still seems like something else depends on it. I've been told to rely on `AnalysisBase_PLATFORM` for example (and we do rely on AnalysisBase and not AnalysisTop so this is a safe suggestion).

**Comment by matthewfeickert** [comment]
Okay, sounds good --- thanks. For the record, I also tried my install script with `${AnalysisBase_PLATFORM}` and it is also getting set to `x86_64-slc6-gcc62-opt`.

**Comment by kratsg** [comment]
You can see what I did to get the CondorDriver working in the merge request here: https://gitlab.cern.ch/atlas/athena/merge_requests/4077/diffs -- but note that AnalysisBase_PLATFORM and CMTCONFIG point to the architecture containing the set-up for the shell scripts and so on, which isn't necessarily the architecture of the machine.

**Comment by matthewfeickert** [comment]
To summarize why this is closed:
- Attila thinks it should be clear (it wasn't to me) that `AnalysisBase_PLATFORM` should refer to the platform that the `AnalysisBase` release was compiled for. To quote him
> If you want to run locally on a non-SLC6 platform, you do that at your own peril. In reality using CC7 is quite safe at this point, but I don't want to hide it from the build system that you did use a different platform. Otherwise we could very easily get into problems with somebody sending grid jobs from non-SLC6 machines, and then being surprised that the binaries don't work on the SLC6 grid workers. (Again, in the SLC6 <-> CC7 case this issue is practically non-existent, but there could be other platforms as well.)
>So:
>  - It's allowed to use the SLC6 analysis release from non-SLC6 machines, but you need to keep in mind that you're doing something non-standard.
>  - As you're doing something non-standard, just use common sense when setting up your runtime environment with your own build area included in it. (Use the CC7 platform name in this.)
- A future change being considered is to make the build directory always have a soft link to the platform directory, which would fix this

**Comment by matthewfeickert** [comment]
A small (and obvious) note, that this can be avoided/dealt with by the following:

```bash
# baseDir is set up here, but isn't relevant
mkdir src run build
cd src
git clone https://github.com/UCATLAS/xAODAnaHelpers
git clone ssh://git@gitlab.cern.ch:7999/johnda/StudyTrigTracks.git
asetup AnalysisBase,21.2.0,here
cd ../build
cmake ../src
make > xAH_CMake_out.txt 2>&1
echo "Build has finished at "$(tail -n 1 ${baseDir}/build/xAH_CMake_out.txt | sed 's/].*$/]/')" complete"
cd ..
if [[ "${CMTCONFIG}" == "$(find ${baseDir}/build -iname "x86*gcc*" | sed 's/.*build\///')" ]]; then
    source build/${CMTCONFIG}/setup.sh
else
    BUILDCONFIG="$(find ${baseDir}/build -iname "x86*gcc*" | sed 's/.*build\///')"
    source build/${BUILDCONFIG}/setup.sh
fi
```

**Comment by kratsg** [comment]
I think you can avoid this entirely by doing this:

```
source build/*/setup.sh
```

**Comment by matthewfeickert** [comment]
Indeed. That is a much more elegant solution. Thanks!
