### ISSUE TITLE
Unclear how muon trigger SFs are meant to be retrieved in MuonContainer

### ISSUE THREAD

**Issue by alexandertuna** [UCATLAS/xAODAnaHelpers#1012]
Hello again muon enthusiasts.

@kratsg  @mmilesi  @ntadej  @MihaMuskinja  @jdandoy  @kkrizka 

I'm not sure how muon trigger SFs are supposed to be retrieved in the MuonContainer class. I think the accessor defined there is inconsistent with the decorator defined in MuonEfficiencyCorrector. How the shit has anyone been writing this to an ntuple?

[decorator](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/MuonEfficiencyCorrector.cxx#L857)
`sfName = "MuTrigEff_SF_syst_" + trig_it + "_Reco" + m_WorkingPointRecoTrig + "_Iso" + m_WorkingPointIsoTrig`

[accessor](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/MuonContainer.cxx#L800)
`trigEffSF = "MuTrigEff_SF_syst_" + trig `

The accessor doesn't know about what offline ID or isolation is applied. But it needs to know. Or am I reading something incorrectly?

If nobody speaks up, I'm gonna make a PR which puts the trigger SF accessors in MuonContainer into a loop over ID and isolation, same as the MuonEfficiencyCorrector.

**Comment by ntadej** [comment]
I agree this should probably be simplified and unified with electrons. Currently you need to pass full trigger configuration to `TreeAlgo` (like what you observed in decorator).

An example of the code is here:
```
wp_mu_branches = []
for t in wp_mu_trig:
    for r in wp_mu_reco:
        for i in wp_mu_isol:
            wp_mu_branches.append("_".join([t, "Reco%s" % r, "Iso%s" % i]))
```

**Comment by alexandertuna** [comment]
Ah, I see. Thanks @ntadej. 

Yeah, it's unfortunate that the muon and electron configurations are different. But if nobody else seems to mind, I'll just implement this in the TreeAlgo config, and not rewrite that part of MuonContainer. Hopefully future analyzers will see this issue.
