### ISSUE TITLE
Upgrade from 2.3.13 to 2.3.14 (w/ pre-recommendations) - Electron* and Muon* stuff 

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#102]
In 2.3.14 we are having some ASG tool interface changes:

See here: https://twiki.cern.ch/twiki/bin/view/AtlasProtected/AnalysisBase#Run2_EDM_xAOD_Rel20_i_e_mc15_and

**Comment by kratsg** [comment]
Why do they keep constantly changing? Ugh.

**Comment by mmilesi** [comment]
Closed through #118
