### ISSUE TITLE
METConstructor: Value assignment failed for SoftTermReso

### ISSUE THREAD

**Issue by vpascuzz** [UCATLAS/xAODAnaHelpers#1045]
Using the latest revision of the code in 21.2.4,AnalysisBase, we are seeing:
```
...
METConstructor.DijetLe...DEBUG   Trying to set-up tool: _DijetLepton_METConstructor::0x1b87c8d0
PropertyMgr              ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/PropertyMgr.icc:43 (StatusCode PropertyMgr::setProperty(const string&, const T&) [with T = int; std::__cxx11::string = std::__cxx11::basic_string<char>]): Value assignment failed for SoftTermReso
AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:240 (StatusCode asg::detail::AnaToolPropertyValueRootCore<Type>::applyPropertyRootCore(asg::AsgTool&, const string&, asg::detail::AnaToolCleanup&) const [with Type = int; std::__cxx11::string = std::__cxx11::basic_string<char>]): Failed to call "tool.setProperty (name, m_value)"
AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:429 (StatusCode asg::detail::AnaToolConfig::makeToolRootCore(const string&, asg::IAsgTool*&, asg::detail::AnaToolCleanup&) const): Failed to call "property.second->applyPropertyRootCore (*rawToolPtr, property.first, mycleanup)"
AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:515 (StatusCode asg::detail::AnaToolConfig::makeBaseTool(const string&, asg::parentType_t*, ToolHandle<asg::IAsgTool>&, asg::detail::AnaToolCleanup&) const): Failed to call "makeToolRootCore (toolName, baseToolPtr, baseCleanup)"
AsgTools_UserCode        ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:551 (StatusCode asg::detail::AnaToolConfig::makeTool(const string&, asg::parentType_t*, ToolHandle<T>&, asg::detail::AnaToolCleanup&) const [with ToolType = asg::IAsgTool; std::__cxx11::string = std::__cxx11::basic_string<char>; asg::parentType_t = INamedInterface]): Failed to call "makeBaseTool (name, parent, baseTH, baseCleanup)"
AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:106 (StatusCode asg::detail::AnaToolShareList::makeShare(const string&, const asg::detail::AnaToolConfig&, std::shared_ptr<asg::detail::AnaToolShare>&)): Failed to call "config.makeTool (name, nullptr, th, cleanup)"
AsgTools_AnaToolHandle   ERROR   /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.4/InstallArea/x86_64-slc6-gcc62-opt/src/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:822 (StatusCode asg::AnaToolHandle<T>::initialize() [with T = IMETSignificance]): Failed to call "detail::AnaToolShareList::singleton().makeShare (m_name, m_config, sharedTool)"
METConstructor.DijetLe...ERROR   /afs/cern.ch/user/v/vpascuzz/work/private/analysis/lxqq/code/DijetFramework_r21/source/DijetFramework/xAODAnaHelpers/Root/METConstructor.cxx:181 (virtual EL::StatusCode METConstructor::initialize()): Failed to call "m_metSignificance_handle.retrieve()"
/build1/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:48:exception: Algorithm::initialize returned StatusCode::FAILURE
...
```

Please advise. Thanks in advance.

**Comment by vpascuzz** [comment]
I guess our config would be useful:
```
c.setalg("METConstructor",     {
  "m_name"                      : "DijetLepton_METConstructor",
  "m_referenceMETContainer"     : "MET_Reference_AntiKt4EMTopo",
  "m_mapName"                   : "METAssoc_AntiKt4EMTopo",
  "m_coreName"                  : "MET_Core_AntiKt4EMTopo",
  "m_outputContainer"           : "MET_rebuilt",
  #----------------------- MET objects ----------------------------#
  "m_inputElectrons"	        : "Electrons_Calib",
  "m_inputMuons"		: "Muons_Calib",
  "m_inputJets"		        : "AntiKt4EMTopoJets_Calib",
  #----------------------- MET config ----------------------------#
  #"m_rebuildUsingTracksInJets"  : False,
  #"m_addSoftClusterTerms"       : True,
  "m_doJVTCut"	                : True,
  "m_doMuonEloss"               : True,
  "m_doIsolMuonEloss"           : True,
    #----------------------- Other ----------------------------#
  "m_msgLevel"		        : "Debug"
})
```
Also note this worked fine in 21.2.3 and earlier. However, there don't seem to be many grid nodes available with releases < 21.2.4.

**Comment by kratsg** [comment]
Relevant code is here: https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/METConstructor.cxx?utf8=%E2%9C%93#L166-L184 

Specifically, it seems to have a problem with `m_significanceSoftTermReso` which is set at `10` right now by default: http://xaodanahelpers.readthedocs.io/en/master/METConstructor.html?highlight=m_significanceSoftTermReso#_CPPv2N14METConstructor26m_significanceSoftTermResoE 

And it might be because of the static_cast<int> here: https://gitlab.cern.ch/atlas/athena/blob/21.2/Reconstruction/MET/METUtilities/METUtilities/METSignificance.h#L145 (https://gitlab.cern.ch/atlas/athena/blob/21.2/Reconstruction/MET/METUtilities/Root/METSignificance.cxx#L114)

I wonder if `declareProperty` is unable to convert types correctly.

**Comment by vpascuzz** [comment]
I have seen. Trying something now...keep you posted.

**Comment by vpascuzz** [comment]
Also, in the comments it reads " property is int for some reason", however looking at the `METSignificance` code, it's actually a `double`:
http://acode-browser1.usatlas.bnl.gov/lxr/source/athena/Reconstruction/MET/METUtilities/METUtilities/METSignificance.h?v=21.2#0145

**Comment by vpascuzz** [comment]
Alright, it's all better.

@kratsg You want a diff, or for me to make a MR?

**Comment by kratsg** [comment]
`acode` is from gitlab -- so the problem is that in release 21, it's a double, but in release 20 -- it's an int. We need to support both: https://svnweb.cern.ch/trac/atlasoff/browser/Reconstruction/MET/METUtilities/tags/METUtilities-00-02-48/METUtilities/METSignificance.h?rev=808240

**Comment by vpascuzz** [comment]
I see...maybe an `#ifdef` could work here?

**Comment by vpascuzz** [comment]
Beat me to it.

Cheers.

**Comment by vpascuzz** [comment]
Hi @kratsg,

Seems the patch doesn't work. I am working in 21.2.5 at 662aa0f2daf7eaada7376c42918ad44a22755d49 and I still get the same crash...

**Comment by kratsg** [comment]
Not sure: https://github.com/UCATLAS/xAODAnaHelpers/blob/662aa0f2daf7eaada7376c42918ad44a22755d49/Root/METConstructor.cxx#L170-L174 

Can you at least confirm that the code is executing the CMake version correctly? What's the error? copy/paste again from what you're seeing now.

**Comment by vpascuzz** [comment]
Make `m_significanceSoftTermReso` a `double` and you're golden.

**Comment by vpascuzz** [comment]
Make `m_significanceSoftTermReso` a `double` and you're golden.

**Comment by kratsg** [comment]
@vpascuzz it cannot be the same as before. The variable is a `float` type and the error would complain that it's a float and not an int:

```
PropertyMgr              ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/PropertyMgr.icc:43 (StatusCode PropertyMgr::setProperty(const string&, const T&) [with T = int; std::__cxx11::string = std::__cxx11::basic_string<char>]): Value assignment failed for SoftTermReso
```

Can you copy/paste the error you see now? It can't be the same.

**Comment by vpascuzz** [comment]
Same error:
```
PropertyMgr              ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/PropertyMgr.icc:43 (StatusCode PropertyMgr::setProperty(const string&, const T&) [with T = float; std::__cxx11::string = std::__cxx11::basic_string<char>]): Value assignment failed for SoftTermReso
```
different reason.

Change `m_significanceSoftTermReso` to a `double`. Works for me.

**Comment by vpascuzz** [comment]
Possible for me to get push access for MRs?

**Comment by ntadej** [comment]
Just create a fork and push there.

**Comment by vpascuzz** [comment]
That works.

**Comment by kratsg** [comment]
Closed with #1047.

**Comment by kratsg** [comment]
@vpascuzz - since you have this set up, do you mind testing to see if passing a string to the property works instead? According to the pat-help email, you should be able to do this in release 21.

**Comment by vpascuzz** [comment]
@kratsg - Pass a `string` to `m_significanceSoftTermReso` in my config? Like, `"10.0"`, for example?

**Comment by vpascuzz** [comment]
OK, I've seen the email thread. I will give it a shot tomorrow.
