### ISSUE TITLE
Lepton d0sig should be signed

### ISSUE THREAD

**Issue by alexandertuna** [UCATLAS/xAODAnaHelpers#1055]
It's currently hit with fabs:
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/MuonContainer.cxx#L797
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronContainer.cxx#L900

The sign is important. Ask [johnda](https://twiki.cern.ch/twiki/pub/AtlasPublic/BJetTriggerPublicResults/trk_d0Sig_signed.pdf). Are there objections to getting rid of those fabs?

**Comment by alexandertuna** [comment]
@kratsg  @mmilesi  @ntadej  @MihaMuskinja  @jdandoy  @kkrizka 

:snake: :snake:

**Comment by kratsg** [comment]
I agree, it should be signed.
