### ISSUE TITLE
Python autocompletion does not work with zsh

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#1057]
Python autocompletion does not work with zsh. Probably initialisation should be disabled for now until it will work as I currently get an error:
```
(eval):32: command not found: complete
```

This might scare users.

**Comment by kratsg** [comment]
Hi @ntadej - if you're using zsh, you need to enable it:

```
autoload compinit bashcompinit
compinit
bashcompinit
```

**Comment by kratsg** [comment]
@ntadej any updates? I tested this briefly on a zsh shell and it works for me.

**Comment by ntadej** [comment]
Sorry, didn't have time to get back to this. Will try to look at it tomorrow.

**Comment by ntadej** [comment]
It works now, thanks.
