### ISSUE TITLE
Problem in AsgElectronLikelihoodTool::accept

### ISSUE THREAD

**Issue by vpascuzz** [UCATLAS/xAODAnaHelpers#1058]
Hi experts,

Running in 21.2.5+, we are seeing *many* `ERROR`s of the type:
```
ElectronSelect_X    ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/ElectronPhotonID/ElectronPhotonSelectorTools/Root/AsgElectronLikelihoodTool.cxx:409 (virtual const Root::TAccept& AsgElectronLikelihoodTool::accept(const Electron*, double) const): Skipping LH rectangular cuts! The following variables are missing: ambiguityType 
```
Looking at the `AsgElectronLikelihood` code, the variable is a `uint8_t`. There is no such property in the `ElectronSelector` algorithm. Should this be added? It seems these errors could be tied to issues with our output electrons.

Cheers,
vrp

**Comment by kratsg** [comment]
Not our problem: https://its.cern.ch/jira/browse/ATLASG-1309. Specifically, you need to append `_Rel20p7` to any working point to get the Release 20.7 working point in Release 21.

- The wiki with all the option is here : 
https://twiki.cern.ch/twiki/bin/view/AtlasProtected/EGammaIdentificationRun2#Electron_Identification 

-The Jira is here
https://its.cern.ch/jira/browse/ATLASRECTS-3567?focusedCommentId=1669392&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1669392

- The merge is this :
https://gitlab.cern.ch/atlas/athena/merge_requests/4471

- The presentation in PC   https://indico.cern.ch/event/664588/contributions/2714131/attachments/1520698/2376229/2017.09.11_egammaRoundTable.pdf slide 8 

- The presentation in e/gamma https://indico.cern.ch/event/657143/contributions/2717440/attachments/1522775/2379641/2017.09.13_egammaIntro.pdf slide 3

**Comment by vpascuzz** [comment]
Thanks a lot for all the info!
