### ISSUE TITLE
Use of deprecated `retrieve` in `HelperFunctions`

### ISSUE THREAD

**Issue by vpascuzz** [UCATLAS/xAODAnaHelpers#1061]
Hi experts,

`WARNING`s of the type:
```
HelperFunctions.getPri...WARNING retrieve<T>(..., bool) is deprecated. See https://github.com/UCATLAS/xAODAnaHelpers/pull/882
```
are quite agitating. Is it worth fixing this?

Cheers,
      vrp

**Comment by kratsg** [comment]
Hi @vpascuzz where are you seeing these? Are you using HF::retrieve() in an algorithm of yours? If so, just use the current signature which is (... msg()).

**Comment by vpascuzz** [comment]
@kratsg - Ah, so you're saying it's us, not you? ;)

I will check it out. Thanks for the reply.

**Comment by kratsg** [comment]
For now, I'll close this in favor of the other issue mentioned above.

**Comment by vpascuzz** [comment]
@kratsg - All good, friend. As you suspected, it was on our end.

Cheers.
