### ISSUE TITLE
JERTool crashes due to MC property assignment error

### ISSUE THREAD

**Issue by kkrizka** [UCATLAS/xAODAnaHelpers#1072]
I am seeing the ntupling code crash with the following error. Seems to be caused by #1069. Replacing `isMC()` with `true` (`isMC()==1` in my case) when setting the `isMC` property of the tool gets rid of the crash.

> PropertyMgr              ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/PropertyMgr.icc:43 (StatusCode PropertyMgr::setProperty(const string&, const T&) [with T = int; std::__cxx11::string = std::__cxx11::basic_string<char>]): Value assignment failed for isMC
> AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:240 (StatusCode asg::detail::AnaToolPropertyValueRootCore<Type>::applyPropertyRootCore(asg::AsgTool&, const string&, asg::detail::AnaToolCleanup&) const [with Type = int; std::__cxx11::string = std::__cxx11::basic_string<char>]): Failed to call "tool.setProperty (name, m_value)"
> AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:429 (StatusCode asg::detail::AnaToolConfig::makeToolRootCore(const string&, asg::IAsgTool*&, asg::detail::AnaToolCleanup&) const): Failed to call "property.second->applyPropertyRootCore (*rawToolPtr, property.first, mycleanup)"
> AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:515 (StatusCode asg::detail::AnaToolConfig::makeBaseTool(const string&, asg::parentType_t*, ToolHandle<asg::IAsgTool>&, asg::detail::AnaToolCleanup&) const): Failed to call "makeToolRootCore (toolName, baseToolPtr, baseCleanup)"
> AsgTools_UserCode        ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:551 (StatusCode asg::detail::AnaToolConfig::makeTool(const string&, asg::parentType_t*, ToolHandle<T>&, asg::detail::AnaToolCleanup&) const
> [with ToolType = asg::IAsgTool; std::__cxx11::string = std::__cxx11::basic_string<char>; asg::parentType_t = INamedInterface]): Failed to call "makeBaseTool (name, parent, baseTH, baseCleanup)"
> AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:106 (StatusCode asg::detail::AnaToolShareList::makeShare(const string&, const asg::detail::AnaToolConfig&, std::shared_ptr<asg::detail::AnaToolShare>&)): Failed to call "config.makeTool (name, nullptr, th, cleanup)"
> AsgTools_AnaToolHandle   ERROR   /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.5/InstallArea/x86_64-slc6-gcc62-opt/src/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:822 (StatusCode asg::AnaToolHandle<T>::initialize() [with T = IJERSmearingTool]): Failed
> to call "detail::AnaToolShareList::singleton().makeShare (m_name, m_config, sharedTool)"
> JetCalibrator.Calibrat...ERROR   /global/homes/k/kkrizka/DijetISRCode_Organizer/xAODAnaHelpers/Root/JetCalibrator.cxx:329 (virtual EL::StatusCode JetCalibrator::initialize()): Failed to call "m_JERSmearingTool_handle.retrieve()"
> /global/homes/k/kkrizka/DijetISRCode_Organizer/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:48:exception: Algorithm::initialize returned StatusCode::FAILURE
>

**Comment by kratsg** [comment]
I see, I suspected one of these would show up, unfortunately. I don't like that the tool takes an obvious boolean configuration as an integer property only. Can you try setting this as a string instead? According to Nils, all tool properties can be set as strings and the internal code will convert it to the right type for you at the end.

**Comment by kkrizka** [comment]
Unless we make `isMC()` return a string (not a good idea), might as well do an explicit bool cast for the JER tool and for every single single tool that works like this.

I'm about to make a PR with another fix. I make `isMC()` return a boolean. In case the type cannot be determined, it throws an exception. I am assuming that dataset type not being determined correctly would affect the results and the user should be explicitly notified of it and fix it.

**Comment by kkrizka** [comment]
Fixed by #1075
