### ISSUE TITLE
Electron efficiency scale factors work down to 7 GeV, not 15 GeV

### ISSUE THREAD

**Issue by alexandertuna** [UCATLAS/xAODAnaHelpers#1088]
15 GeV is hard-coded. But the recommendations nowadays are 7 GeV (if not 4.5 GeV). Does anyone object to me changing this hardcode to 7 GeV?

https://twiki.cern.ch/twiki/bin/view/AtlasProtected/LatestRecommendationsElectronIDRun2

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L642
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L745
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L848
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L957
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L1064

@kratsg @mmilesi @ntadej @MihaMuskinja @jdandoy @kkrizka

**Comment by alexandertuna** [comment]
In case merges affect the line number, just search for "15e3".

**Comment by ntadej** [comment]
Why not make this configurable? The recommendation might change again.

**Comment by alexandertuna** [comment]
New strategy: make it configurable. I'll make the default 15e3 to not annoy anyone.
