### ISSUE TITLE
Add frac_MV2c10X_vs_actMu histogram bookings

### ISSUE THREAD

**Issue by matthewfeickert** [UCATLAS/xAODAnaHelpers#1095]
In PR #1086 bookings for histograms for fractions of jets that pass `MV2c20X` (at various operating points `X`) were added. As these are desired for `MV2c10X` should we just add bookings for the `MV2c10X` histograms or should we change `MV2c20` to `MV2c10`?

**Comment by kratsg** [comment]
Nobody uses MV2c20 anymore. Switch over.

**Comment by matthewfeickert** [comment]
Closed by PR #1096
