### ISSUE TITLE
Why is xrootd required for prun

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#1101]
Since moving to rel. 21.2, the usual `lsetup panda` for prun grid submission is not enough anymore. If I comment out XRD requirement, jobs still seem to be submitted fine. What is the reason for this?

**Comment by kratsg** [comment]
> Anyways, I don't think XRD should be needed for prun in either case. I think it is something that we overlooked on the xAH side.
> 
> It should still be needed for running on non-grid systems with Rucio inputs, since XRD is used to open the files located by FAX. This is independent of release.

I'll fix this.

**Comment by ntadej** [comment]
@kkrizka, inputRucio is needed (at least it seems so) if I specify containers in the txt file (one container per line). If I manually force submission without XRD it seems to work just fine.

**Comment by kkrizka** [comment]
Yes, inputRucio is needed if you are specifying rucio containers. I am not sure how that is related to needing (or not needing) XRD setup when submitting to the grid.

What do you mean by "manually force submission without XRD"?

**Comment by ntadej** [comment]
Commenting out the lines in xAH_run :)

**Comment by kkrizka** [comment]
Ah I understand. Small logic error on my end. One should not just remove prun from the driver requirements as was done in #1102. One also needs to add a check that args.driver!='prun'.

**Comment by kratsg** [comment]
Ahh, I see. @kkrizka do you mind PR'ing?
