### ISSUE TITLE
Missing `ambiguityType` property in `ElectronSelector`?

### ISSUE THREAD

**Issue by vpascuzz** [UCATLAS/xAODAnaHelpers#1103]
Hi,

We are seeing many `ERROR`s of the type:
```
ElectronSelect_Loose     ERROR /build1/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/ElectronPhotonID/ElectronPhotonSelectorTools/Root/AsgElectronLikelihoodTool.cxx:409 (virtual const Root::TAccept& AsgElectronLikelihoodTool::accept(const Electron*, double) const): Skipping LH rectangular cuts! The following variables are missing: ambiguityType
```

Does `xAH::ElectronSelector` need this variable, `ambiguityType`, added?

Cheers,
      vrp

**Comment by kratsg** [comment]
What AB release are you using? This is not xAH's problem.

- https://groups.cern.ch/group/hn-atlas-PATHelp/Lists/Archive/DispForm.aspx?ID=23004 
- https://its.cern.ch/jira/browse/ATLASG-1309
- https://groups.cern.ch/group/hn-atlas-PATHelp/Lists/Archive/DispForm.aspx?ID=23415

Follow up with the EGamma group if this is still a problem.

**Comment by vpascuzz** [comment]
Shoot -- sorry, Giordon. We are using `21.2.10`.

**Comment by kratsg** [comment]
> 21.2.10

Follow up with EGamma.

**Comment by vpascuzz** [comment]
Thanks!
