### ISSUE TITLE
Ntuples size reduction proposal

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#1109]
To reduce output ntuple size it would be useful not to output:
 - [x] muon isolation status for unused WPs
 - [x] electron isolation status for unused WPs
 - [x] muon quality status for unused WPs
 - [x] electron ID status for unused WPs
 - [x] particle counts - Is there a use case for those? Usually they are wrong if you do extra cuts on ntuple processing and you can always check a size of vectors in branches.

Most of upper branches contain -1 anyway if not used so it's useless to store them. I propose to propagate some of the settings to final tree algo to avoid complicated output configuration. What do you think?

I can go forward with implementing those changes but they might be breaking (especially particle counts). Let me know if this sounds rights so I can proceed.

**Comment by kratsg** [comment]
How do you check if it's not needed? As it currently is, with my massive changes to how Electrons are handled -- you can specify the individual isolation that you want.

**Comment by ntadej** [comment]
For the SFs, yes but not for "status" branches (el_isIsolated, muon_isMedium, ...). I counted at least 25 branches that I do not need and just take up space. When doing systematics this can account to quite a lot of size I guess.

Let's look at the electron isolation example:

All `el_isIsolated_*` branches are still present all the time. In ElectronSelector you define `m_IsoWPList` of isolations you want to be decorated. This is usually one or two WPs. Others that get filled with -1s just take space.

I realised now that just storing this vector to TStore will not work as branches need to be connected before filling the variables, am I correct? Is there another way to propagate algorithms configuration to the final TreeAlgo?

Another option would be to just use your code also for those branches. Then you would always need SFs and "status branches".

**Comment by kratsg** [comment]
I suspect it would be nicer to define the status in the same way as we do for SFs.

**Comment by ntadej** [comment]
Ok, I will come up with a proposal. Thanks for the feedback.

**Comment by jbossios** [comment]
noMultiplicity flag added to remove particle count: https://github.com/UCATLAS/xAODAnaHelpers/pull/1500

Closing since everything seems to have been implemented
