### ISSUE TITLE
Fix nGBPerJob for prun, string to int

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#1114]
AB 21.2.10 breaks if this is a string and not an int

**Comment by ntadej** [comment]
I used it as string in AB 21.2.10 just fine. Are you sure it doesn’t work?

**Comment by kratsg** [comment]
Chris Delitzsch had issues with it in 21.2.0 and it wouldn't convert it right. Changing it to `int` fixed things.

**Comment by kkrizka** [comment]
What was the error?

**Comment by kratsg** [comment]
It was unable to set the value (from SampleHandler's side) using the default value of `2` in our code. It could be a type-conversion problem...

**Comment by vpascuzz** [comment]
FYI: ```2``` -> ```'2'``` works for me in ```21.2.10``` with xAH@a3facfaa. Otherwise, ```nGBPerJob``` is, by default, an ```int```, and I get:
```
An exception was caught! (xAH_run.py:663)
Traceback (most recent call last):
  File "/afs/cern.ch/work/v/vpascuzz/private/analysis/lxqq/code/DijetFramework_r21/build/x86_64-slc6-gcc62-opt/bin/xAH_run.py", line 561, in <module>
    getattr(driver.options(), setter)(getattr(ROOT.EL.Job, opt), getattr(args, opt))
TypeError: void SH::MetaObject::setString(const string& name, const string& value) =>
    could not convert argument 2
```
