### ISSUE TITLE
Decorating jets

### ISSUE THREAD

**Issue by alexandertuna** [UCATLAS/xAODAnaHelpers#112]
Hi xAH experts,

Upstream of my analysis selections, I would like to decorate jets with their MV2 b-tagging score. This seems general enough to be included in xAH, not my analysis code.

``` cpp
const xAOD::BTagging *myBTag = jet->btagging();
double discriminant_MV2c20 = -99;
myBTag->MVx_discriminant("MV2c20", discriminant_MV2c20);
jet->auxdecor<double>("MV2c20_discriminant") = discriminant_MV2c20;
```

Is there a natural place to put this decoration? I considered putting it in the b-tagging section of JetSelector, but that seems misleading, because JetSelector should be for selecting jets, not decorating them. (Currently, the b-tagging section also only runs if a b-tag cut is requested.) I could imagine an analogous JetDecorator but it doesn't exist now. What do you think?

This also probably applies to decorating other objects (electrons, muons, et al) but I haven't gotten there yet.

Sorry in advance if this is a noob question, I'm still new to xAODs and xAH. Thanks for your help.

**Comment by gfacini** [comment]
Hi Alex,

Firstly, thanks for the interest and looking into the framework.

What is the point of this - you are suggesting a copy of something already in the aux store.
Is this just that you want to have 1 line downstream instead of 4?

Cheers,
Gabriel

**Comment by alexandertuna** [comment]
Hi Gabe,

It is my distinct pleasure.

Exactly. There's a lot of b-tagging in hh→4b, and it would be great to have 1 line instead of 4 every time we wanted to access MV2.

Another example I can imagine is truth labeling. It'd be cool to do this once, upstream, and then everyone can access it easily later on.

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L687

**Comment by kratsg** [comment]
Hi @alexandertuna, it's funny you say that because your code actually retrieves the `MVx` variable as a decoration (that's what the helper function is for!). The main reason we don't add a lot of decorations is because it can slow down the code. A better equivalent (if we put it in is)

```c++
const xAOD::BTagging *myBTag = jet->btagging();
double discriminant_MV2c20 = -99;
myBTag->MVx_discriminant("MV2c20", discriminant_MV2c20);
jet->setAttribute("MV2c20_discriminant", discriminant_MV2c20);
```

but otherwise, what I suggest is the doing the following in your code:

```
c++
float MV2c20(const xAOD::Jet*){

  float discriminant_MV2c20 = -99;
  if(!jet->getAttribute("MV2c20_discriminant", discriminant_MV2c20)){
    const xAOD::BTagging *myBTag = jet->btagging();
    myBTag->MVx_discriminant("MV2c20", discriminant_MV2c20);
    jet->setAttribute("MV2c20_discriminant", discriminant_MV2c20);
  }
  return discriminant_MV2c20;
}

and then you can just call a one-liner using

```c++
val = MV2c20(jet);
```

**Comment by alexandertuna** [comment]
Thanks @kratsg. I think both your suggestions are reasonable. The CxAODMaker people do something similar to your second suggestion (sorry if it's blasphemous to mention them).

Does anyone think this is a general enough piece of code for the xAH community to want? Maybe in HelperFunctions? Or should I just toss it in my code?

**Comment by gfacini** [comment]
Hi Alex,

Thanks for understanding.

If you want to put something in HelperFunctions, that would be great!!
I am surprised the b-tagging group does not have something themselves
like the Helper classes of the Egamma group.

Either way, we are happy to have this in the helper class.
If that file is getting cluttered and you need a lot of helpers you can made
a btaghelperfunction file just for btag related things....unless others object.

Cheers,
Gabriel

**Comment by kratsg** [comment]
@gfacini - I think I have a good solution that works for us all in the future. We'll add a "Variables" file in the "xAH" namespace so that these things can be added.

**Comment by gfacini** [comment]
Hi! @alexandertuna @kratsg 

Where did we end up with these ideas?  Was a decision taken and a resolution found?

Cheers,
Gabriel

**Comment by kratsg** [comment]
@gfacini - there wasn't a resolution. I can start working on this soon, but it doesn't have as high a priority because this is an aesthetic change.

**Comment by alexandertuna** [comment]
Right -- since it was an aesthetic thing, I just tossed a function into the 4b code for now.

https://svnweb.cern.ch/cern/wsvn/atlasphys-exo/Physics/Exotic/JDM/hh4b/Run2/Code/XhhCommon/trunk/Root/Helpers.cxx

    float MV2(const xAOD::Jet* jet, std::string flavor)

The original decoration suggest by Giordon failed because the jet was a const and didn't want to be augmented. But since our code is only calling this function 1-2x per jet, the current implementation isn't terribly inefficient (I think).

**Comment by kratsg** [comment]
@alexandertuna -- yes, setAttribute only works on `non-const` jets. There's no current equivalent yet, but it's in the xAODJet pipeline :)

**Comment by gfacini** [comment]
@alexandertuna 
#214 covers this request.
The flavor tagging community provided a tool for selection and another for scale factors so we now wrapped all that together so one can make a consistent set of decorations for jets which say if the jets was tagged and the appropriate scale factor (efficiency and inefficiency appropriately).  Scale factors are only added if the OP is calibrated.

**Comment by alexandertuna** [comment]
@gfacini Looks good to me. We may want to add configurability for track jets in GetBTagMV2c20_Cut, but this can be done in the future. For inspiration, see MV2_benchmark:

https://svnweb.cern.ch/cern/wsvn/atlasphys-exo/Physics/Exotic/JDM/hh4b/Run2/Code/XhhCommon/trunk/Root/Helpers.cxx?rev=242545

**Comment by gfacini** [comment]
@alexandertuna 
Thanks for looking!! Trackjets would be a nice extension, I agree.
