### ISSUE TITLE
Grid submission without hidden files

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#1129]
I followed some discussion at the mailing lists but I did not see a conclusion. How to exclude hidden files and folders from grid submission? Especially there is a problem with xAH as a submodule as there were binary files added and this makes repository size > 100 MB.

Ideally this issue would be solved directly in xAH to benefit all users.

**Comment by kratsg** [comment]
Which discussion are you talking about? Right now, I look at the repository size of xAH:

```
Lord Stark:~/xAODAnaHelpers (master)$ git bundle create tmp.bundle --all
Counting objects: 11269, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2754/2754), done.
Writing objects: 100% (11269/11269), 29.51 MiB | 0 bytes/s, done.
Total 11269 (delta 8541), reused 11179 (delta 8471)
Lord Stark:~/xAODAnaHelpers (master)$ du -sh tmp.bundle 
 30M	tmp.bundle
```

and the size seems pretty decent (30MB).

**Comment by ntadej** [comment]
There was a thread "Excluding files using prun (EventLoop) -- re-asking this question".

Yes, the .git folder is now 39M for me which I guess it's acceptable. I hope .git gets excluded soon but if I understand you correctly it's nothing we can do on our side?

**Comment by kratsg** [comment]
Ahh, I see. The solution, as usually, is to have prun exclude files. There is an option under prun `--excludeFile` that can do it. We can probably have xAH add this by default. Lemme see.

**Comment by kratsg** [comment]
@ntadej Could you try testing with a setup doing something like `xAH_run.py .... prun --optSubmitFlags="--excludeFile .git`  and see if the resulting tarball made looks better?

**Comment by kratsg** [comment]
Did this work for you? I can certainly update `xAH_run` to exclude all `.git` directories by default for prun submissions.

**Comment by ntadej** [comment]
I didn't have time to test it. I will submit new jobs in a day or two, so I can report back then.

**Comment by ntadej** [comment]
Ok, it does not seem to be working, neither `.git` or `.git/*`. I will try some other combinations.

Also I think it's not the size that's problematic, but a lot of small files that are copied to a temp directory and then tarred.

**Comment by kratsg** [comment]
> Ok, it does not seem to be working, neither .git or .git/*. I will try some other combinations.

Ok, I sent another email to pathelp and cc'd you on it.

> Also I think it's not the size that's problematic, but a lot of small files that are copied to a temp directory and then tarred.

I'm not so sure this is the problem.

**Comment by ntadej** [comment]
> I'm not so sure this is the problem.

It seem so, as the final tar is "only" 65 MB but it still takes a few minutes to submit the first sample.

**Comment by ntadej** [comment]
A short follow-up: it seems that EL code makes the tar and passes it to prun. So this needs to be fixed in EL itself, not just with some prun flags.

**Comment by kratsg** [comment]
`EL` isn't making the tar for grid, it's using `prun` for it via a `CPack` command. For `condor` jobs, it will make it's own tarball, but that excludes the sources.

**Comment by ntadej** [comment]
Strange, I couldn't find any flag to exclude `.git`. I will report back to the DAST ticket.

**Comment by ntadej** [comment]
This has been fixed upstream.

**Comment by kkrizka** [comment]
@ntadej What does the fix look like? Are hidden files now excluded automatically or `--excludeFile .git` is still needed?

**Comment by ntadej** [comment]
All `.git` folders are ignored by default. Also it seems like `--excludeFile` does not even work for EventLoop as the tarball is created beforehand.

**Comment by kkrizka** [comment]
Thanks! Does one need the latest panda or AnalysisBase for this?

**Comment by ntadej** [comment]
It needs (I think) at least 21.2.24 as externals were updated there. Note that there are problems with xrootd starting with this version so you should probably use ``--forceStaged`` to make it work on all sites.
