### ISSUE TITLE
MuonEfficiencyCorrector and prw tool

### ISSUE THREAD

**Issue by othrif** [UCATLAS/xAODAnaHelpers#1135]
Hello xAH users!

I am setting up some code that uses xAODAnaHelpers and I am running into some problems with the MuonEfficiencyCorrector. 

The way I have it setup is to first run a BasicEventSelection algorithm where I apply pileup reweighing, later I call the MuonEfficiencyCorrector which gives the following error:
"MuonEfficiencyCorrector.cxx:127 (virtual EL::StatusCode MuonEfficiencyCorrector::initialize()): A configured  must have been previously created! Are you creating one in xAH::BasicEventSelection?"
Relevant code:
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/MuonEfficiencyCorrector.cxx#L123-L132

My code is located in /afs/cern.ch/user/o/othrif/public/myVBFrel21. The configuration file is /afs/cern.ch/user/o/othrif/public/myVBFrel21/VBFInv/python/vbfinv_baseline21.py

Othmane

**Comment by kratsg** [comment]
What version of xAH are you using? Run `git rev-parse HEAD` inside it to let us know.

**Comment by ntadej** [comment]
This was fixed in #1131.

**Comment by othrif** [comment]
Thanks! It worked. I had an older version…

Does this variable need to be set: "m_MCCampaign” ?
Looking at https://twiki.cern.ch/twiki/bin/view/AtlasProtected/MCPAnalysisGuidelinesMC16 <https://twiki.cern.ch/twiki/bin/view/AtlasProtected/MCPAnalysisGuidelinesMC16>, I don’t see a recommendation to do: ANA_CHECK( m_muTrigSF_tools[yr]->setProperty("MC", m_MCCampaign ));
that appears here <https://github.com/UCATLAS/xAODAnaHelpers/blob/1aab21691804e8b3e9ab911eed8cfb8eb1df2340/Root/MuonEfficiencyCorrector.cxx#L249>. 

The code is crashing if I set it to mc16a or did I miss something else.

Othmane

**Comment by kratsg** [comment]
> Does this variable need to be set: "m_MCCampaign” ?
> Looking at https://twiki.cern.ch/twiki/bin/view/AtlasProtected/MCPAnalysisGuidelinesMC16 <https://twiki.cern.ch/twiki/bin/view/AtlasProtected/MCPAnalysisGuidelinesMC16>, I don’t see a recommendation to do: ANA_CHECK( m_muTrigSF_tools[yr]->setProperty("MC", m_MCCampaign ));
> that appears here <https://github.com/UCATLAS/xAODAnaHelpers/blob/1aab21691804e8b3e9ab911eed8cfb8eb1df2340/Root/MuonEfficiencyCorrector.cxx#L249>.
> 
> The code is crashing if I set it to mc16a or did I miss something else.

This question is somewhat better suited for our mailing list... but as you can see in the code - if you don't set it at all, it will not set the variable. Lots of pieces of our code is configurable like this for expert-mode as well as user-mode.

https://github.com/UCATLAS/xAODAnaHelpers/blob/1aab21691804e8b3e9ab911eed8cfb8eb1df2340/Root/MuonEfficiencyCorrector.cxx#L248-L251
