### ISSUE TITLE
B-tagging result variables filled with -1

### ISSUE THREAD

**Issue by beojan** [UCATLAS/xAODAnaHelpers#1136]
I have `jetBTag_MV2c10_FixedCutBEff_707785` set in my `AddJets` call. The `jet_is_FixedCutBEff_70` etc variables are, however, filled with -1s. The same is true for `jetBTag_MV2c10_HybBEff_707785`.

This is with AnalysisBase 21.2.10 and an up-to-date xAODAnaHelpers.

**Comment by kkrizka** [comment]
Hi @beojan ,

Can you post your config file? Make sure that the corresponding `BJetEfficiencyCorrector` is correctly configured.

--
Karol Krizka

**Comment by beojan** [comment]
That explains it, I didn't *have* a `BJetEfficiencyCorrector`.
The documentation is also unclear on how I would set multiple working points in the `BJetEfficiencyCorrector`. How is this done?

**Comment by kkrizka** [comment]
Hi @beojan ,

You need to make a `BJetEfficiencyCorrector` per working point. Take a look at the ZprimeDM code on how it is done:
https://gitlab.cern.ch/atlas-phys-exotics-dijetisr/ZprimeDM/blob/413ae95db78b14d89cdb81e741e0d66d692a1085/python/commonconfig.py#L147

--
Karol Krizka
