### ISSUE TITLE
xAH_run xrootd has a bug in parsing root:// paths

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#1145]
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/scripts/xAH_run.py#L386-L390

This should contain instead `os.path.join('/', path)` to make sure the path is always prepended with a slash correctly.

**Comment by jbossios** [comment]
Closing since this was fixed already in https://github.com/UCATLAS/xAODAnaHelpers/pull/1534
