### ISSUE TITLE
JetCalibrator issue

### ISSUE THREAD

**Issue by othrif** [UCATLAS/xAODAnaHelpers#1147]
I am probably overlooking something obvious but I am getting an error in the initialisation of the JetCalibrationTool when I run on data. MC runs fine.

I am using xAODAnaHelpers: 1aab21691804e8b3e9ab911eed8cfb8eb1df2340
The configuration I am using is located here: /afs/cern.ch/user/o/othrif/public/xAH/config_JetCalib.py
The details of the error are here: /afs/cern.ch/user/o/othrif/public/xAH/error_JetCalib.log

Thanks,
Othmane

**Comment by othrif** [comment]
I still get the same error if I use “JetArea_Residual_EtaJES”.

**Comment by kratsg** [comment]
@jdandoy this seems like a question about the config. It seems `InsituCalibrationFile` is not defined in the `m_globalConfig` and so takes the default value of `None` as seen here http://acode-browser.usatlas.bnl.gov/lxr/source/athena/Reconstruction/Jet/JetCalibTools/Root/InsituDataCorrection.cxx#0035 

That said, according to the twiki -- insitu is still in process and may not exist yet? https://twiki.cern.ch/twiki/bin/view/AtlasProtected/ApplyJetCalibrationR21#Calibration_of_small_R_jets_in_M

I suspect in xAH, we force insitu, so can you try adding

```python
"m_forceInsitu": False
```

**Comment by othrif** [comment]
Indeed, that was the next thing I tried and it works. Thanks!

**Comment by kratsg** [comment]
Looks like it was turned on here: https://github.com/UCATLAS/xAODAnaHelpers/commit/d38e4c406a209ffe5d64074b696b9503384c0591

I'll wait for Jeff to let me know if this should be turned back to `False`.

**Comment by ntadej** [comment]
I think for 20.7 the recommendation was to use in situ calibrations for data, so this was defaulted to prevent mistakes. In 21.2 they are not available yet as far as I know.

**Comment by jdandoy** [comment]
I think it should be kept True to generally force people to use insitu for data.  We're in a temporary place where they are not yet available so it should be false, but I think it's better that the user is aware of that and sets it to false themselves.
