### ISSUE TITLE
Automatic PRW file setup for mc16c failing on old p-tags (mc16a)

### ISSUE THREAD

**Issue by kpachal** [UCATLAS/xAODAnaHelpers#1161]
Hi folks,

A recent update from @kkrizka awesomely created a way to automatically set up the right PRW file for mc16a vs mc16c using the information from xAOD::FileMetaData::amiTag. Sadly this value only exists in my mc16c files (*s3126_r9781_r9778_p3340) and not in my mc16a files (*s3126_r9364_r9315_p3309). Guessing it was added with the later p-tag?

Anyway, running on an mc16a file with the above tags gives the following error:

`BasicEventSelection.Ba...INFO    Adding Pileup files for CP::PileupReweightingTool:
BasicEventSelection.Ba...INFO    Adding LumiCalc files for CP::PileupReweightingTool:
	 GoodRunsLists/data15_13TeV/20170619/PHYS_StandardGRL_All_Good_25ns_276262-284484_OflLumi-13TeV-008.root
	 GoodRunsLists/data16_13TeV/20170605/PHYS_StandardGRL_All_Good_25ns_ignore_TOROID_STATUS_297730-311481_OflLumi-13TeV-008.root
	 GoodRunsLists/data17_13TeV/20170901/physics_25ns_Triggerno17e33prim.lumicalc.OflLumi-13TeV-001.root
PathResolver             WARNING Locating dev directory dev/SUSYTools/PRW_AUTOCONGIF/files/. Do not let this propagate to a release
BasicEventSelection.Ba...ERROR   /afs/cern.ch/work/k/kpachal/DijetISR/Resolved2017/CodeBase/DijetISRCode_Organizer/xAODAnaHelpers/Root/BasicEventSelection.cxx:1054 (StatusCode BasicEventSelection::autoconfigurePileupRWTool()): autoconfigurePileupRWTool(): access to FileMetaData failed, but don't panic. You can try to manually set the 'mcCampaign' BasicEventSelection property to 'mc16a', 'mc16c' or 'mc16d' and restart your job. If you set it to any other string, you will still incur in this error.
BasicEventSelection.Ba...ERROR   /afs/cern.ch/work/k/kpachal/DijetISR/Resolved2017/CodeBase/DijetISRCode_Organizer/xAODAnaHelpers/Root/BasicEventSelection.cxx:525 (virtual EL::StatusCode BasicEventSelection::initialize()): Failed to call "autoconfigurePileupRWTool()"
/build1/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:48:exception: Algorithm::initialize returned StatusCode::FAILURE
worker finished:
Real time 0:00:13, CP time 2.730
[2018-02-12 22:57:25,262][ERROR  ]  --------------------`

Does anyone know of another way to access equivalent information?

I'm working on extending this to add the right lumicalc files, and that decision depends on the same information.

Cheers,
Kate

**Comment by kratsg** [comment]
Interesting -- I wasn't aware it wasn't in mc16a. This seems annoying. Here's how I programmed it in for the MBJ analysis https://gitlab.cern.ch/MultiBJets/MultibjetsAnalysis/blob/master/Root/MainAnalysis.cxx#L276-309 if @kkrizka wants to think more. I'd rather let him take charge since he wrote the functionality in first :)

**Comment by kpachal** [comment]
Aha, thanks @kratsg ! This looks like what we want. I'll modify the code to try your method and see how things go...

Cheers,
Kate
