### ISSUE TITLE
Strange memory issues when running systematics

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#1170]
It seems that systematics memory issues are back. The strangest thing is that they are only occurring for specific samples. I plan to follow this up but opening a ticket for reference. Looking at the example tasks below, I suspect something might be wrong with electrons (but this is just a rough guess).

Working tasks:
 - [single top](https://bigpanda.cern.ch/jobs/?jeditaskid=13269025&display_limit=100)
 - [Zmumu](https://bigpanda.cern.ch/jobs/?jeditaskid=13267563&display_limit=100)

Problematic tasks:
 - [ttbar](https://bigpanda.cern.ch/jobs/?jeditaskid=13268980&display_limit=100)
 - [diboson](https://bigpanda.cern.ch/jobs/?jeditaskid=13263951&display_limit=100)
 - [Zee](https://bigpanda.cern.ch/jobs/?jeditaskid=13267805&display_limit=100)

#824 should probably be closed now as there were many changes and fixes since it was reported.

**Comment by kratsg** [comment]
> #824 should probably be closed now as there were many changes and fixes since it was reported.

done.

**Comment by rhankache** [comment]
Hello all,
I wanted to ask what is the status of this issue?
I am getting the same problem when running on jet systematics.
For some samples, the memory consumed is more  than 10 GB, while for others it is less than 1GB, even though both samples have very similar number of events.
I attached the panda report of one of my jobs:
https://bigpanda.cern.ch/task/18274693/#jobsconsumptionplots

**Comment by kratsg** [comment]
> I wanted to ask what is the status of this issue?
> I am getting the same problem when running on jet systematics.
> For some samples, the memory consumed is more than 10 GB, while for others it is less than 1GB, even though both samples have very similar number of events.

Can you give me a list of systematics in jobs where memory is > 10 GB, and in jobs where memory is < 1 GB? Also, what are the sizes of the inputs for each set of jobs?

**Comment by rhankache** [comment]
Hello @kratsg ,
Both jobs run on the 146 systematics of the JES_JER.
The input sizes range between 3 to 5 GB.

@kpachal suggested me a fix (using a smaller value for trees AutoFlash) that she describes here:
https://github.com/UCATLAS/xAODAnaHelpers/pull/1198
As far as I can tell, this fix solved my memory problem.
I tried it on 2 jobs with 111 files each, and no sub-job failed
https://bigpanda.cern.ch/task/18297020/

**Comment by kratsg** [comment]
@rhankache, setting it to the -5000000 number or w/e from the PR works for you?

If people are fine, we can make this a numerically-configurable option where the default is set to -500000 or w/e, and can still be changed...

**Comment by rhankache** [comment]
I used double this values, -1000000 , and it worked fine
For 147 TTrees (nominal+systematics) per job, the average memory usage was 1.2 GB
