### ISSUE TITLE
Add documentation on running docker

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#1181]
See #1168 for the relevant issue and fix:

```bash
find_packages(xAODAnaHelpers)
```

in your top-level CMakeLists.txt

and set

```bash
export xAODAnaHelpers_VERSION=$AnalysisBase_VERSION
```

**Comment by jbossios** [comment]
This is only needed for very very old images, so it doesn't worth documenting this anymore.
