### ISSUE TITLE
Interrupted by shell prompt when running locally

### ISSUE THREAD

**Issue by beojan** [UCATLAS/xAODAnaHelpers#1196]
When running locally using the direct driver, `xAH_run` is repeatedly interrupted by the shell prompt. Pressing `CTRL-D` at this prompt a couple of times gives the error:
`tput: No value for $TERM and no -T specified`, then after another couple of presses `xAH_run` continues further before being interrupted again the same way.

**Comment by kratsg** [comment]
Hi,

Are you using an interactive bash shell or not? https://askubuntu.com/a/592839

**Comment by beojan** [comment]
This is from within a ZSH script. The real problem is the dropping to a prompt, not the tput error.

This happens when SampleHandler is querying Rucio, which uses `sh::exec_read`, which calls `gSystem->Exec`, which (on *NIX) uses the C standard `system` function, which calls `/bin/sh -c`.

It appears the command is being incorrectly interpreted, causing the prompt.

**Comment by kratsg** [comment]
Ok, so this is an EL driver issue. Can you report to PATHelp?

**Comment by beojan** [comment]
Nevermind, solved. Turns out SampleHandler calls  `lsetup 'rucio -w'` and this wrapper version for some reason sources `.bash_profile`.

I have (had) a `.bash_profile` that then starts `zsh`, so I was getting a prompt.
