### ISSUE TITLE
PileUpReweighting in MuonCalibrator.cxx

### ISSUE THREAD

**Issue by prbbing** [UCATLAS/xAODAnaHelpers#1197]
Hi:

I ran into a problem when using MuonCalibrator.

Release: AnalysisBase21.2.22

The pileup reweighting was turned off in the BasicEventSelection. But I received the following error when running the MuonCalibrator:

EL::StatusCode MuonCalibrator::initialize()): A configured CP::PileupReweightingTool/Pileup must have been previously created! Are you creating one in xAH::BasicEventSelection?
/build1/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:48:exception: Algorithm::initialize returned StatusCode::FAILURE

It is traced back to line 128:

 if( isMC() ){
    if(!m_pileup_tool_handle.isUserConfigured()){
     ANA_MSG_FATAL("A configured " << m_pileup_tool_handle.typeAndName() << " must have been previously created! Are you creating one in xAH::BasicEventSelection?" );
     return EL::StatusCode::FAILURE;
    }

I temporarily commented off the lines in the if statement. The program runs fine now.

Maybe there is a way to avoid this in the BasicEventSelection?

Thanks in advance!

Cheers.

Bingxuan Liu

**Comment by kratsg** [comment]
I'm not sure why you want to calibrate muons without PURW. Remember that the PURW tool also adds a random number which is used by a variety of calibration/scale factor tools to correctly calculate certain things. I'm not sure it's recommended to turn it off here.

**Comment by ntadej** [comment]
Yes, you need random run numbers from PURW. You can always run it and then not apply the pile-up weights if for some reason you do not want to.

**Comment by prbbing** [comment]
Hi, thanks for your quick replies! 

I was trying to include the pileup reweighting at first but I got another error:

CP::TPileupReweighting... ERROR   No data loaded for period 300000. Did you forget to load a lumicalc file or data config file?

The corresponding flags in the BasicEventSelection:

"m_doPUreweighting"           : True,
"m_PRWFileNames"              : "Hto4bLLPAlgorithm/PRW_QCD.root",
"m_lumiCalcFileNames"         : "Hto4bLLPAlgorithm/ilumicalc_histograms_HLT_j380_303638-303892_OflLumi-13TeV-005.root",
"m_autoconfigPRW"             : True,

The I tried to turn off the pileup reweighting just hoping to see it at least run.

Am I using wrong iLumiCal  or PRW files?

Thanks a lot!!

**Comment by kratsg** [comment]
Your LumiCalc file looks wrong. Why not use the ones in the GroupData?

**Comment by prbbing** [comment]
Hi! Thanks! I switched to the files in GroupData and I still got the same error. 

But I might have found where the problem was. In the BasicEventSelection config, the m_autoconfigPRW is turned on. In the source code, https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BasicEventSelection.cxx#L533, it seems not to load the lumiCalFiles if autoconfig is turned on. 

I tried to set m_autoconfigPRW = false and it ran successfully.

I assume we want to load the lumiCalFiles as long as the pile up reweighting is turned on?

**Comment by kratsg** [comment]
@kkrizka ?

**Comment by mattleblanc** [comment]
I'm also getting this.

**Comment by kratsg** [comment]
Ok, I think I'm going to have to update the code to use the new autoconf provided by PURW tool soon. Unless anyone else wants to take it on so soon?

**Comment by kratsg** [comment]
This should be fine now.
