### ISSUE TITLE
Detail strings: valid options

### ISSUE THREAD

**Issue by vpascuzz** [UCATLAS/xAODAnaHelpers#1219]
Hi,
Not really and issue per se, but I was wondering if there is documentation available for possible detail strings, e.g. what details can I request for `m_trigDetailStr`?

Sorry in advance if this information is available and I missed it.

Best,
Vince.

**Comment by kratsg** [comment]
https://xaodanahelpers.readthedocs.io/en/master/HelperClasses.html - check out Jet Info Switch on that page.

**Comment by vpascuzz** [comment]
BTW: this issue can be closed.
