### ISSUE TITLE
TreeAlgo: FatJetContainerName flag is ignored 

### ISSUE THREAD

**Issue by francescorubbo** [UCATLAS/xAODAnaHelpers#122]
Tried to modify the example config file
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/data/test_treeExample.config

with 
```
FatJetContainerName   AntiKt10LCTopoJets
FatJetDetailStr       "kinematic"
```
but the output ntuple does not contain the corresponding branches.
The debug printout shows that the jet container is actually retrieved: http://pastebin.com/W0NxTfnv

**Comment by kratsg** [comment]
@gfacini - to put some context, it's being initialized as far as I can tell, and `TreeAlgo` seems to be retrieving the jets. I just don't know why it's not showing up in the output ntuple.

**Comment by mmilesi** [comment]
Hi all:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L1850

Seems not implemented yet?

**Comment by kratsg** [comment]
:+1: needs to be implemented! /cc @jdandoy @gfacini -- someone want to do it?

**Comment by francescorubbo** [comment]
Preliminary (only 4-momenta for now) implementation here: https://github.com/UCATLAS/xAODAnaHelpers/pull/130

**Comment by gfacini** [comment]
I think we can merge this in now or did I miss something?

**Comment by mmilesi** [comment]
Yes we can close it!
