### ISSUE TITLE
Crash on grid - Error in <BJetEfficiencyCorrector::execute()>: Problem in getEfficiencyScaleFactor

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#123]
Hi @johnda102 ,

I am seeing some of my grid jobs crashing because of an apparent error when trying to retrieve the btagging efficiency SF. See here for the full log of one of these jobs:

http://aipanda054.cern.ch/media/filebrowser/c222da13-e115-4d3e-981d-3de098a6a8f6/tarball_PandaJob_2511370410_ANALY_FZK/athena_stdout.txt

I am using the 'master' version of the xAH code for my submission.

This is the JetSelector config I am using: [link](https://svnweb.cern.ch/trac/atlasphys-hsg8/browser/Physics/Higgs/HSG8/AnalysisCode/multileptons/xAOD/HTopMultilepAnalysis/trunk/data/Jets/jetSelect_HTopMultilep_DxAOD-2015-13TeV.config)
And this is the BJetEffCorr config: [link](https://svnweb.cern.ch/trac/atlasphys-hsg8/browser/Physics/Higgs/HSG8/AnalysisCode/multileptons/xAOD/HTopMultilepAnalysis/trunk/data/Jets/bjetEffCorr_DxAOD-2015-13TeV.config)

Perhaps we should not throw an error when the SF can't be accessed, but just a warning: this actually happened only after successfully running on >112k events! What do you think?

Cheers

**Comment by johnda102** [comment]
agree.  closed with latest pull request.
Now do not return SC:Failure, just decorate with SF = -2
