### ISSUE TITLE
Unhandled, unknown C++ exception

### ISSUE THREAD

**Issue by vpascuzz** [UCATLAS/xAODAnaHelpers#1244]
Hi, friends.
AB: 21.2.39
xAH: 8550e6f9bd0359b3c003984638d8f04da5600514
Input: mc16_13TeV.361020.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ0W.deriv.DAOD_STDM4.e3569_s3126_r10201_r10210_p3596
PRW: mc16_13TeV.361020.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ0W.deriv.NTUP_PILEUP.e3569_s3126_r10201_r10210_p3384
MCCampaign: MC16d

I get a crash (running on 1 or 1000 events, so must be crashing on the first event) that I am sure is related to either the DAOD or PRW file:
```
...
JetCalibrate.JetCleani...DEBUG   DFCommon jet cleaning variable not available ... Using jet cleaning tool
JetCalibrate.JetUncert...DEBUG   Deleting JetUncertaintiesTool named JetCalibrate.JetUncertaintiesTool
DijetLepton_MuonSelect...DEBUG   Deleting MuonSelectionTool named DijetLepton_MuonSelector.MuonSelectionTool
eigenvariations destructor: removing 17 eigenvariations
eigenvariations destructor: removing 4 eigenvariations
eigenvariations destructor: removing 6 eigenvariations
eigenvariations destructor: removing 4 eigenvariations
                CalibrationDataInterfaceROOT object out-of-bounds summary:
                        No issues found
...
eigenvariations destructor: removing 14 eigenvariations
eigenvariations destructor: removing 4 eigenvariations
eigenvariations destructor: removing 6 eigenvariations
eigenvariations destructor: removing 4 eigenvariations
                CalibrationDataInterfaceROOT object out-of-bounds summary:
                        No issues found
worker finished:
Real time 0:00:18, CP time 17.030
[2018-09-12 22:19:10,998][ERROR  ]  --------------------
An exception was caught! (xAH_run.py:701)
Traceback (most recent call last):
  File "/afs/cern.ch/work/v/vpascuzz/private/analysis/lxqq/code/DijetFramework_r21/build/x86_64-slc6-gcc62-opt/bin/xAH_run.py", line 683, in <module>
    driver.submit(job, args.submit_dir)
Exception: void EL::Driver::submit(const EL::Job& job, const string& location) =>
    unhandled, unknown C++ exception
```

If it were a problematic PRW, I could imagine the PRW tool failing/complaining, but even with `m_msgLevel = "Debug"`, I get nothing more than what's shown above.

I've tried, to no avail, different input samples -- e.g. JZ0, JZ1, JZ2, etc.... -- with both self-generated PRWs and those available from the grid. Other inputs work fine, e.g.
mc16_13TeV.361104.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Wminusmunu.deriv.DAOD_STDM4.e3601_s3126_r10201_r10210_p3374

so I'm sure this isn't a problem with xAH, but instead inputs.

Any thoughts? Is there a way to check the integrity of the DAODs? I've run `checkPRW.py` and the results came back OK. Kind of out of ideas. Perhaps someone who knows what happens runs after `MuonSelectionTool` is destructed and I could have a better idea as to where the crash comes from.

Thanks in advance,
Vince.

**Comment by vpascuzz** [comment]
Complete logs can be found here:
```
/eos/atlas/user/v/vpascuzz/dijetlepton
```

`log.xAH_run_JZ0` fails, while `log.xAH_run_Wminusmunu` works fine.

Best,
Vince.

**Comment by kratsg** [comment]
Can you try it in 21.2.38 or 21.2.42? It looks like the error shows up after the job finishes.

**Comment by vpascuzz** [comment]
Thanks for the quick reply, @kratsg.

A change of release — good idea. (Just when I thought I had all avenues covered.)

Will give it a shot when I get back to work later this evening.

**Comment by vpascuzz** [comment]
Oui, mon ami -- 21.2.42 works fine!

**Comment by vpascuzz** [comment]
Oh, right. What the hell was the problem with 21.3.39 and the prejudice against multijet JZxW datasets? Any idea?

**Comment by kratsg** [comment]
I've heard 21.2.39 was buggy.

**Comment by vpascuzz** [comment]
Accepted answer. Thanks for the help.
