### ISSUE TITLE
Unrecognised channelNumber 410470 for periodNumber 310000

### ISSUE THREAD

**Issue by beojan** [UCATLAS/xAODAnaHelpers#1247]
I'm doing some tests on MC16e, and I'm getting the error
```
CP::TPileupReweighting... ERROR   Unrecognised channelNumber 410470 for periodNumber 310000
```

**Comment by ntadej** [comment]
Your PRW config is not complete. Are you using auto-config?

**Comment by beojan** [comment]
I thought I was, but it turns out I was on the wrong branch of my code.
