### ISSUE TITLE
Bug in JVT cut in JetSelector

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#1249]
Hello,

I just want to report that the JVT cut should be updated to use DetectorEta instead of eta at EM/Consit scale, since that eta is no longer the detector eta in R21:
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L1109

I never used that option but there might be someone using it.

Best,
Jona

**Comment by kratsg** [comment]
Shouldn't that be detector eta at the EM/Constit scale by default? Did this actually get changed (that seems like a really silent change)? Can you point me to the change in atlas/athena somewhere? I'm looking at what some other people currently do in R21 (such as ST) and it seems like we match, so this might have flown under the radar.

**Comment by mattleblanc** [comment]
Constituents are origin-corrected by default in R21, which will cause what Jona is reporting. The DetectorEta decoration should be used in cases where you care about the location of the jet within the actual detector geometry.

MLB

**Comment by kratsg** [comment]
> Constituents are origin-corrected by default in R21, which will cause what Jona is reporting. The DetectorEta decoration should be used in cases where you care about the location of the jet within the actual detector geometry.

Thanks @mattleblanc. Is DetectorEta decorated on all jets by default then? I believe in R20, this was not always the case, but maybe this changed. What do you do in cases where DetectorEta is missing (if that ever happens)? Have JVT fail?
