### ISSUE TITLE
Wrong sign inequality in JVT cut

### ISSUE THREAD

**Issue by kalderon** [UCATLAS/xAODAnaHelpers#1288]
https://github.com/UCATLAS/xAODAnaHelpers/blob/33fbde6d76031af33f52eac0288996363fdfe7c6/Root/JetSelector.cxx#L1110 asks for jet_jvt < m_JVTCut when it should be >

I wrote some more info at https://github.com/UCATLAS/xAODAnaHelpers/pull/1250

If this is indeed accidental, maybe it's easiest for someone with direct commit rights to just fix it?

**Comment by kalderon** [comment]
The previous logic was the other way around - i.e. jet_jvt < m_JVTCut led to the jet failing JVT as it should.

https://github.com/UCATLAS/xAODAnaHelpers/blob/8b9f476a948882b02a184f609bbc38d258fb6e41/Root/JetSelector.cxx#L1113

**Comment by vpascuzz** [comment]
We are feeling this harsh bug as well...what it looks like is we are accepting only pile-up jets and none with pT > 60 GeV.
PastedGraphic-2.png
PastedGraphic-3.png
