### ISSUE TITLE
Reorganize the data folder

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#129]
It's got quite a few files. Would be easier if we split it up into different folders like...
- GRL
- config
- json

etc.

**Comment by gfacini** [comment]
Can we do this and set a goal for a new release?

**Comment by kratsg** [comment]
@gfacini We would want to do it after EPS I think. You and @jdandoy are the big users right now?

**Comment by jdandoy** [comment]
Hi Giordon,

I'm doing a bit of that right now.  I'll have a branch soon, then I'll try
to clean up the configs as well.

Jeff

**Comment by kratsg** [comment]
Want to assign yourself to this issue Jeff?

**Comment by kratsg** [comment]
@jdandoy any progress on this?

**Comment by jdandoy** [comment]
After ignoring the problem for 1 year, it seems to have solved itself.  The data directory is pretty clean, I'll leave it as it is and close this.
