### ISSUE TITLE
module import error

### ISSUE THREAD

**Issue by rhankache** [UCATLAS/xAODAnaHelpers#1319]
after changing
    from xAODAnaHelpers.utils import parse_json
to
    import xAODAnaHelpers.utils as xAH_utils
    from xAH_utils import parse_json
(https://github.com/UCATLAS/xAODAnaHelpers/commit/da7c9f4f0b4a877b1e336463d97f160f97eb5e30#diff-cb5f08db26ddfc303ac493ddf5e08cb9R431)

I am getting the following error when running xAH_run.py
  **File "/afs/cern.ch/work/r/rhankach/workDir/jet_x_section/build/x86_64-slc6-gcc62-opt/bin/xAH_run.py", line 431, in <module>
    from xAH_utils import parse_json
  File "/cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.62/InstallArea/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named xAH_utils**

**Comment by ntadej** [comment]
That's not the correct python syntax. Once you import something, you can not import again from it.

You should use either
```
import xAODAnaHelpers.utils as xAH_utils
xAH_utils.parse_json()
```
or
```
from xAODAnaHelpers.utils import parse_json
```
or
```
import xAODAnaHelpers.utils as xAH_utils
from xAODAnaHelpers.utils import parse_json
```

**Comment by rhankache** [comment]
Thanks for the reply.
Yes I replaced in my local file only the line 431 from:
    from xAH_utils import parse_json
to
    from xAODAnaHelpers.utils import parse_json
and things work fine.

We need to correct the git code.
Do you want me to do the change and commit it?

**Comment by kratsg** [comment]
you can also additionally just do

```python
import xAODAnaHelpers
# xAODAnaHelpers.utils.parse_json
```

or

```python
import xAODAnaHelpers as xAH
# xAH.utils.parse_json
```

Note that the change was made to separate things a bit better (it makes `xAH_run.py` much shorter/easier to read) and a bit more robust to pre-compilation versus post-compilation.

**Comment by rhankache** [comment]
I corrected the code and sent a merge request.
Thanks.
