### ISSUE TITLE
Custom jet calibration files

### ISSUE THREAD

**Issue by akilgall** [UCATLAS/xAODAnaHelpers#1322]
Hello, I am trying to include a custom calibration configuration file for use by the JetCalibrator algorithm.  I was told that this could be achieved by putting the file in the src/xAODAnaHelpers/data directory, rerunning cmake and make, and then specifying the config file by the following:

        c.algorithm("JetCalibrator",     {
        "m_name"                    :   "2016calib",

        "m_inContainerName"         :   "HLT_xAOD__JetContainer_a4tcemsubjesFS",
        "m_jetAlgo"                 :   "AntiKt4EMTopoTrig",
        "m_outContainerName"        :   "AntiKt4EMTopoJets_Calib",
        "m_outputAlgo"              :   "AntiKt4EMTopoJets_Calib_Algo",
        "m_sort"                    :   True,
        "m_redoJVT"                 :   False,
        #----------------------- Systematics ----------------------------#
        "m_systName"                :   "Nominal",            ## For data
        "m_systVal"                 :   0,                    ## For data
        #----------------------- Calibration ----------------------------#
        "m_calibConfigFullSim"      :   "xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config",
 
        "m_calibSequence"           :   "EtaJES_GSC", # GSC needs changes to JetCalibTools
        "m_overrideCalibArea"       :   "00-04-81",
        "m_jetCalibToolsDEV"        :   True
        )}

However, I get the following error:

JetCalibrator.2016calib  INFO    Number of events in file: 60000
JetCalibrator.2016calib  WARNING Could not access simulation flavour from EL::Worker. Treating MC as FullSim by default!
JetCalibrator.2016calib  WARNING Overriding jet calibration area to 00-04-81
2016calib.JetCalibrati...INFO    Initializing 2016calib.JetCalibrationTool...
2016calib.JetCalibrati...INFO    ===================================
2016calib.JetCalibrati...INFO    Initializing the xAOD Jet Calibration Tool for AntiKt4EMTopoTrigjets
2016calib.JetCalibrati...WARNING Dev Mode is ON!!!
2016calib.JetCalibrati...WARNING Dev Mode is NOT RECOMMENDED!!!
PathResolver             WARNING Could not locate JetCalibTools/xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config
2016calib.JetCalibrati...INFO    Reading global JES settings from: xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config
2016calib.JetCalibrati...INFO    resolved in:
TEnv::ReadFile            ERROR   no file name specified
2016calib.JetCalibrati...FATAL   /build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Reconstruction/Jet/JetCalibTools/Root/JetCalibrationTool.cxx:106 (virtual StatusCode JetCalibrationTool::initializeTool(const string&)): Cannot read config file

How do I include custom calibration files?   Thank you

**Comment by kratsg** [comment]
This looks like a problem with the JetCalibTool actually. @jdandoy do you know why it's prepending a "JetCalibTools" in the front?

**Comment by kratsg** [comment]
Update: looks like you need to turn off dev-mode since it'll preprend with `JetCalibTools/` in the front [which seems like a bad idea that it's hard-coded]: https://gitlab.cern.ch/atlas/athena/blob/21.2/Reconstruction/Jet/JetCalibTools/Root/JetCalibrationTool.cxx#L91-97

```
  if ( config.EqualTo("") || !config ) { ATH_MSG_FATAL("No configuration file specified."); return StatusCode::FAILURE; } 
  // The calibration area tag is a property of the tool
  const std::string calibPath = "CalibArea-" + m_calibAreaTag + "/";
  if(m_devMode){
    ATH_MSG_WARNING("Dev Mode is ON!!!");
    ATH_MSG_WARNING("Dev Mode is NOT RECOMMENDED!!!");
    dir = "JetCalibTools/";
  }
  else{dir.insert(14,calibPath);} // Obtaining the path of the configuration file
  std::string configPath=dir+m_config; // Full path
  TString fn =  PathResolverFindCalibFile(configPath);
```

**Comment by akilgall** [comment]
I turned off dev-mode, and it is still unable to find the file:

JetCalibrator.2016calib  INFO    Initializing JetCalibrator Interface...
JetCalibrator.2016calib  INFO    Number of events in file: 60000
JetCalibrator.2016calib  WARNING Could not access simulation flavour from EL::Worker. Treating MC as FullSim by default!
JetCalibrator.2016calib  WARNING Overriding jet calibration area to 00-04-81
2016calib.JetCalibrati...INFO    Initializing 2016calib.JetCalibrationTool...
2016calib.JetCalibrati...INFO    ===================================
2016calib.JetCalibrati...INFO    Initializing the xAOD Jet Calibration Tool for AntiKt4EMTopoTrigjets
PathResolver             WARNING Could not locate JetCalibTools/CalibArea-00-04-81/CalibrationConfigs/xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config
2016calib.JetCalibrati...INFO    Reading global JES settings from: xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config
2016calib.JetCalibrati...INFO    resolved in:
TEnv::ReadFile            ERROR   no file name specified
2016calib.JetCalibrati...FATAL   /build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Reconstruction/Jet/JetCalibTools/Root/JetCalibrationTool.cxx:106 (virtual StatusCode JetCalibrationTool::initializeTool(const string&)): Cannot read config file
2016calib.JetCalibrati...ERROR   /build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Reconstruction/Jet/JetCalibTools/Root/JetCalibrationTool.cxx:62 (virtual StatusCode JetCalibrationTool::initialize()): Failed to call "this->initializeTool( name() )"
AsgTools_AnaToolHandle   ERROR   /build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:421 (StatusCode asg::detail::AnaToolConfig::makeToolRootCore(const string&, asg::IAsgTool*&, asg::detail::AnaToolCleanup&) const): Failed to call "rawToolPtr->initialize()"
AsgTools_AnaToolHandle   ERROR   /build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:505 (StatusCode asg::detail::AnaToolConfig::makeBaseTool(const string&, asg::parentType_t*, ToolHandle<asg::IAsgTool>&, asg::detail::AnaToolCleanup&) const): Failed to call "makeToolRootCore (toolName, baseToolPtr, baseCleanup)"
AsgTools_UserCode        ERROR   /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.52/InstallArea/x86_64-slc6-gcc62-opt/src/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:551 (StatusCode asg::detail::AnaToolConfig::makeTool(const string&, asg::parentType_t*, ToolHandle<T>&, asg::detail::AnaToolCleanup&) const [with ToolType = IJetCalibrationTool; std::__cxx11::string = std::__cxx11::basic_string<char>; asg::parentType_t = INamedInterface]): Failed to call "makeBaseTool (name, parent, baseTH, baseCleanup)"
AsgTools_AnaToolHandle   ERROR   /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.52/InstallArea/x86_64-slc6-gcc62-opt/src/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:819 (StatusCode asg::AnaToolHandle<T>::initialize() [with T = IJetCalibrationTool]): Failed to call "m_config.makeTool (m_name, m_parentPtr, th, cleanup)"
JetCalibrator.2016calib  ERROR   /export/home/aakilgal/comp/src/xAODAnaHelpers/Root/JetCalibrator.cxx:232 (virtual EL::StatusCode JetCalibrator::initialize()): Failed to call "m_JetCalibrationTool_handle.retrieve()"
/build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:49:exception: Algorithm::initialize returned StatusCode::FAILURE
worker finished:
Real time 0:00:08, CP time 5.540
[2019-02-14 08:50:18,403][ERROR  ]  --------------------
An exception was caught! (xAH_run.py:706)
Traceback (most recent call last):
  File "/export/home/aakilgal/comp/build/x86_64-slc6-gcc62-opt/bin/xAH_run.py", line 688, in <module>
    driver.submit(job, args.submit_dir)
Exception: void EL::Driver::submit(const EL::Job& job, const string& location) =>
    /build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:49:exception: Algorithm::initialize returned StatusCode::FAILURE (C++ exception of type RCU::ExceptionMsg)

**Comment by kratsg** [comment]
We're gonna need to add a patch to allow for a custom `ConfigDir`.

**Comment by kratsg** [comment]
After I apply the patch, you'll be able to do

```
    "m_calibConfigFullSim"      :   "JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config",
    "m_calibDir": "xAODAnaHelpers/",
```

**Comment by kratsg** [comment]
When #1323 is merged in, you can grab master of xAH and try again with the above suggested configuration.

**Comment by akilgall** [comment]
Thank you for the fast response time!  I'll test it and let you know if it isn't successful.

**Comment by kratsg** [comment]
You can also run `git fetch && git checkout feature/JetCalibToolsConfigDir` and test on that branch if you want to test now.

**Comment by kratsg** [comment]
@akilgall , it's merged in. If you can confirm it works for you with the latest of xAH (21.2.61+) then we can close this ticket.

**Comment by akilgall** [comment]
I'm not sure if this is an issue on my end or not:

JetCalibrator.2016calib  INFO    Initializing JetCalibrator Interface...
JetCalibrator.2016calib  INFO    Number of events in file: 60000
JetCalibrator.2016calib  WARNING Could not access simulation flavour from EL::Worker. Treating MC as FullSim by default!
JetCalibrator.2016calib  WARNING Overriding jet calibration area to 00-04-81
2016calib.JetCalibrati...INFO    Initializing 2016calib.JetCalibrationTool...
2016calib.JetCalibrati...INFO    ===================================
2016calib.JetCalibrati...INFO    Initializing the xAOD Jet Calibration Tool for AntiKt4EMTopoTrigjets
PathResolver             WARNING Could not locate xAODAnaHelpersCalibArea-00-04-81//JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config
2016calib.JetCalibrati...INFO    Reading global JES settings from: JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config
2016calib.JetCalibrati...INFO    resolved in:
TEnv::ReadFile            ERROR   no file name specified
2016calib.JetCalibrati...FATAL   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Reconstruction/Jet/JetCalibTools/Root/JetCalibrationTool.cxx:106 (virtual StatusCode JetCalibrationTool::initializeTool(const string&)): Cannot read config file
2016calib.JetCalibrati...ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Reconstruction/Jet/JetCalibTools/Root/JetCalibrationTool.cxx:62 (virtual StatusCode JetCalibrationTool::initialize()): Failed to call "this->initializeTool( name() )"
AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:421 (StatusCode asg::detail::AnaToolConfig::makeToolRootCore(const string&, asg::IAsgTool*&, asg::detail::AnaToolCleanup&) const): Failed to call "rawToolPtr->initialize()"
AsgTools_AnaToolHandle   ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/Control/AthToolSupport/AsgTools/Root/AnaToolHandle.cxx:505 (StatusCode asg::detail::AnaToolConfig::makeBaseTool(const string&, asg::parentType_t*, ToolHandle<asg::IAsgTool>&, asg::detail::AnaToolCleanup&) const): Failed to call "makeToolRootCore (toolName, baseToolPtr, baseCleanup)"
AsgTools_UserCode        ERROR   /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.61/InstallArea/x86_64-slc6-gcc62-opt/src/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:551 (StatusCode asg::detail::AnaToolConfig::makeTool(const string&, asg::parentType_t*, ToolHandle<T>&, asg::detail::AnaToolCleanup&) const [with ToolType = IJetCalibrationTool; std::__cxx11::string = std::__cxx11::basic_string<char>; asg::parentType_t = INamedInterface]): Failed to call "makeBaseTool (name, parent, baseTH, baseCleanup)"
AsgTools_AnaToolHandle   ERROR   /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.61/InstallArea/x86_64-slc6-gcc62-opt/src/Control/AthToolSupport/AsgTools/AsgTools/AnaToolHandle.icc:819 (StatusCode asg::AnaToolHandle<T>::initialize() [with T = IJetCalibrationTool]): Failed to call "m_config.makeTool (m_name, m_parentPtr, th, cleanup)"
JetCalibrator.2016calib  ERROR   /export/home/aakilgal/comp/src/xAODAnaHelpers/Root/JetCalibrator.cxx:235 (virtual EL::StatusCode JetCalibrator::initialize()): Failed to call "m_JetCalibrationTool_handle.retrieve()"
EventLoop                ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/AlgorithmStateModule.cxx:42 (StatusCode EL::Detail::{anonymous}::forAllAlgorithms(EL::Detail::ModuleData&, const char*, F&&) [with F = EL::Detail::AlgorithmStateModule::onNewInputFile(EL::Detail::ModuleData&)::<lambda(EL::Detail::AlgorithmData&)>]): executing initialize on algorithm 2016calib
EventLoop                ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:517 (StatusCode EL::Worker::processEvents(EL::EventRange&)): Failed to call "module->onNewInputFile (*this)"
EventLoop                ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/DirectWorker.cxx:93 (void EL::DirectWorker::run()): Failed to call "processEvents (eventRange)", throwing exception
EventLoop                INFO    worker finished

**Comment by kratsg** [comment]
What's your config? Did you update it?

**Comment by akilgall** [comment]
c.algorithm("JetCalibrator",     {
        "m_name"                    :   "2016calib",
        #----------------------- Container Flow ----------------------------#
        "m_inContainerName"         :   "HLT_xAOD__JetContainer_a4tcemsubjesFS",
        "m_jetAlgo"                 :   "AntiKt4EMTopoTrig",
        "m_outContainerName"        :   "AntiKt4EMTopoJets_Calib",
        "m_outputAlgo"              :   "AntiKt4EMTopoJets_Calib_Algo",
        "m_sort"                    :   True,
        "m_redoJVT"                 :   False,
        #----------------------- Systematics ----------------------------#
        "m_systName"                :   "Nominal",            ## For data
        "m_systVal"                 :   0,                    ## For data
        #----------------------- Calibration ----------------------------#
        #"m_calibConfigData"         :   "xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config",
        #"m_calibConfigFullSim"      :   "xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config",
        #"m_calibConfigAFII"         :   "xAODAnaHelpers/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK_rel21.config",

        "m_calibConfigData"         :   "JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config",
        "m_calibConfigFullSim"      :   "JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config",
        "m_calibConfigAFII"         :   "JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config",
        "m_calibConfigDir": "xAODAnaHelpers/",
        "m_calibSequence"           :   "EtaJES_GSC", # GSC needs changes to JetCalibTools
        "m_overrideCalibArea"       :   "00-04-81",
        "m_jetCalibToolsDEV"        :   False,
        #----------------------- Cleaning ----------------------------#
        "m_doCleaning"              :   False,
        "m_jetCleanCutLevel"        :   "",
        "m_jetCleanUgly"            :   False,
        "m_saveAllCleanDecisions"   :   True,
        "m_cleanParent"             :   False,

        # "m_doCleaning"            :   False,
        # "m_jetCleanCutLevel"      :   "LooseBadTrigger",
        # "m_saveAllCleanDecisions" :   False,
        # "m_isTrigger"             :   True,

        } )

c.setalg("qcdAna", {})

**Comment by kratsg** [comment]
Hrmm, disable dev-mode and try again.

**Comment by akilgall** [comment]
Is this not sufficient for disabling it?  

    "m_jetCalibToolsDEV"        :   False,

**Comment by kratsg** [comment]
This is an issue with the Jet/MET software now.

**Comment by akilgall** [comment]
Do you know who I should bounce this issue to?

**Comment by jdandoy** [comment]
It is a bit messy, could probably get JetCalibTools changed with a complaint, but it's meant to look into a local version of JetCalibTools for the new configs.  Have you tried just making a JetCalibTools folder next to xAODAnaHelpers?

**Comment by akilgall** [comment]
So place the config file in src/JetCalibTools/data?

**Comment by kratsg** [comment]
> It is a bit messy, could probably get JetCalibTools changed with a complaint, but it's meant to look into a local version of JetCalibTools for the new configs. Have you tried just making a JetCalibTools folder next to xAODAnaHelpers?

Problem is that CMake will see two targets of the same name when trying to deal with sym-links and so on -- so it might not be able to work that way. But he's on the right track that atm, you'll have to somehow massage your config locations to be in a place that the JetCalibTools will pick it up from.

**Comment by jdandoy** [comment]
Worth a try, if it doesn't work then a sparse checkout of JetCalibTools will get it to work.  I agree this can be burdensome, so might be worth messaging Maria Daneri who is currently in charge of the package, as well as Jona Bossio who did much of the development.

**Comment by kratsg** [comment]
pinging @jbossios  :) good point @jdandoy

**Comment by akilgall** [comment]
I placed the config file in src/JetCalibTools/CalibArea-00-04-81/CalibrationConfigs/, and it doesn't seem to be able to find it, even after a cmake.

JetCalibrator.2016calib  INFO    Initializing JetCalibrator Interface...
JetCalibrator.2016calib  INFO    Number of events in file: 60000
JetCalibrator.2016calib  WARNING Could not access simulation flavour from EL::Worker. Treating MC as FullSim by default!
JetCalibrator.2016calib  WARNING Overriding jet calibration area to 00-04-81
2016calib.JetCalibrati...INFO    Initializing 2016calib.JetCalibrationTool...
2016calib.JetCalibrati...INFO    ===================================
2016calib.JetCalibrati...INFO    Initializing the xAOD Jet Calibration Tool for AntiKt4EMTopoTrigjets
PathResolver             WARNING Could not locate JetCalibTools/CalibArea-00-04-81/CalibrationConfigs/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config
2016calib.JetCalibrati...INFO    Reading global JES settings from: JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config
2016calib.JetCalibrati...INFO    resolved in:
TEnv::ReadFile            ERROR   no file name specified

**Comment by kratsg** [comment]
It needs to be added to `build/x86_64-slc6-gcc62-opt/data/JetCalibTools/CalibArea-00-04-81/CalibrationConfigs/JES_Nov2017_Full2016Data_TLA_AllCalib_trig_periodAtoK.config` for it to be picked up right.

**Comment by jbossios** [comment]
Hi

I agree, this should be improved so people don't need to checkout JetCalibTools. We needed to append JetCalibTools because inside each config file there is (hardcoded) the path to the rest of the config files which assumes some structure. I would say also that when implemented it was meant to be used as a way of easily test new codes+configs. Now, it is more widely used and should be simplified.

Best,
Jona

**Comment by jbossios** [comment]
Outside the dev mode, JetCalibTools will expect a particular structure of the folders (for example,JetCalibTooll/CalibArea-XX-YY-ZZ/CalibrationConfigs) for all the configs, and is different for the internal configs. So that will not work without modifying JetCalibTools.

**Comment by mattleblanc** [comment]
Why do you need to use a nonstandard config? There are basically no circumstances when this should need to happen unless it is to develop the calibration, in which case dev mode does exactly what is requested here. I've used dev mode + xAH with a sparse checkout often, and it works well.

MLB

**Comment by akilgall** [comment]
Hi,
It seems to be finding the file correctly, so that is a workaround.

Matt, the custom TLA calibration isn't in the standard configs, and we were hoping to be able to implement it quickly without having to do a sparse checkout with dev mode, which is cumbersome.

Unfortunately it crashes, but for other reasons that are probably unrelated.  Thanks for the help everyone!

BasicEventSelection.my...INFO    Entry number = 0
BasicEventSelection.my...INFO    *** Triggers used (in OR) are:

BasicEventSelection.my...INFO           L1_J100
ToolSvc.TrigDecisionTool INFO    decision not set on first (?) assert. deciding how to unpack
ToolSvc.TrigDecisionTool INFO    SG contains xAOD decision, use DecisionUnpackerStandalone
EventLoop                ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/MessageCheck.cxx:41 (void EL::Detail::report_exception()): caught exception: SG::ExcBadAuxVar: Attempt to retrieve nonexistent aux data item `::JetConstitScaleMomentum_pt' (70).
EventLoop                ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:673 (StatusCode EL::Worker::algsExecute()): while calling execute() on algorithm 2016calib
EventLoop                ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:533 (StatusCode EL::Worker::processEvents(EL::EventRange&)): Failed to call "algsExecute ()"
EventLoop                ERROR   /build1/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/DirectWorker.cxx:93 (void EL::DirectWorker::run()): Failed to call "processEvents (eventRange)", throwing exception
EventLoop                INFO    worker finished
[2019-02-14 10:06:23,080][ERROR  ]  --------------------
