### ISSUE TITLE
Systematics for multiple jet algorithms

### ISSUE THREAD

**Issue by rhankache** [UCATLAS/xAODAnaHelpers#1333]
Dear all,

I am producing ntuples with both EMTopo and EMPFlow jets in the same time.
I want to produce the systematic variations of these jet algos also in the time.

The json files I am using is:
```[
  { "class": "BasicEventSelection",
    "configs": {
      "m_name": "basicEventSel",
      "m_truthLevelOnly": false,
      "m_applyGRLCut": false,
      "m_GRLxml": "",
      "m_doPUreweighting": false,
      "m_applyPrimaryVertexCut": true,
      "m_vertexContainerName": "PrimaryVertices",
      "m_PVNTrack": 2,
      "m_checkDuplicatesMC": true,
      "m_derivationName": "STDM11Kernel"
    }
  },

  { "class": "JetCalibrator",
    "configs": {
      "m_calibConfigFullSim": "JES_data2017_2016_2015_Consolidated_EMTopo_2018_Rel21.config",
      "m_name": "jetCalib",
      "m_calibSequence": "JetArea_Residual_EtaJES_GSC_Smear",
      "m_sort": true,
      "m_doCleaning": true,
      "m_jetCleanCutLevel": "LooseBad",
      "m_saveAllCleanDecisions": true,
      "m_jetCleanUgly": false,
      "m_inContainerName": "AntiKt4EMTopoJets",
      "m_outContainerName": "AntiKt4EMTopoJets_Nominal",
      "m_jetAlgo": "AntiKt4EMTopo",
      "m_outputAlgo": "AntiKt4EMTopoJets_Nominal_Algo",
      "m_uncertConfig": "rel21/Fall2018_fullStatUncertanties/R4_AllNuisanceParameters_2017_AllJERNP.config",
      "m_systName": "All",
      "m_systVal" : 1,
      "m_pseudoData" : true
    }
  },

   { "class": "JetSelector",
     "configs": {
      "m_inContainerName": "AntiKt4EMTopoJets_Nominal",
      "m_name": "jetSel",
      "m_inputAlgo": "AntiKt4EMTopoJets_Nominal_Algo",
      "m_decorateSelectedObjects": true,
      "m_createSelectedContainer": true,
      "m_outContainerName": "AntiKt4EMTopoJets_Signal",
      "m_outputAlgo":  "AntiKt4EMTopoJets_Signal_Algo",
      "m_cleanJets": false,
      "m_pT_min": 30e3,
      "m_useCutFlow": true
    }
   },

  { "class": "JetCalibrator",
    "configs": {
      "m_calibConfigFullSim": "JES_data2017_2016_2015_Consolidated_PFlow_2018_Rel21.config",
      "m_name": "jetCalibPFlow",
      "m_calibSequence": "JetArea_Residual_EtaJES_GSC_Smear",
      "m_sort": true,
      "m_doCleaning": false,
      "m_jetCleanCutLevel": "LooseBad",
      "m_saveAllCleanDecisions": true,
      "m_jetCleanUgly": false,
      "m_inContainerName": "AntiKt4EMPFlowJets",
      "m_outContainerName": "AntiKt4EMPFlowJets_Nominal",
      "m_jetAlgo": "AntiKt4EMPFlow",
      "m_outputAlgo": "AntiKt4EMPFlowJets_Nominal_Algo",
      "m_uncertConfig": "rel21/Fall2018_fullStatUncertanties/R4_AllNuisanceParameters_2017_AllJERNP.config",
      "m_systName": "All",
      "m_systVal" : 1,
      "m_pseudoData" : true
    }
  },

   { "class": "JetSelector",
     "configs": {
      "m_inContainerName": "AntiKt4EMPFlowJets_Nominal",
      "m_name": "jetSelPFlow",
      "m_inputAlgo": "AntiKt4EMPFlowJets_Nominal_Algo",
      "m_decorateSelectedObjects": true,
      "m_createSelectedContainer": true,
      "m_outContainerName": "AntiKt4EMPFlowJets_Signal",
      "m_outputAlgo":  "AntiKt4EMPFlowJets_Signal_Algo",
      "m_cleanJets": false,
      "m_pT_min": 30e3,
      "m_useCutFlow": true
    }
   },


   { "class": "JetSelector",
     "configs": {
      "m_name": "TruthSelector",
      "m_inContainerName": "AntiKt4TruthWZJets",
      "m_decorateSelectedObjects": true,
      "m_createSelectedContainer": true,
      "m_outContainerName": "AntiKt4TruthWZJets_Signal",
      "m_outputAlgo":  "AntiKt4TruthWZJets_Signal_Algo",
      "m_cleanJets": false,
      "m_pT_min": 30e3,
      "m_useCutFlow": true
    }
   },

   { "class": "TreeAlgo",
     "configs": {
      "m_name": "treeAlgo",
      "m_jetContainerName": "AntiKt4EMTopoJets_Signal AntiKt4EMPFlowJets_Signal",
      "m_jetBranchName": "jet EMPFlowJet",
      "m_jetDetailStr": "kinematic rapidity energyLight layer cleanLight scales truth",
      "m_truthJetContainerName": "AntiKt4TruthWZJets_Signal",
      "m_truthJetDetailStr": "kinematic rapidity",
      "m_evtDetailStr": "pileup",
      "m_jetSystsVec": "AntiKt4EMTopoJets_Signal_Algo",
      "m_systName": "All"
    }
  }

]
```

Using this config, only EMTopo jets are varied.
Even if I put "m_jetSystsVec": "AntiKt4EMPFlowJets_Signal_Algo", only EMTopo jets are varied.

If I generate separate ntuples for each jet algo, things work well.
But I want to have to have them in the same ntuple.
Is there a way to do that?

Thanks,

**Comment by kratsg** [comment]
You can just run multiple tree algorithms. Nothing's stopping you from doing that and pointing it at the same tree -- or different tree -- and hadd'ing at the end.

**Comment by rhankache** [comment]
What I wanted is to have in each tree entry both the jet algos with their systematic variations.
If I understand well what you suggest, this will create double the entries with each time one of the jet algos.
Is that right?

**Comment by kratsg** [comment]
No. It's done event-by-event. So TreeAlgo is adding branches to a tree.

**Comment by rhankache** [comment]
Sorry but I don't get what I should do.
If I create two "class": "TreeAlgo", I get an error:
please make sure that every output stream has a unique label.

**Comment by kratsg** [comment]
Because you can't have the same `m_name` here. It will make a separate tree for this. I think you're asking for something significantly more custom than any framework can do. xAH is custom-enough so maybe you can rework the logic of what you want to fit with the independent-algorithm-drop-in model that xAH does.

**Comment by rhankache** [comment]
No I am not doing anything special here.
I found out the issue.
The json file I attached earlier is fine.
The issue comes from the code.
In the loop at https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/TreeAlgo.cxx#L398 , it is explicitly coded to take the systematic value only for the first jet container (L400). For the others, it will use the nominal values even for the systematic trees.

I removed the if condition at L400.
Everything works fine for me.

Could this just be a bug, or is there some reason for it?
Could there be some cases where we should only use the systematic for the first jet container?
Maybe someone recalls why it was coded like that.

**Comment by kratsg** [comment]
This is a good question -- @jbossios added this in #779 a long time ago and might be able to comment on the specifities here. Nothing comes to mind why we only look at the first, but I might be missing something obvious.

**Comment by jbossios** [comment]
Hi @rhankache 

I honestly didn't even think about systematics when I implemented this. I only needed to save more than one jet collection at the nominal scale. So far, nobody else needed to store more than one collection together with systematics but if you need to and know how to solve it, I would say go ahead and extend the current functionality, it might be beneficial for some other people in the future.

Best,
Jona

**Comment by rhankache** [comment]
Thanks @kratsg and @jbossios ,
I did the changes and sent the pull request.

The only thing I want to note is that when running systematics on multiple jet container, obviously they should have the same syst configuration in the JetCalibrator class (same m_systName and m_systVal).

Best,

**Comment by kratsg** [comment]
Done in #1334.
