### ISSUE TITLE
Adding primary vertex variables to ntuples?

### ISSUE THREAD

**Issue by ecorrigan** [UCATLAS/xAODAnaHelpers#1335]
Hi!

I would like to add the z position of the hard-scatter (first) PV to some ntuples I'm making. As far as I can see, there is no way to do this currently implemented, right? I am happy to implement something (perhaps an event-level detailString keyword that saves PV_z for the first entry in the PV vector), but I just wanted to make sure that I haven't missed an existing method first.

Thanks!

Eric

**Comment by kratsg** [comment]
I'm not sure -- email the mailing list to check that this functionality doesn't already exist (I'd be somewhat surprised nobody's needed that information before now...)

**Comment by jbossios** [comment]
Closing since I added that feature a few months after this issue was created (https://github.com/UCATLAS/xAODAnaHelpers/pull/1356).
