### ISSUE TITLE
Rethink SLC6 check

### ISSUE THREAD

**Issue by beojan** [UCATLAS/xAODAnaHelpers#1336]
LXPLUS has now been switched to CC7. The SLC6 check when submitting grid jobs means it's no longer possible to submit an xAH grid job from LXPLUS.

`lxplus6` is an option for now but I expect it will be removed at some point. In the meantime, the error message could at least explain the situation and suggest the user try `lxplus6.cern.ch`.

**Comment by ntadej** [comment]
You can also use `setupATLAS -c slc6` to run in a SLC6 container.

**Comment by kratsg** [comment]
We most likely need to figure out how to submit jobs from CC7 correctly -- and Asoka sent an email outlining some of the ways to do it that I can look at tomorrow - unless someone else gets to it.

**Comment by lschaefer** [comment]
I tried using `setupATLAS -c slc6` and still I'm getting the SLC6 error -- it could easily be an issue on my side but at least for me it's not obvious that this fixes the problem.

**Comment by kkrizka** [comment]
I'm trying to submit to the grid from a CC7 machine too, via the slc6 container (`setupATLAS -c slc6`). The xAH_run.py check also fails for me, but disabling it shows no further issues. Although I am still waiting for the jobs to start (the state is still [submitting](https://bigpanda.cern.ch/tasks/?taskname=user.kkrizka.*.20190404-test-01*&display_limit=2000)).

It seems that the image Asoka created is based on CC6 and not SLC6. We only allow SLC6 or RHEL6. I'll submit an PR adding CC6 to the list.

```
kkrizka@cori05 ~/DijetISRCode_Organizer/build $ lsb_release -d
Description:    CentOS release 6.10 (Final)
kkrizka@cori05 ~/DijetISRCode_Organizer/build $ cat /etc/redhat-release 
CentOS release 6.10 (Final)
```

**Comment by kratsg** [comment]
Closing due to #1338 for now. If submission from CC7 works fine, then we can remove the check -- but this issue is specifically about work-arounds on CC7.
