### ISSUE TITLE
Corrections applied to Data

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#134]
Hi All,

Are we sure that the tools that should not apply corrections to data are not doing this?  I.E. Marco and I are discussing now the MuonCalibrator and I am wondering what the BJetEfficiencyCorrector if given a set of jets from data?

Can we please double check this?  I do not think we can rely on the user to know what to do - we need to make some dummy proofing.

Cheers,
Gabriel

**Comment by kratsg** [comment]
I agree. I'm starting to run into very annoying subtle problems with branch access versus class access mode in https://github.com/kratsg/TheAccountant/issues/63 which is sort of related to dummy proofing. Let me make an appropriate commit that to discuss this.

**Comment by mmilesi** [comment]
Ok, it seems that based on the [latest recommendations](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/MCPAnalysisGuidelinesMC15#Muon_selection_Loose_Medium_and) I am not doing the right thing in the muon calibrator. At the moment I am correcting both data and mc, but looks like it should be only MC.

I am going to make a PR with the fix. However, before merging it, I will double check with the muon guys that applying the calibration only to MC is really the right thing to do.

We'll touch base tomorriow morning (CERN time)

Marco

**Comment by kratsg** [comment]
See the above commit. This adds two new features:

The following are meant to be used within `execute()` only:
- use `isMC() == 1` to verify that it is MC
- use `isMC() == 0` to verify that it is data
- `isMC() == -1` will occur if one cannot identify whether it is data or MC

If you wish to override this automatic detection, you can set `m_isMC` on any algorithm to `0` or `1

**Comment by kratsg** [comment]
@mmilesi where do we stand on this issue? We will still need to onboard code with the `isMC()` function that is newly available.

**Comment by mmilesi** [comment]
Hi @kratsg ,

the issue can be closed. The calibration for muons must be on MC only. I already merged the PR #135  .

I am goping to open an issue regarding the change to isMC() across the board (there are many places where the change should be done...)
