### ISSUE TITLE
Queue error when running on Condor

### ISSUE THREAD

**Issue by rhankache** [UCATLAS/xAODAnaHelpers#1344]

**Comment by rhankache** [comment]
When running using condor option, I am getting the following error:
ERROR: "submit" doesn't contain any "queue" commands -- no jobs queued

my submission is like:
xAH_run.py --files XXX --submitDir=XXX --config XXX.json condor

Can you advise?
Thanks,

**Comment by kratsg** [comment]
Did you set up your X509 proxy?

**Comment by kkrizka** [comment]
Hi @rhankache ,

Not sure if I am the best person to help here. I no longer use condor, so I am not sure what the state of the driver is. But let's try.

1. What AnalysisBase release are you running?
2. Are you running on lxbatch or some other cluster?
3. Can you post the contents of `XXX/submit/submit`, where XX is your submitDir?

--
Karol Krizka

**Comment by mattleblanc** [comment]
Try an `lsetup rucio` and then re-queue. I think that your environment does not include something like e.g.

```
X509_USER_PROXY=/tmp/x509up_u43257
```

MLB

**Comment by rhankache** [comment]
Thanks all for your replies.
Indeed, setting up rucio (and thus X509 proxy) solved the problem.
