### ISSUE TITLE
Grid submission from centos7

### ISSUE THREAD

**Issue by kalderon** [UCATLAS/xAODAnaHelpers#1357]
With the latest analysis release (21.2.90) not coming with an slc6 install, it seemed like it might be time to revisit #1336? I didn't follow the original problem so I don't know if it was xAODAnaHelpers-specific or for all centos7, and hence whether this is just a matter of removing an obsolete check or needs some work.

**Comment by kratsg** [comment]
Yes, let me invert the check and support only 21.2.90 for docker image building.
