### ISSUE TITLE
Ordering of objectName and detailStr arguments in HelpTreeBase

### ISSUE THREAD

**Issue by taehyounpark** [UCATLAS/xAODAnaHelpers#1371]
Hi everyone,

This is a very minor point but I've noticed that the Add*() methods for some objects (TrackParts, TruthParts) in HelpTreeBase have different ordering of arguments from others.

Most:
`
AddSomething(const std::string detailStr = "", const std::string somethingName = "sth");
`
TrackParts & TruthParts:
`
AddSomething(const std::string somethingName, const std::string detailStr);
`

Personally, harmonizing everything to have arguments in the first style makes more sense since one is often processing one collection of objects at a time (i.e. have detailStr come first, supply default objectName)? But it is also possible that many users have custom ntuple setups that might be affected?

**Comment by kratsg** [comment]
It's a good question. We should harmonize, and ask on the xAH mailing list to see if anyone is currently affected or rely on the ordering.

**Comment by kkrizka** [comment]
I fully support this.

**Comment by jbossios** [comment]
This would affect my xAH-based analysis code but I support this change. Would be possible to set a given advertised date for the merging to be done so I (and others) can prepare the needed changes so the transition is smooth?

**Comment by kratsg** [comment]
> This would affect my xAH-based analysis code but I support this change. Would be possible to set a given advertised date for the merging to be done so I (and others) can prepare the needed changes so the transition is smooth?

sure. We generally advertise on the mailing list for any breaking-backward-compatibility API changes.

**Comment by kratsg** [comment]
@taehyounpark don't close this until the PR is merged in...
