### ISSUE TITLE
~PhotonContainer() crash when running on data

### ISSUE THREAD

**Issue by davide-melini** [UCATLAS/xAODAnaHelpers#1405]
Code crushes when using the photon container destructor.  This happens on data only.

After a deeper reading I think the problem is on LL 108-119, where the pointer to the photon SF are deleted.  Such pointers where only initialized in case of running on mc though.

A solution to this would be o add to the 'if' statement on [L108 ](https://github.com/UCATLAS/xAODAnaHelpers/blob/3999f533378b361215916e75a3c1d221f6b9b67b/Root/PhotonContainer.cxx#L108)  the following: "&& m_mc". 

Cheers,
Davide

**Comment by jbossios** [comment]
You are right. I just made a PR to fix it: #1406
