### ISSUE TITLE
Warning in eventNumber branch setup

### ISSUE THREAD

**Issue by beojan** [UCATLAS/xAODAnaHelpers#1419]
Where the event number is stored into a `TTree`, the branch is setup as `eventNumber/LI`.

This leads to the warning
```
TBranch::TBranch          WARNING Extra characters after type tag 'LI' for branch 'eventNumber'; must be one character.
```
It should just be `eventNumber/L`.

(Weirdly, the [docs](https://root.cern.ch/doc/master/classTTree.html#addcolumnoffundamentaltypes) explicitly state that extra characters after the first are legal, but it seems a warning is produced anyhow.)

**Comment by kratsg** [comment]
Ok, submit a PR?

**Comment by jbossios** [comment]
@beojan will you create a PR or should we take care of it?

**Comment by beojan** [comment]
Sorry, totally forgot about this. I've submitted the PR.
