### ISSUE TITLE
condor-only crashes in JetContainer::updateEntry

### ISSUE THREAD

**Issue by lhenkelm** [UCATLAS/xAODAnaHelpers#1420]
I recently started using the `xAH_run.py [...] condor [...]` driver to submit ntuple-->histos jobs to my institutes cluster. This largely works, but in every large submission, a small fraction of all jobs crashes.
The cause appears to be a std::out_of_range being thrown by some vector access somewhere inside of the `JetContainer` - specific virtual `JetContainer::updateParticle`. 

The curious aspect is that these crashes occur only when the job is distributed through condor.
I.e. when I log onto the same worker node and run the same job, over the same file, but using `xAH_run.py [...] direct [...]` instead, no crash occurs and the job processes the entire file successfully. 

Could these crashes somehow be due to how xAH_run wraps condor submission?

**Comment by lhenkelm** [comment]
Some more detail:
* the exact command used to submit to condor is [here](https://gitlab.cern.ch/lhenkelm/histos_boosted_dijet_isr/blob/master/CondorHelpers/submit.sh#L32)
* this is how I run the local jobs that work fine:
`xAH_run.py --treeName outTree --files <ntuple_input.root> --config ../ZprimeDM/data/config_jetJet.py --submitDir test_1 direct`
* the files that the condor/out_of_range issue occurs with  ( as `<containername>/<filename>`) :

```user.lhenkelm.309712.e6584_s3126_r9364_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713541._000001.tree.root
user.lhenkelm.309720.e6584_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713591._000001.tree.root
user.lhenkelm.309720.e6584_s3126_r9364_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713548._000001.tree.root
user.lhenkelm.309722.e6584_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713592._000001.tree.root
user.lhenkelm.364375.e7048_s3126_r10724_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713595._000001.tree.root
user.lhenkelm.364378.e7048_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713557._000001.tree.root
user.lhenkelm.364706.e7142_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713571._000003.tree.root
user.lhenkelm.364706.e7142_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713571._000005.tree.root
user.lhenkelm.364706.e7142_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713571._000010.tree.root
user.lhenkelm.364706.e7142_s3126_r10724_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713614._000003.tree.root
user.lhenkelm.364706.e7142_s3126_r10724_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713614._000005.tree.root
user.lhenkelm.364706.e7142_s3126_r9364_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713529._000003.tree.root
user.lhenkelm.364707.e7142_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713572._000006.tree.root
user.lhenkelm.364707.e7142_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713572._000012.tree.root
user.lhenkelm.364707.e7142_s3126_r9364_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713531._000004.tree.root
user.lhenkelm.364708.e7142_s3126_r10201_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713575._000005.tree.root
user.lhenkelm.364708.e7142_s3126_r10724_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713616._000006.tree.root
user.lhenkelm.364709.e7142_s3126_r10724_p4004.NTUP_TAR_20200302_tree.root/user.lhenkelm.20713618._000004.tree.root
```

* part of one log, near the crash:

```Algorithm.jJ_trigHLT_j...DEBUG   ZprimeISRBoostHistsAlgo::initialize()
Package.EventLoop        INFO    Processing events 0-144862 in file file:///r02/atlas/henkel/dijet_isr_boosted_ntuples/NTUP_TAR_20200302/renamed/mc16e_bkg/mc16e.364375.Sherpa_225_NNPDF30NNLO_Zqq_PTV280_500.ntuples_TAR_20200302/user.lhenkelm.20713595._000001.tree.root
MiniTreeEventSelection   DEBUG   Processing Event
MiniTreeEventSelection   VERBOSE Got entry
MiniTreeEventSelection   VERBOSE saved eventInfo
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:133in updateEntry: resized m_particles to 4
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:137in updateEntry: about to update particle no. 0
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:233in updateParticle: updated particle no 0
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/MessageCheck.cxx:35 (void EL::Detail::report_exception()): caught exception: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:654 (StatusCode EL::Worker::algsExecute()): while calling execute() on algorithm MiniTreeEventSelection
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:517 (StatusCode EL::Worker::processEvents(EL::EventRange&)): processing event 0 on file user.lhenkelm.20713595._000001.tree.root
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:862 (StatusCode EL::Worker::batchExecute(unsigned int, const char*)): Failed to call "processEvents (eventRange)"
Package.UserCode         ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/util/eventloop_batch_worker.cxx:36 (int main(int, char**)): Failed to call "worker.batchExecute (job_id, confFile)"
abort EL_JOBID=0
Exiting due to job failure: unspecified error (11/03/2020 14:22:43 GMT)
```

**Comment by kratsg** [comment]
xAH doesn't do anything for condor submission. This would be an event loop problem. The error seems to be that you're running over some event that has 0 jets and trying to access it using `MiniTreeEventSelection` which is crashing -- both the condor and `MiniTreeEventSelection` are not part of xAH specifically.

**Comment by lhenkelm** [comment]
Thanks for taking a look. 

I don't think it's an issue of there not being jets. I had added some couts to the xAH ParticleContainer template in my local source, and you can see from the resulting lines in the log above (the ones beginning with a long path) that:
* The particle container resizes m_particles to fit 4 elements,
* it successfully updates the 4vector kinematics for the first jet,
* it then returns from the templates updateParticle method and enters the extra code specific to the JetContainers updateParticle, and the exception is raised before that function returns (as there should otherwise be a cout about the second jet appearing)


The reasons I thought this might be due to xAH were that:
* using this same code to process the same inputs on the same machine succeeds without crashes if I run interactively. The *only* difference being that I start the jobs through the direct driver. 
* the exception is raised in the xAH wrapping code. Not MiniTreeEventSelection, which is already deeper down the stack at that point. 

You are right that these two observations don't mean that it can't be due to some underlying eventloop issue. I hadn't really considered this, because I would have expected eventloop issues to be communicated through status code returns, not exceptions. Do you know a way how I could confirm that this is not due to the xAH IO container classes? (I will go and litter the JetContainer::updateParticle with more couts tomorrow, but maybe there is a more elegant way?)

**Comment by kratsg** [comment]
> * the exception is raised in the xAH wrapping code. Not MiniTreeEventSelection, which is already deeper down the stack at that point.

The only reason that's done is because of how the call stack works. `xAH_run.py` is calling `job.submit()` and it is `job.submit()` that returns an exception which is caught by xAH before exiting to let you know there was an exception. That doesn't mean it's xAH-specific.



> Do you know a way how I could confirm that this is not due to the xAH IO container classes? (I will go and litter the JetContainer::updateParticle with more couts tomorrow, but maybe there is a more elegant way?)

Just litter with couts to understand what's going on. The code snippet you posted

```Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/MessageCheck.cxx:35 (void EL::Detail::report_exception()): caught exception: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:654 (StatusCode EL::Worker::algsExecute()): while calling execute() on algorithm MiniTreeEventSelection
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:517 (StatusCode EL::Worker::processEvents(EL::EventRange&)): processing event 0 on file user.lhenkelm.20713595._000001.tree.root
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:862 (StatusCode EL::Worker::batchExecute(unsigned int, const char*)): Failed to call "processEvents (eventRange)"
Package.UserCode         ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/util/eventloop_batch_worker.cxx:36 (int main(int, char**)): Failed to call "worker.batchExecute (job_id, confFile)"
```

indicates a vector of size 0 somewhere. If you look at the `updateParticle` code, it's accessing these member variables:

```
	      particle.p4.SetPtEtaPhiM(m_pt ->at(idx),
				       m_eta->at(idx),
				       m_phi->at(idx),
				       m_M  ->at(idx));
```

so it would be useful to see which of these 4 are not being set (maybe all of them?)

**Comment by lhenkelm** [comment]
so, the line that throws the exception is here: [log-littered fork](https://github.com/lhenkelm/xAODAnaHelpers/blob/7fe530a62479d349cb04fca07bb42525be0cb395/Root/JetContainer.cxx#L1822),  [master](https://github.com/UCATLAS/xAODAnaHelpers/blob/bdcba2c6cae4fae658786af2dd2cf67cef01c262/Root/JetContainer.cxx#L1665)

Here are the log snippets to go with the claim (note they both process the same file, using the same code and config):
* this is a job that crashes:
```
Package.EventLoop        INFO    Processing events 0-69121 in file file:///r02/atlas/henkel/dijet_isr_boosted_ntuples/NTUP_TAR_20200302/condor_problem_files/user.lhenkelm/user.lhenkelm.20713591._000001.tree.root
MiniTreeEventSelection   DEBUG   Processing Event
MiniTreeEventSelection   VERBOSE Got entry
MiniTreeEventSelection   VERBOSE saved eventInfo
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:133 in updateEntry: resized m_particles to 4
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:136 in updateEntry: about to update particle no. 0
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:231 in updateParticle: updated particle no 0
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1454 in updateParticle: entering huge B-tags switch statement
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1926 in updateParticle: default (noop)
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1926 in updateParticle: default (noop)
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1926 in updateParticle: default (noop)
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1821 in updateParticle: case Jet::BTaggerOP::MV2c10_FixedCutBEff_30
Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/MessageCheck.cxx:35 (void EL::Detail::report_exception()): caught exception: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```
* this is a job that succeeds (same input file, config, etc.):
```
Package.EventLoop        INFO    Processing events 0-69121 in file file:///r02/atlas/henkel/dijet_isr_boosted_ntuples/NTUP_TAR_20200302/condor_problem_files/user.lhenkelm/user.lhenkelm.20713591._000001.tree.root
MiniTreeEventSelection   DEBUG   Processing Event
MiniTreeEventSelection   VERBOSE Got entry
MiniTreeEventSelection   VERBOSE saved eventInfo
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:133 in updateEntry: resized m_particles to 4
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:136 in updateEntry: about to update particle no. 0
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:231 in updateParticle: updated particle no 0
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1454 in updateParticle: entering huge B-tags switch statement
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1926 in updateParticle: default (noop)
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1926 in updateParticle: default (noop)
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1926 in updateParticle: default (noop)
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1926 in updateParticle: default (noop)
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1930 in updateParticle: hundreds of copy-pasted lines later, leave the  huge B-tags switch statement
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:136 in updateEntry: about to update particle no. 1
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/xAODAnaHelpers/ParticleContainer.h:231 in updateParticle: updated particle no 1
/usera/henkel/git_projects/dijetISRboosted/HistosBoostedDiJetISR/xAODAnaHelpers/Root/JetContainer.cxx:1454 in updateParticle: entering huge B-tags switch statement
[... and so on ...]
```

So its btagging related? What I cannot wrap my head around is that somehow, sometimes, when being submitted through the condor driver, the content of the m_btags member changes? 
I would have thought this is fixed once at initialisation, and then just distributed.
Can this be affected by environment differences somehow?

**Comment by kratsg** [comment]
Gonna need a full log of the two... but this isn't necessarily an xAH problem per-se because the code should be identical in both direct/condor. Likely, you're passing in some configuration path that PathResolver is unable to resolve on condor, but only locally...

**Comment by lhenkelm** [comment]
I'll upload the full logs as soon as I am back on a machine where I can access them, tomorrow. (Sorry about the delay)

Just to comment, I am not sure about your point concerning configuration paths. 
* The inputfiles, configfiles, sources and binaries all live on a shared filesystem. Both local and distributed jobs access them through that. Further, the successful job above was **also** running through the condor driver.  (The inputfiles that the exception occurs with do not reliably produce the crash - only in something like 13/17 individual jobs, though which or how many files crash varies between submissions. The two reproducible facts about the exception are that it is not raised when running through the direct driver, nor raised for files other than these 17 ones.)
* The specific config used is [this one](https://gitlab.cern.ch/atlas-phys-exotics-dijetisr/ZprimeDM/blob/9fe2332c233844596e90b00fe078c95f4c91ea3a/data/config_jetJet.py),
which imports [this script](https://gitlab.cern.ch/atlas-phys-exotics-dijetisr/ZprimeDM/blob/9fe2332c233844596e90b00fe078c95f4c91ea3a/python/commonconfig.py),
in the context of [this metaproject](https://gitlab.cern.ch/lhenkelm/histos_boosted_dijet_isr/tree/master). While this is admittedly messy, as far as I can tell it all ends up setting the various b-tags-settings containers to be empty tuples/lists in the config that is actually applied. So as far as I understand this (should) not depend on the PathResolver.
* Do you know if there are any environment- or shell variables that either the JetContainer or the PathResolver access? I had a look at shell variable dumps, but there are many variables flying around, most of which are likely not related to this.

**Comment by kratsg** [comment]
There really should be nothing that changes between the two, especially on a shared filesystem. If you are unable to reliably produce the error, it sounds tied to some random number generator which doesn't help debug. But unless you can give the exact line in the code causing the problem, I can't help.

**Comment by lhenkelm** [comment]
Here are the full logs:
* [log-10.out_ok.txt.tar.gz](https://github.com/UCATLAS/xAODAnaHelpers/files/4329368/log-10.out_ok.txt.tar.gz) **be warned: this expands to ~ 1.3 Gigs**
* [log-10.out_crash.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/4329371/log-10.out_crash.txt)

And like I said above, the exception is thrown in [line 1665 of JetContainer.cxx](https://github.com/UCATLAS/xAODAnaHelpers/blob/bdcba2c6cae4fae658786af2dd2cf67cef01c262/Root/JetContainer.cxx#L1665). (which is corresponds)

To the best of my knowledge, the MiniTreeSelection/Zprime Analysis code should not be using random number generators for anything in these jobs. These jobs are just for reducing ntuples into histograms, so that would not make any sense.

**Comment by kratsg** [comment]
Ok, but then can you try and actually debug what `btag->m_isTag` looks like? How many entries? If it's empty, why is it not getting filled?

./cc @kkrizka since this is code you modified quite heavily. It's throwing errors here, but I don't know why.

**Comment by lhenkelm** [comment]
`btag->m_isTag` is empty because the ntuples I run over have no branches for the btag-related stuff (the analysis does not differentiate between tagged/non-tagged jets) .The issue is not what that line is doing, it is that that line should not be called. Somehow, the [switch on `btag->m_op`](https://github.com/UCATLAS/xAODAnaHelpers/blob/bdcba2c6cae4fae658786af2dd2cf67cef01c262/Root/JetContainer.cxx#L1374)
recieves values that cause it to enter these cases (<-- this is the buggy/unexpected behavior). In the log without crash, it just correctly defaults to doing nothing every time.

I added a bit of logging to the [`btagOpPoint` class](https://github.com/UCATLAS/xAODAnaHelpers/blob/bdcba2c6cae4fae658786af2dd2cf67cef01c262/xAODAnaHelpers/JetContainer.h#L313),
which appears to be the type of `btag`. It turns out that the field the switch statement checks (`btagOpPoint::m_op`) is **declared, but is never set to anything**, unless a known (in the sense of matching one of the 87 consecutive else/if statements in that c'tor) string is passed to the  `tagger` argument. As a result, the value of `btagOpPoint::m_op` is undefined behavior (in fact, the logs below show that this value changes between the beginning and end of the c'tor call).
Since the `btagOpPoint` instances are created on the heap, and after the input files are opened,
it appears that my special 17 files above have the unlucky property of a high chance to push these accidental values of `btagOpPoint::m_op` to a value that happens to also be checked in one of the cases of the switch statement. I still do not get why this should only happen when running through the condor driver though, but maybe there is a subtle difference in how EventLoop lays out frameworks  stuff that conspires with the memory footprint of loading these files. But then again, the compiler is free to do wild stuff with undefined behavior, so I probably should not try too hard to understand that part.

Logs (with `btagOpPoint::btagOpPoint` as modified [here](https://github.com/lhenkelm/xAODAnaHelpers/blob/litterati/xAODAnaHelpers/JetContainer.h#L373) ):
* [log-0.out_crash.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/4330091/log-0.out_crash.txt)
* [log-2.out_ok.txt.tar.gz](https://github.com/UCATLAS/xAODAnaHelpers/files/4330123/log-2.out_ok.txt.tar.gz) **warning: 1 GB expanded**

**Comment by lhenkelm** [comment]
So, based on the above, I think the easiest fix is to just set default for `btagOpPoint::m_op` in the c'tor. Fortunately, the [enum even declares a `None` value](https://github.com/UCATLAS/xAODAnaHelpers/blob/bdcba2c6cae4fae658786af2dd2cf67cef01c262/xAODAnaHelpers/Jet.h#L14).  Then the [huge switch in updateParticle](https://github.com/UCATLAS/xAODAnaHelpers/blob/bdcba2c6cae4fae658786af2dd2cf67cef01c262/Root/JetContainer.cxx#L1374) can just make that an explicit case, and change the default to warn/terminate/throw or something like that. to preclude people relying on undefined behavior in this way in the future again.

IMO though this particular issue is just a symptom of the design of btagOpPoint/JetContainer.
I think this would be far easier to maintain and debug if all the branch handling were done dynamically (i.e. looking up by std::string/ char*/ some custom key type), instead of through these endless if/else/switch hardcoded conditional jumps.
E.g. you could  look up and connect to branches by an index into a std::array, std::unordered_map, or something similar.
I realise though that at this point, that would be a enourmous task to overhaul (and the current design may have reasons/advantages that I am not aware of).

**Comment by kratsg** [comment]
Let's set a default value for it to `None`  which should be caught here? https://github.com/UCATLAS/xAODAnaHelpers/blob/bdcba2c6cae4fae658786af2dd2cf67cef01c262/Root/JetContainer.cxx#L1748-L1749

**Comment by lhenkelm** [comment]
I'm preparing a PR (still testing to see this really does fix the crashes)

**Comment by lhenkelm** [comment]
PR is up, its checks have passed, and all 17 out of 17 critical files were processed without crashes on condor.

**Comment by kkrizka** [comment]
I am looking at this PR a bit more as part of cleaning up the `btagOpPoint` and there is one thing I don't understand. @lhenkelm , you say that "no branches for the btag-related stuff". Then why are you trying to load them? The crash occurred in the [loop over m_btags](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetContainer.cxx#L1373) while is [constructed from the info switch](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetContainer.cxx#L360).

**Comment by lhenkelm** [comment]
Hi Karol,

I am not trying to load them. I am passing empty/meaningless strings 
into the info switch. Some context to explain why I would do such a thing:
I use xAH in the context of the ZprimeDM 
<https://gitlab.cern.ch/atlas-phys-exotics-dijetisr/ZprimeDM>framework.
 From this framework I inherit this python config 
<https://gitlab.cern.ch/atlas-phys-exotics-dijetisr/ZprimeDM/-/blob/9fe2332c233844596e90b00fe078c95f4c91ea3a/data/config_jetJet.py> 
(the link points to the version of the code I used when debugging this 
issue).
As you can see, the authors of the config intended it to be used such 
that specifying a False-ish object (None, empty container, etc.) in the 
switches controlling what btagging data to read
overrides that switch with the default setting (which in this case is 
some valid btagging working point, i.e. no good for my use case). So 
instead I pass lists containing an empty string,
which avoids the override, but still does not result in btags being 
(attempted to) read out.

Regards,
Lars
