### ISSUE TITLE
Filling branches crashes in multiple locations when a primary vertex cannot be found

### ISSUE THREAD

**Issue by robinnewhouse** [UCATLAS/xAODAnaHelpers#1431]
We've run into a problem when running over a newly processed set of data. There seem to be a couple events missing primary vertices, but that's a different issue.

The problem I've found here is that the ntuple maker crashes when trying to access a null pointer and it would be great if the xAH could keep on running.

So I've seen this happen in `ElectronContainer.cxx` and `VertexContainer.cxx`.

This can be reproduced by filling the vertices with `"primary"` in the `vertexDetailString` on the dataset: `data18_13TeV:DAOD_RPVLL.20361820._000157.pool.root.1`

I've prepared a merge request that I will attach to this issue.

#### Running details
* AnalysisBase 21.2.90
* Running on lxplus using `xAH_run.py`
* Waxing Crescent

**Comment by kratsg** [comment]
> * Waxing Crescent

you know the names of the algorithms are randomly generated if you don't set one?
