### ISSUE TITLE
Broken xAH

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#1439]
The following PR broke xAH in 21.2.113:

https://github.com/UCATLAS/xAODAnaHelpers/pull/1433

The MinPt property was added in 21.2.116, so in 21.2.113 (the newer release that we support) xAH crash because that property does not exists. I don't know how xAH even compiled since in those releases where MinPt is available xAH does not compile:
https://github.com/UCATLAS/xAODAnaHelpers/issues/1438

Anyway, I'm about to push a PR to fix this so MinPt is only set if m_minPt != -1 which will work in <21.2.116 releases and will work in 21.2.116 since the tool crashes if MinPt is not set by the user.

**Comment by kratsg** [comment]
It seems to have always compiled somehow... looking at this: https://github.com/UCATLAS/xAODAnaHelpers/runs/604951447 -- i see no issues with compilation (this is on master). I just also tried compiling myself on lxplus and it compiled fine in 21.2.113. I guess I'm confused.

Are you just hitting a runtime error?

**Comment by kratsg** [comment]
Yes, it's a runtime error, not compilation.
