### ISSUE TITLE
Add fraction of jet pT from tracks to jet container?

### ISSUE THREAD

**Issue by matthewfeickert** [UCATLAS/xAODAnaHelpers#1445]
For jet cleaning studies I'm interested in looking at a quantity ("the charge fraction") which would be the scalar sum of the pT of tracks associated with a jet divided by the jet pT. To get this into the `JetHistsAlgo` and the jet `TreeAlgo` this would need to be added to the jet container when the "clean" detail string is used. `m_SumPtTrkPt1000` and `m_SumPtTrkPt500` already exist (if the "trackAll" detail string is used)

https://github.com/UCATLAS/xAODAnaHelpers/blob/b3feeb1e34782478900bf060dd5a27eb8d8ed2d7/Root/JetContainer.cxx#L118-L121

however, I think that I should be instead checking to see if the jet is decorated with `TrackSumPt` (as is `JETM1`) and creating the charge fraction from this. Is there a better way to do what I'm interested in, and if not would there be any objections to a PR adding this in?

cc @mattleblanc @kkrizka @kratsg @jbossios

**Comment by jbossios** [comment]
Personally, I would avoid adding more things to the current options (clean, trackAll, etc) so people currently using them don't see an increase in the TTree size. You could create a dedicated string for this. Also, you could indeed use the DFCommonJets_TrackSumPt decoration.

**Comment by matthewfeickert** [comment]
> Personally, I would avoid adding more things to the current options (clean, trackAll, etc) so people currently using them don't see an increase in the TTree size.

Sure, though if this would only affect `"clean"` are there that many people using `"clean"` at the moment? I had (wrongly?) assumed that this detail string was created for jet cleaning studies.

> Also, you could indeed use the DFCommonJets_TrackSumPt decoration.

Ah great. I didn't know this was derivation independent. :+1:

**Comment by jbossios** [comment]
Regarding DFCommonJets_TrackSumPt decoration, it is a matter of the derivation format. Some they save it, most of them not. Doing a quick LXR search, I could only find (IIRC) EXOT8.

**Comment by mattleblanc** [comment]
I am inclined to agree with @matthewfeickert's proposal, although I do recognise your point about TTree sizes, @jbossios. I think that the `trackAll` option should probably contain all of the track moments, and the `clean` one should also toggle all of the information we use for cleaning. Otherwise, this is how we wound up with this issue in the first place ...

That said, I think that `m_SumPtTrkPt500` is the one to use, at least historically?

**Comment by matthewfeickert** [comment]
> I think that the `trackAll` option should probably contain all of the track moments, and the `clean` one should also toggle all of the information we use for cleaning. 

Yeah, I have no interest in polluting things unrelated to jet cleaning. I don't think this should be an issue for anyone else(?).

> That said, I think that `m_SumPtTrkPt500` is the one to use, at least historically?

Hm. If that's true then as this is already in `JetContainer.cxx` under `trackAll` then probably want to do something like is done already while inside the 

https://github.com/UCATLAS/xAODAnaHelpers/blob/b3feeb1e34782478900bf060dd5a27eb8d8ed2d7/Root/JetContainer.cxx#L32

block to also check 

```c++
if ( m_infoSwitch.m_trackAll ) {
```

@mattleblanc I can follow up with you offline to educate myself on the motivation to use tracks with `pT > 0.5 GeV.

**Comment by matthewfeickert** [comment]
Picking this up again...

> I think that `m_SumPtTrkPt500` is the one to use, at least historically

For jet cleaning the thing we care about is the scalar sum of the pT of tracks _from the primary vertex_ associated with a jet divided by the jet pT, so the quantity that we're interested in here (if I understand things correctly) would be the existing quantity `m_SumPtTrkPt500PV`

https://github.com/UCATLAS/xAODAnaHelpers/blob/d3a39d971b1580ab8b23acd50ccbf225a174ca8b/Root/JetContainer.cxx#L128-L138
divided by the jet pT. As that is already calculated for the `trackPV` infoSwitch

https://github.com/UCATLAS/xAODAnaHelpers/blob/d3a39d971b1580ab8b23acd50ccbf225a174ca8b/Root/JetContainer.cxx#L2622-L2624

then I could probably just put in an additional check for the `clean` infoSwitch and then just push back `m_ChargeFrac` from the previously calculated `m_SumPtTrkPt500PV` and jet pT so that the only `clean` is affected. As JetDef is the only ones using `clean` at the moment (I think) this should only affect us and so I think that's fine.
