### ISSUE TITLE
Produce skims from ntuple?

### ISSUE THREAD

**Issue by jburzy01** [UCATLAS/xAODAnaHelpers#1447]
I am interested in producing additional skimmed trees during my ntuple->histogram step for further downstream studies. Currently HelpTreeBase methods only accept xAOD containers and not xAH containers. It would be nice to have overloaded methods like in the various histogram classes to facilitate producing new trees when running over ntuples.

Is there a better way to do what I am trying to do, and if not would there be any objections to a PR adding this in?

**Comment by kratsg** [comment]
Not sure I completely follow. If you have the xAH containers already, why can't you make your own, register them to a new tree, and fill it in there? HelpTreeBase is primarily to automate the xAOD->xAH object but trees are filled directly from xAH objects.

**Comment by jburzy01** [comment]
thanks @kratsg, this is indeed what I implemented. I shouldn't be allowed to post issues before my coffee :) thanks for the reply, closing this
