### ISSUE TITLE
Bug with mcEventWeight decoration

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#145]
Hi all,

I have spotted a bug in BasicEventSelection.cxx

The problem is that now the decoration for mcEvetWeight exists only for MC (see [here](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BasicEventSelection.cxx#L527) in the code), which then causes a crash in the selectors when the algorithm is trying to retrieve the mc event weight for Mc AND for data.

The minimal solution would be to go back to what we had before :8ball: 
 

```
  float mcEvtWeight(1.0), pileupWeight(1.0);
  if ( m_isMC ) {
     const std::vector< float > weights = eventInfo->mcEventWeights(); // The weights of all the MC events used in the simulation
     if ( weights.size() > 0 ) mcEvtWeight = weights[0];

    .... do something ...
  }
  // decorate with  mc event weight for data and MC!!
  static SG::AuxElement::Decorator< float > mcEvtWeightDecor("mcEventWeight");
  mcEvtWeightDecor(*eventInfo) = mcEvtWeight;

```

, i.e., apply the decoration also for data (it will be always = 1.0).

Another option of course is to retrieve the weight only for MC, but it implies a bit more changes, so I'd stick to what we had before.

I am filing a PR soon.

Marco

**Comment by kratsg** [comment]
See my current solution that handles both data and MC: https://github.com/kratsg/TheAccountant/blob/master/Root/VariableDefinitions.cxx#L141-L175

```
float VD::eventWeight(const xAOD::EventInfo* ei, const SH::MetaObject* metaData){
  // for now, we will return 1.0 to make it consistent and scale in optimization and plotting (fuck)
  static SG::AuxElement::ConstAccessor<uint32_t> eventType("eventTypeBitmask");
  if(!eventType.isAvailable(*ei)){
    std::cout << "Warning: eventType is not available. Returning 1." << std::endl;
    return 1.0;
  }

  //if(!ei->eventType( xAOD::EventInfo::IS_SIMULATION ))
  if( !(static_cast<uint32_t>(eventType(*ei)) & xAOD::EventInfo::IS_SIMULATION) )
    return 1.0;

  static SG::AuxElement::ConstAccessor<float> weight_mc("weight_mc");
  float weight(weight_mc.isAvailable(*ei)?weight_mc(*ei):1.0);
  //float weight(weight_mc.isAvailable(*ei)?weight_mc(*ei):ei->mcEventWeight());

  return weight;
  // don't need to do this
  float crossSection(1),
        kFactor(1),
        filterEfficiency(1),
  //      xsUncertainty(1),
        numEvents(1);

  // if metadata is set, use it, otherwise pass the event weight, uncorrected
  if(metaData){
    crossSection = metaData->castDouble(SH::MetaFields::crossSection, crossSection);
    kFactor = metaData->castDouble(SH::MetaFields::kfactor, kFactor);
    filterEfficiency = metaData->castDouble(SH::MetaFields::filterEfficiency, filterEfficiency);
    //xsUncertainty = metaData->castDouble(SH::MetaFields::crossSectionRelUncertainty, xsUncertainty);
    numEvents = metaData->castDouble(SH::MetaFields::numEvents, numEvents);
  }

  return (weight*crossSection*kFactor*filterEfficiency/numEvents);
}

```

**Comment by mmilesi** [comment]
Hi @kratsg,

I guess this can be easily made slimmer with your isMC() function, right?

Btw, I have one question and a few comments:

1. Question:

Can you show us how SamplleHandler retrieves the MetaData like Xsec, kfactor etc. ? Also a pointer to some documentation is enough!

2. Comments:

I heard a while ago that we should be careful at applying Xsec etc . weights that are taken directly from AMI, since sometimes they are incorrect. And I guess that SH simply reads the AMI database to get that info, right?

Also, what is the 
```
    numEvents = metaData->castDouble(SH::MetaFields::numEvents, numEvents);

```
?

Is it the total number of events of the sample you process?

There are two potential issues with this:

1. How does this take into account the fact that some grid jobs might fail? Ther's the risk that the denominator above will be larger than it should be, as in that case you would be processing less events than the whole number of events available in the sample.

2. Keep in mind the "derivation skimming issue": if your DAODs have a skimming applied, you need to use for the denominator the total number of events in the original file from which the DAOD you are processing was made. This implies you need to look at the CutBookkeepers part in BasicEventSelection.cxx:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BasicEventSelection.cxx#L303

 and use that number as denominator.

**Comment by kratsg** [comment]
> Can you show us how SamplleHandler retrieves the MetaData like Xsec, kfactor etc. ? Also a pointer to some documentation is enough!

https://github.com/kratsg/TheAccountant/blob/master/scripts/CookTheBooks.py#L198-L200
```python
    # read susy meta data
    cookBooks_logger.info("reading all metadata in $ROOTCOREBIN/data/TheAccountant")
    ROOT.SH.readSusyMetaDir(sh_all,"$ROOTCOREBIN/data/TheAccountant")
```

> I heard a while ago that we should be careful at applying Xsec etc . weights that are taken directly from AMI, since sometimes they are incorrect. And I guess that SH simply reads the AMI database to get that info, right?

Yes and no. It's better to make your own file of weights and manage it yourself. In my analysis, I apply the weights downstream: https://github.com/kratsg/TakeOverTheWorld/blob/master/weights.yml



> Also, what is the
> 
>     numEvents = metaData->castDouble(SH::MetaFields::numEvents, numEvents);
> 
> ?
> 
> Is it the total number of events of the sample you process?

That is always meant to be the number that goes into the denominator of the calculation for event weight. However, if you look at my code, I don't use any of it (there's a `return` statement before it all). I kept it to show what could have been.

The main reason I cannot rely on metadata is because I usually do most of my workflow at the mini-xAOD level, and there's usually not much effort put into trying to get the metadata correctly (it's hard to copy it right outside of a Derivation Framework) so it's much easier to just check if `isMC()` and return either `1` or a call to `mcEventWeight()` or a decoration of your choosing.

**Comment by mmilesi** [comment]
Let's continue this on #146 . Closing this one.
