### ISSUE TITLE
bug in trigger SF portion of MuonEfficiencyCorrector?

### ISSUE THREAD

**Issue by jburzy01** [UCATLAS/xAODAnaHelpers#1460]
I am running in to issues when using the MuonEfficiencyCorrector to try to obtain the muon trigger SFs. I am running over MC16a and using the following `m_MuTrigLegs`: `2015:HLT_mu20_iloose_L1MU15_OR_HLT_mu50,2016:HLT_mu26_ivarmedium_OR_HLT_mu50,2017:HLT_mu26_ivarmedium_OR_HLT_mu50,2018:HLT_mu26_ivarmedium_OR_HLT_mu50`

The algorithm crashes with the error:

```
MuonTriggerScaleFactor...ERROR   /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/MuonID/MuonIDAnalysis/MuonEfficiencyCorrections/Root/MuonTriggerScaleFactors.cxx:458 (virtual CP::CorrectionCode CP::MuonTriggerScaleFactors::getMuonEfficiency(Double_t&, const TrigMuonEff::Configuration&, const Muon&, const string&, const string&) const): Could not find what you are looking for in the efficiency map. The trigger you are looking for, year and mc are not consistent, or the trigger is unavailable in this data period. Please check how you set up the tool.
```

I believe that the issue is with these lines of code:

https://github.com/UCATLAS/xAODAnaHelpers/blob/fa64b23d3867c3b63b93273155606c07090f124e/Root/MuonEfficiencyCorrector.cxx#L694-L698

It appears to crash when `trig.first == 2018`. I do not understand the logic used here to determine which muon trigger leg to use based on the run number. If I am running over mc16a this should not be looking at the 2018 trigger leg. If I change L698 to
```
else if ((trig.first.find("2016")!=std::string::npos || trig.first.find("2017")!=std::string::npos || trig.first.find("2018")!=std::string::npos) && run<=284484) continue; 
```
then the issue is resolved, however I am not convinced that the correct trigger SFs are being applied. I should note that this configuration runs fine over MC16d/e, only MC16a causes issues. Is this indeed a bug or am I using this tool incorrectly?

**Comment by jbossios** [comment]
I think rather than a bug is just a missing protection. I use the same triggers in my analysis and I never had this problem. In my case, if I run on MC16a, I just provide 2015 and 2016. Technically, you need to provide only those years correspongind to the MC16 campaign, those if/else if are protections when the incorrect ones are provided and indeed there is a missing protection for 2018.

**Comment by jbossios** [comment]
Do you want to create a PR to add the missing protection that you are suggesting?

**Comment by jburzy01** [comment]
Thanks @jbossios, that makes sense. Yes I will make a PR.
