### ISSUE TITLE
Fix missing headers for messaging macro

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#1496]
Should be using `AsgMessaging/MessageCheck.h`.

https://github.com/UCATLAS/xAODAnaHelpers/blob/fdf20b294d76bf8c721d60b2973eb3d61ee652f0/xAODAnaHelpers/tools/ReturnCheck.h#L3

Reported by Sara A. over Skype.

**Comment by jbossios** [comment]
Fixed by #1497, closing
