### ISSUE TITLE
Metadata - EventBookkeepers for mc15

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#15]
Read metadata and lumiblocks in mc15.

**Comment by kratsg** [comment]
@mmilesi Updates on this?

**Comment by mmilesi** [comment]
Event Metadata is done. Lumiblocks not. Awaiting from experts help.

**Comment by kratsg** [comment]
This will be included in the next.

**Comment by gfacini** [comment]
Status?

**Comment by mmilesi** [comment]
There has been recently a conversation on PATHelp as people (included me) still have problems with this.

See the email thread started on 16 of July of title:

"Incomplete CutBookkeepers (Fwd: Corrupted SUSY5 data samples?)"

Atm I have no time to look into this, @gfacini can you maybe give it a go (will fwd you the discussion)?

Marco

**Comment by mmilesi** [comment]
Hi @gfacini ,

PR #207 would close this.
