### ISSUE TITLE
Trigger menu not loading in R22

### ISSUE THREAD

**Issue by aroepe** [UCATLAS/xAODAnaHelpers#1502]
Hello,

I am working on the r22/master branch and when applying trigger selections in the ```BasicEventSelector``` I get the following error:

```BasicEventSelect.xAODC...FATAL   /build/atnight/localbuilds/nightlies/AnalysisBase/master/athena/Trigger/TrigConfiguration/TrigConfxAOD/Root/xAODConfigTool.cxx:180 (virtual uint32_t TrigConf::xAODConfigTool::masterKey() const): Trigger menu not loaded```

I was looking at the tool in athena and there seems to be a change when loading the trigger menu between r21 and r22 here: https://gitlab.cern.ch/atlas/athena/-/blob/master/Trigger/TrigConfiguration/TrigConfxAOD/Root/xAODConfigTool.cxx 

Could you please look into this? We cannot run electron and muon calibrators without the trigger decision tool loaded. Thank you for your help!

Sincerely,
Amber Roepe

**Comment by jbossios** [comment]
@aroepe I believe this is no longer an issue, right?

**Comment by aroepe** [comment]
Correct, updating to AnalysisBase,22.2.35 and updating xAODAnaHelpers worked. Thank you for your help!
