### ISSUE TITLE
Photons isolation problem

### ISSUE THREAD

**Issue by chekanov** [UCATLAS/xAODAnaHelpers#1503]
I was trying to fill photon isolation using:

` "m_photonDetailStr"             : "kinematic PID isolation",`

It fails: ptvarcone20 does not exits for recent tags and release 21.2.173

Package.EventLoop        ERROR   /build/atnight/localbuilds/nightlies/AnalysisBase/21.2/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/MessageCheck.cxx:35 (void EL::Detail::report_exception()): caught exception: SG::ExcBadAuxVar: Attempt to retrieve nonexistent aux data item `::ptvarcone20' (57).

**Comment by jbossios** [comment]
Were you needing to save any of the other variables that are saved with the 'isolation' option? Are they available? If ptvarcone20 is no longer available but the others are, then we could simply remove that one.

**Comment by chekanov** [comment]
Ok, I've commented out  ptvarcone20  variable in PhotonContainer.cxx and it works now
