### ISSUE TITLE
`MuonEfficiencyCorrector` instances delete tool ptrs they do not (uniquely) own

### ISSUE THREAD

**Issue by lhenkelm** [UCATLAS/xAODAnaHelpers#1508]
In [`MuonEfficiencyCorrector::initialize()`](https://github.com/UCATLAS/xAODAnaHelpers/blob/5e29a301aa1c7b53c35e2e437ceb77587032d728/Root/MuonEfficiencyCorrector.cxx#L142) the algo is being clever and re-uses already-created tool instances if a tool with the same working point is being requested again. 
However in [`MuonEfficiencyCorrector::finalize()`](https://github.com/UCATLAS/xAODAnaHelpers/blob/5e29a301aa1c7b53c35e2e437ceb77587032d728/Root/MuonEfficiencyCorrector.cxx#L430) it deletes every tool it has a pointer to, disregarding ownership.

This is fine so long as only a single `MuonEfficiencyCorrector` exists at one time. Configuring a job with two instances (e.g. targeting two different isolation working points, but the same reconstruction working point) that share at least one tool among them leads to a crash at the end of the job.

**Comment by kratsg** [comment]
> is that what `ToolHandle<T>::retrieve()` does?

That's my understanding, yes.
