### ISSUE TITLE
cannot load default lumicalc files in autoconfigurePileupRWTool 

### ISSUE THREAD

**Issue by morgensterns** [UCATLAS/xAODAnaHelpers#1510]
Dear developers,

While calling the auto-configured PU reweighing tool I noticed an issue when passing the lumicalc files from cvmfs, e.g. : /cvmfs/atlas.cern.ch/repo/sw/database/GroupData/GoodRunsLists/data18_13TeV/20190708/ilumicalc_histograms_None_348885-364292_OflLumi-13TeV-010.root. The year parsing in https://github.com/UCATLAS/xAODAnaHelpers/blob/r22/master/Root/BasicEventSelection.cxx#L1270 will catch `database` and thus return `ba`. I think using a regex here is a safer approach, i.e. like that:
```
	  std::regex expr("data[1-9]{2}_");
	  std::smatch match;
	  std::regex_search (filename, match ,expr);
	  std::string year = "unkown";
	  if(match.size() > 0)
	    year = match[0].str().substr(4, 2);
```
Would you consider this useful or am I calling it in an unintended way?

Thanks,
Stefanie

**Comment by kratsg** [comment]
Ping @kkrizka who implemented this initially, I think. We'd be happy if you submitted a PR to fix it. But I need to ask, why are you passing in the full path on CVMFS? This won't work for things that don't have CVMFS mounted. You should be able to use `GoodRunsLists/data18_13TeV/20190708/ilumicalc_histograms_None_348885-364292_OflLumi-13TeV-010.root` safely as the PathResolver can expand after the fact.

**Comment by morgensterns** [comment]
Thanks @kratsg. Indeed, with the PathResolver is does work, so there is not strict need for this. Nevertheless, I think a regex would be more safe in case there are special needs for non-standard lumicalc files or name changes on cvmfs. If there're no objections I'll open a pull request.
Thanks,
Stefanie
