### ISSUE TITLE
eventInfo::Core event cut

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#152]
Hi @jdandoy , @gfacini 

this is just a question, so feel free to close the issue after answering.

What is the meaning of the event cut "Core" defined [here](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BasicEventSelection.cxx#L627)?

I couldn't find any recommendation for it, although I guess there is.

Thanks!

Marco

**Comment by gfacini** [comment]
Incomplete event reconstruction

**Comment by mmilesi** [comment]
Hi @gfacini 

thanks. Can you send me a link to where the need for this cut is documented?
I am making an acceptance challenge with other people in the ttH, and I was asked where did this cut come from.

**Comment by gfacini** [comment]
I forward a PATHelp discussion to the xAH e-group.
It is for "incomplete events" so it might not have to
do with the reconstruction itself but also the readout.
I am not sure about the fine details. Eric Torrence is
the guy to ask if you need a lot a details - or the data
prep group in general.

G

**Comment by mmilesi** [comment]
Ok, thanks very much. Closing this issue now.
