### ISSUE TITLE
DL1r error

### ISSUE THREAD

**Issue by mattleblanc** [UCATLAS/xAODAnaHelpers#1528]
Please note the email recently sent by the FTAG conveners:

```
Dear FTAG Liaisons,

It just caught our attention that in the xAODAnaHelper package, the DL1r score is calculated by hand here: https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetContainer.cxx#L3020

The formula is outdated as the fraction should be 0.018 not 0.3 for DL1r. Could you please check with the physics analysis groups to see whether there are analyses using this variable to select b-tagged jets? 

In general we recommend analysis to apply the b-tagging selection using the default xAODBTagging efficiency tool [[link](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/BTagging_Selection_Tool)].

Thanks a lot!

Bing & Valerio
```

I am just reporting this, as they seem to have not opened an issue here.

MLB

**Comment by prbbing** [comment]
Thanks @mattleblanc  for reporting here. Yeah, we would recommend all users to rely on the CP tools to get the tag weight or select b-tagged jets by default.

**Comment by mswiatlo** [comment]
@prbbing As far as I know most people were using the CP tools, which have very well supported and developed algorithms. But indeed good to be aware of this and fix/remove this misleading issue.

**Comment by prbbing** [comment]
Hi all, 

Finally I got sometime to clean it up: https://github.com/UCATLAS/xAODAnaHelpers/pull/1540

I think it is possible to just use the fc value from the CDI directly. I will follow up there and implement it.

In this PR, old taggers are removed and new rel22 tagger, DL1dv00, is added.

Cheers.

Bing

**Comment by mattleblanc** [comment]
As #1540 is merged, this can be closed.

MLB
