### ISSUE TITLE
Error while using EOS ( changing the server)

### ISSUE THREAD

**Issue by zfarazpa** [UCATLAS/xAODAnaHelpers#1529]
This is ERROR I got when trying to use EOS 

File "/afs/cern.ch/user/z/zfarazpa/work/analysis/build/x86_64-centos7-gcc8-opt/bin/xAH_run.py", line 319, in <module>
    ROOT.SH.ScanDir().sampleDepth(0).samplePattern(eosDataSet).scanEOS(sh_all,base)
Exception: const SH::ScanDir& SH::ScanDir::scanEOS(SH::SampleHandler& sh, const string& eosDir) =>
    /build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/RootCoreUtils/Root/ShellExec.cxx:42:exception: command failed: eos ls -l group.phys-sm.26039294._000001.ANALYSIS.root

I alrady checked the file exits. This code was runnig for for another server but I could not get it run for EOS. (FYI, I added the argument related to EOS)
It would be a great help if you could look into this.

**Comment by kratsg** [comment]
You're going to need to provide more details... such as what you specified for the server/directory . How did you run `xAH_run.py` ?

**Comment by zfarazpa** [comment]
Thank you for you reply. The issue was related to the format of file name.
It is working now.
