### ISSUE TITLE
m_do2StationsHighPt Failure in Release 22

### ISSUE THREAD

**Issue by mdhank** [UCATLAS/xAODAnaHelpers#1589]
Dear Developers,

I am testing a Release 22 setup on the r22/master branch and am encountering an exception whenever I set m_do2StationsHighPt to True. I am running AnalysisBase 22.2.97 through the BLstop framework (https://gitlab.cern.ch/atlassusy-bminusl/BLstopWorkspace). I am running on mc20_13TeV:mc20_13TeV.346345.PhPy8EG_A14NNPDF23_NNPDF30ME_ttH125_dilep.deriv.DAOD_PHYS.e7148_s3681_r13167_p5440 , though I have tested other files as well and had the same issue every time. My command is

./source/xAODAnaHelpers/scripts/xAH_run.py -f --files ttH_dilep_mc20e.txt --nevents 10000 --config source/BLstopAnalysis/data/myconfig.py --inputRucio --inputList --isMC --submitDir ttH_2stations_3 direct >> ttH_dilep_2stations_3.log

which I have verified works if m_do2StationsHighPt is not enabled. I am running on the Chicago analysis facility. I have found that the error occurs in the line https://github.com/UCATLAS/xAODAnaHelpers/blob/r22/master/Root/MuonCalibrator.cxx#L249:

	        `if ( m_muonCalibrationTool_handle->applyCorrection(*muSC_itr) == CP::CorrectionCode::Error ) {  // Can have CorrectionCode values of Ok, OutOfValidityRange, or Error. Here only checking for Error.`

however, it can sometimes pass (it does not always fail on the first event). The reported error is:

`Package.EventLoop        ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase/master/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/MessageCheck.cxx:37 (void EL::Detail::report_exception(std::__exception_ptr::exception_ptr)): caught exception: map::at
Package.EventLoop        ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase/master/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:669 (StatusCode EL::Worker::algsExecute()): while calling execute() on algorithm MuonCalibrator
Package.EventLoop        ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase/master/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:532 (StatusCode EL::Worker::processEvents(EL::EventRange&)): processing event 1104 on file DAOD_PHYS.31200944._000001.pool.root.1
Package.EventLoop        ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase/master/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Worker.cxx:800 (StatusCode EL::Worker::directExecute(const SH::SamplePtr&, const EL::Job&, const string&, const SH::MetaObject&)): Failed to call "processEvents (eventRange)"
Package.EventLoop        ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase/master/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/DirectDriver.cxx:81 (virtual StatusCode EL::DirectDriver::doManagerStep(EL::Detail::ManagerData&) const): Failed to call "worker.directExecute (*sample, *data.job, data.submitDir, data.options)"
`
The full log is attached. I'm not sure if this is an issue in xAODAnaHelpers, an issue with the muon calibration tool, or a user error but I have not been able to find a fix on my end.

Best,
Michael

**Comment by mdhank** [comment]
[ttH_dilep_2stations_3.log](https://github.com/UCATLAS/xAODAnaHelpers/files/10249132/ttH_dilep_2stations_3.log)
Here is the log file. Please ignore all the "test MH" lines; these were used to narrow down the line causing the error.

**Comment by jbossios** [comment]
Hi @mdhank 

I think this is a problem from the muon calibration tool. I think this option is yet not implemented in R22. There is a "todo" in the header file for that option:

https://acode-browser1.usatlas.bnl.gov/lxr/source/athena/PhysicsAnalysis/MuonID/MuonIDAnalysis/MuonMomentumCorrections/MuonMomentumCorrections/MuonCalibTool.h#0101

Best,
Jona

**Comment by jbossios** [comment]
ok, maybe the "todo" only means that a meaningful comment should be placed, but the implementation is there. Either way, I would ask in the PAThelp list.

**Comment by mdhank** [comment]
I have confirmed this is an issue with the Athena release. It should be fixed in AnalysisBase 22.2.103. I was unable to validate this due to errors, but this may just be because xAodAnaHelpers currently supports up to 22.2.97.

**Comment by jbossios** [comment]
Hi @mdhank,

I tried xAH on 22.2.105 with m_do2StationsHighPt set to True and I had no issues (while on it crashes on 22.2.102). I would like move xAH to 103+ releases, but first I would like to understand why your config is crashing on 103. Could you please share the log and the config?

**Comment by mdhank** [comment]
Hi @jbossios,

It turns out I was missing the last few updates to xAODAnaHelpers (I only had through November 11).  After including these, I can run in 22.2.103. The only change that stands out to me in the log file is I now have numerous instances of

Dealing with a None uncertainty - returning no error
CDIROOT->getScaleFactor : returning 1 and 0

in the logs (with or without 2stations). However, I believe this is expected given the changes in https://gitlab.cern.ch/atlas/athena/-/blob/release/22.2.103/PhysicsAnalysis/JetTagging/JetTagPerformanceCalibration/CalibrationDataInterface/Root/CalibrationDataInterfaceROOT.cxx#L942 .

**Comment by jbossios** [comment]
I see. I will then close this ticket since it looks like there is no issue with xAH.
Thanks for reporting and following up.

P.S.: I will add other releases to CI and mention that newer releases are also supported.
