### ISSUE TITLE
New test xAOD for xAH to include in the package - Release 20.1.4.7

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#16]
It would be good to create a new up-to-date super-skimmed sample to put into the package, as the one we have now might belong to a too old release.

We might want to use a ttbar 50ns:

AtlasProduction 20.1.4.7 for digitization and reconstruction

For that release I have found the following dataset container:
mc15_13TeV.410000.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad.AOD.e3698_s2608_s2183_r6630_r6264

**Comment by kratsg** [comment]
I'll add in a note on the wiki, as well as probably the code, on how to skim using Athena. Unfortunately, that's what we need to do (and it may take a bit of time, so we should be using this kind of skimming sparingly).

**Comment by kratsg** [comment]
I can't seem to get the skimming to work. I use the script here: https://gist.github.com/30c4809cb0bfb29cc476

Input file: mc15_13TeV.410000.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad.merge.AOD.e3698_s2608_s2183_r6630_r6264_tid05419191_00/AOD.05419191._000003.pool.root.1

I have tried it using `asetup 19.3.0,here` and `asetup 20.1.4.7,here` and both do not work.

So I'll be trying to figure out what is different about rel20 root files that breaks this code.

**Comment by kratsg** [comment]
I've added wiki details here: https://github.com/UCATLAS/xAODAnaHelpers/wiki/Package-Development#skimming-new-test-files
