### ISSUE TITLE
Running on PHYSLITE

### ISSUE THREAD

**Issue by mdhank** [UCATLAS/xAODAnaHelpers#1607]
Dear Developers,

I have been testing my code using the PHYSLITE kernel and have found 3 potential issues.

I am using commit f3fd76c40947985e151aa8e021d21013075639e6 of xAODAnaHelpers. I am running AnalysisBase 22.2.105 through a modified version of the BLstop framework (https://gitlab.cern.ch/atlassusy-bminusl/BLstopWorkspace). I have tested samples mc20_13TeV:mc20_13TeV.410470.PhPy8EG_A14_ttbar_hdamp258p75_nonallhad.deriv.DAOD_PHYSLITE.e6337_a899_r13144_p5511 and and mc20_13TeV:mc20_13TeV.410472.PhPy8EG_A14_ttbar_hdamp258p75_dil.deriv.DAOD_PHYSLITE.e6348_a899_r13167_p5511
. An example of my commands is
```
/source/xAODAnaHelpers/scripts/xAH_run.py -f --files ttbar_dilep_physlite.txt --nevents 2000 --config source/BLstopAnalysis/data/myconfigLite.py --inputRucio --inputList --isMC --submitDir ttll_Feb9 direct > ttll_Feb9.log 2>&1 &
```
1. The first issue is on https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/JetSelector.cxx#L1284 . I believe the PHYSLITE container no longer includes the "Jvt" decoration. I was able to run after switching this to "NNJvt". Without the change, it fails with the error
```
Package.EventLoop        ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase/master/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/MessageCheck.cxx:37 (void EL::Detail::report_exception(std::__exception_ptr::exception_ptr)): caught exception: SG::ExcBadAuxVar: Attempt to retrieve nonexistent aux data item `::Jvt' (344).
```

2. I also got failures in TruthMatching. I was able to get this running by changing https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/Algorithm.cxx#L130 to 
```
return (metaData->GetBranch("StreamDAOD_PHYS") || metaData->GetBranch("StreamDAOD_LLP1") || metaData->GetBranch("StreamDAOD_PHYSLITE"));
```
Without this change, InputPrefix never gets set at https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/ElectronSelector.cxx#L371.

3. I was able to run without this change, so am unsure if it's necessary. However, I noticed that some other frameworks have the equivalent of 
```ANA_CHECK( m_trigElectronMatchTool_handle.setProperty( "RemapBrokenLinks", true) );``` 
after https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/ElectronSelector.cxx#L371 (and similar for muons). I don't know if this is needed or not, but thought I would bring it to your attention just in case.

Best,
Michael

**Comment by jbossios** [comment]
Hi @mdhank,

Thanks for reporting this. Could you please create a PR including all these changes?

Regarding 1. I don't know if you are supposed to apply an NNJvt cut by hand, instead of relying on the JVT tool when using using PHYSLITE. I would expect the tool to still work (disabling ```m_recalculateJvtScores```) since the NNJvt values were computed before hand.

**Comment by jbossios** [comment]
Absolutely, I would change the name but also as you suggested, we could move those lines so we get those attributes only when we need to.

Thanks for taking care of creating the PR.
