### ISSUE TITLE
ClearTaus() misses tauName argument

### ISSUE THREAD

**Issue by janascha** [UCATLAS/xAODAnaHelpers#1610]
This line
https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/HelpTreeBase.cxx#L965

should maybe rather be
this->ClearTaus(tauName);

to avoid a seg fault.

**Comment by jbossios** [comment]
Indeed, thanks for reporting. Would you like to create a PR to fix it?

**Comment by janascha** [comment]
Yes I can try (first time for me)
