### ISSUE TITLE
LooseBL Electrons in PHYSLITE

### ISSUE THREAD

**Issue by mdhank** [UCATLAS/xAODAnaHelpers#1619]
Dear Developers,

I have been testing my code using the PHYSLITE kernel and found a potential issue.

I am using commit https://github.com/UCATLAS/xAODAnaHelpers/commit/781ced0b0aa4ad37a8d2347178070cfb8ed8c450 of xAODAnaHelpers. I am running AnalysisBase 22.2.108 through a modified version of the BLstop framework (https://gitlab.cern.ch/atlassusy-bminusl/BLstopWorkspace). I have tested samples mc20_13TeV.410472.PhPy8EG_A14_ttbar_hdamp258p75_dil.deriv.DAOD_PHYS.e6348_s3681_r13167_p5511 and mc20_13TeV.410472.PhPy8EG_A14_ttbar_hdamp258p75_dil.deriv.DAOD_PHYSLITE.e6348_s3681_r13167_p5511
. An example of my commands is

`
./source/xAODAnaHelpers/scripts/xAH_run.py -f --files ttbar_dilep_physlite_full.txt --nevents 10000 --config source/BLstopAnalysis/data/myconfigLite.py --inputRucio --inputList --isMC --submitDir tt_ll_test direct
`

The issue I found is that no electrons survive when using the LooseAndBLayer WP with PHYSLITE. This is due to https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/ElectronSelector.cxx#L284-286, where the BL cut is made locally as it was at one point not in the derivations. The local cut always fails on PHYSLITE. However, I am able to run with these lines removed, suggesting LooseBL now exists in the derivations. This allows PHYSLITE to run, and also yields slightly different results in PHYS (408/10k events survived my preselections, which include a 2L cut, vs. 405 with the local BL cut). Therefore I would suggest using the WP information from the derivation directly when m_readIDFlagsFromDerivation is enabled.

If you are in agreement, I will create a pull request for this.

Best,
Michael

**Comment by jbossios** [comment]
Hi @mdhank 

Thanks a lot for reporting this!

It sounds good to me to remove that (old) protection, so people can use PHYSLITE w/o problems and fixes the tiny inconsistent for PHYS and other DAOD formats.

Thanks also for volunteering to create a PR.

Best,
Jona

**Comment by jbossios** [comment]
Closing since already implemented here: https://github.com/UCATLAS/xAODAnaHelpers/pull/1620
