### ISSUE TITLE
Explain how to change JVT tagger via the Python config

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#1628]
### Discussed in https://github.com/UCATLAS/xAODAnaHelpers/discussions/1626

<div type='discussions-op-text'>

<sup>Originally posted by **rbarrue** March  5, 2023</sup>
Currently, the C++ code in JetSelector uses the enum defined in the JVT namespace, but that enum can't be accessed in the Python config (only via the int directly). 

One way would be reimplement the JVT tagger enum in xAH, but that would require tracking the JVT enum and change in xAH anytime it changes in the ATLAS code.

Is there a smarter way to do this ?</div>

**Comment by kratsg** [comment]
Is the `IJetJvtEfficiency` exposed at all through python (do we have a ROOT dict file generated for it for the python bindings)? If so, you could use the string names and use `getattr(CP.JvtTagger)` to get the integer value but...?

**Comment by jbossios** [comment]
That might work. I will merge the above PR anyway since it works for sure but if @rbarrue wants to give that a try, then if it works I can add this to the docs/header.
