### ISSUE TITLE
Error in METConstructer

### ISSUE THREAD

**Issue by mdhank** [UCATLAS/xAODAnaHelpers#1630]
Dear Developers,

I have been receiving a nan error in the METConstructor.

I am using commit https://github.com/UCATLAS/xAODAnaHelpers/commit/ae64473c94194a705ea0cfd9eff7dd7641aaa95a of xAODAnaHelpers. I am running AnalysisBase 22.2.108 through a modified version of the BLstop framework (https://gitlab.cern.ch/atlassusy-bminusl/BLstopWorkspace). I am testing various samples using e8351_s3681_r13167_p5511 of DAOD_PHYS
. An example of my commands is

./source/xAODAnaHelpers/scripts/xAH_run.py -f --files ttbar_dilep_physlite_full.txt --nevents 10000 --config source/BLstopAnalysis/data/myconfig.py --inputRucio --inputList --isMC --submitDir tt_ll_test direct

When running on certain samples, I get a repeated error

TROOT::TVector2::Phi_m... ERROR   function called with NaN

This error has only occurred for samples containing Z bosons decaying to ee or mumu. It occurs often in Z+jets ee or mumu samples (DSIDs 700320-700326), as well as less often for ttZee, ttZmumu, and ZH (DSIDs 410218, 410219, and 346310). The error has not occurred for any other samples I’ve tested (Z+jets tautau, ttZqq, ttZtautau, data, ttbar non-all-hadronic, ttbar dileptonic, ttH, ttW, W+jets, or WH).

Using the debug mode, the nan first appears at https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/METConstructor.cxx#L531, but only for systematics MET_SoftTrk_ScaleDown, MET_SoftTrk_ScaleUp, MET_SoftTrk_ResoPara, and MET_SoftTrk_ResoPerp (not for nominal). This then causes the error, which I believe is raised in met::buildMETSum. This error does not stop the processing, and I am able to get working output files.

Best,
Michael

**Comment by mswiatlo** [comment]
@miholzbo and @hollypacey are more relevant here-- something does smell wrong here though. What's in your config-- how are you setting up the MET algorithms?

**Comment by miholzbo** [comment]
Hi, we're aware of this eror and indeed it only occurs when processing the MET systematics (and only for a fraction of the events). That's extremely likely more an issue of the METSystematics tool than xAH where in some rare cases the variations of the soft term seem to cause some issue in the final MET calculation.

**Comment by jbossios** [comment]
Hi @miholzbo 

Is this issue being tracked on JIRA or somewhere?

**Comment by miholzbo** [comment]
Hi @jbossios,

No, it's not yet tracked "officially" somewhere; In principle we also don't have recommendations for the MET systematics in R22 yet so we didn't expect people to run these :)
We have observed this only last week (which actually made me spot the bug in METConstructor I made a PR for recently) and I'll have further looks soon.

**Comment by mdhank** [comment]
Hi @miholzbo ,

I'm not actually using these yet; I just never turned them off.

In case it helps your debugging, here's the frequency by DSID:
700320, 700323 (Z+jets BFilter): 2-3% of events
700321, 700324 (Z+jets CFilterBVeto): 7-8% of events
700322, 700325 (Z+jets CVetoBVeto): 25-32% of events

**Comment by miholzbo** [comment]
The problem occurred in events where no hard object was added to the MET calculation, i.e. the MET consists only of the TST soft term. This resulted in a division by 0 when the soft term was adjusted for the MET TST systematics. A projection for this is present in R21 but wasn't migrated to R22 yet. This is fixed in https://gitlab.cern.ch/atlas/athena/-/merge_requests/61504

**Comment by jbossios** [comment]
Thanks for letting us know. I will keep this open until the MR is merged and the fix available in a release, then I will add that release to the CI jobs.
