### ISSUE TITLE
"Could not find input string in enum!" and LooseBL updates

### ISSUE THREAD

**Issue by mdhank** [UCATLAS/xAODAnaHelpers#1631]
Dear Developers,

I've been seeing the line "Could not find input string in enum!" in my output and attempted to investigate.

I am using commit https://github.com/UCATLAS/xAODAnaHelpers/commit/ae64473c94194a705ea0cfd9eff7dd7641aaa95a of xAODAnaHelpers. I am running AnalysisBase 22.2.108 through a modified version of the BLstop framework (https://gitlab.cern.ch/atlassusy-bminusl/BLstopWorkspace). I am testing various samples using e8351_s3681_r13167_p5511 of DAOD_PHYS
. An example of my commands is

./source/xAODAnaHelpers/scripts/xAH_run.py -f --files ttbar_dilep_physlite_full.txt --nevents 10000 --config source/BLstopAnalysis/data/myconfig.py --inputRucio --inputList --isMC --submitDir tt_ll_test direct

I traced the output to https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/ParticlePIDManager.cxx#L85 . This occurs because "VeryLooseNoPix" does not exist in https://gitlab.cern.ch/atlas/athena/-/blob/master/PhysicsAnalysis/ElectronPhotonID/ElectronPhotonSelectorTools/ElectronPhotonSelectorTools/LikelihoodEnums.h . The output no longer occurs if "VeryLooseNoPix" is removed from lines 17, 23, and 33. However, I don't understand the code well enough to know if this is desired- if "VeryLooseNoPix" can still be accessed in other ways, it might be better to manually add like in https://github.com/UCATLAS/xAODAnaHelpers/pull/1324.

While looking into this, it also made me realize https://github.com/UCATLAS/xAODAnaHelpers/pull/1620 isn't quite right. LooseBL is being overwritten on https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/ParticlePIDManager.cxx#L26 and https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/ParticlePIDManager.cxx#L44. If these are fixed and LooseBL is added to https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/HelperClasses.cxx, it appears to work as desired. LooseBL was only added to LikelihoodEnums.h last July, not 3 years ago when it was added to the smart slimming list.

As a final note, "Could not find input string in enum!" also occurs for the HighPt Muon WP, but this appears to be expected behavior.

I can make an PR for the second part if this sounds reasonable, and for the first part if a way forward is decided on.

Best,
Michael

**Comment by jbossios** [comment]
Hi @mdhank,

Thanks for reporting all this.

1. Indeed VeryLooseNP doesn't seem to be supported anymore, so it should be fine to remove all its mentions
2. You are absolutely correct about #1620. This kind of hardcoded things can easily be overlook. Very good catch!

Thanks for offering making this changes into a PR!

Best,
Jona

**Comment by mdhank** [comment]
On a related note I forgot to mention, I also found hints that m_doModifiedEleId is no longer needed (SUSYTools removed it in December https://gitlab.cern.ch/atlas/athena/-/commit/92c60e28b95872589d1ad6e0fda381445cae2143).  If this is the case, I can also clean that up.

**Comment by jbossios** [comment]
Since m_doModifiedEleId is false by default, I guess it doesn't hurt to keep it around in case is needed in the future.

**Comment by mdhank** [comment]
I looked closer, and I'm pretty sure it won't matter even if it's left on- by construction, it won't change the behavior if there's no bug.
