### ISSUE TITLE
Unfortunate seg fault if input file has no CollectionTree

### ISSUE THREAD

**Issue by SagarA17** [UCATLAS/xAODAnaHelpers#1653]
While running on DAODs on the grid, especially data, there are many cases in which none of the input events pass the trigger skimming of the DAODs, and hence there is no `CollectionTree` in the input file. While the EventLoop is smart enough to ignore it and move on to the next file, there's a segmentation violation in the end which causes the job to fail. This behaviour is harmful for large scale dagman or grid jobs which rely on a certain % non-failure, without which the whole task is killed.

I give an example of such a case where all input DAODs had no `CollectionTree` tree, which caused a segmentation violation at the end after the loop had run over all five files.
https://bigpanda.cern.ch//media/filebrowser/7af69ffe-655f-473b-915c-cd3c432c5e30/panda/tarball_PandaJob_5928221565_CERN/payload.stdout

**Comment by kratsg** [comment]
It does appear that the segfault occurs outside of xAH however -- rather than anything xAH-specific. See this portion

```
xAOD::TFileAccessTracer   INFO    Sending file access statistics to http://rucio-lb-prod.cern.ch:18762/traces/
Finished executing root
Thu Aug 10 17:39:39 CEST 2023
```

which means it's already handed off the control back to the EventLoop worker so I believe segfault is occurring outside of the framework. If you can reproduce this through `gdb` to see where the segfault is occurring, that would help -- but I would recommend emailing the mailing lists (pathelp, amg) to see if anyone knows what is going on here.

**Comment by SagarA17** [comment]
HI @kratsg,

I tried to run on such an "empty" file locally, and again I ran into a seg fault.

```
Package.EventLoop        INFO    Processing events 0-0 in file file:///eos/atlas/atlasdatadisk/rucio/data18_13TeV/30/82/DAOD_LLP1.34214133._000001.pool.root.1
ElectronCalibrator.Ele...INFO    Calling histFinalize
ElectronSelector.Elect...INFO    Calling histFinalize
MuonCalibrator.MuonCal...INFO    Calling histFinalize
MuonSelector.MuonSelect  INFO    Calling histFinalize
JetCalibrator.JetCalib...INFO    Calling histFinalize
BJetEfficiencyCorrecto...INFO    Calling histFinalize
OverlapRemover.Overlap...INFO    Calling histFinalize
IsoCloseByCorr.IsoClos...INFO    Calling histFinalize
 *** Break *** segmentation violation
[2023-08-10 20:33:33,948][ERROR  ]  --------------------
An exception was caught! (xAH_run.py:656)
Traceback (most recent call last):
  File "/home/sagara17/dHNL/dHNL_Algorithm/build/x86_64-centos7-gcc11-opt/bin/xAH_run.py", line 638, in <module>
    driver.submit(job, args.submit_dir)
cppyy.ll.SegmentationViolation: string EL::Driver::submit(const EL::Job& job, const string& location) =>
    SegmentationViolation: segfault in C++; program state was reset
[2023-08-10 20:33:33,949][INFO   ]  ======================================== (timing.py:22)
[2023-08-10 20:33:33,949][INFO   ]  469914:33:33.949-End Program (timing.py:23)
[2023-08-10 20:33:33,949][INFO   ]  Elapsed time: 0:00:09.666 (timing.py:25)
[2023-08-10 20:33:33,949][INFO   ]  ======================================== (timing.py:26)
xAOD::TFileAccessTracer   INFO    Sending file access statistics to http://rucio-lb-prod.cern.ch:18762/traces/
```
Here is the file if you would like to try and reproduce the error - `file:///eos/atlas/atlasdatadisk/rucio/data18_13TeV/30/82/DAOD_LLP1.34214133._000001.pool.root.1`

I will try to run with `gdb` and can let you know what I find.

**Comment by kratsg** [comment]
Can you share your configuration? I ran this with just BES and it runs fine w/o a segfault.. which tells me you're probably using an algorithm that's segfaulting, or the issue has to do with the configuration somehow.

**Comment by SagarA17** [comment]
Not sure what level of detail you would like! I will try anyway. Any of the releases in the pipeline work fine.
This is the framework that I use - https://gitlab.cern.ch/atlas-phys/exot/ueh/EXOT-2017-19/dhnl-algorithm-r22
The config is a python based file - https://gitlab.cern.ch/atlas-phys/exot/ueh/EXOT-2017-19/dhnl-algorithm-r22/-/blob/master/data/config_main.py
Let me know if I could supply any more info!

**Comment by kratsg** [comment]
Looking at the config quickly, it seems that the algorithms you're running in `dhnl-algorithm-r22` is what is causing the segfault, and not any algorithm in xAH. Remember xAH is just a framework that comes with a useful `xAH_run.py` that many people use to steer their own written algorithms.

**Comment by SagarA17** [comment]
Indeed. I will try to iteratively remove algorithms and see what could fix it. I would request to not close this issue for some time. If I haven't found an issue in a week, feel free to close it! Thanks for the help!

**Comment by SagarA17** [comment]
Hi @kratsg. I found the problematic seg fault piece of code in our framework. It wasn't xAH related, like you said. Thanks for the help. I will close this issue now.
