### ISSUE TITLE
Adding truth / Mulitple collection to ntuple in HelpTreeBase

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#172]
Issue here is we would like to write out jets and truth jets to an ntuple. 
In the past we've either done one or the other. I can think of two ways forward

a) void HelpTreeBase::AddTruthJets(const std::string detailStr)

or 

b) void HelpTreeBase::AddJets(const std::string detailStr, const std::string jetColName="")

In a) we would call AddJets to add the jets and AddTruthJets to add truth jets

In b) we would call AddJets as usual to add jets. then we would call AddJets("kinematic ...", "truth") 
where the second string specifies a postfix for branches in the ntuple. 

What do people think ?  I can see b) being useful if people want to write out multiple jet collections of any type...eg: trigger jets and offline jet ect. 

john

**Comment by gfacini** [comment]
Hi John,

I like the idea of adding more collections vis AddJets with a ColName.  I have a 2 requests:
1. jetColName = "" gives what we have now (no ones code breaks)
2. The names of the collections are forced to some degree to agree with the naming conventions in the xAODs.  For example, all of the jet variables in the tree have the same name as the corresponding xAOD jet moment as it is not our job to remake or rename the EDM but to make using it easier.  I would like to avoid one person having EMTopo and someone else having TopoEM.  We quickly start to get into a configuration where every tree coming out of this code has unique names - sounds like the 100 flavors for D3PDs....

Cheers,
Gabriel

**Comment by mmilesi** [comment]
Hi @johnda102 , @gfacini

sorry for hijacking this conversation, but it's probably the right place for me to go.

A guy that shares the framework with me would like to perform jet constituents truth matching, as well as get somehow the truth jet origin information (e.g., jet is from a W, from a top quark, etc.).

I guess you are familiar with this and have already implemented it in xAH somewhere. Could you kindly point me to the parts of the code where this truth matching for jets is actually implemented, and how the relevant info gets dumped in the ntuple?

Thanks!

Marco

**Comment by johnda102** [comment]
Hi Marco, 

  Sorry just saw this now.  I havent done any truth info at this level.  Ive only used the standard bjet truth matching in btagging.
