### ISSUE TITLE
Muon Weight Decoration Name

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#204]
Ciao, @mmilesi 

The name given to the decoration for the muon weights are a bit odd:
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/MuonEfficiencyCorrector.cxx#L478
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/MuonEfficiencyCorrector.cxx#L503

I recently changed the b-tagging code to use the decor string

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BJetEfficiencyCorrector.cxx#L329

Which starts off as ""BTag_SF" then gets appended with the operating point the tools is
configured with:
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BJetEfficiencyCorrector.cxx#L112

With this I made a standard method for the scale factors and corresponding decisions to be put into
the tree

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L1058

Can we adopt something similar for the lepton weights?

Also, do we really need to store doubles?  We are using floats everywhere and I don't see how the additional precision is needed for scale factors.  

I am happy to make some of these changes myself but do not want to encroach too much.

Cheers,
Gabriel

**Comment by gfacini** [comment]
@mmilesi 

Any comments here!?  If not objections I will make the change next week

**Comment by mmilesi** [comment]
Hi Gabriel,

Sorry but has been a busy week. I promise I'll check it out next week!

Marco

**Comment by mmilesi** [comment]
Hi @gfacini ,

check out #229 : I have addressed ~90% of the points raised here.
