### ISSUE TITLE
B-Tagging Changes

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#212]
@johnda102 @kratsg 

Flavor tagging made some changes.  There is now a tool to select jets at a given operating point and there are several OPs for an inclusive efficiency and others for flat efficiencies vs pT.  The current thing we have will not work any more.

Proposed changes:
1A. BJetEfficiencyCorrector - will configure the selector tool and the efficiency retrieval tool and decorate the jet accordingly.  One can then use a series of these to test various operating points down stream.  No cuts applied here.
1B. Adding the inefficiency scale factor - needed by most you use a b-tag

2. Add this selection tool to the JetSelector so one can still select only b-jets.  Next iteration allow for the BJetEfficiencyCorrector to pick up parameters from the JetSelector but for now, one will have to configure both separately.

Any major issues with this plan...I am implementing now.

Gabriel

**Comment by gfacini** [comment]
https://twiki.cern.ch/twiki/bin/view/AtlasProtected/BTaggingCalibrationDataInterface#Example_AN1

**Comment by gfacini** [comment]
I got things which compile - debugging and working on the tree next
branch: BTagChanges staring with this commit 
https://github.com/UCATLAS/xAODAnaHelpers/commit/752ebeba05bd32e800dcd736e95df6794dc0b7a2

**Comment by AndreaCoccaro** [comment]
This may also help:
https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/JetTagging/JetTagPerformanceCalibration/xAODBTaggingEfficiency/trunk/util/BTaggingSelectionToolTester.cxx
