### ISSUE TITLE
Defining MetaData

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#223]
@mmilesi 
Can you fill in these details?
https://github.com/UCATLAS/xAODAnaHelpers/wiki/xAH_JetCalibrator.h#how-to-define-sample-metadata-for-simulation-flavour--full-sim-vs-afii-

**Comment by mmilesi** [comment]
Hi @gfacini 

The idea would be to have in your steering macro something like:

```
    // access a single sample
    Sample *sample = sh.get ("mc14_13TeV. blahblahblah");
    sample->setMetaString ("SimulationFlavour", "AFII");
```
