### ISSUE TITLE
Problem with BTag SF switch in Tree

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#225]
Hi @gfacini ,

I was trying to test the brand new stuff you added for BTagging  (whoa! That was a lot of nice new features!)

Unfortunately I am encountering a problem when trying to add the SF (fixed efficiency) switch in the output tree:

```
JetDetailStr:             "kinematic energy flavorTag sfFTagFix70" [Local]
```

This is the run time error I am getting:

```
Info in <TreeAlgo::treeInitialize()>: Succesfully configured! 
Info in <HelpTreeBase()>: HelpTreeBase setup
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::erase
Aborted
```

Could you please have a look at that? Or maybe I am just mis-using the option...

Marco

**Comment by gfacini** [comment]
@mmilesi 
What was the operating point you passed to the BJetCorrection Algo?

**Comment by mmilesi** [comment]
`FixedCutBEff_70`
