### ISSUE TITLE
Putting common job submission in xAH

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#227]
Hi All, 

   A bunch of packages have tools for job submission/retrieval to the grid.  (Dijet/Multijet/ BJetTrigger studies ...) Instead of having code duplicated in several places lets put the common functionality in xAH. 

Ill work on this today.

**Comment by kratsg** [comment]
@johnda102 this exists in xAH_run.py :) [going to keep pushing the python script here]

**Comment by johnda102** [comment]
@kratsg ok yes it also exists in the Dijet/Multijet code. I guess moving to xAH_run.py for the top-leve is a much bigger change. I think we want to consolidate what we have first and then understand the pros and cons of going to xAH_run

**Comment by gfacini** [comment]
@johnda102 @kratsg 
One point here is that Giordon is working on Condor support in the python script.  I think once that is ready and we pass LHCP we should do as John says - understand the differences and consolidate.  For now we remain (slightly) inefficient.

**Comment by kratsg** [comment]
@gfacini Condor support is now complete as of last night in my code minimally. I'll be able to make the appropriate updates to `xAH_run.py` pretty soon.

**Comment by gfacini** [comment]
Amazing!
