### ISSUE TITLE
Updates to xAH_run

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#252]
Hi All, 

  Id like to (finally:) ) move to using xAH for top level steering.  However there are a few things that are not clear to me.

Configuration: 
-) Seems like the driver option needs to be given without "--" whereas the other arguments need "--", any reason for this ?

-) Seels like other arguments cannot come after the driver.  Any reason for this ?

-) Head crashes for me on
     l407 user_confirm(args, 4+args.optimization_dump) 
 Not clear what this is for or where its defined. 

-) -optGridOutputSampleName is defined to be a required option. I assume we dont want this.

**Comment by kratsg** [comment]
> -) Seems like the driver option needs to be given without "--" whereas the other arguments need "--", any reason for this ?
> -) Seels like other arguments cannot come after the driver. Any reason for this ?

The `driver` option is a special one called a subparser. It actually switches the context of `xAH_run.py` into a new portion of the script defining which driver to run as well as a whole new set of arguments. You can see this with` xAH_run.py -h driver` or `xAH_run.py direct -h` or `xAH_run.py prun -h`. As you can see, the help menu changes a bit. The idea is to have the user always specify files, other arguments, and then how to run it.



> -) Head crashes for me on
> l407 user_confirm(args, 4+args.optimization_dump) 
> Not clear what this is for or where its defined.

I'll fix that.



> -) -optGridOutputSampleName is defined to be a required option. I assume we dont want this.

Yeah, I'll fix that, the default should be ok.

**Comment by johnda102** [comment]
ok thanks @kratsg makes sense. 

Ive also been talking to some people (@kkrizka @alexandertuna) who have been playing around with the xAH_run.py and I think there is a consensus that we should move away from configuration with json files. 

One idea is for each analysis to write a configure script in python that xAH_run.py then imports.
These would do job set up in python and add algs to the ROOT.EL.Job() 

Of course we could support both json files and direct python configuration if there is a community happy with the json config. 

What do people think ?

**Comment by kratsg** [comment]
Why don't people like json? I would be curious to know what's wrong with that. I haven't heard any comments about it and it's a well-documented format.

I would totally use yaml if it was possible (it supports references).

**Comment by alexandertuna** [comment]
Is it possible to request yaml be included in an analysis release? Or are analysis releases not like athena releases? And it's unrealistic to require users to install it locally, right?

**Comment by kratsg** [comment]
@alexandertuna what's the reason strictly for yaml? Is it just references? I added a feature that allows you to add comments to json files.

It is quite unreasonable to ask users to install yaml unfortunately :-/

HOWEVER, if you want to write your files in yaml, and you've installed it on whatever machine you're on, you can just do

```bash
python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < file.yaml > file.json
```

which allows you to quickly convert if you write a configuration file in yaml. It's not hard at all to add the same configuration for python - but it's not trivial to support yaml for all users. We could add the package into xAH but that seems bloated.

**Comment by alexandertuna** [comment]
I don't have major reasons for preferring yaml to json, I just like the cleanliness and python api.

**Comment by kratsg** [comment]
We could end up doing something like this: https://docs.python.org/2/library/configparser.html

It isn't THAT bad and might be a bit more reasonable?

**Comment by johnda102** [comment]
@kratsg 

Configuring in python has the advantage that you can use all the power of the programing language. 
eg: loops, variables, function calls etc.

Its also less verbose (no ","s "{"s etc) that are needed in the json file. 

Heres what I would have in mind for a 

def addJobs(Job);
     # load Basic event selection
    basicEventSelection = BasicEventSelection() # could be used defined or in common library 
    Job.addAlg(basicEventSelection)

    jetCalib = JetCalibration() # could be used defined or in common library 
   Job.addAlg(JetCalibration())

    preJetSelection = JetSelection("preSelJets", etaCut = 2.5, bTagCut = None) 
   Job.addAlg(preJetSelection)

    preJetPlots = JetHistAlgo(inCol = "preSelJets") 
   Job.addAlg(preJetPlots)

   operatingPts = ["Loose", "Medium","Tight"]
   for opPt in operatingPts:
        tagJetSelection = JetSelection(opPt+"TagJets", etaCut = 2.5, bTagCut = opPt) 
       Job.addAlg(tagJetSelection)
    
        tagJetPlots = JetHistAlgo(inCol = opPt+"TagJets") 
       Job.addAlg(tagJetPlots)
   ....


For me, its much easier to think about the logic of the analysis at this level.  It would also be much clearer whats happening than writting the corresponding json file directly. 

Of course, If people really like using the json files your python config file could simply open the json file and add the algs to the Job exactly as we are doing now.

**Comment by kratsg** [comment]
Hi @johnda102 so what you're proposing is a bit more specific. It may not have been blatantly obvious from what's been written here, but the configuration file can handle non-xAH algorithms as well by default.

> def addJobs(Job);
> # load Basic event selection
> basicEventSelection = BasicEventSelection() # could be used defined or in common library 
> Job.addAlg(basicEventSelection)
> 
> jetCalib = JetCalibration() # could be used defined or in common library

This assumes the user only needs to call that algorithm once. Because it's a mutable object, it gets passed around by reference in python. If a user wants to create another one, they will have to re-initialize the algorithm as well.

> operatingPts = ["Loose", "Medium","Tight"]
> for opPt in operatingPts:
> tagJetSelection = JetSelection(opPt+"TagJets", etaCut = 2.5, bTagCut = opPt) 
> Job.addAlg(tagJetSelection)
> 
>     tagJetPlots = JetHistAlgo(inCol = opPt+"TagJets") 
>    Job.addAlg(tagJetPlots)

That's probably a strong use-case for it.

> For me, its much easier to think about the logic of the analysis at this level. It would also be much clearer whats happening than writting the corresponding json file directly.
> 
> Of course, If people really like using the json files your python config file could simply open the json file and add the algs to the Job exactly as we are doing now.

It is probably clearer. We could think of the json file as the proper translation, and you're free to write up a python script that generates the JSON file for you. It's a relatively simple operator, so to take one of your examples:

```
import json

jobConfigurations = []

for opPt in ["Loose", "Medium", "Tight"]:
  jetSelect = {"class": "JetSelector", "configs": [{"m_operatingPt": opPt, "m_eta_max": 2.5, "m_eta_min": -2.5, "m_doBTagCut": True"}]}
  jobConfigurations.append(jetSelect)

with open(outfile, 'w') as f:
  f.write(json.dumps(jobConfigurations, sort_keys=True, indent=4))
```

and then use that generated json file to run the job.

**Comment by johnda102** [comment]
@kratsg 

We could have the python config scripts write out json files that are then opened by the main python run script and added to the Job.  Although I dont really see the advantage of the intermediate format. (maybe you want it for saving the exact configuration run?).  Seems simpler to me to have the python configuration directly add algorithms to the Job.

**Comment by kratsg** [comment]
Hi @johnda102 - if you really want to do it fully in python, there's no strict reason for you to use xAH_run.py as you're going to be also doing an intermediate format that gets passed in to xAH_run technically.

One can easily do

```
jetSelect = ROOT.JetSelector()
...
jobs.algsAdd(jetSelect)
```

in python, forgoing the actual step of JSON. The reasons for having a text format like this are:

1. as you mentioned, saving the exact configuration run so you can repeat the analysis later without having to copy and paste anything [it's a plain text file essentially] -- xAH_run.py also creates a `xAH_run.log` file in the submission directory containing information about when/how a specific job was run too!
2. allowing anyone (including new UGs, grad students, post-docs, and profs) who are not familiar with xAOD analysis, writing correct C++ code, or writing python, to simply look up what they need in our header files, and just write out the algorithms they need to run and how to configure it. The python script will take this in, and do all of their work for them with less of a headache.
3. providing a standard interface so if you need to run someone's analysis based on xAH - you can ask for their json configuration file and you know how to run it on your files as well as locally. It makes it _very_ easy to test these things and pass around examples, as you only need a simple text file to effectively to run up a whole analysis

**Comment by johnda102** [comment]
@kratsg 

I think the big reason to have a common run script is the handling the details of the drivers (condor,grid etc).

ok sounds like we get 1) for free. 
For 2) as I wrote before I think the python is much cleaner for a new comer or prof.
For 3) we can establish a common interface for all users, eg in my example before,  all python config files would implement an 

```python
addJobs(Job);
```
function which takes ROOT.EL.Job().

**Comment by kratsg** [comment]
If we switch to using a python, we would have to think about the logic to get `1` working again. Technically, because it's a json file that tells me all the configurations a user does, it's easy to write a log file writing out all the configurations that the user does.

If we do python, we would have to write a function introspection to parse and evaluate the python line by line so we know what configurations the user does [one cannot simply use `dir(object)` and grab all the attribute values, because we care less about ALL attributes. we only want the ones that the user sets]. One way to get around it is to provide a function that does it for the user:

```python
set_attr(algorithm, "m_debug", True)
```

for example. This would globally log things into some container that keeps track of things being set.

I'm not sure why we need `3` however. You could simply instruct the user to append all objects created to a list called `algs` - and we would just retrieve that list, iterate over it, and add each algorithm to the job.

**Comment by johnda102** [comment]
Hi Giordon, 

  Heres a more concrete example of how I see the python config files used for the case of Xhh 4b running the resolved and mergered together.

I would run with: (in the testPyConfig branch of xAH) 

```bash
xAODAnaHelpers/scripts/xAH_run.py    --files mc15_13TeV.301495.MadGraphPythia8EvtGen_A14NNPDF23LO_RS_G_hh_bbbb_c10_M1000.merge.DAOD_EXOT8.e3820_s2608_s2183_r6630_r6264_p2406  --config XhhCommon/scripts/combinedMaster.py --inputDQ2 -f   --nevents 1000 direct
```

which is configured with: 

https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/JDM/hh4b/Run2/Code/XhhCommon/trunk/scripts/combinedMaster.py

that in turn calls: 
https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/JDM/hh4b/Run2/Code/XhhCommon/trunk/scripts/XhhResolved_config.py
for resolved. 

and 
https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/JDM/hh4b/Run2/Code/XhhCommon/trunk/scripts/XhhBoosted_config.py
for boosted

**Comment by kratsg** [comment]
Sure, that would be for your Xhh analysis. What about say, another analysis that has completely different algorithms and so forth? Having to write a custom python function that has all the arguments/parameters also means we have to always do the work of making sure the python script is up to date with the xAH algorithms involved.

With a plain text file, we don't worry about this since it will attempt to dynamically configure. This is the part that I worry about, as well as making sure _any_ algorithm can be configured from xAH_run.py.

**Comment by johnda102** [comment]
yes for different analysis we need different configuration (these costum algorithms would of course have to be added to the json files too). However some of the common core configuration can be shared. 

For the Multijet it could look something like:

```python
import ROOT
from xAH_config         import *
from MultiJetAlgo       import *

#                                                                                                                                                        
# Main Algo                                                                                                                                              
#                                                                                                                                                        
def addAlgs(Job):

   #                                                                                                                                                    
    # Basic Setup                                                                                                                                        
    #                                                                                                                                                    
    triggers = "HTL_ht850.*
    config_BasicEventSelection(Job, derivationName="EXOT8", triggerSelection=triggers)
    # reuses conifguration in xAH

    #                                                                                                                                                    
    #  Jet Calibration                                                                                                                                   
    #                                                                                                                                                    
     #... use common jetcalibration config in xAH

   #
   #  Jet Selection
  #
   #... Use common jet seleciton config in xAH

    #                                                                                                                                                    
    # Ntuples                                                                                                                                            
    #                                                                                                                                                    
    #... Use costum ntupler in MultiJet package

   #
   # Jet Plotter
   #
   # ... Use common jet plotter config in xAH
```

So the interface to xAH_run is the same and it can reuse some common config of core packages.

**Comment by johnda102** [comment]
Heres a more concrete example of what the Multijet version would look like. 
All but the last function call is in xAH base and can be shared with the packages. 

```python
import ROOT
from xAH_config         import *

def config_MultijetAlgorithm(Job, **kw):
    multijetAlgo = ROOT.MultijetAlgorithm()
    setMemberFunctions(multijetAlgo, kw)
    Job.algsAdd(multijetAlgo)

#
# Main Algo
#
def addAlgs(Job):

    #
    # Basic Setup 
    #
    triggers = "HLT_j.*|HLT_ht.*|L1_J.*|L1_HT.*|HLT_noalg_L1J.*"
    config_BasicEventSelection(Job, 
                               m_name                = "basicEventSel",
                               m_applyGRLCut         = False,
                               m_derivationName      = "EXOT1", 
                               m_storePassL1         = True,
                               m_storePassHLT        = True,
                               m_storeTrigDecisions  = True,
                               m_storeTrigKeys       = True,
                               m_applyTriggerCut     = True,
                               m_triggerSelection    = triggers, 
                               )

    #
    #  Jet Calibration
    #
    config_JetCalibrator(Job, 
                         m_name                   = "jetCalib_AntiKt4TopoEM", 
                         m_inContainerName        = "AntiKt4EMTopoJets",
                         m_jetAlgo                = "AntiKt4EMTopo",
                         m_outContainerName       = "AntiKt4EMTopoJets_Calib", 
                         m_outputAlgoSystNames    = "AntiKt4EMTopoJets_Calib_Algo",
                         m_sort                   = True,
                         m_saveAllCleanDecisions  = True,
                         m_calibConfigAFII        = "JES_MC15Prerecommendation_AFII_June2015.config",
                         m_calibConfigFullSim     = "JES_MC15Prerecommendation_April2015.config",
                         m_calibConfigData        = "JES_MC15Prerecommendation_April2015.config",
                         m_calibSequence          = "JetArea_Residual_Origin_EtaJES_GSC",
                         m_JESUncertConfig        = "$ROOTCOREBIN/data/JetUncertainties/JES_2015/Prerec/PrerecJES2015_3NP_Scenario1_25ns.config",
                         m_JESUncertMCType        = "MC15",
                         m_JERUncertConfig        = "JetResolution/Prerec2015_xCalib_2012JER_ReducedTo9NP_Plots_v2.root",
                         m_JERApplyNominal        = False,
                         m_redoJVT                = False,
                         m_systName               = "All", 
                         m_systVal                = 1,
                         )

    #
    #  Jet Selection
    #
    config_JetSelector(Job, 
                       m_name                    = "JetSelector",
                       m_inContainerName         =  "AntiKt4EMTopoJets_Calib",
                       m_inputAlgo               =  "AntiKt4EMTopoJets_Calib_Algo",
                       m_outContainerName        =  "SignalJets",
                       m_outputAlgo              =  "SignalJets_Algo",
                       m_decorateSelectedObjects =  True, 
                       m_createSelectedContainer =  True, 
                       m_cleanJets               =  False, 
                       m_pT_min                  =  50e3,
                       m_eta_max                 =  2.8,
                       m_useCutFlow              =  True,
                       m_doJVF                   =  False,
                       )

    #
    # Ntuples
    #
    config_MultijetAlgorithm(Job, 
                             m_name                   = "MultijetAlgo",
                             m_debug                  = False, 
                             m_truthLevelOnly         = False, 
                             m_isMC                   = False,
                             m_writeTree              = True, 
                             m_inContainerName        = "SignalJets",
                             m_inputAlgo              = "SignalJets_Algo",
                             m_leadingJetPtCut        = 40000, 
                             m_MCPileupCheckContainer = "None", 
                             m_eventDetailStr         = "pileup", 
                             m_jetDetailStr           = "kinematic rapidity clean energy  layer scales trackPV",
                             m_trigDetailStr          = "passTriggers basic menuKeys", 
                             )
```

**Comment by kratsg** [comment]
Thanks for all the comments @johnda102 - I think you have a strong argument so I propose we support both methods. One method allows the user to specify a json file (default) to configure the script. This is the simplest and a "works out of the box". The second method will allow the user to specify a correctly-written python script (instead of json) like what you have above.

I have an idea that will allow us to automatically write out the functions for the configurations of algorithms without needing to define the functions ourselves (meta-programming and the like).

Does that sound agreeable?

**Comment by johnda102** [comment]
Hi Goirdon, 
  Yes sounds very sensible to me.  Also in like with @jdandoy comments about preserving backward compatibility
