### ISSUE TITLE
xAH_run Assumes DQ2 With Condor

### ISSUE THREAD

**Issue by kkrizka** [UCATLAS/xAODAnaHelpers#262]
The xAH_run.py scripts assume that the input files come from DQ2 when running on condor. This is not always true. For example, I have a set of private samples on faxbox which manage using txt filelists (ie --inputList option).

**Comment by kratsg** [comment]
Do you have an example of running on condor and setting up SH using the input filelist? I wasn't able to get SampleHandler to treat my xrootd paths correctly.

**Comment by kkrizka** [comment]
Other than this problem with the DQ2, I don't have any problems with running using xrootd paths when I use the --inputList option of the xAH_run script. What problems are you seeing?

For an example, you can look at the code here:
https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/JDM/DiJetISR/Run2/Code/ZprimeDM/trunk

There is a list of filelists at:
/afs/cern.ch/user/k/kkrizka/public/mcgen/filelists/

I run the code with (up to now, I was using a modified xAH_run with this DQ2 problem fixed, adding of xsec weights and --waitForDone option):
./ZprimeDM/scripts/xAH_run.py --config ZprimeDM/data/gammajetjet.json --files /afs/cern.ch/user/k/kkrizka/public/mcgen/filelists/MC15*dmA_dijetgamma_*mDM1000*txt --inputList --submitDir OUT_gammajetjet_offline --force condor --waitForDone

**Comment by kratsg** [comment]
I think it might have been resolved since AB,2.3.19 actually!

The other question I have is - do you notice that this is faster using xrootd paths directly than trying to use `fax-get-gLFNs` when scanning dq2?

**Comment by kkrizka** [comment]
Actually I've switched back to using fax-get-gLFNs. It is quite fast.

These filelists are for private samples that are not on DQ2.

**Comment by kratsg** [comment]
@kkrizka I've noticed that with a condor submission, if I specify something like 10 samples which have 100+ gLFNs, it hangs on the submitting portion.
