### ISSUE TITLE
BJet SF - Default value

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#263]
Hi @johnda102 , @gfacini ,

Looking at line:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BJetEfficiencyCorrector.cxx#L426

Shouldn't the SF be = 1 by default?
I am asking this because I wish to apply the SF in a TTree::Draw cut string, and being it = 0 by default gives of course some trouble.

Is that ok for you to change it to 1?

Cheers

Marco

**Comment by johnda102** [comment]
Hi Marco, 

 Do you actually see Bjets with SF == 0 ?

I think you should only see. 
-1 / -2 / the result returned by the tool 

Maybe the 0 is coming from the tool ?

**Comment by mmilesi** [comment]
Hi @johnda102 ,

I still haven't looked at the BTag SF in my final ntuple. I have reported this because I noticed  the problem with electron and muon SFs (my bad!) that are incorrectly initialised to 0. This is going to be fixed as soon as I push a branch I am working on now, tomorrow I think.

However, having a -1 weight to multiply each event where the SF hasn't been calculated isn't dodgy as well?

**Comment by johnda102** [comment]
Yeah maybe we want to change some of these 

-2 is set if there is an error thrown when calculating the SF
-1 is set for jets for which the BTag SF is not defined (eg: outside eta acceptance)

**Comment by mmilesi** [comment]
For the reasons gave above, I would be more inclined to having 1 as default, and -2 only in case of errors.

**Comment by johnda102** [comment]
ok sounds fine with me.

In which case we should only need to change
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BJetEfficiencyCorrector.cxx#L445

On Wed, Sep 23, 2015 at 1:35 PM, Marco Milesi <notifications@github.com>
wrote:

> For the reasons gave above, I would be more inclined to having 1 as
> default, and -2 only in case of errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/263#issuecomment-142573808>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mmilesi** [comment]
Thanks John! I will include the change in the PR I'll release tomorrow.
