### ISSUE TITLE
b-tagging scale factors in the tree and for more than 1 operating point

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#27]
We have dijet collaborators working on this and should pull them into git land

**Comment by mmilesi** [comment]
What do you mean by multiple decision?

**Comment by gfacini** [comment]
the scale factors for multiple working points - I changed the title of the issue to make that clear
potentially the scale factors for several taggers as well
A lot of this will not be needed when continuous tagging is available ... I have no idea what the status of that is
