### ISSUE TITLE
overlap removal: don't run nominal of nominal's not there.

### ISSUE THREAD

**Issue by JamesSaxon** [UCATLAS/xAODAnaHelpers#273]
If one runs 

jcal->setName("jetCal")->setConfig(rcdir + "VBFInv/jetCal.config" )->setSyst( "SingleSyst", 1 );

the algo just provides the positive and negative variations of the jet calibration.

One then threads the systematics through to OverlapRemover.cxx, where at L325 nominal runs regardless.  This causes a crash if one tries to run a single systematic.  Presumably if one does this, only the variations are desired.  Could we make so that it only runs if it can (i.e., nominal exists)?  

Thanks -- 

Jamie

**Comment by mmilesi** [comment]
Hi @JamesSaxon ,

I am having a look at this. Will get back to you soon!

**Comment by mmilesi** [comment]
I have opened a PR #275 for this

**Comment by mmilesi** [comment]
@kratsg, this one refers to #275 (not #274). So this is not to be closed

**Comment by mmilesi** [comment]
This now is covered by #287
