### ISSUE TITLE
new xAH tag?

### ISSUE THREAD

**Issue by AndreaCoccaro** [UCATLAS/xAODAnaHelpers#277]
Hello,
Just curious if a new xAH tag is SVN is expected soon. This [update](https://github.com/UCATLAS/xAODAnaHelpers/commit/0ceca8c2bb8ad44a5063149a02d18fd65ab02db1#diff-1e01b62a8f7eae95562403a9d9812164) is crucial at least for the b-tagged di-jet search and is not in the latest xAH tag in SVN (00-03-15). 
Cheers,
Andrea

**Comment by kratsg** [comment]
I'll take care of this. One second.

**Comment by kratsg** [comment]
svn+ssh://svn.cern.ch/reps/atlasinst/Institutes/UChicago/xAODAnaHelpers/tags/xAODAnaHelpers-00-03-20

https://github.com/UCATLAS/xAODAnaHelpers/releases/tag/00-03-20

have been tagged. Enjoy.

**Comment by AndreaCoccaro** [comment]
Sweet!
