### ISSUE TITLE
Does not return to Nominal

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#282]
Hi @mmilesi,

In these lines:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronCalibrator.cxx#L323-L328
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/MuonCalibrator.cxx#L285-L290

when running over systematics, the tool does not return to the nominal case for the next event but
rather stays on the last systematic which was configured for the previous event. No?

Is the check needed at all?

Cheers,
Gabriel

**Comment by kratsg** [comment]
Unless I'm unaware of new functionality, you first tell the tool which systematic variation you want to apply.. then you apply it. The lines you point to are simply telling the tool which variation to apply.

**Comment by gfacini** [comment]
Hi Giordon,

But it only does that if the name is not blank. If the
name is blank it should setup the nominal case.

Cheers,
Gabriel

**Comment by kratsg** [comment]
Oof, I see what you mean now. In this case, there should be a corresponding `if` statement around the systematic calculation. This should take care of the switch -- I don't think the tool knows how to apply the nominal calibration.

**Comment by mmilesi** [comment]
Hi @gfacini ,

good catch, I think you're right on this. @kratsg , I would seriously expect that `applySystematicVariation` does effectively do nothing when passing an empty systematic to it. If that's the case, we can safely remove the `if()` and be done with it, but this needs to be checked

**Comment by mmilesi** [comment]
Ok, I checked what happens with and w/o the check when running on the nominal only, and to me there are no differences at all for the values of pT after calibration in the two cases. So, I assume `applySystematicVariation ` does nothing when passing an empty syst. I made a PR #285 with the fix

**Comment by mmilesi** [comment]
Closed by #285
