### ISSUE TITLE
Add multiple jet collections to output ntuple

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#286]
In HelpTreeBase we only support outputting one jet collection to an ntuple. 
We have a use case where we would like to output a few different collections. 

I propose to make changes similar to that done for truth particles which allowed multiple truth particle types to be written out. 

ie: change:
  void AddJets(const std::string detailStr = "");
  void FillJets( const xAOD::JetContainer* jets, int pvLocation = -1 );
  void ClearJets();

to 
   void AddJets(const std::string detailStr = "", const std::string jetName = "jet");
   void FillJets(const xAOD::JetContainer* jets, int pvLocation = -1,   const std::string jetName = "jet");
   void ClearJets(const std::string jetName = "jet");

This should preserve backward compatibility and give us the flexibility we need. 

I would also like to extend to FillJet interface to have a per jet signature:
  void FillJets( const xAOD::Jet* jet, int pvLocation = -1 );
 (the jets we would like to fill are not part of JetContainer) 

Sounds sensible ?

**Comment by kratsg** [comment]
I would probably call it `FillJet()` at that point.

**Comment by johnda102** [comment]
yes

On Thu, Oct 15, 2015 at 3:41 PM, Giordon Stark <notifications@github.com>
wrote:

> I would probably call it FillJet() at that point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/286#issuecomment-148390401>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by urania277** [comment]
I'm happy to support this change - Merlin and I have a few updates for the TLA to make things work seamlessly for trigger jets as signal, and this addition would mean that we don't have to save the jets from the minitree in DijetAlgo. Thanks!
