### ISSUE TITLE
JVT Question

### ISSUE THREAD

**Issue by JamesSaxon** [UCATLAS/xAODAnaHelpers#292]
Hi @jdandoy, @gfacini --

I had a question about JVT in JetSelector.  I tried making a [minimal example](https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/VBFInv/AnalysisCode/trunk/scripts/jvt_test.py), and ran on unskimmed MC15.  But this failed when I turned on the JVT cut.  

I added in debug statements, and for 

```
std::cerr << __FILE__ << "::" << __LINE__ << std::endl;
if ( jet->pt() < m_pt_max_JVT ) {
  std::cerr << __FILE__ << "::" << __LINE__ << std::endl; ### line 730
  xAOD::JetFourMom_t jetScaleP4 = jet->getAttribute< xAOD::JetFourMom_t >( m_jetScaleType.c_str() );
  std::cerr << __FILE__ << "::" << __LINE__ << std::endl;
```

I see:

```
/share/home/jsaxon/xaod_new/xAODAnaHelpers/Root/JetSelector.cxx::730
terminate called after throwing an instance of 'SG::ExcBadAuxVar'
  what():  SG::ExcBadAuxVar: Attempt to retrieve nonexistent aux data item `::_pt' (1409).
Aborted
```

I assume that we're using getAttribute<>() to get the detector eta.  Any idea why this would fail?

Thanks a lot -- 

Jamie

**Comment by jdandoy** [comment]
Hi Jamie,

It looks like the "pt" aux decoration does not exist for your jet.  Which input xAOD / derivation are you using?  What is the "OutputContainer" and "OutputAlgo" values in your jet calibrator config file, and what are the "InputContainer" and "InputAlgo" for your jet selector config file?

Jeff

**Comment by mmilesi** [comment]
H @JamesSaxon ,

in addition to what Jeff said, which AB release are you testing on?
You should refrain from using 2.3.30, since in that release there are issues with decorating SC containers (use 2.3.28, or the latest 2.3.31 maybe).

Marco

**Comment by JamesSaxon** [comment]
Hi @jdandoy and @mmilesi -- 

Thanks a lot for your attention.  I am using 2.3.28 and unskimmed/underived MC and data -- do I _need_ to use a derived sample for this to work?  I tried with the samples below; both reliably switch between working and crashing with JVT in or out.

``` data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480/ ```
``` mc15_13TeV.301399.PowhegPythia8EvtGen_CT10_AZNLOCTEQ6L1_VBFH125_ZZ4nu.merge.AOD.e3909_s2608_s2183_r6630_r6264/ ```

The [minimal example](https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/VBFInv/AnalysisCode/trunk/scripts/jvt_test.py) shows the containers and (in this case, empty) algos.

Thanks -- 

Jamie

**Comment by kratsg** [comment]
@JamesSaxon - with RootCore setup (via `rcSetup`) can you run `checkxAOD.py` on the file you're using to see if it's ok? There must be something broken in the file -- I can't imagine the code breaking because of an error like that.

**Comment by gfacini** [comment]
Hi!

I think in some derivations the EM scale 4-vector is saved explicitly...I
have a vague memory of this. I would think you need the EM scale vector to
do the jet calibration correctly so there might be a more secure way of
getting the EM scale eta that is used in the jet calib package.

If the solution is down this road there are a few experts who could give us
some precise information. Let me know if you think this would be useful to
follow up on.

Cheers,
Gabriel

**Comment by JamesSaxon** [comment]
Hi @starkg -- 

I think the file is fine and, as I wrote, I tried on multiple samples/files.  Running checkxAOD.py looks OK to me; if you want to see the output of the (underived) data file you can run this on the t3:

```
checkxAOD.py /share/t3data3/jsaxon/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480._lb0586._0003.1
```

From the Chicago t3, this should show the crash (completely 'self-contained'):

```
xAH_run.py --force --files /share/t3data3/jsaxon/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480._lb0586._0003.1 --submitDir /tmp/jsaxon/vbf_out/ --config ~jsaxon/xaod_new/VBFInv/scripts/jvt_test.py direct
```

I did this with a completely clean area with only xAH checked out.

Thanks -- 

Jamie

**Comment by johnda102** [comment]
Hi Jamie,

  I think you need to set the scale explicitly in the JetSelector.

eg: run with
                             ...
                              "m_doJVT"                   :  True,
                              "m_jetScaleType"            :
 "JetConstitScaleMomentum",
                              ...
in your JetSelector config

john

On Sun, Oct 18, 2015 at 8:29 AM, JamesSaxon <notifications@github.com>
wrote:

> Hi @starkg <https://github.com/starkg> --
>
> I think the file is fine and, as I wrote, I tried on multiple
> samples/files. Running checkxAOD.py looks OK to me; if you want to see the
> output of the (underived) data file you can run this on the t3:
>
> checkxAOD.py /share/t3data3/jsaxon/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480._lb0586._0003.1
>
> From the Chicago t3, this should show the crash (completely
> 'self-contained'):
>
> xAH_run.py --force --files /share/t3data3/jsaxon/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480._lb0586._0003.1 --submitDir /tmp/jsaxon/vbf_out/ --config ~jsaxon/xaod_new/VBFInv/scripts/jvt_test.py direct
>
> I did this with a completely clean area with only xAH checked out.
>
> Thanks --
>
> Jamie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/292#issuecomment-148985023>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by JamesSaxon** [comment]
Hi John --

Thanks, that works.  I just thought that the "semi-automatic setting" here
<https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L142>
would
take care of it/was correct.

Cheers --

Jamie

**Comment by johnda102** [comment]
That code is not being called if your not using .config files
if ( !getConfig().empty() ) {...

On Sun, Oct 18, 2015 at 11:27 PM, JamesSaxon <notifications@github.com>
wrote:

> Hi John --
>
> Thanks, that works. I just thought that the "semi-automatic setting" here
> <
> https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L142
> >
> would
> take care of it/was correct.
>
> Cheers --
>
> Jamie
>
>
>
> On Sun, Oct 18, 2015 at 2:56 AM, johnda102 <notifications@github.com>
> wrote:
>
> > Hi Jamie,
> >
> > I think you need to set the scale explicitly in the JetSelector.
> >
> > eg: run with
> > ...
> > "m_doJVT" : True,
> > "m_jetScaleType" :
> > "JetConstitScaleMomentum",
> > ...
> > in your JetSelector config
> >
> > john
> >
> > On Sun, Oct 18, 2015 at 8:29 AM, JamesSaxon <notifications@github.com>
> > wrote:
> >
> > > Hi @starkg <https://github.com/starkg> --
> > >
> > > I think the file is fine and, as I wrote, I tried on multiple
> > > samples/files. Running checkxAOD.py looks OK to me; if you want to see
> > the
> > > output of the (underived) data file you can run this on the t3:
> > >
> > > checkxAOD.py
> >
> /share/t3data3/jsaxon/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480._lb0586._0003.1
> > >
> > > From the Chicago t3, this should show the crash (completely
> > > 'self-contained'):
> > >
> > > xAH_run.py --force --files
> >
> /share/t3data3/jsaxon/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480/data15_13TeV.00276731.physics_Main.merge.AOD.f620_m1480._lb0586._0003.1
> > --submitDir /tmp/jsaxon/vbf_out/ --config
> > ~jsaxon/xaod_new/VBFInv/scripts/jvt_test.py direct
> > >
> > > I did this with a completely clean area with only xAH checked out.
> > >
> > > Thanks --
> > >
> > > Jamie
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/UCATLAS/xAODAnaHelpers/issues/292#issuecomment-148985023
> > >
> > > .
> > >
> >
> >
> >
> > --
> > University of Chicago
> > http://hep.uchicago.edu/~johnda
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/UCATLAS/xAODAnaHelpers/issues/292#issuecomment-148987690
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/292#issuecomment-149048630>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
@johnda102 we should probably move that piece of code outside of the config section... since it should work regardless?

**Comment by JamesSaxon** [comment]
Of course you're right.  So I guess what I want is "JetEMScaleMomentum."
 But thanks, that solves my problem.

**Comment by kratsg** [comment]
Was this resolved?

**Comment by jdandoy** [comment]
I'm going to say yes.
