### ISSUE TITLE
Clean up HelpTreeBase.cxx

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#298]
HelpTreeBase is also getting a little out of control. 
I think we probably want separate dumper classes for each object which share common functionality.

**Comment by kratsg** [comment]
It does need to be refactored -- but it is a little tricky.

**Comment by johnda102** [comment]
I think it would be straight forward.
Weve already implemented separate jetInfo and trunkInfo objects to write
out multiple collections.
We just promote these to classes (probably with a common base) and then do
add branch in a member function.

On Wed, Oct 21, 2015 at 2:26 PM, Giordon Stark <notifications@github.com>
wrote:

> It does need to be refactored -- but it is a little tricky.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/298#issuecomment-149877462>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
Why separate classes? It seems easier to just make them protected/private member functions.

**Comment by johnda102** [comment]
its much better to have separate classes which handle the objects separately than one giant class with a bunch of large independent structs. 

We will likely also want a common base class for the different ntuple fillers.

**Comment by kratsg** [comment]
@johnda102 Use templates, then you don't need separate classes. The more classes we add, the more complex this code is going to get.

**Comment by johnda102** [comment]
I dont see templates are relevant here (or in the other issue you commented
on).
We need separate objects to hold the data.

On Wed, Oct 21, 2015 at 3:06 PM, Giordon Stark <notifications@github.com>
wrote:

> @johnda102 <https://github.com/johnda102> Use templates, then you don't
> need separate classes. The more classes we add, the more complex this code
> is going to get.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/298#issuecomment-149888296>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mmilesi** [comment]
Hi @johnda102 ,

I agree the tree management part of xAH could be improved. However, I am not sure I got your idea. Could you please try to sketch it more in detail here, highlighting also how it would change the `HelpTreeBase` class and the `xAH:;TreeAlgo` module (which is the one that gets called for each event, and that can be ultimately be configured by the user)?

Thanks!

Marco

**Comment by johnda102** [comment]
Hi Marco, 

  If you look in the master of HelpTreeBase, there is a struct jetInfo that holds the jet data when adding different output collections. One idea would be to promote this to a class, (eg: JetTreeBase) and move the  code in AddJets and FillJets to be member functions of JetTreeBase.   HelpTreeBase can then configure instances of JetTreeBase on demand and call AddJets and FillJets at the appropriate times.

This has the advantage that the end user still only deals with HelpTreeBase and that the details of a given object (in this case jets) are encapsulated in the JetTreeBase helper class.   

Im sure we will eventually want to have the capability to write to the ntuple more than one instance for types of objects, in which case we could just migrate the other objects to have <Object>TreeBase following the Jet example.

**Comment by johnda102** [comment]
Now Done.
