### ISSUE TITLE
Do not patch ElectronEfficiencyCorrectionTool

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#3]
See https://its.cern.ch/jira/browse/ATLASG-70 for more details.

**Comment by kratsg** [comment]
@gfacini -- Going to assign you to verify this :+1: when it's in the AB release.

**Comment by mmilesi** [comment]
In 2.3.12 we don't need to patch anymore. Just run the python helper at the very beginning and it will checkout the fixed tag of the package. In 2.3.13 that tag becomes the default. Issue can be closed
