### ISSUE TITLE
menuKeys in HelpTreeBase

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#30]
Info in <HelpTreeBase::FillTrigger()>: Switch: m_trigInfoSwitch->m_menuKeys
xAODConfigToolForTree      FATAL /build1/atnight/localbuilds/nightlies/AnalysisBase-2.3.X/AnalysisBase/rel_nightly/TrigConfxAOD/Root/xAODConfigTool.cxx:130 (virtual uint32_t TrigConf::xAODConfigTool::masterKey() const): Trigger menu not loaded
terminate called after throwing an instance of 'std::runtime_error'
  what():  Tool not initialised correctly

**Comment by mmilesi** [comment]
Do I understand correctly that this problem is due to missing trigger information in the new skimmed test xAOD?

**Comment by kratsg** [comment]
I can't skim xAODs and keep the trigger information. It requires setting up a derivation framework completely for that. Too complicated for me and I don't have time to skim a better one now.

**Comment by mmilesi** [comment]
I understand that. Well, for me it's okay to download locally single files and use them for testing. 

I have a colleague in Melbourne who is doing private derivations for HSG3,  maybe he's got all the setup working and can do this on the fly. Will let you know.

The current test_multiAlgo macro supports running on specific files of user's choice, although the command parsing is done still in a pretty ugly way. If I have a bit of time I'll work to make it more flexible.

Marco

**Comment by kratsg** [comment]
Ok, this is definitely not something to fix.

**Comment by gfacini** [comment]
I fixed this - there is only one trigger decision tool in the package now.
