### ISSUE TITLE
Derivation event counts / weights to output trees

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#319]
How are people dealing with derivation input and output event counts and weights ?

Naively I just want the MetaData_EventCount histograms written to the tree output streams. 

The regular cutflow histograms appear there, but im actually confused as to where the cut flow histograms are told which output files to be written to.  Any clues as to where I should look ?

**Comment by kratsg** [comment]
Bookkeeper Cutflows does this for you.

**Comment by johnda102** [comment]
what do you mean by bookkeeper cutflows ?

How do I configure it to write to the same output file I write the trees to
?

On Tue, Nov 3, 2015 at 12:38 AM, Giordon Stark <notifications@github.com>
wrote:

> Bookkeeper Cutflows does this for you.
> On Mon, Nov 2, 2015 at 18:16 johnda102 <notifications@github.com> wrote:
>
> > How are people dealing with derivation input and output event counts and
> > weights ?
> >
> > Naively I just want the MetaData_EventCount histograms written to the
> tree
> > output streams.
> >
> > The regular cutflow histograms appear there, but im actually confused as
> > to where the cut flow histograms are told which output files to be
> written
> > to. Any clues as to where I should look ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/UCATLAS/xAODAnaHelpers/issues/319>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/319#issuecomment-153193797>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
See an example here: https://svnweb.cern.ch/trac/atlasphys-susy/browser/Physics/SUSY/Analyses/MultiBJets/MultibjetsAnalysis/trunk/Root/MainAnalysis.cxx#L198

If you make a new histogram, just create it in `finalize()` and use `SetDirectory()` to set it to the output file you want to store it in.

**Comment by johnda102** [comment]
ok thanks @kratsg. 

Any reason to not write this info by default to the standard m_cutflowHist and m_cutflowHistW hists ?

**Comment by kratsg** [comment]
> Any reason to not write this info by default to the standard m_cutflowHist and m_cutflowHistW hists ?

Nope. But I think this is resolved now. Close it if you need more help.
