### ISSUE TITLE
Migrate the wiki over to code documentation

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#330]
I'll take care of this - it won't be restrictively difficult and we already have a halfway decent wiki full of documentation. It will be great to move it all into one location :)

**Comment by jdandoy** [comment]
@kratsg happy with this?

**Comment by kratsg** [comment]
I think so -- https://github.com/UCATLAS/xAODAnaHelpers/wiki I don't see anything on there that needs to move over?
