### ISSUE TITLE
New files to svn tags

### ISSUE THREAD

**Issue by jdandoy** [UCATLAS/xAODAnaHelpers#34]
To create a git tag and push this to an svn tag, the recommended commands are below.  Unfortunately this does not seem to be transferring new files, such as Algorithm.cxx .  Is there a better way to set up the svn space?

git tag -a XX-XX-XX -m “Message”  vesionHash
git push —tags
git checkout tags/XX-XX-XX
cd ../
svn co —force svn+ssh://jdandoy@svn.cern.ch/reps/atlasinst/Institutes/UChicago/xAODAnaHelpers/trunk xAODAnaHelpers
cd xAODAnaHelpers
svn copy . svn+ssh://jdandoy@svn.cern.ch/reps/atlasinst/Institutes/UChicago/xAODAnaHelpers/tags/xAODAnaHelpers-XX-XX-XX

**Comment by kratsg** [comment]
Hi Jeff,

I've had issues if the new tag isn't from trunk. I'm looking into a work-around which I hacked in by releasing from a new branch. _but_ you can try `svn commit -m "release new tag"` first before doing the svn copy.
