### ISSUE TITLE
Tighten Info switch matching.

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#341]
Im starting to add HLT Bjet support to xAH and ran into a subtle issue with the info switch parsing that others may also come across. 

Accessing the BTagging info is different for HLT jets than for offline jets.
I added a flag to info switch to tell the Jet plot maker which acessor to use. 

I tried naming it "flavorTagHLT" and "HLTflavorTag"  but it turns out that with our current parse function: 

```c++
bool InfoSwitch::parse(const std::string flag)
  {
    return m_configStr.find(flag) != std::string::npos; // not equal to npos means it is found                                                             
  }
```

either of these will also match the offline switch "flavorTag" .

Seems to me we should tighten the matching criteria in parse, so the full space or comma separated token should match. 

What do others think ?

This could break backward compatibility if you're using a silly detail string.

**Comment by kratsg** [comment]
... there's no way for us to do this. I mean, put it this way -- given any arbitrary string from the user, we are searching for a partial string inside it. The `parse` function has no way of knowing that you want to match the string entirely. We can slow down the `parse` function call here by doing the following procedure inside `parse`:

```c++
string a = "hello   my name    is    joe";
stringstream s(a);
string word;
// vector<string> c = ... ;

for (int i = 0; s >> word; i++)
    if (word == c[i]) return true;

return false;
```

**Comment by johnda102** [comment]
Surely we can we split the string by white space (and/or commas) and search each substring for a complete match.

**Comment by kratsg** [comment]
That's what I proposed above and it won't break backwards compatibility.

**Comment by johnda102** [comment]
if someone has: 

"xxxx IAMAflavorTagRETARD  xxxx"

this would currently match flavorTag, but it wouldnt if we split by spaces and require an exact match.

**Comment by johnda102** [comment]
ok, yeah I say let do the split by whitespace

**Comment by johnda102** [comment]
note: I actually had flavorTagG in one of my configs....
