### ISSUE TITLE
ROOT streamable data members and configure() 

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#36]
Hi all, 

I have noticed this.

Since @kratsg  wants to have the possibility to directly configure algo data members in his steering macro, he had to get rid of the //! int he header files for configurable data members (e.g, cuts, strings...)

However, as stated in : 

https://twiki.cern.ch/twiki/bin/view/AtlasComputing/SoftwareTutorialxAODAnalysisInROOT

, whatever gets initialised in intialize() needs //!, the rest doesn't. 
And  at the moment the configuration valuues are read  via TEnv in configure(), which is called inside initialize(). 

So, I'd say we either move the call to configure() to another place ( --> histInitialize() ? ) , or we need to put back //! to the configurable data members. 

Since the latter would go against what Giordon wants to do, so, the first option makes more sense. But we need to check that histInitialize() is a good place for that.

Still, even leaving as it is now does not produce any crash at runtime. But we don't want any unexpected behaviour either.

Let me know what do you think

**Comment by kratsg** [comment]
Yes, #32 would require leaving it off. And in fact, I'm not 100% sure it NEEDS to be initialized in `initialize()`. It just needs to be initialized somewhere in the code (like the constructors) or in the header file... 

I had examples that work in kratsg/TheAccountant where I have code like

https://github.com/kratsg/TheAccountant/blob/master/TheAccountant/Audit.h#L33-L39
```c++
public:
  bool m_minMassJigsaw      = true,
       m_rapidityJigsaw     = true,
       m_contraBoostJigsaw  = true,
       m_hemiJigsaw         = true,
       m_drawDecayTreePlots = false;
  bool m_passPreSel         = true;
```

in the header file, and they're streamable and configurable.

**Comment by kratsg** [comment]
I will email PATHelp (+ Nils) about it since he understands streamable.

**Comment by kratsg** [comment]
Ok, so if we set default values for all of our variables in the header file or in the constructor, then they can be streamable and still work. This way, ROOT will allow us to stream values for configuration, but also will have default values that work across the board. I'm currently putting them in the constructor for right now, but we will need to move them over to the header files.

**Comment by mmilesi** [comment]
Hi @kratsg ,  
has this been fixed, right?

**Comment by kratsg** [comment]
We haven't moved them all to header files yet. but it can be closed for now.
