### ISSUE TITLE
Example Including MeT 

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#365]
I need to implement a basic MeT calculation in the hh->4b package. 
Does anyone have an example configuring the/a standard MeT definition. ?

First timing doing this in Run2,  We only care about leptons and jets, Im happy to use whichever MeT soft term is most commonly used.

**Comment by gfacini** [comment]
Hi John,

I have one from the gjjj business but it is sloppy.

One of the main points is to not put cuts on the jet
container. Just calibrate it then give all the jets to
the MET tool.

For electron and muons I was applying a minimal
preselection.

Jamie pointed me to his standard config:
https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/VBFInv/AnalysisCode/trunk/scripts/vbfinv_baseline.py#L249

This is the config I used:

Debug             False
InputJets         AntiKt4EMTopoJets_Calib
InputElectrons    PreSelectElectrons
InputPhotons      Photons
InputTaus         TauJets
InputMuons        PreSelectMuons
ApplyElectronCuts False
ApplyPhotonCuts   True
ApplyTauCuts      True
ApplyMuonCuts     False
# one of the below causes a crash
#DoMuonEloss       True
#DoIsolMuonEloss   True
MapName           METAssoc_AntiKt4EMTopo
CoreName          MET_Core_AntiKt4EMTopo
OutputContainer   RefFinalEM
Reference         MET_Reference_AntiKt4EMTopo

Gabriel

**Comment by mmilesi** [comment]
Hi @johnda:

heres's what I do:

https://github.com/mmilesi/HTopMultilepAnalysis/blob/master/data/MET/MET_HTopMultilep_DxAOD-2015-13TeV.config

Note that you must pass unfiltered jets (i.e., only apply calibration!) and set the JVT flag to true if yu are going to apply a JVT cut in your jet selector, and make sure you call the MET constructor BEFORE the overlap removal!

Marco

**Comment by johnda102** [comment]
ok thanks guys, This should be enough to get me started.

john

On Sat, Nov 21, 2015 at 8:05 AM, Marco Milesi <notifications@github.com>
wrote:

> Hi @johnda <https://github.com/johnda>:
>
> heres's what I do:
>
>
> https://github.com/mmilesi/HTopMultilepAnalysis/blob/master/data/MET/MET_HTopMultilep_DxAOD-2015-13TeV.config
>
> Note that you must pass unfiltered jets (i.e., only apply calibration!)
> and set the JVT flag to true if yu are going to apply a JVT cut in your jet
> selector, and make sure you call the MET constructor BEFORE the overlap
> removal!
>
> Marco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/365#issuecomment-158598942>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by johnda102** [comment]
ok Saxons example it looks like the MetConstructor is being called after the overlap removal...

**Comment by gfacini** [comment]
I think the MET tool does its own OR but I cannot find that TWiki right
now...looking

**Comment by jdandoy** [comment]
It is the case that MET has it's own distinct overlap removal, so this should not be done before METConstructor.  An example config file was linked a while back [here](https://github.com/UCATLAS/xAODAnaHelpers/issues/737#issuecomment-256694739).
