### ISSUE TITLE
Bad crash when running master on the grid

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#378]
Hi guys,

I just noticed that running on the grid with master (or HTopMultilep-00-01-02) I get this threatening message when calling the OLR constructor at the very beginning of the job

```
OverlapRemover::Overla... INFO    Calling constructor
TStreamerInfo::BuildOld   WARNING Cannot convert OverlapRemover::m_dummyElectronContainer from type:DataVector<xAOD::Electron_v1>* to type:DataVector<xAOD::Electron_v1>, skip element
TStreamerInfo::BuildOld   WARNING Cannot convert OverlapRemover::m_dummyMuonContainer from type:DataVector<xAOD::Muon_v1>* to type:DataVector<xAOD::Muon_v1>, skip element

...

TStreamerInfo::WriteBu... ERROR   The element OverlapRemover::m_dummyElectronContainer type 169 (DataVector<xAOD::Electron_v1>*) is not supported yet

TStreamerInfo::WriteBu... ERROR   The element OverlapRemover::m_dummyMuonContainer type 169 (DataVector<xAOD::Muon_v1>*) is not supported yet

TBufferFile::CheckByte... ERROR   object of class OverlapRemover read too many bytes: 574 instead of 568
TBufferFile::CheckByte... WARNING OverlapRemover::Streamer() not in sync with data, fix Streamer()
```

which, for some samples, eventually leads to a crash:

```
BasicEventSelection::e... INFO    Event number = 70000
Caught exception while executing algorithm:
std::bad_alloc
```

I tried to run locally and nothing seems to happen (I don't get that error message either!), and I tried to check for leaks with valgrind, but everything looks good:

```
==6511== 
==6511== HEAP SUMMARY:
==6511==     in use at exit: 62,690 bytes in 1,342 blocks
==6511==   total heap usage: 2,633 allocs, 1,291 frees, 201,540 bytes allocated
==6511== 
==6511== Searching for pointers to 1,342 not-freed blocks
==6511== Checked 214,528 bytes
==6511== 
==6511== LEAK SUMMARY:
==6511==    definitely lost: 0 bytes in 0 blocks
==6511==    indirectly lost: 0 bytes in 0 blocks
==6511==      possibly lost: 0 bytes in 0 blocks
==6511==    still reachable: 62,690 bytes in 1,342 blocks
==6511==         suppressed: 0 bytes in 0 blocks
==6511== Reachable blocks (those to which a pointer was found) are not shown.
==6511== To see them, rerun with: --leak-check=full --show-reachable=yes
==6511== 
==6511== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
--6511-- 
--6511-- used_suppression:      4 U1004-ARM-_dl_relocate_object
--6511-- used_suppression:      2 glibc-2.5.x-on-SUSE-10.2-(PPC)-2a
==6511== 
==6511== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
```

Anyone has an idea of what is going on here?

A link to the grid job std output:
http://aipanda056.cern.ch/media/filebrowser/a5bc20af-a4b9-4908-9bf5-e3dc0b1b4252/tarball_PandaJob_2685301469_ANALY_INFN-T1/athena_stdout.txt

@kratsg 
@johnda102 
@gfacini

**Comment by gfacini** [comment]
I have not tested the new version. John?
Gabriel

**Comment by kratsg** [comment]
We should talk to the Muon folks.

**Comment by johnda102** [comment]
My guess is that the crash is not related to the warning message.

and the warning message means we need to add

```c++
//!
```
to the dummy container pointers in the header.


How do you know the crash is related to the warning message ?

On Wed, Nov 25, 2015 at 3:19 PM, Giordon Stark <notifications@github.com>
wrote:

> We should talk to the Muon folks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/378#issuecomment-159620040>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mmilesi** [comment]
Hi @johnda102 ,

I am indeed not 100% sure that's the reason of the crash, but it's something that worried me. 
Also, there are some runtime warnings caused by `CP::MuonEfficiencyScaleFactors` but who knows...

**Comment by mmilesi** [comment]
Could someone try to run a grid job on the following dataset:

mc15_13TeV.361505.MadGraphPythia8EvtGen_A14NNPDF23LO_Zmumu_Np0.merge.DAOD_HIGG8D1.e3898_s2608_s2183_r6869_r6282_p2438/

with `master` and the overlap remover on, and see if you get a crash?

Thanks very much in advance!

Marco

**Comment by mmilesi** [comment]
Problem solved, was a missing call to `std::vector::clear()` for one of my tree custom branches (so outside of xAH) that caused the memory usage to continuously increase. Sorry for the noise!

**Comment by kratsg** [comment]
:+1: no problem!
