### ISSUE TITLE
Grid submissions with xAH_run.py

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#380]
Hi guys @johnda102 , @gfacini @jdandoy @JamesSaxon ,

is anybody out there using `xAH_run.py` for prun grid submissions?

Could you please show me a working example of a command to launch a grid job?
Thanks!

Marco

**Comment by kratsg** [comment]
`xAH_run.py --files "user.lgagnon.370150.Gtt.DAOD_SUSY10.e4049_s2608_r6765_r6282_p2411_tag_10_v1_output_xAOD.root" --config=test.py --inputDQ2 prun --optGridMergeOutput=1 --optGridNFilesPerJob=1.0 --optGridOutputSampleName=user.gstark.test`

https://gist.github.com/762032c4ad5b36f0d17a

with the following environment

```
lsetup fax
lsetup panda
rcSetup
```

and it works for me. We should have a documentation on a test case to make sure there's no issue with the user's side?

**Comment by johnda102** [comment]
Heres an example running over a list of input DS in
XhhCommon/scripts/grid_samples_EXOT8_mc.txt

xAH_run.py --files XhhCommon/scripts/grid_samples_EXOT8_mc.txt --inputList
--config XhhCommon/scripts/combinedMaster.py -f --inputDQ2 --isMC prun
--optGridOutputSampleName="user.johnda.%in:name[1]%.%in:name[2]%.%in:name[3]%.hh4b-00-04-02v2/"

On Thu, Nov 26, 2015 at 5:54 AM, Giordon Stark <notifications@github.com>
wrote:

> xAH_run.py --files
> "user.lgagnon.370150.Gtt.DAOD_SUSY10.e4049_s2608_r6765_r6282_p2411_tag_10_v1_output_xAOD.root"
> --config=test.py --inputDQ2 prun --optGridMergeOutput=1
> --optGridNFilesPerJob=1.0 --optGridOutputSampleName=user.gstark.test
>
> https://gist.github.com/762032c4ad5b36f0d17a
>
> with the following environment
>
> lsetup fax
> lsetup panda
> rcSetup
>
> and it works for me. We should have a documentation on a test case to make
> sure there's no issue with the user's side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/380#issuecomment-159804657>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mmilesi** [comment]
Thanks John.

Indeed my problem was that `--inputDQ2` must be given explicitly , and I thought it was included by default when selecting prun as driver.

@kratsg, could you please update the docs of `xAH_run` to explicitly require that command?

**Comment by kratsg** [comment]
As Karol mentioned, you don't need that command if you're not providing dq2
samples - but instead xrootd paths...

So you don't always need it.

**Comment by mmilesi** [comment]
Ok, but at least could we make a note to say that it's needed when providing dq2 datasets?

**Comment by kratsg** [comment]
It's in there already. That's why there's an entire documentation on using
it.

**Comment by eakilli** [comment]
Hi,
I have been trying to use prun. I have used the above examples (with two different environment settings: one that you suggested and without fax) to test, with the test.py. Both submitted the job to the grid however the job failed with the error "Trf exit code 221. trans: Proot: Framework decided to abort the job due to an internal problem". 

Finally, I could run my own configuration file on the grid following the guidelines here with some small changes and it succeeded. 

Maybe the example needs a modification?

**Comment by kratsg** [comment]
Hi @eakilli -- can you point us to your bigpanda page for the jobs that failed? It would be nice to see what the internal error is.

Also, what was the `xAH_run.py` command you used to submit the job?

**Comment by urania277** [comment]
Hi all,

if it helps, I used this thread to get a line to submit a test job that succeeded (no fax involved, just setting up panda and dq2):

bash-4.1$ xAH_run.py -f -vv --files "mc15_13TeV.361027.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ7W.merge.DAOD_EXOT2.e3668_s2608_s2183_r6765_r6282_p2432" --config TLABasicConfigAllCollectionsMC.json --inputDQ2 prun --optGridDestSE=""

Now the question is: dq2 died today and we moved to Rucio. I assume everything is transparent from that point of view? 

Caterina

-------------------------------------
Caterina Doglioni
Lund University, Fysikum
Division of Particle Physics
+46 (0) 46-22 27695
-------------------------------------

**Comment by eakilli** [comment]
Hi,

Yes, I used xAH_run.py. 

Here is a link to the example that failed: http://bigpanda.cern.ch/task/7464706/
And here is a link to another job that succeeded: http://bigpanda.cern.ch/task/7463808/

Thank you!

**Comment by kratsg** [comment]
@eakilli What's the actual command you used with `xAH_run.py`?

**Comment by kratsg** [comment]
Actually, if you look at the log...

http://bigpanda.cern.ch/job?pandaid=2733609981

```
- Errors from athena_stdout.txt (no jobReport) -
ERROR: %s failed to make dummy tracer
_CONDOR_WRAPPER_ERROR_FILE=/N/dc2/scratch/usatlas/rcc_karst.usatlas/rcc.v6E7lfw0xN/execute.149.165.233.19-20111/dir_25908/.job_wrapper_failure
BasicEventSelection::i... ERROR   Failed to retrieve IncompleteCutBookkeepers from MetaData! Exiting.
Aborting job due to internal GridWorker error:
```

https://github.com/UCATLAS/xAODAnaHelpers/blob/022794e4f84274edc1b6ca402a4fc5905aa51e83/Root/BasicEventSelection.cxx#L319-L323

You can try setting the configuration variable due to a common issue listed here (https://xaodanahelpers.readthedocs.org/en/master/Issues.html)

with

```
"m_useMetaData": False
```

**Comment by eakilli** [comment]
@kratsg Okay, thanks a lot, I get it know. 
This is not a problem for my jobs and they are successfully running. But maybe the example test configuration file that was pointed to (https://gist.github.com/kratsg/762032c4ad5b36f0d17a) needs an update for people who wants to get started with running on the grid quickly.

**Comment by kratsg** [comment]
> pointed to (https://gist.github.com/kratsg/762032c4ad5b36f0d17a) needs an update for people who wants to get started with running on the grid quickly.

updated :)
