### ISSUE TITLE
xAH_run.py doesn't scanDQ2 automatically when running prun

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#383]
@kkrizka this was a change I pointed out here: https://github.com/UCATLAS/xAODAnaHelpers/pull/363#issuecomment-158058832

@mmilesi ran into this issue. I'm still confused about what kinds of files that don't need scanDQ2 but still work for the grid in a file list or something.

**Comment by kkrizka** [comment]
Files stored on faxbox do not need scanDQ2 and still work with batch driver
line condor.

On Thu, Nov 26, 2015 at 6:03 AM, Giordon Stark <notifications@github.com>
wrote:

> @kkrizka <https://github.com/kkrizka> this was a change I pointed out
> here: #363 (comment)
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/363#issuecomment-158058832>
>
> @mmilesi <https://github.com/mmilesi> ran into this issue. I'm still
> confused about what kinds of files that don't need scanDQ2 but still work
> for the grid in a file list or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/383>.
>



-- 
Cheers,
Karol Krizka

**Comment by kratsg** [comment]
I'll update the documentation.
