### ISSUE TITLE
Muon Trigger SF (and syst)

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#39]
Need to review implementation of this section in MuonEfficiencyCorrector.cxx module
Documentation on TWiki is lacking info, and the test macro in the util/ of the ASG package is not self-contained.

**Comment by kratsg** [comment]
@mmilesi confirm that this gets closed now with #38.

**Comment by mmilesi** [comment]
Hi @kratsg , not really :(

#38 is self-contained, but this issue still needs to be assessed by experts. I have sent an email to PAT Help and awaiting for reply.

**Comment by mmilesi** [comment]
this adds more work towards #38

**Comment by mmilesi** [comment]
Closed through #118
