### ISSUE TITLE
SkimmyDumping

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#4]
Event Skimming and xAOD Outputs

**Comment by mmilesi** [comment]
Hi @kratsg  (and @gfacini , @jdandoy , @johnda102 too),

do you know where do we stand on this?

I was discussing with other people in my analysis group, and we think it can be very useful to be able to **locally** reprocess quickly mini-xAODs and do things like object re-counting (for instance, tightening the ID criteria, or changing kinematic cuts) on the fly by re-using xAH.

Not to mention that having a mini-xAOD output could eventually be the most handy way to deal with systematics, as I already said in an old email thread.

Would be great to hear also your opinion on this, and if needed I can lend a hand in the developing!

Marco

**Comment by kratsg** [comment]
Yeah, I've got some progress on my end. How soon does this need to be done by?

**Comment by mmilesi** [comment]
Thanks @kratsg ,

mmh, would 10 days be a reasonable time scale? As I said, I can give you a hand if you need it!

Marco

**Comment by kratsg** [comment]
Bug me on Thursday, I'll show you some of the code I've got for generic layout of the SkimmyDumper.

**Comment by mmilesi** [comment]
Sounds good, thanks.

**Comment by gfacini** [comment]
@kratsg 
I agree this is super useful and a great that someone is finally pushing on it.
Where does it stand and what is needed to get this done?  I can help if necessary.

Gabriel

**Comment by kratsg** [comment]
https://github.com/UCATLAS/xAODPerfTools --- working on a first version here.

**Comment by kratsg** [comment]
@mmilesi I got this done in 10 days! From June 15th to Dec 10th. Technically, it took me -5 days :smile:

**Comment by mmilesi** [comment]
:tada: :tada: :tada: :balloon: :confetti_ball: :confetti_ball:
