### ISSUE TITLE
kCanRebin gone from ROOT 6.04.10 (and earlier?)

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#422]
Not sure I'm the only one stumbling onto this (locally, on 6.04.10) in BasicEventSelection.cxx:

https://root.cern.ch/content/main-histogram-changes-root-6

This is easily fixed by substituting setting the kCanRebin bit with SetCanExtend(TH1::kAllAxes). Let me know if it's a good idea to put this in for everyone and I will commit it.

**Comment by kratsg** [comment]
@urania277 where in our code are we even using this bit?

**Comment by urania277** [comment]
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BasicEventSelection.cxx#L473 and following. I think it's there to add bins to the cutflow histograms in downstream algorithms.

**Comment by kratsg** [comment]
> https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BasicEventSelection.cxx#L473 and following. I think it's there to add bins to the cutflow histograms in downstream algorithms.

https://github.com/UCATLAS/xAODAnaHelpers/search?utf8=%E2%9C%93&q=kCanRebin

Only in those two locations. I wonder why this wasn't caught before - does it not print an error at all?

**Comment by urania277** [comment]
I just noticed since it doesn't even compile for me since I moved to 6.04.10

**Comment by kratsg** [comment]
> I just noticed since it doesn't even compile for me since I moved to 6.04.10

What analysis base are you using? We use 2.3.38 - that's not going to change ROOT versions...

**Comment by urania277** [comment]
I'm on my local machine with 2.3.38 - I really don't mind changing it locally if I'm the only one who sees this problem, I will just remove this particular change from the commit when I eventually add some stuff

**Comment by kratsg** [comment]
Hi @urania277 - we have to use the ROOT release associated with a RootCore AnalysisBase release. They don't support changing ROOT versions because of things like this. (EG: you couldn't get the current RootCore to compile in ROOT 6.02.02 for lots of other reasons).

**Comment by urania277** [comment]
thanks, I see...I was hoping I didn't have to install multiple ROOT versions but in the end I may have to :)

**Comment by urania277** [comment]
thanks @kratsg, closing!
