### ISSUE TITLE
Question on TreeAlgo detailStr and json configuration

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#425]
I volunteer to update the documentation if someone points me to the correct syntax to have more than one jetInfoSwitch at a time (the 'exact' match may be a problem, but I'm not sure if I navigated everything correctly). E.g. this works as expected: 

 {
   "class": "TreeAlgo",
     "configs": {
     "m_debug": true,
     "m_verbose": true,
     "m_jetContainerName": "HLT_xAOD__JetContainer_TrigHLTJetDSSelectorCollection",
     "m_jetDetailStr": "kinematic",
     "m_name": "HLT_xAOD__JetContainer_TrigHLTJetDSSelectorCollection"
   }
 }

but what should I use if I want e.g. kinematic AND layer at the same time? Thanks!

**Comment by kratsg** [comment]
`"m_jetDetailStr": "kinematic layer"`

**Comment by urania277** [comment]
thanks, that was easy (I tried about every single punctuation I knew but not space...). I will close once I have some basic documentation in place.

**Comment by kratsg** [comment]
@urania277 are we ok with this?

**Comment by urania277** [comment]
See #450

**Comment by kratsg** [comment]
Thanks!
