### ISSUE TITLE
Argument Guidance in Documentation for LSF Submission Confusing

### ISSUE THREAD

**Issue by smeehan12** [UCATLAS/xAODAnaHelpers#430]
We were trying to use the LSF submission driver with xAH_run.py and wanted to use the 

--optLSFConf=-q short

configuration option.  There are two modifications for this portion of the documentation that misguided us on lxbatch:

1) There does not exist a "short" queue.  "--optLSFConf=-q 8nh" Perhaps this is system specific, but it would be nice to make a comment about that in the portion that currently says "Undocumented".

2) The option was parsed incorrectly, and we had to put the "-q 8nh" in quotes.  Again, this may be obvious to some users, but perhaps another note could be put in the section below that currently reads "Undocumented" about this.

**Comment by kratsg** [comment]
https://github.com/ribozz/sphinx-argparse/issues/36

**Comment by kratsg** [comment]
I'll try out a different documentation generator (https://pythonhosted.org/sphinxcontrib-autoprogram/) to see if that one is better.

**Comment by kratsg** [comment]
Unfortunately, I can't seem to auto-generate the documentation in a nicer way. We can try and put a warning just to remind people how it should be configured with an example?

**Comment by kratsg** [comment]
Implemented as requested. Should be fine from now on.
