### ISSUE TITLE
Upgrades to ASG OLR tool

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#434]
Should have a look into this sometime soon.

---------- Forwarded message ---------
From: Steve Farrell <steven.farrell@cern.ch>
Date: Mon, Jan 11, 2016 at 10:44 PM
Subject: AssociationUtils-01-01-17
To: atlas-sw-pat-releaserequests (Requests for new tags to go into release) <atlas-sw-pat-releaserequests@cern.ch>
Cc: Will Buttinger <William.Buttinger@cern.ch>, Ulla Blumenschein <ublumenschein@googlemail.com>, Attila Krasznahorkay <attila.krasznahorkay@cern.ch>, Till Eifert <till.eifert@cern.ch>, Teng Jian Khoo <teng.jian.khoo@cern.ch>, Christian Ohm <christian.ohm@cern.ch>, Federico Meloni <Federico.Meloni@cern.ch>

Hello,

This is to announce the implementation of the new overlap removal recommendations and request that the new tag, AssociationUtils-01-01-17, be collected in the analysis releases.

The package now provides the updated overlap removal recommendations via new tool properties and config helper functions. Here is a summary:
JVT requirements for e-jet and mu-jet tools
mu-jet PT ratio requirements in mu-jet
ghost association (with backup dR) in mu-jet
calo-muon removal now default in the e-mu tool
bjet precedence and sliding dR supported in both e-jet and mu-jet tools
fat jet support in the master OverlapRemovalTool.
new configuration helper functions for RootCore and Athena to use the new recommendations (with extra args to easily enable the btag and sliding-dR options).
The old harmonizedTools config helper function is mainly unchanged for those that want to compare or stick with the old recommendations for now. Usage of the new features via the new config helper functions is documented in the package README (trunk version):
https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/AnalysisCommon/AssociationUtils/trunk/doc/README.rst
The config helper code is still not maximally flexible (though custom config isn't tedious IMO). Nonetheless, I may update it in the coming days.

Feel free to forward this email on to any interested parties.

Cheers,
Steve

**Comment by jdandoy** [comment]
Our current OR code doesn't seem to match the [latest recommendations](https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/AnalysisCommon/AssociationUtils/trunk/doc/README.rst).  I'll update our code.

**Comment by mmilesi** [comment]
Hi @jdandoy ,

that would be great. Thanks!
