### ISSUE TITLE
Behaviour of BJetEfficiencyCorrector in data

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#442]
Hi @johnda102, @kratsg ,

I have noticed that some of my grid jobs on data crash at finalizing stage when we explicitly call the destructor of the xAODBTaggingEfficiency BtagSF tool by deleting the pointer:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BJetEfficiencyCorrector.cxx#L530

See the logfile here:

http://aipanda056.cern.ch/media/filebrowser/827247a4-aa6e-4114-befc-f56db3759455/tarball_PandaJob_2733061423_ANALY_CONNECT/athena_stdout.txt

I have investigated a bit into it, and I think our code is not buggy, rather, the bug is in the CP tool itself

The destructor of the tool:

https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/JetTagging/JetTagPerformanceCalibration/xAODBTaggingEfficiency/tags/xAODBTaggingEfficiency-00-00-26/Root/BTaggingEfficiencyTool.cxx#L128

deletes the pointer `m_CDI`, which is not set to `nullptr` anywhere in the tool, but gets allocated in `initialize`

Since atm we call `m_BJetEffSFTool = new ...` for both data and MC, but call `m_BJetEffSFTool ->initialize()` only for MC, the crash happens when the destructor of the tool tries to delete  `m_CDI` .

For the moment, I propose to move the  `m_BJetEffSFTool = new ...`  part inside the `if ( m_getScaleFactors )` statement. Then we should tell the tool developers to fix the tool, by initializing `m_CDI= nullptr` in the tool constructor.

My doubt is why I get the crash only on few jobs, and not in all of them...any idea?

**Comment by kratsg** [comment]
Shouldn't the default allocator take precedence when this occurs? Can we alert the tool developers now first?

**Comment by jbossios** [comment]
This shouldn't be a problem anymore
