### ISSUE TITLE
prun --optGridDestSE option

### ISSUE THREAD

**Issue by eakilli** [UCATLAS/xAODAnaHelpers#443]
I see from the documentation that while running on the grid, the prun option
--optGridDestSE=MWT2_UC_LOCALGROUPDISK
is set by default. And I am getting the warning 

"TaskID:7463844 cannot process the --destSE request
Reason : Rucio failed to make subscriptions at MWT2_UC_LOCALGROUPDISK since There is insufficient quota on any of the target RSE's to fullfill the operation."

Can I run without this option and should I?

**Comment by kratsg** [comment]
We should remove the default here. Run with

--optGridDestSE=""

Instead.

**Comment by kratsg** [comment]
We should remove the default here. Run with

```
--optGridDestSE=""
```

Instead.

**Comment by kratsg** [comment]
@eakilli this will auto-close when we merge in the PR. Don't worry :)
