### ISSUE TITLE
xAH with production privileges

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#445]
After having tried a couple of things - could someone point me at some documentation, if any, of how to send xAH_run jobs with production privileges? Thanks!

**Comment by kratsg** [comment]
Hi @urania277 -- is this something you use like `nc_official` for? an `optOfficial`? It looks like they've been adding more flags so we just need to add support for that in `xAH_run` if that's the case.

**Comment by johnda102** [comment]
xAH_run.py --files MultijetAlgo/scripts/grid_samples_EXOT1_data.txt  --inputList --config MultijetAlgo/scripts/config_MultijetAlgo.py -f --inputDQ2 prun   --optGridOutputSampleName="group.phys-exotics.%in:name[1]%.%in:name[2]%.%in:name[3]%.v0.1_20150921/" --optSubmitFlags="--official"

**Comment by kratsg** [comment]
@johnda102 they support an `official` flag now via `nc_official` (`--optOfficial` in my new PR). Do you know if that is supported as well?

**Comment by johnda102** [comment]
not sure. This was working as of 2.3.38.

On Thu, Jan 21, 2016 at 2:15 PM, Giordon Stark <notifications@github.com>
wrote:

> @johnda102 <https://github.com/johnda102> they support an official flag
> now via nc_official (--optOfficial in my new PR). Do you know if that is
> supported as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/445#issuecomment-173565043>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by urania277** [comment]
Thanks both, it works (using John's solution for now) - will close.
