### ISSUE TITLE
Bug: m_eventCleaning switch w/o initialisation

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#451]
Hi @urania277 ,

I have found a subtle (but nasty in its effects) bug in a part of code that presumably you added:

https://github.com/UCATLAS/xAODAnaHelpers/blame/master/xAODAnaHelpers/HelperClasses.h#L141

It must have the corresponfing string flag set in HelperClasses.cxx:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelperClasses.cxx#L85

which atm does not. This leads to the switch `m_eventCleaning` being set to true/false completely at random, hence the output ntuples will have those branches saved at random.
This leads to bad issues when merging trees.

Could you please fix this asap?

Ciao!

Marco

**Comment by urania277** [comment]
you're right, it's the newer flags - sorry about this! I'll fix it this morning and you'll have a PR before 12.

**Comment by mmilesi** [comment]
:+1:
