### ISSUE TITLE
Issue with asg::ToolStore and deleting pointers to CP tools in finalize()

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#457]
To be investigated

**Comment by kratsg** [comment]
You don't delete the points to CP tools that are retrieved from the ToolStore.

**Comment by mmilesi** [comment]
Hi @kratsg 

may you clarify on this? I kind of understand that all the tools that get instantiated automatically get registered to this ToolStore. Is it taking care of deleting the pointers then?

If that's the case, okay, I understand the crash as a double deletion. I wonder however why the ToolStore doesn't reassign to `nullptr` the tools after deletion, just to prevent things like this.

Maybe we should just remove in `EL::finalize()` all the tool deletions. There's no risk of memory leak here.

**Comment by kratsg** [comment]
EL::finalize occurs before tool deletion.

**Comment by mmilesi** [comment]
Are you sure? 
Then why should it crash?
NB, the crash I see is happening at the line in EL::finalize() where we delete the pointers, not in the toolstore.

**Comment by kratsg** [comment]
Huh. Time for an email to pat help then... Cause I'm apparently
misunderstanding the asg toolstore

**Comment by kratsg** [comment]
I'm going to close this since we've migrated to AnaToolHandle to fix these sorts of problems.
