### ISSUE TITLE
Events with odd tracks crash HelpTreeBase

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#458]
In a file from a JZ1W Pythia QCD MC sample:

mc15_13TeV.361021.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ1W.merge.DAOD_EXOT2.e3569_s2576_s2132_r6765_r6282_p2432_tid06693339_00/DAOD_EXOT2.06693339._000016.pool.root.1

I came across an event with a vertex vector of size 1 and location of primary vertex -1. This disagrees with L1888 of HelpTreeBase and crashes the entire job. 

I have no problem nuking the event from the analysis (it does not pass the vertex cut, so the user should know that it's dangerous to ask for track-related variables without that cut) but I wonder whether we should add a protection here. The options are:

1) (minimal) issue a warning and just avoid filling the track variables for jets, and whoever uses other objects and hits this should do the same
2) (cleaner) check for this kind of situation at the start of TreeAlgo and turn off all the branches that deal with tracking

I can do 1) for jets because it seems the jets are the only place accessing the vector without checking.

**Comment by kratsg** [comment]
Why is it exactly crashing? Because the location is `-1` meaning there's no primary vertex to be found?

**Comment by urania277** [comment]
yep, there seems to be one vertex that isn't primary. I wonder who would want those events anyways though.

**Comment by kratsg** [comment]
@johnda102 -- you wrote most of the code for the primary vertex stuff. Do you have a specific opinion on how to handle these cases?

**Comment by gfacini** [comment]
Hi!

I like the idea of crashing but maybe with a meaningful warning. These
events are rarely actually desired by a user. The user should use basic
event selection to apply the PV selection. That would clean up the events
 and is the proper handeling. The HS is so soft it doesn't make a
reconstructable vertex!!

All events have a dummy vertex so the reco (I think) doesn't crash from an
empty vertex container.

Cheers,
Gabriel
