### ISSUE TITLE
PileupWeight type mismatch in HelpTreeBase

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#459]
in HelpTreeBase, AB2.3.38, activating the pileup variables with

      static SG::AuxElement::ConstAccessor< float > weight_pileup ("PileupWeight");

crashes with 

libc++abi.dylib: terminating with uncaught exception of type SG::ExcAuxTypeMismatch: SG::ExcAuxTypeMismatch: Type mismatch for aux variable `::PileupWeight' (610); old type is double new type is float

Are there any compatibility problems if we change that to double?

**Comment by kratsg** [comment]
No issue. Must be a change upstream somewhere.

**Comment by mmilesi** [comment]
Hi @urania277 ,

since AB 2.3.32, the pileup weight decoration in the CP tool has been changed from `double` to `float`:

https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/AnalysisBaseReleaseNotes23

I have seen no issues at all with 2.3.38. Are you checking out a specific (old) tag of the PRW tool?

Ciao

Marco

**Comment by urania277** [comment]
Hi both, 

I'm on 2.3.38 (locally) so quite puzzled. 

MacBook-Pro-7:TLACode urania277$ . rcSetup.sh 
Adding private configuration in /Users/urania277/.rcSetup.conf
In current directory, found previous release with config=generic at the following location, going to set up its env: 
	/Users/urania277/Work/ATLAS/sw/releases/AnalysisBase/2.3.38

and you're right that I see

   //decorate with standard PileupWeight 
   if(!m_noWeightsMode) {
      double weight =  /*m_tool->*/getCombinedWeight( eventInfo );
      if(m_unrepresentedDataAction==2) weight *= getUnrepresentedDataWeight( eventInfo );
      eventInfo.auxdecor<float>(m_prefix+"PileupWeight") = weight;
   }

so the decoration is a float. If no one else sees a problem, then I'll investigate from my side and you can close.

**Comment by mmilesi** [comment]
:+1:
