### ISSUE TITLE
JetSelector: m_useCutFlow being ignored in initialize

### ISSUE THREAD

**Issue by clawish** [UCATLAS/xAODAnaHelpers#471]
Since [a condition involving](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L350) `m_useCutFlow` appears before [the configuration of the algorithm](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L377), the value of `m_useCutFlow` given in the configuration file is ignored. As `m_useCutFlow` [is set to true in the constructor](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L67), the block following the condition will always be executed, resulting in abortion of the algorithm [if `cutflow` is not available](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L354).

**Comment by kratsg** [comment]
@clawish -- this is only for when you configure the JetSelector algorithm using a TEnv config file. We are slowly moving away from that and support for this config files is being deprecated.

If you configure using `xAH_run` or by something like

```c++
jetselect = new JetSelector("signal_jets");
jetselect->m_useCutFlow=false;
```

then it will be fine.

**Comment by johnda102** [comment]
Begs the question; do we want to deprecate TEnv config files?

I assume there is a lot of places were we are not providing full support
now.

I vote yes.  TEnv is evil.

On Fri, Feb 5, 2016 at 10:43 PM, Giordon Stark <notifications@github.com>
wrote:

> @clawish <https://github.com/clawish> -- this is only for when you
> configure the JetSelector algorithm using a TEnv config file. We are slowly
> moving away from that and support for this config files is being deprecated.
>
> If you configure using xAH_run or by something like
>
> jetselect = new JetSelector("signal_jets");
> jetselect->m_useCutFlow=false;
>
> then it will be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/471#issuecomment-180571758>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
@UCATLAS/xah - VOTE!

**Comment by fizisist** [comment]
I’m not a fan of TEnv myself....seems error prone. So, for what it's worth, that's my vote.

**Comment by alexandertuna** [comment]
TEnv is evil

**Comment by urania277** [comment]
TE(n)vil, go away

**Comment by mmilesi** [comment]
It caused me many troubles in the past, so I am in to deprecate it!
