### ISSUE TITLE
Why are the jet cleaning flags chars?

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#478]
See e.g. JetCalibrator L623 and HelpTreeBase L2051. 

Just trying to understand the logic and failing...the reason why I'm turning them into ints in my fork is that they produce a large amount of spam when attached to trigger jets, which in the data scouting stream seem to exist only in bytestream format, and there is no converter yet:

ERROR xAOD::ByteStreamAuxContainer_v1::getData Unknown variable type (c) requested

Sure, we could ask someone to write said converter, but it seems odd that something that we ultimately read out as true/false is saved as a char. (It probably has to do with TAccept but that's as far as I went).

**Comment by kratsg** [comment]
Booleans are converted to chars when saved to output root file. So we use
chars in all cases when booleans are used.

**Comment by urania277** [comment]
Hmm, that gets converted to an int before saving to the , no? Also the problem is when we attach it to the jet in JetCalibrator, not when we write it out.

**Comment by kratsg** [comment]
Bools -> Chars. Ints are ints.

**Comment by urania277** [comment]
I turned bools into ints in my fork and the error has disappeared - not merging that though. I could look into it more and try to get dictionaries written for bytestream. But it's a little overkill...
