### ISSUE TITLE
Systematic Propagation in OverlapRemover

### ISSUE THREAD

**Issue by kkrizka** [UCATLAS/xAODAnaHelpers#480]
Hi all,

The systematics don't seem to be propagated through the OverlapRemover algorithm. For example, the `m_outputAlgoJets` variable is not used for anything other than receiving a value from TEnv. Can someone that is used to this class comment if this hasn't been implemented yet or I am not understanding something?

--
Karol Krizka

**Comment by mmilesi** [comment]
Hi @kkrizka ,

have a look at the OLR module docs:

https://xaodanahelpers.readthedocs.org/en/latest/OverlapRemover.html

The overlap removal algorithm is not designed to create any output systematic list. All the algorithms downstream must be configured to pick up the systematic list(s) from upstream algorithms (e.g., the selectors or the calibrators).

I think I will soon remove all the `m_outputAlgo*` members to avoid any further confusion.

Cheers

Marco

**Comment by kkrizka** [comment]
Hi @mmilesi, thank you for the information.

Could we make OR algorithm to just copy the input systematic list to the the output systematic list? This would make the interface of the algorithm the same as others.

--
Karol Krizka

**Comment by kratsg** [comment]
@kkrizka - don't you think it's confusing to create output systematic lists for algorithms that don't make systematics? EG: we have them for calibrators because they do indeed make the systematics.

**Comment by kkrizka** [comment]
We also have them for selectors, which do not make new systematics. Although they do remove existing ones, if no objects pass the selection.

I am thinking more about this now. Shouldn't OR algorithm output one systematics list that is the combination of systematics associated with the different input containers? For example if you are looking at m_{jet,gamma}, you would want to make the distributions with photons+jets containers after OR with JES variation and the containers after OR with photon ES variations. Instead of looping first over photon systematics and then over jet systematics, it might be better just to have a single list containing the combined systematics after the OR algorithm. Does that make sense?

**Comment by mmilesi** [comment]
Hi @kkrizka ,

Giordon's statement actaully summarises my point of view on this

Your final question certainly does make sense :wink: 
The same question you have was already asked by @JamesSaxon in #287

I'll have to think a bit more about any possible caveats with what you suggest. For the time being, what you could do is to merge the input systematics into a single one at the beginning of your final private algorithm, and perform a single loop on that.

Marco

**Comment by kkrizka** [comment]
After talking to others about this, the combination of the systematics in the OR seems to be the correct approach. I have a push request with this change ready, but I'll wait a bit to see if you have any other comments.
