### ISSUE TITLE
memory leak in HelpTree Base

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#481]
Crashing grid jobs when all systematics are run

**Comment by kratsg** [comment]
@johnda102 -- would you be able to identify the latest point which doesn't crash grid jobs?

See history here: https://github.com/UCATLAS/xAODAnaHelpers/commits/master/Root/HelpTreeBase.cxx

**Comment by jbossios** [comment]
I'm having the same problem using 00-03-29. @johnda102: Did you manage to find the problem? 
This seems to not solve my problem: "fix memory leak in jet #512"

**Comment by kratsg** [comment]
@jbossios -- @tongbaojia's commit doesn't fix that though, as pointed out. I'm still trying to find it.

**Comment by kratsg** [comment]
@urania277 may have identified it already.

**Comment by jbossios** [comment]
@johnda102 @kratsg: Any news on this?

**Comment by kratsg** [comment]
I haven't found it :-/

**Comment by mmilesi** [comment]
Sorry to hijack this...in the past I had similar issues because I forgot to call `std::vector::clear()` on a vector branch (not technically a "memory leak", but...). Did you check that already?
However, it would be strange not to have this issue when running the nominal case only.

**Comment by gbesjes** [comment]
Apologies for hijacking this thread (I mostly follow the xAODAnaHelpers package out of interest), but I always notice a leak when I attach a TTree to an output file using wk()->addOutput(tree) in EventLoop-derived code. There's a thread on the ROOT forums here: https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=21282 but no solution has been identified yet. Without the addOutput() call, I don't see any leaks.

**Comment by jbossios** [comment]
I already look for missing std::vector::clear() but I didn't found any. I checked in the nominal case and indeed it seems there is no memory leak.

**Comment by jbossios** [comment]
@gbesjes thanks for the help. I'm not doing this: wk()->addOutput(tree)

**Comment by kratsg** [comment]
If there's a leak that comes up again, let me know. I'm closing this issue otherwise.
