### ISSUE TITLE
Inheritance Based Particle Histogram Classes

### ISSUE THREAD

**Issue by kkrizka** [UCATLAS/xAODAnaHelpers#482]
I am working on adding a `PhotonHists` class for useful photon histograms. Since some of the code is similar to the other particle histogram classes, I think it would be useful to use inheritance to simplify the code. I have a prototype ready for the photons. You can see it at https://github.com/kkrizka/xAODAnaHelpers/commit/69c2c395fa6c68c4013f6573d76d923d525a0300

It adds a new `IParticleHists` class that plots the particle 4-vectors, with separate histograms for `NLeading#` particles. The particles are distinguished by a `prefix` string (output histogram name) and `title` string (for x-axis labels), initialized though the constructor. Then the `PhotonHists` class inherits from it, adding (in the future) photon specific histograms. What do others think of propagating this structure to other histogram classes? It will automatically add support for plotting `NLeading#` in `MuonHists` and ability to plot 4-vector information for particles not supported in xAODAnaHelpers yet (ie: TruthParticles).

Before I perform a pull request, I need to finish the following tasks:
- rebase on latest master
- add inheritance to `ParticleHistsAlgo` (aka share code for the systematics loop)
- add the photon-specific histograms

**Comment by johnda102** [comment]
I think this is clearly the way to go.

On Tue, Feb 9, 2016 at 10:31 AM, Karol Krizka <notifications@github.com>
wrote:

> I am working on adding a PhotonHists class for useful photon histograms.
> Since some of the code is similar to the other particle histogram classes,
> I think it would be useful to use inheritance to simplify the code. I have
> a prototype ready for the photons. You can see it at kkrizka@69c2c39
> <https://github.com/kkrizka/xAODAnaHelpers/commit/69c2c395fa6c68c4013f6573d76d923d525a0300>
>
> It adds a new IParticleHists class that plots the particle 4-vectors,
> with separate histograms for NLeading# particles. The particles are
> distinguished by a prefix string (output histogram name) and title string
> (for x-axis labels), initialized though the constructor. Then the
> PhotonHists class inherits from it, adding (in the future) photon
> specific histograms. What do others think of propagating this structure to
> other histogram classes? It will automatically add support for plotting
> NLeading# in MuonHists and ability to plot 4-vector information for
> particles not supported in xAODAnaHelpers yet (ie: TruthParticles).
>
> Before I perform a pull request, I need to finish the following tasks:
>
>    - rebase on latest master
>    - add inheritance to ParticleHistsAlgo (aka share code for the
>    systematics loop)
>    - add the photon-specific histograms
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/482>.
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
This is a good idea. We will need to be careful with documentation here (making sure the inheritance is clear and that people know the options available for the info switch). In this particular case -- we now have two info switches people need to look up for options.

The other thing is that the inheritance for your Hist classes is also adding more arguments to the initializers which we don't want to have (it should just be `m_name` and `m_detailStr`). Anything else needs to be a public member of the class to keep the interface uniform.

**Comment by kkrizka** [comment]
I would like to keep the new initializers there, because I expect to use them more often than not. But I set their default to "", so the interface should stay the same.

There is also a question about consistent binning for pt histograms of all particles. For example, right now both muon and jet pt histograms have the same range. I am not sure how ideal this is, since muon and jets have different energies of interest. I think this is a more general problem. Even just for jet histograms, some might not want to go up to high pt. I believe @johnda102 solved this for some other histograms by having several histograms per variable (small, medium, large ranges). Should we do that here too?
