### ISSUE TITLE
Script to get normalizations from metadata files?

### ISSUE THREAD

**Issue by mswiatlo** [UCATLAS/xAODAnaHelpers#494]
Hey all,

Does anyone have a script to compute normalizations from metadata files? xAH stores this in a nice way, but I'd rather not have to write a script to parse it if someone has already done so.

Cheers,
Max

**Comment by mswiatlo** [comment]
Does no one really have a script for this? @johnda102 or @kkrizka maybe? Thanks guys.

**Comment by johnda102** [comment]
HI Max,

    there is a script to get the dis / cross sections/ filter eff  which:

scripts/getDSInfo.py

Here you can input a .txt file with the inputs you want and it queres ami
and outputs the relevant data in the format used by the data/metadata/
cross section files.

There is also:
scripts/getEventCounts.py
which takes an input file and writes out the expected AMI evnet counts.

I then I have separate analysis specif py scripts eg:
UCT3: ~johnda/Analysis/Xhh_2.3.38/XhhCommon/scripts/checkEventCounts.py

that compare my downloaded ntuples to the expected counts.

(This last script can probably also be made common if we had a common
ntuple format in the end)

On Tue, Feb 23, 2016 at 1:43 AM, Maximilan Swiatlowski <
notifications@github.com> wrote:

> Does no one really have a script for this? @johnda102
> <https://github.com/johnda102> or @kkrizka <https://github.com/kkrizka>
> maybe? Thanks guys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/494#issuecomment-187455249>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kkrizka** [comment]
I also have a script for rescaling the histograms made by xAODAnaHelpers using the information stored in metadata.

https://svnweb.cern.ch/trac/atlasphys-exo/browser/Physics/Exotic/JDM/DiJetISR/Run2/Code/ZprimeDM/trunk/scripts/applyEventCountWeight.py

Usage is `applyEventCountWeight.py OUT_submitdir`. It loops over all histograms in all `hist-X.root` files in `OUT_submitdir`. It then scales the histograms inplace by the `sumOfWeights initial` bin from `data-metadata/X.root`. Unscaled histograms are backed up to `orig` directory.

**Comment by mswiatlo** [comment]
Awesome, thanks guys! @kkrizka's script is exactly what I needed. Might make sense to put this into github at some point, but for now I'll close this.
