### ISSUE TITLE
Add EventInfoContainerName configuration

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#5]
CxAODs have them named "EventInfo__Nominal"

**Comment by mmilesi** [comment]
Hi @kratsg , can you please add documentation to this issue? It's not clear what the point is....

**Comment by kratsg** [comment]
@mmilesi - so, all EventInfo containers we retrieve use "EventInfo" which is hard-coded. We want to be quite configurable about this. I will probably add this in the Algorithm.h class since all algorithms should use something like `m_eventInfoContainerName`. Calibrated xAODs will create specialized EventInfo containers that users might want to use in our algorithms, but as it is hard-coded, they can't.

**Comment by mmilesi** [comment]
Ok, now this makes sense. Thanks.
