### ISSUE TITLE
MinixAOD and CutBookkeeper

### ISSUE THREAD

**Issue by kkrizka** [UCATLAS/xAODAnaHelpers#501]
I don't think the implementation of CutBookkeeper output in the `MinixAOD` algorithm is correct yet. Right now it just copies the `CutBookkeepers` container in the `initialize()` function. The problem is that this means only the information from the first input xAOD is used. We need to merge the CutBookkeepers from all of the input xAODs. Also we should add our own CutBookkeeper and add an empty `IncompleteCutBookkeepers` container.

I think there is a good guide of we should do here:
https://indico.cern.ch/event/401703/contribution/2/0/attachments/804708/1102864/CutFlowMetaData.pdf
I will look into doing this by porting the Athena `CutFlowSvc` service that does this (https://svnweb.cern.ch/trac/atlasoff/browser/Event/EventBookkeeperTools/trunk/src/CutFlowSvc.h).

**Comment by kratsg** [comment]
See #500.

**Comment by kratsg** [comment]
I guess this will be implemented in Mini-xAOD and it should be somewhat trivial to implement a cutflow here (you only need # events processed)?

**Comment by kkrizka** [comment]
That's correct. I am working on it now.
