### ISSUE TITLE
Crash when running over data

### ISSUE THREAD

**Issue by zqhsfz** [UCATLAS/xAODAnaHelpers#519]
I notice that the code would crash when running over data after checking out newest rev. Below is the error message:

JetSelector::execute()    ERROR   mcEventWeight is not available as decoration! Aborting

It looks like this comes from newest commit in BasicEventSelection.cxx, that it decorates the "mcEventWeight" only in MC sample and only when it does not exists, while before this decoration was applied in both data and MC.  

Could someone help fix on that? Thanks!

**Comment by kkrizka** [comment]
Can you try now?

**Comment by zqhsfz** [comment]
Yes, it works now. Thanks!
