### ISSUE TITLE
Switch from RETURN_CHECK to ANA_CHECK

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#538]
We should move towards matching centrally-provided ASG tool functions and macros for these things of things -- this is one of them.

https://twiki.cern.ch/twiki/bin/view/AtlasComputing/SoftwareTutorialxAODAnalysisInROOT

Do we want to use the `ANA_CHECK` here? Requires a bit of updating.

**Comment by mmilesi** [comment]
Related to this....shall we have also a macro to wrap all the `myAccessor.isAvailable()` checks in a more compact way (should just check the boolean)? We have quite a few scattered in the code.

**Comment by kratsg** [comment]
Closed with #896.

> shall we have also a macro to wrap all the myAccessor.isAvailable() checks in a more compact way (should just check the boolean)

Not sure if we should. There's lots of different use cases for it.
