### ISSUE TITLE
IncompleteCutBookkeepers check

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#542]
See "Problem with IncompleteCutBookkeepers in derived data (p2524)" on PATHelp

**Comment by kratsg** [comment]
https://groups.cern.ch/group/hn-atlas-PATHelp/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fhn-atlas-PATHelp%2FLists%2FArchive%2FProblem%20with%20IncompleteCutBookkeepers%20in%20derived%20data%20%28p2524%29&FolderCTID=0x0120020084D7E80CB0C3394A8D54EF07C309B044
