### ISSUE TITLE
deal with 2.4.X and 2.3X development

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#543]
HI All, 
 
 Im seeing that there are a number of changes in base code we need to make for 2.4.X which are incompatible with 2.3.X (these are all related to underlying atlas tools changin in 2.4.X) 

How to we want to deal with this? Seems like we need to be able to support development in both releases.

**Comment by kratsg** [comment]
@johnda102 -- what's the releases for? Isn't 2.4.X for 21.X releases?

**Comment by johnda102** [comment]
2.4.X is for 20.7.X (MC)  and 20.11.X (data)

On Tue, Mar 15, 2016 at 5:05 PM, Giordon Stark <notifications@github.com>
wrote:

> @johnda102 <https://github.com/johnda102> -- what's the releases for?
> Isn't 2.4.X for 21.X releases?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/UCATLAS/xAODAnaHelpers/issues/543#issuecomment-196898952
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by gfacini** [comment]
I am not following....are the two releases incompatible?

Gabriel

**Comment by johnda102** [comment]
yeah some packages are getting deprecated and replaced. The interface
changes for some others.

On Thu, Mar 17, 2016 at 12:50 PM, gfacini <notifications@github.com> wrote:

> I am not following....are the two releases incompatible?
>
> Gabriel
>
> On Tue, Mar 15, 2016 at 5:08 PM, johnda102 <notifications@github.com>
> wrote:
>
> > 2.4.X is for 20.7.X (MC) and 20.11.X (data)
> >
> > On Tue, Mar 15, 2016 at 5:05 PM, Giordon Stark <notifications@github.com
> >
> > wrote:
> >
> > > @johnda102 <https://github.com/johnda102> -- what's the releases for?
> > > Isn't 2.4.X for 21.X releases?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub:
> > >
> >
> https://github.com/UCATLAS/xAODAnaHelpers/issues/543#issuecomment-196898952
> > >
> >
> >
> >
> > --
> > University of Chicago
> > http://hep.uchicago.edu/~johnda
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/UCATLAS/xAODAnaHelpers/issues/543#issuecomment-196900171
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/543#issuecomment-197843450>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
@johnda102 -- is there a list of these things we can look up so we can start? The problem is going to be awkward because we can't really just completely switch xAH. Maybe we can tag an End-Of-Life version and then state that we move to 2.4.X from this point on? This would be annoying for those who need to use 2.3.X for some reason though, no?

**Comment by gfacini** [comment]
John, any news?

**Comment by johnda102** [comment]
not really.

Most of these issuees come up in some nightly 2.4.X tests I was running for
Attila.
But Ive been booked with other stuff the past few days.

Ill send around a summary when I get back to it


On Tue, Mar 22, 2016 at 3:13 PM, gfacini <notifications@github.com> wrote:

> John, any news?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/543#issuecomment-199833316>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by johnda102** [comment]
coming back to this now. 

Changes in AB are discussed here:
https://twiki.cern.ch/twiki/bin/view/AtlasProtected/AnalysisBaseReleaseNotes24

So far changes Ive needed for nightly are:
  Remove TrigMuonMatching
  Remove TrigEgammaMatching

im pushing to master-2.4.X for now

**Comment by kratsg** [comment]
@johnda102 -- can you create a branch called `2.4.X`? We'll continuously rebase on it. We're going to need to maintain to branches for right now for the time being it that's ok. I'll help make sure the branch is up to date with other changes on top.

**Comment by johnda102** [comment]
Hi Giordon,

yesh ive pushed a branch

master-2.4.X

On Fri, Mar 25, 2016 at 3:34 PM, Giordon Stark <notifications@github.com>
wrote:

> @johnda102 <https://github.com/johnda102> -- can you create a branch
> called 2.4.X? We'll continuously rebase on it. We're going to need to
> maintain to branches for right now for the time being it that's ok. I'll
> help make sure the branch is up to date with other changes on top.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/543#issuecomment-201314876>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
So let's start with the obvious:

> Remove TrigMuonMatching
> Remove TrigEgammaMatching

If these are removed, are there replacements or just removed forever? Are we just temporarily removing it until we find out what's new [eg: because you commented it out rather than deleting].

**Comment by rsmith54** [comment]
Hey @kratsg ,

According to [this PAT help thread](https://groups.cern.ch/group/hn-atlas-PATHelp/Lists/Archive/Flat.aspx?RootFolder=%2fgroup%2fhn-atlas-PATHelp%2fLists%2fArchive%2fTriggerMatching&FolderCTID=0x0120020084D7E80CB0C3394A8D54EF07C309B044), you can find the new examples at [https://svnweb.cern.ch/trac/atlasoff/browser/Trigger/TrigAnalysis/TriggerMatchingTool/trunk/src/TestMatchingToolAlg.cxx](https://svnweb.cern.ch/trac/atlasoff/browser/Trigger/TrigAnalysis/TriggerMatchingTool/trunk/src/TestMatchingToolAlg.cxx)

**Comment by rsmith54** [comment]
Hey all,

I'm not sure what the status of this is, but to use BasicEventSelection with 2.4.X, I needed to update to the master to fix the CBK issues.  I then picked @johnda102 's commit to fix the trig matching tool issues see : https://github.com/rsmith54/xAODAnaHelpers/tree/feature/2.4.X

**Comment by urania277** [comment]
Hi all,

I've hacked around this (by commenting everything out since I just need the jets), but is there a solution to find_packages problem: 

RootCore: Error package TrigMuonMatching not known, required by xAODAnaHelpers

I am on AB 2.4.6.

Thanks!
Caterina

**Comment by rsmith54** [comment]
Hey,

I think just make sure that TrigMuonMatching isn't on this line : 

https://github.com/rsmith54/xAODAnaHelpers/blob/feature/2.4.X/cmt/Makefile.RootCore#L16

Just make sure it's not listed there and ``` rc find_packages``` shouldn't complain.

Cheers,
Russell

**Comment by urania277** [comment]
Hi @rsmith54, thanks, turns out that we weren't picking up the branch correctly.

**Comment by jdandoy** [comment]
The TrigMuonMatching and TrigEgammaMatching issue also applied to 2.3.49 and later.  Would it be possible to merge the master-2.4.X branch back to master, or are there still many differences between 2.3.X and 2.4.X?
