### ISSUE TITLE
Example script for merging outputs

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#547]
This is an example of a script that will take in the paths provided and merge outputs. Could be cleaned up to be configurable -- but works perfectly:

https://gist.github.com/1c95c956fb4646d451eb

**Comment by kkrizka** [comment]
I think #650 takes care of this issue.

**Comment by kratsg** [comment]
Don't forget we will need some form of documentation somewhere so people know it exists ;)
