### ISSUE TITLE
input file 

### ISSUE THREAD

**Issue by mdevesa** [UCATLAS/xAODAnaHelpers#550]
Hi, I couldn’t use a tex file with the list of path in it, as an input file for "xAH_run.py", maybe I'm missing something with the format (?)

Thanks!
cheers!

**Comment by kratsg** [comment]
Hi @mdevesa -- can you upload your file to https://gist.github.com/ so we can help you?

How are you trying to run `xAH_run`?

**Comment by mdevesa** [comment]
Hi , sure
[sample.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/180845/sample.txt)
and Im using:
xAH_run.py --files sample.txt --config StudyTrigTracks/scripts/config_StudyFTKTracks.py   -f --submitDir TestAODFTK --isMC  direct

and the error says: 
/afs/cern.ch/work/m/mdevesa/BJet_test_varios_mod_v3/sample.txt not a ROOT file

Thanks for the help!
Cheers

**Comment by kratsg** [comment]
Add `--inputList` to your arguments there.

```
xAH_run.py --files sample.txt --inputList --config StudyTrigTracks/scripts/config_StudyFTKTracks.py -f --submitDir TestAODFTK --isMC direct
```

**Comment by mdevesa** [comment]
Thanks! it works :)
