### ISSUE TITLE
Double underscore in BTagging weight branch name

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#557]
This might sound a bit silly but...is there a reason why the branch name:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L1672

has got a double underscore in it? Can we change it to a single underscore?

(I see @jdandoy is the last who changed the involved lines, so the question is to you :wink: )

**Comment by jdandoy** [comment]
Hi @mmilesi ,

That honor goes to @johnda102 
https://github.com/UCATLAS/xAODAnaHelpers/commit/0a0190dda547744c11397b690e47d89157524502#diff-536048c8c92cb3373780d12a4b75a621R1314

**Comment by johnda102** [comment]
kill it

On Thu, Mar 24, 2016 at 8:56 AM, jdandoy <notifications@github.com> wrote:

> Hi @mmilesi <https://github.com/mmilesi> ,
>
> That honor goes to @johnda102 <https://github.com/johnda102>
> 0a0190d#diff-536048c8c92cb3373780d12a4b75a621R1314
> <https://github.com/UCATLAS/xAODAnaHelpers/commit/0a0190dda547744c11397b690e47d89157524502#diff-536048c8c92cb3373780d12a4b75a621R1314>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/557#issuecomment-200719605>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kkrizka** [comment]
Speaking of branch names, what is a `Fracnergy`?

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L1537
