### ISSUE TITLE
Accessing a variable added by the JetCalibTools

### ISSUE THREAD

**Issue by eakilli** [UCATLAS/xAODAnaHelpers#570]
Hi all,

I have been trying to access a variable that is added as decoration to the jet during the calibration (using latest JetCalibTools included in AnalysisBase 2.3.45). 
I am trying to do this in the inherited class (FillFatJetsUser) and using the calibrated jets as the input container. I couldn't manage to get the variable. Is there a way that I can do it or check if the variable is created without a problem?

Thank you!
Ece

**Comment by kratsg** [comment]
You should be using something like

```
m_someVar = -99;
if(decor.isAvailable(*jet))  m_someVar = decor(*jet);
```

**Comment by eakilli** [comment]
@kratsg thank you but I am doing this and the decor is not available. Can I somehow check what information is written to the calibrated output container during the calibration?

**Comment by kratsg** [comment]
@eakilli - you'll have to look at the code for the tool itself. The only thing `xAH::JetCalibrator` applies that I can see is the Jet Cleaning:

```
static SG::AuxElement::Decorator< char > isCleanDecor( "cleanJet" );
```
