### ISSUE TITLE
JetSelector JVT Calibration and Truth Jets

### ISSUE THREAD

**Issue by kkrizka** [UCATLAS/xAODAnaHelpers#571]
Running the `JetSelector` on TRUTH1 DAODs currently crashes when "Applying JVT SF" with the error:

```
An exception was caught!
Traceback (most recent call last):
  File "./xAODAnaHelpers/scripts/xAH_run.py", line 583, in <module>
    driver.submit(job, args.submit_dir)
Exception: void EL::Driver::submit(const EL::Job& job, const string& location) =>
    SG::ExcBadAuxVar: Attempt to retrieve nonexistent aux data item `::DetectorEta' (371). (C++ exception)
```

Can we add an option to disable running this when running on truth? Is checking `m_doJVT` appropriate here?

**Comment by urania277** [comment]
Related: a bunch of other errors running on trigger jets are fixed by changing L535 to: 
if ( m_isMC && m_doJVT) {
