### ISSUE TITLE
undefined variable when using inputEOS and inputList

### ISSUE THREAD

**Issue by btamadio** [UCATLAS/xAODAnaHelpers#580]
On line 318 of xAH_run.py, there is an undefined variable, namely args.eosDataSet. Using --inputList and --inputEOS fails because of this. I'm not sure what it should be replaced with to make sample handler read the input file list correctly.

ROOT.SH.ScanDir().sampleDepth(0).samplePattern(args.eosDataSet).scanEOS(sh_all,base)

**Comment by kratsg** [comment]
This seems to have been introduced by @johnda102 in d3c9b9c4b5d631770812c64de28d055c8023f1d6 but I cannot figure what it should be.. I think `args.inputTag` but John didn't rebase here, and instead, merged changes -- so it's not clear why this change was introduced here.

**Comment by btamadio** [comment]
How is the --inputEOS option meant to be used? Should it be followed by the path to a single file on EOS? If I try to give it the path to a directory on EOS, I get a crash.

I'm running the following command: xAH_run.py --files /eos/atlas/atlastier0/rucio/data16_13TeV/express_express/00296939/data16_13TeV.00296939.express_express.merge.AOD.x412_m1576 --inputEOS --config run/config_data16.py -f --inputTag m412 direct

And I get this error:

xAOD::Init                INFO    Environment initialised for data access
Running on EOS directory /eos/atlas/atlastier0/rucio/data16_13TeV/express_express/00296939/data16_13TeV.00296939.express_express.merge.AOD.x412_m1576 with tag m412
sh: /afs/cern.ch/project/eos/installation/0.3.4/bin/eos.select: No such file or directory
RootCoreUtils:/build1/atnight/localbuilds/nightlies/AnalysisBase-2.3.X/AnalysisBase/rel_nightly/RootCoreUtils/Root/ShellExec.cxx:58:exception: command failed: /afs/cern.ch/project/eos/installation/0.3.4/bin/eos.select ls -l /eos/atlas/atlastier0/rucio/data16_13TeV/express_express/00296939/data16_13TeV.00296939.express_express.merge.AOD.x412_m1576
with output:
--------------------
An exception was caught!
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/btamadio/RPV_SUSY/RootCoreBin/bin/x86_64-slc6-gcc49-opt/xAH_run.py", line 357, in <module>
    ROOT.SH.scanDir (sh_all, eoslist, args.inputTag); #Run on all files within dir containing inputTag
TypeError: none of the 3 overloaded methods succeeded. Full details:
  void SH::scanDir(SH::SampleHandler& sh, SH::DiskList& list, const string& pattern = "*.root*", const string& samplePattern = "*", const string& samplePostfix = "") =>
    RootCoreUtils:/build1/atnight/localbuilds/nightlies/AnalysisBase-2.3.X/AnalysisBase/rel_nightly/RootCoreUtils/Root/ShellExec.cxx:58:exception: command failed: /afs/cern.ch/project/eos/installation/0.3.4/bin/eos.select ls -l /eos/atlas/atlastier0/rucio/data16_13TeV/express_express/00296939/data16_13TeV.00296939.express_express.merge.AOD.x412_m1576
with output:
 (C++ exception)
  void SH::scanDir(SH::SampleHandler& sh, const string& dir) =>
    takes at most 2 arguments (3 given)
  void SH::scanDir(SH::SampleHandler& sh, const string& dir, const string& prefix) =>
    could not convert argument 2

========================================
405983:58:04.302-End Program
Elapsed time: 0:00:11.076
========================================

**Comment by kratsg** [comment]
That error looks like you're running it on a machine that does not have EOS
access. You need to run it from lxplus -- I think -- rather than a regular
tier3.

**Comment by btamadio** [comment]
I realized that SampleHandler was trying to call an old version of eos. I just tried checking out the latest SampleHandler tag so we'll see if that fixes the problem.

**Comment by btamadio** [comment]
With the updated version of SampleHandler, and running on lxplus, I don't see the crash anymore. But the scanEOS function doesn't seem to be finding the files:

xAOD::Init                INFO    Environment initialised for data access
Running on EOS directory /eos/atlas/atlastier0/rucio/data16_13TeV/express_express/00296939/data16_13TeV.00296939.express_express.merge.AOD.x412_m1576/ with tag 
SampleHandler with 0 files

**Comment by kratsg** [comment]
Then I'm not entirely sure what's going on here. It should, by definition,
be scanning it correctly. Actually, looking at the code

                base = os.path.basename(line)

ROOT.SH.ScanDir().sampleDepth(0).samplePattern(args.eosDataSet).scanEOS(sh_all,base)

Whoever wrote this intended it to be that

base = *
args.eosDataSet
= /eos/atlas/atlastier0/rucio/data16_13TeV/express_express/00296939/data16_13TeV.00296939.express_express.merge.AOD.x412_m1576

EG: the base is a file pattern in a given directory you specified.
Technically, it should be splitting up the input path based on the basename
and the directory name.

base = os.path.basename(pathPattern)
args.eosDataSet = os.path.dirname(pathPattern)

Technically.

**Comment by johnda102** [comment]
Hi all, 

  In the end I didnt get eos running with files lists. 

I just stuck to running with the input data sets directly eg: 
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/scripts/xAH_run.py#L345

**Comment by kratsg** [comment]
I'll see if I can get this working again. We might just deprecate support for it -- I'm not sure how often people need EOS unless they're running on the AODs produced directly from ESDs at the start of runs?
