### ISSUE TITLE
Add support for Athena access mode

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#581]
This needs to be added to xAH_run

**Comment by johnda102** [comment]
should be there already

On Wed, Apr 27, 2016 at 10:42 PM, Giordon Stark <notifications@github.com>
wrote:

> This needs to be added to xAH_run
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/issues/581>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by johnda102** [comment]
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/scripts/xAH_run.py#L90

On Wed, Apr 27, 2016 at 10:46 PM, John Alison <John.Alison@cern.ch> wrote:

> should be there already
>
> On Wed, Apr 27, 2016 at 10:42 PM, Giordon Stark <notifications@github.com>
> wrote:
>
>> This needs to be added to xAH_run
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UCATLAS/xAODAnaHelpers/issues/581>
>>
>
>
>
> --
> University of Chicago
> http://hep.uchicago.edu/~johnda
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by urania277** [comment]
confirm and use it :)
