### ISSUE TITLE
JetCalibTools in JetCalibrator

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#597]
Hello 

I'm implementing some changes in JetCalibrator concerning JetCalibTools in a personal branch and I would like to make a pull request but I'm encountering a problem explained below:

First I created and new branch:
git checkout -b upgrade/JetCalibrator

then I made some modifications and I did the following:
git add Root/JetCalibrator.cxx
git commit Root/JetCalibrator.cxx -m ""

then:
git pull --rebase origin master

At this point, everything was fine.

Then I tried to do:
git push -u origin upgrade/JetCalibrator

and I got the following error:

error: The requested URL returned error: 403 Forbidden while accessing https://github.com/UCATLAS/xAODAnaHelpers/info/refs

fatal: HTTP request failed

Any idea? 

I also don't know how to make visible this new branch by others. It's not listed here:
https://github.com/UCATLAS/xAODAnaHelpers/branches/active

BTW: I don't actually know if I have permissions...

P.S.: This branch is meant to change the initialization of JetCalibTools to start using setProperty(). The actual initialization used in JetCalibrator to set the properties with the constructor will be deprecated soon. 

Cheers,
Jona

**Comment by kratsg** [comment]
Hi Jona,

You don't have write access to UCATLAS/xAH which is expected. You will want to make a fork of your repo in order to do this (https://help.github.com/articles/fork-a-repo/) and then you can make a pull request from your fork.

Giordon

**Comment by jbossios** [comment]
Hi Giordon

Many thanks! Sorry for the very long delay. I made a fork and a pull request already.

Cheers,
Jona

**Comment by kratsg** [comment]
Ok, so #692.
