### ISSUE TITLE
Overlap removal	

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#6]
wrapper of AssociationUtils ASG O.R. tool

**Comment by mmilesi** [comment]
Hi @kratsg , may I ask you why did you open this issue? I see you labelled it with "question"...

**Comment by kratsg** [comment]
This issue was opened because it was on the xAH twiki. A question was added because I'm not sure if there was anything else to do.

**Comment by mmilesi** [comment]
Ok, then I am going to close #6
