### ISSUE TITLE
Wrong numbers in metadata histogram

### ISSUE THREAD

**Issue by btamadio** [UCATLAS/xAODAnaHelpers#607]
If you run xAODAnaHelpers on this file:
DAOD_EXOT3.08131447._000010.pool.root.1
In this dataset:
data15_13TeV.00279259.physics_Main.merge.DAOD_EXOT3.r7562_p2521_p2614/
With m_useMetaData = true, and m_derivationName = EXOT3Kernel, and whatever configuration file you want, you'll find that the metadata histogram does not show the correct number of selected events. The histogram shows 375 instead of 5794.

I don't actually know if this is a CutBookKeeper bug or an xAODAnaHelpers bug, but I thought I'd post it here in case anyone else has seen a similar problem.

**Comment by kratsg** [comment]
@gfacini - have you seen this before? This seems really strange and might be a CutBookkeeper Bug actually. I don't think we do anything that isn't recommended by the experts. Can you run with the debug/verbosity turned on and see what the names of the cutbookkeeper objects are? Maybe you're picking the wrong one (but it doesn't look like it!)

**Comment by mswiatlo** [comment]
The prescription for  accessing CBK changed a bit between 20.1 and 20.7— if this code wasn’t updated then it could be related to that.

Best,
Max

**Comment by kratsg** [comment]
@mswiatlo - got a link to the current prescription? We'll need to update it as our master now points to 2.4.X releases (eg: 20.7).
