### ISSUE TITLE
Muon trigger scale factors for 2015 and 2016

### ISSUE THREAD

**Issue by fscutti** [UCATLAS/xAODAnaHelpers#652]
Hello @mmilesi and all! 
I am running a muon selection with 2015 and 2016 data + mc15c. The trigger chain I consider for 2015 ( HLT_mu20_iloose_L1MU15 || HLT_mu50 ) cannot be used for 2016 for which I have HLT_mu26_ivarmedium || HLT_mu50. With xAODAnaHelpers, there is no problem including the trigger bits for both chains in the output ntuples, however, when it comes to the trigger SF, I've noticed that the MuonEfficiencyCorrector module only accepts one string among the available options in the [muon CP twiki](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/MCPAnalysisGuidelinesMC15#Muon_trigger_efficiency_scale_fa). As reported in the twiki, the MuonTriggerScaleFactors tool should be configurable with the "Year" property (line 45/46 of   [the muon SF tool]( https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/MuonID/MuonIDAnalysis/MuonEfficiencyCorrections/tags/MuonEfficiencyCorrections-03-03-10/Root/MuonTriggerScaleFactors.cxx) ), so I'd like to ask if it would be possible to configure the MuonEfficiencyCorrector "m_SingleMuTrig" property with a list of single-muon chains rather than just having to pick up only one. Or maybe there is a more straightforward configuration I can use?

Thanks!
Federico

**Comment by kratsg** [comment]
Can you provide an example of what the current input configuration is and what you would like it to be?

**Comment by fscutti** [comment]
Hi all, sorry for the late reply! This is just to let you know that I am investigating if this all problem can be resolved by choosing a different set of triggers. In fact, the chain HLT_mu26_imedium_OR_HLT_mu50 is available for 2015+2016. Unfortunately, there seems to be a bug in the way muon trigger scale factors are accessed for this chain and sometimes I get an error. In essence, I am following the discussion [here](https://its.cern.ch/jira/browse/ATLSUSYSW-130), which Giordon kindly pointed me to, as I have the same problem.

Thanks again!
Federico

**Comment by mmilesi** [comment]
Federico and I are waiting for clarification from the Muon Trigger folks on this. Will keep people posted on developemnts

**Comment by fscutti** [comment]
This was closed in #676

**Comment by kratsg** [comment]
Just an fyi, but in the PR message, you can say something like "This closes #652" and it will auto-close the corresponding issue when the PR is merged :)
