### ISSUE TITLE
Lumi-weighted prescale in BasicEventSelection.cxx

### ISSUE THREAD

**Issue by fscutti** [UCATLAS/xAODAnaHelpers#670]
Hi all,
I am using an or of prescaled triggers for 2015+2016 data (HLT_mu20_L1MU15 + HLT_mu24) and would like to write in my ntuples the luminosity weighted prescale, as opposed to the simple trigger prescale which is currently supported by the framework but would be ill-defined for these chains. This prescale would be computed as described in here [ATL-COM_SOFT-2015-119](https://cds.cern.ch/record/2014726/files/ATL-COM-SOFT-2015-119.pdf) (line 126). The method to be called is then PileupReweightingTool::getDataWeight(const xAOD::EventInfo& eventInfo, const TString& trigger, bool mu_dependent). I would like to decorate the event in BasicEventSelection.cxx. Would it be ok for everybody for me to introduce this additional feature?

Cheers,
Federico

**Comment by kratsg** [comment]
Go ahead and add it. Just make sure you decorate it like we decorate everything else!

**Comment by fscutti** [comment]
yes indeed this should not be executed by default by BasicEventSelection. I'll add a flag.

**Comment by kratsg** [comment]
This was closed in #671.
