### ISSUE TITLE
Running the framework on full xAODs

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#677]
Dear developers,

I tried to run the framework on a full xAOD in the past days, but without success. The xAOD in question is: mc15_13TeV.302454.Pythia8EvtGen_A14NNPDF23LO_DCH800.merge.AOD.e3986_a766_a821_r7676 .

I used the newest master branch of the framework (with the m_Years fix). Some modifications were initially needed to run the full xAOD:
- access mode needs to be changed to "athena" via the --mode athena command,
- set "use meta data" to false to avoid reading CutBookkeeperContainer, which doesn't exist in this xAOD.

After these modifications I got this error:

> worker finished:
> Real time 0:00:14, CP time 13.280
> --------------------
> An exception was caught!
> Traceback (most recent call last):
>   File "/afs/cern.ch/work/g/gorisek/miha/xAODAnaHelpers-2-4-18/RootCoreBin/bin/x86_64-slc6-gcc49-opt/xAH_run.py", line 600, in <module>
>     driver.submit(job, args.submit_dir)
> Exception: void EL::Driver::submit(const EL::Job& job, const string& location) =>
>     SG::ExcAuxTypeMismatch: Type mismatch for aux variable `::DFCommonElectronsLHLoose' (1187); old type is int new type is char (C++ exception)

However, running the framework with exactly the same settings on an EXOT12 DxAOD did not cause this crash.

Best,
Miha

**Comment by kratsg** [comment]
Hi Miha,

This is unfortunately not a problem with our framework:  https://github.com/UCATLAS/xAODAnaHelpers/search?utf8=%E2%9C%93&q=DFCommonElectronsLHLoose -- we have nothing in our code that explicitly references this variable. The error you're seeing is from some particular tool somewhere that is written incorrectly or does not work on this particular AOD. 

In fact, looking further, it's a problem with the OR Tool:

```
134     // Workaround for derivations with "int" type ID flags.
135     catch(const SG::ExcAuxTypeMismatch& e) {
136       if(electron.isAvailable<int>(m_eleID)) {
137         pass = electron.auxdata<int>(m_eleID);
138       }
```

in `AssociationUtils/Root/TauLooseEleOverlapTool.cxx`. I'll get in contact with S. Farrell about this.

**Comment by kratsg** [comment]
> access mode needs to be changed to "athena" via the --mode athena command,

That makes sense. Primary AODs are run using `kAthenaAccess.

> set "use meta data" to false to avoid reading CutBookkeeperContainer, which doesn't exist in this xAOD.

This isn't an xAOD. It's a Primary AOD. It should still have a CutBookkeeperContainer. @mmilesi should know what's going on.

**Comment by fscutti** [comment]
Hi all, 
I just wanted to add to what Miha said that the same error he is reporting also occurred while running on DxAODs. My recent pull request #676 includes a fix to this problem by replacing the VeryLoose working point flag in the ElectronSelector algorithm with the Loose one [see here](https://github.com/UCATLAS/xAODAnaHelpers/pull/676/files). If this problem turns out to be unrelated to that working point I will restore it.

Cheers,
Federico

**Comment by kratsg** [comment]
> I used the newest master branch of the framework (with the m_Years fix). Some modifications were initially needed to run the full xAOD:

He mentions that he has that, so my guess is it is unrelated.

**Comment by MihaMuskinja** [comment]
Dear all,

thanks for the answers and for forwarding the issue to PAT. Just to reassure you, I included the #676 pull:

> commit dcb82e7f2b4c3d3482f2d9fe6ebc68f33e1c566a
> Author: fscutti <federicoscutti@gmail.com>
> Date:   Fri Sep 16 23:09:28 2016 +1000
> 
>     Fix/muon s fs year (#676)
>     
>     * Add Year and MC campaign properties in MuonEfficiencyCorrector
>     
>     * Muon Corrector calls 2015 + 2016 tools
>     
>     * configure two trigger efficiency tools for 2015 and 2016

Best,
Miha

**Comment by kratsg** [comment]
@MihaMuskinja -- what is your configuration for the jobs? (You can post a gist: https://gist.github.com/)

**Comment by mmilesi** [comment]
Hi guys,

as for the Metadata issue, indeed I found a small bug that caused an unnecessary error throw when running on full xAODs. This is going to be fixed here #678

I need to look still in the decoration issue, but my guess is that "DFCommonElectronsLHLoose" exists only on DAODs, as it is augmented by the DF

**Comment by kratsg** [comment]
@mmilesi -- check the email in pathelp -- the only thing that refers to that specific decoration is in the OR Tool code.

**Comment by MihaMuskinja** [comment]
> @MihaMuskinja -- what is your configuration for the jobs?

I was using this configuration with the mentioned modifications:
- config_FF.py : https://github.com/SameSignDiLepton/SSDiLepAnalysis/blob/master/scripts/config_FF.py
- job options : https://github.com/SameSignDiLepton/SSDiLepAnalysis/blob/master/scripts/jobOptions_FF.py
- launch shell script : https://github.com/SameSignDiLepton/SSDiLepAnalysis/blob/master/scripts/launch_FF.sh

Best,
Miha

**Comment by MihaMuskinja** [comment]
Dear all,

another important piece of information, that was maybe missing: I was running this in 2.4.18 and I also modified .travis.yml file accordingly.

Best,
Miha

**Comment by kratsg** [comment]
@MihaMuskinja -- the `.travis.yml` is only for running automated tests on github. It won't change your code.

What other packages do you have checked out?

**Comment by MihaMuskinja** [comment]
Hi Giordon,

nothing else was checked out, your posted setup on PAT is exactly right.

> rcSetup Base,2.4.18
> git clone https://github.com/UCATLAS/xAODAnaHelpers
> cd xAODAnaHelpers && git checkout dcb82e7 && cd ../
> git clone https://github.com/SameSignDiLepton/SSDiLepAnalysis
> rc find_packages
> rc compile

**Comment by kratsg** [comment]
@MihaMuskinja - any updates on this?

**Comment by MihaMuskinja** [comment]
Hi @kratsg ,

no updates. However, we will not need to run the framework on full xAODs, so this will not be a real issue for us.

Best,
Miha

**Comment by kratsg** [comment]
Nothing from PATHelp?

**Comment by MihaMuskinja** [comment]
No, there was no answer after we posted the instructions on how to reproduce the crash in the "AssociationUtils bug?" thread.

**Comment by kratsg** [comment]
Go ahead and ping them again. It must've fallen by the wayside.

**Comment by jdandoy** [comment]
I believe this was an issue with ElectronSelector that was fixed by #738 .  Please reopen this if it was not fixed.

**Comment by alexandertuna** [comment]
Hello old friends, especially @fscutti 

Was VeryLoose exonerated? Can this be added back to ElectronSelector?

**Comment by kratsg** [comment]
Hi @alexandertuna : @fscutti kicked it out in this MR: https://github.com/UCATLAS/xAODAnaHelpers/commit/dcb82e7f2b4c3d3482f2d9fe6ebc68f33e1c566a

I think it's just a matter of uncommenting one of the lines related to VeryLoose? File an issue.

**Comment by alexandertuna** [comment]
Hi @kratsg -- yeah, he definitely kicked it out. I was wondering if it caused the problem, or if it was just a red herring. I'll happily file a MR if it wasn't actually the problem.

**Comment by kratsg** [comment]
@alexandertuna it's probably a red herring, you can probably add it back in. I think @jdandoy fixed it :)

**Comment by alexandertuna** [comment]
Party. PR soon.

**Comment by fscutti** [comment]
Hi @alexandertuna, the VeryLoose working point was causing an exception with my ntuples. I'm a simple man and I commented it. But that's a very old issue and if it's working for you please uncomment those two lines. Peace.

**Comment by alexandertuna** [comment]
Thank you benevolent @fscutti. It works for me on two different versions of DAOD, so I feel comfortable making the PR (https://github.com/UCATLAS/xAODAnaHelpers/pull/992).
