### ISSUE TITLE
Alternative electron working points

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#679]
Dear developers,

what is the easiest way to add additional working points for electrons to the output ntuples? A concrete example would be isolation working points. Looking at the HelpTreeBase it seems that only two working points are defined for isolation:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L633
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L634

what should we do if we want to include additional isolation scale-factors to the output ntuples? There are 24 different isolation scale-factors:

http://atlas.web.cern.ch/Atlas/GROUPS/DATABASE/GroupData/ElectronEfficiencyCorrection/2015_2016/rel20.7/ICHEP_June2016_v3/isolation/

Best,
Miha

**Comment by kratsg** [comment]
I think the best thing is to follow the template for the current working points and add in the others through a pull request 😄

**Comment by MihaMuskinja** [comment]
Dear Giordon,

it is actually not so trivial to add isolation working points. The reason is that isolation scale-factors are a function of ID level and isolation, but the framework seems to be sensitive only to the isolation level.

Lets take this scale-factors as an example:

efficiencySF.Isolation.**LooseAndBLayerLLH**_d0z0_v11_**isolLoose**.root 

In the ElectronEfficiencyCorrector (https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L249) we can see that it would only read the isolation level from the string:

m_Iso_WP would be set to "IsoLoose" in the above case completely regardless of the ID level. m_Iso_WP is then used to decorate electrons (L302, L788, and L822).

This means that it is not trivial to write isolation scale-factors for two working points with the same isolation level (e.g. LooseAndBLayerLLH+isoLoose / MediumLLH+isoLoose) to the same output. However, this is what we would actually need in the output for the analysis.

Best,
Miha

**Comment by kratsg** [comment]
Hi @MihaMuskinja -- indeed. I'm not very familiar with this portion for electrons. Indeed, it seems like the following combinations exist:

```
Lord Stark:~$ pbpaste | cut -d ' ' -f 5 | cut -d '.' -f 3 | cut -d '_' -f1,4
LooseAndBLayerLLH_isolFixedCutLoose
LooseAndBLayerLLH_isolFixedCutTight
LooseAndBLayerLLH_isolFixedCutTightTrackOnly
LooseAndBLayerLLH_isolGradient
LooseAndBLayerLLH_isolGradientLoose
LooseAndBLayerLLH_isolLoose
LooseAndBLayerLLH_isolLooseTrackOnly
LooseAndBLayerLLH_isolTight
MediumLLH_isolFixedCutLoose
MediumLLH_isolFixedCutTight
MediumLLH_isolFixedCutTightTrackOnly
MediumLLH_isolGradient
MediumLLH_isolGradientLoose
MediumLLH_isolLoose
MediumLLH_isolLooseTrackOnly
MediumLLH_isolTight
TightLLH_isolFixedCutLoose
TightLLH_isolFixedCutTight
TightLLH_isolFixedCutTightTrackOnly
TightLLH_isolGradient
TightLLH_isolGradientLoose
TightLLH_isolLoose
TightLLH_isolLooseTrackOnly
TightLLH_isolTight
```

My guess is the easiest thing to do is have the output/factors associated with this use the name derived as a combination of the two inputs (ID level and isolation). Would this be a suitable approach? What would you like to see in the output, for example?

**Comment by MihaMuskinja** [comment]
Dear Giordon,

> use the name derived as a combination of the two inputs (ID level and isolation). Would this be a suitable approach?

Yes, this is exactly what I would expect to see in the output. Specifically, el_IsoEff_SF_Loose_LooseLH or something similar. I'm afraid that the same is true for trigger scale-factors as well.

This TWiki page explains the naming convention of the electron scale-factors: https://twiki.cern.ch/twiki/bin/view/AtlasProtected/LatestRecommendationsElectronIDRun2. This table portrays it most clearly:

![table](https://cloud.githubusercontent.com/assets/12948551/18786808/0cb62b4e-81a0-11e6-82d0-6dce4970dcd9.png)

I would expect that the output is formed in a similar way:

- only one branch for the reco SF (el_RecoEff_SF) OK as it is
- four branches for PID SFs: (el_PIDEff_SF_LHLoose, ..., el_PIDEff_SF_LHTight) OK as it is
- isolation SFs: el_IsoEff_SF_isoWP_PID WP
- trigger SFs: el_TrigEff_SF_isoWP_PID WP

Best,
Miha

**Comment by mmilesi** [comment]
Hi @MihaMuskinja ,

you're right, looks like the configuration needs to be updated.

I have started a new working branch that you can retrieve it and track with `git fetch origin && git checkout --track origin/work/IsolationAndIDSF` to add your changes on top of mine.

I added logic for parsing of the configuration file names to get the ID as well as the isolation WP, also for the Trigger SF (no need to pass it in the config dictionary anymore: the code just parses it from the config file name, as it already does for Iso and ID). Please have a careful look at what I did, in case similar stuff needs to be done in the future.  

The next step for you would be to read in `HelpTreeBase.cxx` the accessors for the various SF decorations. You can run the `ElectronEfficiencyCorrector` in debug mode for a handful of events to see the actual names of the decorators, and add stuff in the tree accordingly.

You will need to change the current accessor names a bit, but should be straightforward.

 BTW, if you can come up with a more clever way of storing the SFs in the tree rather than manually hardcoding the accessor names, please let us know ;-)

Let me know if there's something not clear.

Marco

**Comment by MihaMuskinja** [comment]
Dear @mmilesi,

thanks a lot for the new branch! I tested it out and it works perfectly! I was able to modify the HelpTreeBase.cxx to correctly write all the scale-factors to the output tree (I noticed that you also changed the PID decoration name so that it matches all the other names, e.g. LHLoose->LooseLLH):

![electroneffsf](https://cloud.githubusercontent.com/assets/12948551/18833618/dec8cd14-83f1-11e6-9ee0-32d3931d18f0.png)

> BTW, if you can come up with a more clever way of storing the SFs in the tree rather than manually hardcoding the accessor names, please let us know ;-)

I will think about it. Changing the accessor names and adding new accessors was quite a tedious work.

How should we deal with this in the future? As HelpTreeBase.cxx is a part of the xAODAnaHelpers, would we have to add this accessors every time there is a new update in the framework? I could maybe share the current version of my local HelpTreeBase.cxx (see output in screenshot) to add it to this working branch.

Best,
Miha

**Comment by mmilesi** [comment]
Hi @MihaMuskinja 

glad it works fine 😉 

As these SFs are of general interest (all analyses using electrons will use the same SFs, etc. ), we believe they should be stored in the output centrally by xAH, that is, in the `HelpTreeBase` class.

Changes sometimes are needed, but usually these additions do not happen that often. So I personally see no problems with adding the branches directly in xAH.

I agree it's quite tedious to hardcode all the decorations, but this is the situation atm...

Cheers

Marco

**Comment by MihaMuskinja** [comment]
Dear @mmilesi ,

I don't seem to have access:

`ERROR: Permission to UCATLAS/xAODAnaHelpers.git denied to MihaMuskinja.`

One more question regarding the SFs:

At the moment I only added accessors for isolLoose working point. What is your opinion on having all the working points in the output? This would mean 24 branches for iso SF, 48 branches for trig SF, 1 branch for reco SF, and 4 branches for PID SF. Would this be too much?

In this case I could also introduce a map object to not manually write 300 lines..

std::map< std::string, std::vector< std::vector< float > > > m_el_TrigEff_SF

Best,
Miha

**Comment by mmilesi** [comment]
Hi @MihaMuskinja ,

I think you need permissions to push into remote. @kratsg , what's the best way to share work with Miha?

The amount of branches to bookkeep it's not a problem per se: you could split the `m_elInfoSwitch` to be configurable with more options than just `m_effSF` as it is atm (could have something like `m_TrigEffSF, m_IsoEffSF ...` and so on to dump barnches selectively, and keep the current `m_effSF` if one wants to dump all the SFs. See [here](https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelperClasses.cxx#L134))

I was also thinking about maps. I guess it's the right direction to go.

Marco

**Comment by MihaMuskinja** [comment]
Dear @mmilesi and @kratsg ,

I have now implemented a local version where all of the combinations of isolation and trigger scale factors are stored to the output. I did not yet implement the m_elInfoSwitch, but I guess that we can do that later. 

![lotsofbranches](https://cloud.githubusercontent.com/assets/12948551/18848898/bf5b558e-8430-11e6-9356-be1774237e06.png)

I introduced three maps instead of 3x24 branches:
```
  std::map< std::string, std::vector< std::vector< float > > > m_el_IsoEff_SF;
  std::map< std::string, std::vector< std::vector< float > > > m_el_TrigEff_SF;
  std::map< std::string, std::vector< std::vector< float > > > m_el_TrigMCEff;
```
I tested locally that the output makes sense w.r.t. the ElectronEfficiencyCorrector tools. I also verified that the scale-factors are stored fore each individual object in case of multiple electrons per event.

I can push the branch if you give me the permissions. Could you please also verify that the code is acceptable? There is one technical point which I would like to discuss after you have the code..

Best,
Miha

**Comment by kratsg** [comment]
> I think you need permissions to push into remote. @kratsg , what's the best way to share work with Miha?

Fork us. Push it to your fork. Submit a pull request.

**Comment by mmilesi** [comment]
Hi @MihaMuskinja ,

okay, following Giordon's suggestion, you should do as explained here: https://xaodanahelpers.readthedocs.io/en/latest/Development.html (look at the "New User" section)

@kratsg : how do I access the forked repo which Miha will have made (just in case I need to add stuff to it)?

Marco

**Comment by kratsg** [comment]
> @kratsg : how do I access the forked repo which Miha will have made (just in case I need to add stuff to it)?

Two different ways.

1) Fork his fork, add stuff to your fork, request a merge request to his fork.
2) He can add you as a collaborator to his fork.

**Comment by MihaMuskinja** [comment]
Dear @mmilesi and @kratsg ,

I forked the repository and submitted a pull request. I hope I did everything correctly as I'm more or less new to git.

Best,
Miha

**Comment by MihaMuskinja** [comment]
Dear @mmilesi ,

I just noticed one additional difficulty regarding the naming convention of the scale factors. There are also scale-factors for working points without any isolation requirement, e.g.:

`efficiency.DI_E_2015_e12_lhloose_L1EM10VH_2016_e15_lhvloose_nod0_L1EM13VH.LooseAndBLayerLLH_d0z0_v11.root`   

These config files don't have the "isol" keyword in them. What should we do with them? All of the trigger SF files are here:

http://atlas.web.cern.ch/Atlas/GROUPS/DATABASE/GroupData/ElectronEfficiencyCorrection/2015_2016/rel20.7/ICHEP_June2016_v3/trigger/

Best,
Miha

**Comment by kratsg** [comment]
Allow for no isolation as well. Always look for the working point, but the isolation may be missing and set that to an empty string / null.

**Comment by mmilesi** [comment]
Hi @kratsg 
I will fix this on the `work/IsolationAndIDSF` branch and then make a PR

**Comment by mmilesi** [comment]
This should be fixed by #686 .

@MihaMuskinja

**Comment by MihaMuskinja** [comment]
Dear @mmilesi and @kratsg ,

in addition to the isolation and ID working points, trigger scale factors are also a function of the trigger.

> http://atlas.web.cern.ch/Atlas/GROUPS/DATABASE/GroupData/ElectronEfficiencyCorrection/2015_2016/rel20.7/ICHEP_June2016_v3/trigger/

Would it be possible to include this into the framework, as we would be interested in testing several different triggers?

I would actually manage to add this myself. Should I go for it and make a pull request?

Best,
Miha

**Comment by MihaMuskinja** [comment]
Dear @mmilesi and @kratsg ,

I started by implementing the "elInfoSwitch" compatibility for the new isolation and trigger scale-factors:

https://github.com/UCATLAS/xAODAnaHelpers/pull/716

Best,
Miha

**Comment by kratsg** [comment]
> we should still implement different branches for trigger SFs with different trigger, right?
> 
> e.g.:
> trig1_isolLoose_LooseID_SF
> trig2_isolLoose_LooseID_SF

**Comment by MihaMuskinja** [comment]
Hi all, @kratsg , @johnda102 , @mmilesi 

how should we go about this? The trigger names are rather long. We could extend the parse_wp helper function to also read the trigger name from the config file:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelperFunctions.cxx#L462

We could then extend the output name:

m_outputSystNamesIso = m_outputSystNamesIso + "_" + m_IsoPID_WP + "_isol" + m_Iso_WP;

This is all fine, but how should we name the output branches? Furthermore, how should we name these trigger in the ElectronInfoSwitch? 

> DI_E_2015_e12_lhloose_L1EM10VH_2016_e15_lhvloose_nod0_L1EM13VH
> DI_E_2015_e12_lhloose_L1EM10VH_2016_e17_lhvloose_nod0
> DI_E_2015_e17_lhloose_2016_e17_lhloose
> MULTI_L_2015_e7_lhmedium_2016_e7_lhmedium_nod0
> MULTI_L_2015_e12_lhloose_2016_e12_lhloose_nod0
> MULTI_L_2015_e17_lhloose_2016_e17_lhloose_nod0
> MULTI_L_2015_e24_lhmedium_L1EM20VHI_2016_e24_lhmedium_nod0_L1EM20VHI
> MULTI_L_2015_e24_lhmedium_L1EM20VHI_2016_e26_lhmedium_nod0_L1EM22VHI
> SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_e24_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0
> SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0
> TRI_E_2015_e9_lhloose_2016_e9_lhloose_nod0
> TRI_E_2015_e9_lhloose_2016_e9_lhmedium_nod0
> TRI_E_2015_e17_lhloose_2016_e17_lhloose_nod0
> TRI_E_2015_e17_lhloose_2016_e17_lhmedium_nod0
> e17_lhloose_L1EM15
> e17_lhmedium
> e17_lhmedium_nod0
> e17_lhmedium_nod0_L1EM15HI
> e17_lhmedium_nod0_ivarloose_L1EM15HI

**Comment by MihaMuskinja** [comment]
Closed by https://github.com/UCATLAS/xAODAnaHelpers/pull/733.
