### ISSUE TITLE
Multiple jet collections for non-fat/trigger jets in TreeAlgo

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#681]
Hi all,

following #544 I would like the non-fat/trig/truth jets to follow the fat jets path as in #644. It's still useful for downstream code to have trigJets and truthJets separately because they will need different detail strings. I don't think anyone will want ALL THE JETS ALL THE TIME but performance studies with trigger jets will need multiple trigger/multiple offline/one truth jet collection so might as well add this possibility. I'll try to implement this in the next few days. 

Caterina (& Edgar & Will)

**Comment by kratsg** [comment]
@urania277 did this get implemented? I vaguely remember. If so, can you link the PR?

**Comment by jbossios** [comment]
That would be what I added in #779 and #781.
