### ISSUE TITLE
Correct Weights for Sherpa 2.2 Samples

### ISSUE THREAD

**Issue by jdandoy** [UCATLAS/xAODAnaHelpers#689]
Sherpa 2.2 samples (Z+jets and W+jets) have a weighting issue, as documented at https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/CentralMC15ProductionList#Sherpa_v2_2_0_V_jets_NJet_reweig .  A fix has been provided by the PMG group that should be implemented.

**Comment by kratsg** [comment]
@jdandoy - if the mentioned PR has the fix, go ahead and close this. Thanks!

**Comment by jdandoy** [comment]
Addressed with #690
