### ISSUE TITLE
ERROR message from METConstructor

### ISSUE THREAD

**Issue by fscutti** [UCATLAS/xAODAnaHelpers#698]
Hi all,
I have updated my local copy a few days ago and, when running on data I have now the following warning and error messages:

METSystematicsTool        WARNING This tool should be applied to MC only.  Return without changing the input MET object
METConstructor::METCon... ERROR   Could not apply correction to soft clus met !!!! 

Nothing changed in my configuration which is [here](https://github.com/SameSignDiLepton/SSDiLepAnalysis/blob/master/scripts/config_FF.py) and I always used 2.4.18.

Any insight what could be causing this?

Cheers,
Federico

**Comment by mmilesi** [comment]
Hi @fscutti ,

looks like Marta has been working on that. 

@martaperego : can you please explain a bit what are the changes about? 
Btw: is it intentional to throw an "ERROR" message without stopping the code execution? Maybe a WARNING would be just enough.

**Comment by martaperego** [comment]
Hi @fscutti , @mmilesi, 

I added some modifications iin METConstructor.cxx in order to run the MET systematics (by using METSystematicsTool). 

I did't see that error. Do you see it also if you set "m_runNominal = True" ?

If so, maybe I should add a bool like "m_isMC" in order to use the METSystematicsTool only when running on MC. 
What do you think?

**Comment by fscutti** [comment]
Hi Marta,
I just rerun with my current version of xAH using m_runNominal = True on a data sample and the message still appear. As for the flag, yes I agree. Anything that would make the code understand when this correction is really needed. Btw, I am also getting a lot of 

xAOD::TStore::retrieve    WARNING Couldn't (const) retrieve "DataVector<xAOD::Photon_v1>/Photons"

is this really needed out of m_debug mode?

**Comment by fscutti** [comment]
I see there have been some updates in the code but after updating my branch I still see this error. Also the "Photons" one. 

@martaperego did you introduce the flag?

**Comment by martaperego** [comment]
@fscutti I have not yet added the flag
I will try to do it today

**Comment by martaperego** [comment]
Hi,  
I added the m_isMC bool in order to use METSyst tool only when running on MC, but I still didn't manage to submit a pull request because of problems with git. 
Meanwhile I have put here the updated METConstructor files: /afs/cern.ch/work/m/mperego/public/xAH_METConstructor_updates

**Comment by kratsg** [comment]
@martaperego what problems do you have? Your fork is behind and missing a few commits. You can't submit a pull request until you update all your files and then apply your changes. Like I said in email, you should rebase your changes and follow the tutorials I linked for doing so. This will both put your changes on top and update you.

**Comment by kratsg** [comment]
Hi all,

Point me to the fork so I can see what changes are made. We really need to get this merged in soon.

**Comment by martaperego** [comment]
Hi, 

I think that I sorted out the problems with git and I have submitted a pull request

**Comment by btcarlso** [comment]
Hi Marta, 
when you run on data, there are still the following warnings: 
HelperFunctions::getPr... WARNING No primary vertex was found! Returning nullptr
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics
	you are going to run using met systematics

Can you fix these warnings?

Ben

**Comment by martaperego** [comment]
Hi Ben, 

the 
"HelperFunctions::getPr... WARNING No primary vertex was found! Returning nullptr" 
warning is not related to xAH METConstructor.cxx, it is coming from line 829 of VBFInv Microtuple.cxx. 

Regarding the text message "you are going to run using met systematics", I just removed it from Microtuple.cxx. 

Marta

**Comment by btcarlso** [comment]
Thanks Marta, Good point... this issue is not in the MET constructor code. 

I think your fixes are fine. 

Ben

**Comment by kratsg** [comment]
So what's the status? Are things fixed?

**Comment by btcarlso** [comment]
Yes.

**Comment by kratsg** [comment]
This will be entirely fixed by #714.
