### ISSUE TITLE
Short question: di-electron trigger matching

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#708]
Dear developers,

I have a naive question about di-electron trigger matching. I see that di-electron trigger matching is implemented in the ElectronSelector:

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronSelector.cxx#L744

and it also has a decorator named "diElectronTrigMatchPairMap". However, this decorator is then never accessed in the code.

Is it meant that we implement this accessor in our analysis specific version of the code, or is there another reason why this is not used?

Many thanks,
Miha

**Comment by kratsg** [comment]
At the moment, it's just tacked on to the EventInfo. You can write your own algorithm that runs downstream (after ElectronSelector) which can just grab the relevant decoration off of EventInfo. There's not a huge need for it to be accessed normally though.

**Comment by MihaMuskinja** [comment]
Hi @kratsg ,

thanks for the answer. We will implemented if needed.

Best,
Miha
