### ISSUE TITLE
Remove/update protection on DFCommonElectronsLH decorations

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#709]
This is from @SteveFarrell, referring to https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronSelector.cxx#L1063-L1070

> There are these lines in xAODAnaHelpers ElectronSelector:
> 
> ```
>       // need this exception check b/c an interface change in DF happened at some point :(
>       try {
>         passSelID = electron->auxdataConst<int> ( "DFCommonElectronsLH" + m_LHOperatingPoint );
>       }
>       catch(std::exception& e) {
>         passSelID = electron->auxdataConst<char>( "DFCommonElectronsLH" + m_LHOperatingPoint );
>       }
> 
> ```
> Here's what I think is happening. The DFCommon decorations are not present because you're running on primary xAOD, so the first statement under "try" throws a ExcBadAuxVar which is caught and ignored. I'm guessing this results in the aux store registry mapping the name to type "int". In the second attempt with type "char", then, you get the ExcAuxTypeMismatch which results in program termination. Note the catch statement should be using the intended type of ExcAuxTypeMismatch, which could have made this a bit less confusing.
> 
> The fact that the auxdataConst call seems to add the decoration->type entry to the aux store registry even if the decoration doesn't exist is also a bad thing. I'm not sure why the aux store code would behave that way.
> 

Proposed solutions:
- remove these lines entirely
- update to use `isAvailable()` instead and get rid of the try/catch.

**Comment by kratsg** [comment]
Related to #677 .

**Comment by mmilesi** [comment]
Will be fixed by #738
