### ISSUE TITLE
Warnings about Taus when using taus in METConstructor

### ISSUE THREAD

**Issue by rzouCERN** [UCATLAS/xAODAnaHelpers#710]
When I set "m_inputTaus" = "TauJets" and "m_doTauCuts" = True in METConstructor, I got ridiculous amount of warnings and errors that are just repetitions of the following two lines:
TauSelectionTool.TauSe... ERROR   /build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/ElectronPhotonSelectorTools/Root/AsgElectronLikelihoodTool.cxx:528 (virtual const Root::TResult& AsgElectronLikelihoodTool::calculate(const Electron*, double) const): Failed, no cluster.
xAOD::TStore::retrieve    WARNING Couldn't (const) retrieve "DataVector<xAOD::TauJet_v2>/TauJets"

I was able to get rid of the error message by using a previous tag of ElectronPhotonSelectorTools that's used in Base,2.4.17. But I still got a lot of warnings that I'd much prefer to get only when I turn m_debug on (or not even then). Does anyone know how to fix this?

Thanks!

**Comment by kratsg** [comment]
Well, the first warning is because of the TauSelectionTool -- it seems that there are no clusters associated with your tau jet.

The second warning is actually a lot more crucial in that it is unable to find the "TauJets" container. Are you sure you named it right?

**Comment by rzouCERN** [comment]
No it's not named right.. Sorry for such stupid question.. Thanks a lot! Someone committed a bug in our baseline script...
