### ISSUE TITLE
Documentation of new user instructions

### ISSUE THREAD

**Issue by btcarlso** [UCATLAS/xAODAnaHelpers#719]
The instructions https://github.com/UCATLAS/xAODAnaHelpers/blob/master/docs/Development.rst 

have some missing lines for new users. In particular, it needs to be clear how users are supposed to:
1.) create a new branch
2.) commit 
3.) push the branch 

I suggested:
git checkout -b feature/EXAMPLE
git add
git push -u origin feature/EXAMPLE
I'll let Giordon decide what exactly he wants to tell new users...

**Comment by kratsg** [comment]
I just realized that you only need to make feature branches if you're working off of `origin` (UCATLAS) rather than your account. If it's your account, you do not need to make a feature branch.
