### ISSUE TITLE
xAH_run should check if RootCore.par exists

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#724]
This needs to be done when someone submits to condor using a non-shared filesystem for example. A lot of people mess this up by forgetting it or forgetting to make a recent one. Can either have it made automatically or just check and compare dates against some other files perhaps?

**Comment by matthewfeickert** [comment]
@kratsg Is this still needed for a CMake RC install? Following the [install directions in the docs](http://xaodanahelpers.readthedocs.io/en/master/Installing.html#cmake-based-rootcore-2-5-x) on LXPLUS results in a successful build, but then trying to submit to CERN's HTCondor batch service results in [the `CondorDriver` warning in `xAH_run.py`](https://github.com/UCATLAS/xAODAnaHelpers/commit/30ee07f29db078e43ddd575466b38a12c9472081). Do you have any ideas/thoughts on this?

**Comment by kratsg** [comment]
You can't use condor in release 21 just yet. Once this gets merged in: https://gitlab.cern.ch/atlas/athena/merge_requests/4077 -- then I can remove the check for rel 21.
