### ISSUE TITLE
inputEOS clean up

### ISSUE THREAD

**Issue by btcarlso** [UCATLAS/xAODAnaHelpers#729]
There may be an issue with XRD still, but at least scan EOS does work. However, the xAH_run.py is configured in a way that somehow does not work… 

If one replaces this line:
ROOT.SH.scanDir (sh_all, eoslist, args.inputTag); #Run on all files within dir containing inputTag   
with:
ROOT.SH.ScanDir().filePattern("*").scanEOS(sh_all,fname)
it works fine. 

This command can be used to run:
xAH_run.py  --files "/eos/atlas/user/b/bcarlson/data16/data16_13TeV.00298633.physics_Main.merge.AOD.f697_m1588/" --inputEOS --config RootCoreBin/user_scripts/VBFInv/vbf20p7.py --mode "athena"  --nevents 100 direct

**Comment by kratsg** [comment]
Perhaps we can get a pull request for this then?

**Comment by btcarlso** [comment]
Are you ok with the solution? It seems that this used to be the solution, then it was updated to something else.

**Comment by kratsg** [comment]
I am. I will prefer this solution. I need to think longer about making SampleHandler configuration more streamlined in the future.

**Comment by btcarlso** [comment]
Alright, I'll commit this method then.

**Comment by btcarlso** [comment]
See pull request #735.

**Comment by kratsg** [comment]
For future reference, just say "This closes #729" in your pull request message. It'll link it all and auto-close when merged.
