### ISSUE TITLE
Working point dependent filling of muon corrections

### ISSUE THREAD

**Issue by fscutti** [UCATLAS/xAODAnaHelpers#730]
Dear all,
for muons (and also electrons) we will soon need the possibility to include corrections for many triggers and combinations of reco+iso working points. For this reason, I have created a branch which I would like to merge. However, this is a relevant update so it is useful to review the changes here and see if you approve of them.

From now on, if a user configures the muon details string in this way:

`"m_muDetailStr"           : "kinematic trigger isolation quality trackparams effSF"`,

i.e. with effSF, all muon corrections branches for all triggers and combination of working points
will be created in the ntuple, which will only be filled if the corresponding decoration exists. 
This is a sketch of what the ntuple will look like:

![muon_allcorrections](https://cloud.githubusercontent.com/assets/16931625/19633437/812eb7b4-99fd-11e6-9d3e-a59f6ae276e5.png)

However, if the user will specify a set of working points as well, for either trigger, reco or iso, only those will be written out. As an example

`"m_muDetailStr"           : "kinematic trigger isolation quality trackparams effSF HLT_mu14_RecoMedium_IsoGradient RecoMedium IsoGradient"`
 will lead to:

![muon_corrections](https://cloud.githubusercontent.com/assets/16931625/19633292/8e1d5e82-99fb-11e6-948d-4a3902ce3f87.png)

Please notice that this change will allow also for di-muon trigger corrections, as they can  always be recalculated at the analysis level using corrections on the single trigger legs. So, 
the previous example will be perfectly suitable for say HLT_2mu14. 

I have to warn here that this update required the hardcoding of all trigger chains, reco and iso
working points, so a bit of maintenance will be necessary if new triggers will be added. 

At the level of MuonEfficiencyCorrector configuration, I have created a new attribute m_MuTrigLegs, which has to be filled with a comma-separated list of muon trigger legs, like in 

`"m_MuTrigLegs"      : "HLT_mu8noL1,HLT_mu24,HLT_mu14"`

which replaces both m_SingleMuTrig and m_DiMuTrig.

Shall I go ahead a issue a pull request?

Cheers,
Federico

**Comment by fscutti** [comment]
forgot to ping you guys... @mmilesi @kratsg @MihaMuskinja

**Comment by MihaMuskinja** [comment]
Hi all,

I'm doing something very similar for electrons.

> i.e. with effSF, all muon corrections branches for all triggers and combination of working points
> will be created in the ntuple, which will only be filled if the corresponding decoration exists.
> This is a sketch of what the ntuple will look like:

This is a good idea, we could use the same logic for electrons. Just to make sure, will other triggers be filled as well in this case? I can only see HLT_mu10 in the screenshot.

**Comment by fscutti** [comment]
yes all trigger branches will exist. unless one specifies one or more trigger chains (and corresponding reco+iso WP), then only those will appear

**Comment by mmilesi** [comment]
Ciao @fscutti ,

this plan looks very good. Can you start creating a PR, so we can look at the actual implementation (and comment on that if necessary)?

MArco

**Comment by fscutti** [comment]
done

**Comment by mmilesi** [comment]
@fscutti can this be closed?

**Comment by fscutti** [comment]
Closed #731
