### ISSUE TITLE
make BTag cut configurable, and add decorations of btagging WP for ALL jets 

### ISSUE THREAD

**Issue by mmilesi** [UCATLAS/xAODAnaHelpers#74]
I simply attach an old email thread we had.

1. At the moment, i see that if we specify in the configuration a certain Btag WP , say XXX,  (only for MV1 atm, which btw is not available in Dc14 as you most likely know...), then the selection decoration for a jet will become:

  ```
  passSelBTagXXX
  ```

  Wouldn't be better to have 2 separate flags: a 

  ```
  passSel
  ```

  flag, regardless of whether the jet is also b-tagged or not, and an additional flag

  ```
  passSelBTagXXX (or isBTagXXX)
  ```

  to identify jets that pass also the btag requirement?

  This is quite crucial: in fact, when the Overlap Removal tool is configured to look only at (pre)"selected" objects - as I am doing in my analysis - it assumes all objects: 

  - electrons
  - muons
  - jets
  - (taus)
  - (photons)

  share the same flag name for selected objects, i.e., `passSel`. If the jets have a different name for this flag, then it messes up the OR.

  > OK I can make it use `passSel` and `passSelBTagXXX`
 

2. Do we really wan to have a CUT on a jet if it doesn't pass a btag requirement ( as it is done now in the `PassCuts()` method )? Wouldn't the decoration just suffice?
  > At least, I will keep this cut configurable by the user.

**Comment by AndreaCoccaro** [comment]
I have been looking at the same thing, maybe from a slightly different perspective. I would opt for the possibility to apply different b-tag cuts on the same set of jets.

**Comment by johnda102** [comment]
Hello, 

  Implementing this now.  

  To the point of applying different b-tagging cuts on the same jets, it seems to me this easiest thing to do is configure multiple JetSelectors with differnet working points and call them on the same input jet collections: 

 eg: jetSel_InTracker (Takes AllJets applies |eta| < 2.5 outputs BTagCandidates collection)
       jetSel_VLoose (Takes BTagCandidates outputs BTagCandidates with passSelBTagVLoose decoration added)
     jetSel_Loose (Takes BTagCandidates outputs BTagCandidates with passSelBTagLoose decoration added) 
   ect. 

How do people feel about this ?

**Comment by kratsg** [comment]
Hi @johnda102 - how much overhead is done in initializing the tools? One of the things we might want to do is use `ToolStore::contains()` to see if the tool doesn't already exist in the tool store for btagging (for example). Then multiple algorithms shouldn't be a problem.

**Comment by mmilesi** [comment]
Hi John,

Have a look at what I did in ParticlePIDManager.h for the electron ID. You
might get some inspiration from that....;-)

Marco

**Comment by johnda102** [comment]
@mmilesi : will do

@kratsg:  the Selection doesnt init any tool for applying the cut. 
                for the BJetEfficiencyCorrector.cxx we will have to init separate BTaggingEfficiencyTool in any case

**Comment by kratsg** [comment]
@johnda102 -- multiple calls to the same tool with the same configurations should not be done if the tool exists in the toolstore though. We really don't want terrible memory leaks.

**Comment by johnda102** [comment]
@kratsg: OK maybe im confused. What tool with the same configuration are you worried about being called multiple times?  

Seems to me the only tool that needs configured multiple times is the BTaggingEfficiencyTool.  But this will be configured with differnet configurations (for the differnet operating points).

**Comment by kratsg** [comment]
@johnda102 -- let's say we want to tag two different jet collections at the same working point, then we have two tools with identical configurations, no? EG: the user creates two "tagging algorithms" configured with different jets.

**Comment by johnda102** [comment]
@kratsg: 
Lets say we want: 
     BTagTight on 20 GeV jets and
     BTagTight on 50GeV jets

Seems like we can do:
   JetSelection to make "PreTagCollection" w/eta in the tracker and Pt > 20 GeV
   JetSelection to do BTagTight on "PreTagCollection" 
         - to either set passSel flags or make "BTaggedCollection" collection
    Run BJetEfficiencyCorrector.cxx on "" (which sets scale factors) 
   JetSelction

**Comment by kratsg** [comment]
Ok, this makes a lot of sense :smile:

**Comment by johnda102** [comment]
@kratsg: 
Lets say we want: 
     BTagTight on 20 GeV jets and
     BTagTight on 50GeV jets

Seems like we can do:
   JetSelection to make "PreTagCollection" w/eta in the tracker and Pt > 20 GeV
   JetSelection to do BTagTight on "PreTagCollection" 
         - this can either set passSel flags or make "BTaggedCollection" collection
    Run BJetEfficiencyCorrector.cxx on "BTaggedCollection" (which sets scale factors) 
   JetSelctionPt50  on "BTaggedCollection" to make "BTaggedCollection50GeV"

(Now with out submitting too early)

**Comment by AndreaCoccaro** [comment]
Two comments:

- A possible scenario would be to apply two different b-tag working points on the same set of jets (a tighter cut on the leading jet and a looser cut on the sub-leading jet). I guess studies of the m_bb shape will determine the final strategy. How to accomodate this eventual possibility?

- My feeling would be that in this way the configuration is moved away from the conf data files and further changes to the configuration will be less user-friendly. What about trying to define all the working points in the config data file (one file per jet collection). The b-tagging cut in the `PassCuts` function in the `JetSelector` tool will have to be removed and a `PassBtagCuts` could be added taking as input not only the jet but also the working point. In this way it can be called several times per jet according to how many b-tag flags were activated.

My 2 cents :-)

**Comment by gfacini** [comment]
Where are we going here?  There are a lot of ways to skin this cat but I would like to list the use cases we can think of and design for ease of use in the bulk.

To understand your perspective, I have a few questions:

@johnda102 I don't get the example - You want 2 collections with the same b-tagging WP SFs but different pT cuts.  Why does the b-tagging tools need to worry about that case...it seems more like an ordering issue.   What kind of analysis selection is using something like this?

@AndreaCoccaro, right asymmetric tagging is something to consider but I don't understand the multiple PassBtagCuts?  What is the desired output?

What about continuous tagging - is that going to be commissioned early in Run II?

Gabriel

**Comment by johnda102** [comment]
@gfacini 
   The example addressed goirdons concern about running the same tagging operating point on two different Jet collections. Its easy to see how you can extend that logic however you define your two collections. (Maybe the use case of tagging two collections with the same operating point is not something we need to worry about...but goirdon rasied it and I showed how it could be dealt with) 

My plan is to follow whats done in the electrons. 

 If I understand the electrons correctly (@mmilesi  should correct this) we:
  - configure an ElectronSelector to Cut on one Pid value at a time (eg: Medium)
  - The ElectronSelector then sets the default values for all PIDs to -1 
  - The ElectronSelector then sets pass/fail for all PID values as tight or tighter than the one we configured.
(I assume if we wanted to seperate electron collections, one tight and one loose, we can configure two instances of the ElectronSelector and have them run on the same input collection)

Any reason not to do the same for BJets? 

This has the advantage of coherence and (I believe) has all the features @AndreaCoccaro wanted.
Im testing a local version, once I have this validated ill put a pull request in if there are no further complaints.

**Comment by mmilesi** [comment]
Hi @johnda102 ,

```
If I understand the electrons correctly (@mmilesi should correct this) we:

- configure an ElectronSelector to Cut on one Pid value at a time (eg: Medium)
```
Correct

```
- The ElectronSelector then sets the default values for all PIDs to -1
```
You do this with a call to, e.g.,  ElectronLHPIDManager:: setDecorations( electron ) in the selector. This is mandatory to avoid unexpected behaviour.

Take a closer look at ElectronSelector.cxx for a working example for this.

````
- The ElectronSelector then sets pass/fail for all PID values as tight or tighter than the one we configured. (I assume if we wanted to seperate electron collections, one tight and one loose, we can configure two instances of the ElectronSelector and have them run on the same input collection)
```
I am not sure about this. Do you want to save on TStore two different "selectedElectrons" xAOD containers ( one with electrons >= loose and one with electrons >=medium, for example)?

Marco

**Comment by johnda102** [comment]
Hi @mmilesi 

(How do you make fancy inline replies ?) 

" Do you want to save on TStore two different "selectedElectrons" xAOD containers ( one with electrons >= loose and one with electrons >=medium, for example)?"

--->  Yes, I would want eg: separate collections  "selectedElectronsTight" and "selectedElectronsLoose" 
(Or in my case "selectedBTagLoose" and "selectedBTagTight")  I could then make separate plots (or higgs candidates) using the different tagging weights by simply passing the different collections

**Comment by gfacini** [comment]
@johnda102 I understand now! Thanks =)
This sounds completely reasonable.

**Comment by mmilesi** [comment]
Hi @johnda102 ,

```
Yes, I would want eg: separate collections "selectedElectronsTight" and "selectedElectronsLoose" 
(Or in my case "selectedBTagLoose" and "selectedBTagTight") I could then make separate plots (or higgs candidates) using the different tagging weights by simply passing the different collections
```
In that case, this could be the easiest solution:

1. let's assume that  "medium electrons set" will always contain the "tight electron set" (which seems to be the case for electrons)
2. In ElectronSelector.cxx, after you have called passSel() in the loop on electrons (L536-560) - thus after rejecting all the electrons that don't pass the loosest WP you selected, and decorating the tighter ones -   at line 583  you could make a new loop on the "selectedElectrons" container, and push_back in a new "tightselectedContainer" only the ones for which the decoration "isTight" is true.  Make sure you have declared this new container somewhere upstream.
3. Save this new container to TStore, and you're done!

Does it make sense?

Marco

PS: for fancy inline contents, I copy-paste the previous comment, and wrap it within ```. See https://help.github.com/articles/markdown-basics/

Maybe @kratsg can add tips on this ;-)

**Comment by johnda102** [comment]
Hi @mmilesi 

  ```In ElectronSelector.cxx, after you have called passSel() in the loop on electrons (L536-560) - thus after rejecting all the electrons that don't pass the loosest WP you selected, and decorating the tighter ones - at line 583 you could make a new loop on the "selectedElectrons" container, and push_back in a new "tightselectedContainer" only the ones for which the decoration "isTight" is true. Make sure you have declared this new container somewhere upstream.```

To me it seems best to have separate Selectors configured for different PID points, than to hard code the multiple selections directly in the Selector.  eg: For 4b analysis we will probably want many different operating points.   In run1 we looked at ( L / M /T / not T / not M / (M not T) / (L not M) ) we probably dont want to have all these options hard coded for the general BTagger. But id be curious to hear what others think.

However, looking more into the code, I dont see any reason why we cant run the ElectronSelector multiple times

**Comment by mmilesi** [comment]
HI @johnda102 ,

Yes, you can definitely instantiate multiple selectors with different configurations in your steering macro, and pass them in sequence to the EL::Job. This is what I already do in my analysis btw.

I probably didn't fully get your point, apologies for that!

So, let me know if you have problems implementing the thing following what I have already done for electrons.

Marco

**Comment by kratsg** [comment]
> PS: for fancy inline contents, I copy-paste the previous comment, and wrap it within ```. See https://help.github.com/articles/markdown-basics/
> 
> Maybe @kratsg can add tips on this ;-)

So, to reply to something quickly, highlight the text and press "r". Replies are prefaced with `>` like emails. Code blocks use ```

**Comment by johnda102** [comment]
OK, here we stand on this.  

There is a new tag UpdateBJets that: 
   - Moves baseline tagger to MV2c20 in JetSelector
   - Applies btagging cuts if requested with DoBTagCut, 
   - Applies BTagXXX decoration in addition to passSel decoration for all jets if DoBTagCut is not set 
       and only for passing jets if DoBTagCut is set. 

The BJetEffeciency correction tool has not yet been updated.  It looks like we will need to use a local root file that is not in release.  Do we have a protocol for this ? should I just add this file to data ? There is talk that it may be added to cvms at some point. 

Shall I do a pull request ?

**Comment by kratsg** [comment]
@johnda102 -- you mean a new **branch** right? Yes. That looks good to me. How large is the local root file?

When you make the pull-request, you can add a "Fixes #74" in the message somewhere.

**Comment by johnda102** [comment]
@kratsg oops yes new branch.

New file is  625K

**Comment by kratsg** [comment]
That should be ok. I would be wary of adding anything more than 5 MB to the git repo. Go ahead and make the pull request, assign Marco to it, and if everyone is ok with it, we can merge.

**Comment by AndreaCoccaro** [comment]
@johnda102 I would say 2 weeks are needed before having the CDI file in a release. There is still some development to turn the pre pre-recommendation file into the pre-recommendation file and it's my understanding that only the latter will be injected in a release.

@kratsg the pre pre-recommendation CDI file should be less than 1 MB, there is still little information in there.

@gfacini continuons b-tagging will require some time for being usable in Run-II. It should be doable as long as we save the b-tag weight stored and not only the b-tag decision. I would say it also requires a rather different approach then mimicking the dijet efforts.

Thanks everyone!

**Comment by johnda102** [comment]
ok Updated BJetEffCorrection to new CDI file and submitted pull request. 

Let me know if there is anything needed form my side.

**Comment by AndreaCoccaro** [comment]
Good news, the CDI file with the b-tagging pre-recommendation is now in CVMFS. It will be announced soon. These are the needed changes, to my understanding...
   - update to xAODBTaggingEfficiency-00-00-16
   - UseDevelopmentFile should be set to False
   - new folders are created in CVMFS and as a consequence the file path should be "13TeV/2015-PreRecomm-13TeV-MC12-CDI-May19-v1.root”

Should we give it a try?

**Comment by AndreaCoccaro** [comment]
Good news, the CDI file with the b-tagging pre-recommendation is now in CVMFS. It will be announced soon. The needed changes should be:
   - update to xAODBTaggingEfficiency-00-00-16
   - UseDevelopmentFile to False
   - the file path "13TeV/2015-PreRecomm-13TeV-MC12-CDI-May19-v1.root” (note the new 13 TeV sub-folder)

Should we give it a try?

**Comment by kratsg** [comment]
Should @johnda102 make the necessary changes and add a new PR?

**Comment by gfacini** [comment]
Has this been tested throughly?   I am going to submit some xAODs soon for a few tests and could add this...let me know.

**Comment by johnda102** [comment]
Whats a PR ?

I agree we should move to getting the file form cvmfs, I can look into this later this week. 
(I guess there is no rush here as the trunk is functionally equivelent)

**Comment by gfacini** [comment]
PR = pull request
