### ISSUE TITLE
mcEventWeight is proportional to x-section?

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#744]
Dear developers,

I just noticed that mcEventWeight equals to 1940.8000 in our Powheg Z->ee sample, which is very close to the high-order cross-section of 1950.6321. Is it supposed to be proportional to the cross-section? Where in the xAH code does this happen?

Best,
Miha

**Comment by MihaMuskinja** [comment]
The same thing happens in Powheg W->enu samples. Here, the mcEventWeight equals to 11460.5, where the x-sec is supposed to be 11500.9154.

However, in some samples mcEventWeight is normal, meaning close to 1. I'm guessing that if the x-section exists in the DxAOD the mcEventWeight is somehow multiplied by it and this obviously doesn't happen when the x-section is not present in the DxAOD.

**Comment by kratsg** [comment]
Most cross sections are defined here: https://github.com/UCATLAS/xAODAnaHelpers/tree/master/data/metadata

I don't actually see a problem on my end. What variables are you looking at and where?

**Comment by MihaMuskinja** [comment]
Ah, so is the mcEventWeight supposed to be multiplied by the x-sec? We assumed that this was the actual mc event weight and multiplied everything with the x-sec on top of that.

Our current findings are the following:
Powheg Zee (361106) mcEventWeight ~ 1950
Powheg W+jets (361100) mcEventWeight ~ 11500
Sherpa VV->llll (361063) mcEventWeight ~ 1

Is the x-sec for 361063 not present in the metadata?

**Comment by MihaMuskinja** [comment]
> What variables are you looking at and where?\

I'm talking about the output ntuples. The "mcEventWeight" branch in the "nominal" tree.

**Comment by kratsg** [comment]
> Is the x-sec for 361063 not present in the metadata?

https://github.com/UCATLAS/xAODAnaHelpers/search?utf8=%E2%9C%93&q=361063

**Comment by kratsg** [comment]
> Ah, so is the mcEventWeight supposed to be multiplied by the x-sec? We assumed that this was the actual mc event weight and multiplied everything with the x-sec on top of that.

No. https://github.com/UCATLAS/xAODAnaHelpers/blob/210f6c0f250bfb5ea312384d39df7da95aeb085a/Root/EventInfo.cxx#L228 It's just whatever is on the eventInfo object. It's not getting re-weighted.

**Comment by MihaMuskinja** [comment]
I find it extremely weird that the mcEventWeight equals to cross-section in some of our ntuples. Do you know why this would happen? It really doesn't make sense that mcEventWeight equals to 11500 in the W+Jets sample and equals to 1 in the VV->llll sample.

There actually seem to be some hints in the code:

https://github.com/UCATLAS/xAODAnaHelpers/blob/fdddf36f6267c14bbd76034f9440038c2ddcc53b/xAODAnaHelpers/IParticleHistsAlgo.h#L63

**Comment by kratsg** [comment]
https://github.com/UCATLAS/xAODAnaHelpers/blob/7d7117dcfd944a0cc8211363d6d2368d76d55ec7/Root/BasicEventSelection.cxx#L695-L727

- not really. This seems to show it's decorating it correctly. Can you not dump the original event weight before any of this just to verify?  This can make the plots of the distribution for you: http://kratsg.github.io/xAODDumper/

**Comment by MihaMuskinja** [comment]
Hi @kratsg ,

thanks for linking the xAODDumper. I used it to print the mcEventWeight of this sample:

mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_EXOT12.e3601_s2576_s2132_r7725_r7676_p2823

Surprisingly, the mcEventWeight is very large. This is exactly what we see in our ntuples.
[mcEventWeights.pdf](https://github.com/UCATLAS/xAODAnaHelpers/files/567410/mcEventWeights.pdf)

**Comment by kratsg** [comment]
> Surprisingly, the mcEventWeight is very large. This is exactly what we see in our ntuples.

So then this is not an issue with xAH, correct?

**Comment by MihaMuskinja** [comment]
Correct, sorry for false alarm. The mcEventWeight is ineed that same as in the DxAODs.

**Comment by johnda102** [comment]
Im also seeing issues of the mcEventWeight implausibly small:

Event wieght 7.05977e-07 (sometimes -7.05977e-07)
for mc15_13TeV.410007.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_allhad.merge.DAOD_EXOT8.e4135_s2608_s2183_r7725_r7676_p2719

whereas a previous processing of the same nTulple had event wieghts of 1.

Something odd is going on...not sure if its on our end.

**Comment by kratsg** [comment]
> mc15_13TeV.410007.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_allhad.merge.DAOD_EXOT8.e4135_s2608_s2183_r7725_r7676_p2719

Can you use my dump script and see what the weights are on the input DAOD first?

**Comment by johnda102** [comment]
I see the following from the metadata: 

BasicEventSelection::f... INFO    Meta data from this file:
BasicEventSelection::f... INFO    Initial  events  = 30000
BasicEventSelection::f... INFO    Selected events  = 25736
BasicEventSelection::f... INFO    Initial  sum of weights = 0.020928
BasicEventSelection::f... INFO    Selected sum of weights = 0.017947

which is consistent with tiny weights ill try dumping directly

**Comment by MihaMuskinja** [comment]
Hi all,

if the initial sum of weights is multiplied by this same weird factor, than this effect will cancel out itself during the normalization of MC samples. Is this really the case though?

**Comment by johnda102** [comment]
With help for @kratsg Ive dumped the input mcEventWeights which seems to have different values:

![image](https://cloud.githubusercontent.com/assets/7108106/19945076/ce8cddf6-a114-11e6-87e3-109519684db4.png)

Something is a miss...

**Comment by mattleblanc** [comment]
@MihaMuskinja it's not clear that this would cancel out for all samples, as some samples (e.g. Pythia dijets) are normalised differently than others. So we need to know exactly what's going on ...

@johnda102 have you checked the weights for a different derivation? It might be good to check one that isn't from Exotics ...

**Comment by johnda102** [comment]
@MihaMuskinja  yes scaling by some of weights gives the right order of mangitude. 

But Im worried that there is a deeper problem

Ill try another derivation

**Comment by kratsg** [comment]
> @MihaMuskinja it's not clear that this would cancel out for all samples, as some samples (e.g. Pythia dijets) are normalised differently than others. So we need to know exactly what's going on 

Are you really sure the same prescription doesn't apply to dijets? Dijets still get normalized because at the end of the day, it's the combination of nevents and sum of weights that combine for your normalization.

**Comment by MihaMuskinja** [comment]
I get the same plot as @johnda102 for mc15_13TeV.410007.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_allhad.merge.DAOD_EXOT8.e4135_s2608_s2183_r7725_r7676_p2719 .

[mcEventWeights.pdf](https://github.com/UCATLAS/xAODAnaHelpers/files/567581/mcEventWeights.pdf)

Just to be sure - was the ntuple which shows tiny weights made from exactly the same DxAOD?

**Comment by mswiatlo** [comment]
Miha’s right, dijets don’t get normalized by sum of weights.

On Nov 2, 2016, at 3:14 PM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:


@MihaMuskinja<https://github.com/MihaMuskinja> it's not clear that this would cancel out for all samples, as some samples (e.g. Pythia dijets) are normalised differently than others. So we need to know exactly what's going on

Are you really sure the same prescription doesn't apply to dijets? Dijets still get normalized because at the end of the day, it's the combination of nevents and sum of weights that combine for your normalization.

**Comment by johnda102** [comment]
@MihaMuskinja I ran over the ntuple that I used to the dump the mcEventWeight pdf

**Comment by MihaMuskinja** [comment]
There is a TWiki page which states that the cross-section can be encoded in the event weight for Powheg: https://twiki.cern.ch/twiki/bin/view/AtlasProtected/NegativeWeightPowheg#Powheg_cross_sections

> ... as the cross-section is instead encoded in the average event weight.

So far we only observed this effect for Powheg samples..

**Comment by johnda102** [comment]
So I downloaded the raw xAOD and I see;
![image](https://cloud.githubusercontent.com/assets/7108106/19946281/07ff3174-a11a-11e6-8d98-9b1d9ccae382.png)

**Comment by johnda102** [comment]
OK very confused. 

Look back a previous ntuple making in same base release different version of xAH (but no changes to BasicEventSelection (git diff hh4b-02-00-02 hh4b-02-00-00 --name-only) I see all event weights are one.  Both when printing out mcEventWeight and based on the metadata.

**Comment by kratsg** [comment]
But that's with a different dataset and ptag?

**Comment by MihaMuskinja** [comment]
It was a false alarm on my side. These Powheg samples were supposed to have mcEventWeight equal to the cross-section. The initial sum of events is also multiplied accordingly so there is no problem.

**Comment by johnda102** [comment]
I see 
    mcEventWeight = 1.0 in xAOD
    mcEventWeight: sometimes =1 sometimes ~0 in DAOD
    mcEventWeight always  ~0 from xAH

**Comment by kratsg** [comment]
Just to clear things up:

- most (if not all) but dijets will have the cross-section incorporated into mcEventWeight in such a way that you normalize them properly using the sum of the weights
- dijet samples need to be normalized using the total number of events

So @johnda102, why do you not expect the weights to be the way they are for that ttbar sample? Is it because they should all be one, and not zeros anywhere?

**Comment by johnda102** [comment]
@kratsg see above.

**Comment by johnda102** [comment]
ok think I understand what going on a little better.

heres the bottom line from my side.
   - xAOD and the latest DOAD ptag (p2719 ) are NOT consistent 
     (With a previous tag _p2666 they were) 

   - Wthh new p2719 xAH is consistent with cutbookkeepers and dumping the DAOD directly. 
       (It looked inconsistent at first b/c there are multiple mcEventWieghts but we only care about at(0) )

   - So something changed between p2719 and p2666 at the derivation level. 
        I guess this has somethign to do with including the cross sections in the mcevent wieght
