### ISSUE TITLE
Update To 2.4.22

### ISSUE THREAD

**Issue by jdandoy** [UCATLAS/xAODAnaHelpers#752]
This requires [several changes](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/AnalysisBaseReleaseNotes24) from the current 2.4.18 release. 

 * [x] [Pileup Tool](https://its.cern.ch/jira/browse/ATLASG-833) - no longer uses default channel !!!
 * [x] Updates to [IMETMaker](https://its.cern.ch/jira/browse/ATLASG-801), #750 
 * [ ] ~~Update everything to [asg::AnaToolHandle](https://its.cern.ch/jira/browse/ATLASG-726)~~
 * [ ] ~~[MuonEfficiencySelector](https://its.cern.ch/jira/browse/ATLASG-820)~~ 

Development is ongoing in branch [Update2.4.22](https://github.com/UCATLAS/xAODAnaHelpers/tree/Update2.4.22).

**Comment by jdandoy** [comment]
Hi @fscutti @mmilesi @kratsg ,

Most of the necessary changes to bump up to 2.4.22 have been made.  There have been large changes to the muon efficiency tool, and in order to get things quickly running I had to gut the functionality.  Particularly the removal of applyRecoEfficiency, which [no longer](https://its.cern.ch/jira/browse/ATLASG-820) exists and has been replace by applyMCEfficiency and applyDataEfficiency.  I'm not sure yet which is more appropriate, but we should probably implement both of them.  However some quick checks show that both crash for me.  

If one of you wants to look quickly in the next day we can perhaps quickly edit this and commit it.  Otherwise I'm inclined to push the current status regardless, with the understanding that the efficiencies are not saved in the trunk, so that non-sensitive analyses can use the latest packages (especially concerning MET).  We can then fix MuonEfficiencyCorrector in parallel.  Thoughts on this?

**Comment by kratsg** [comment]
File an issue on the crash and then we'll go back on to it. I don't have time to look into it early this week.

**Comment by mmilesi** [comment]
Hi @jdandoy ,

as for the *lepton reconstruction* correction, I think what matters most people for analysis is the scale factor only ( aka eff_data/eff_mc ), which is to be applied to MC.

Sometimes though it can be useful to get the info on the efficiencies themselves, e.g., when one needs to calculate a per-event *trigger* correction (see the discussions we already had about that).

In principle, given the MC efficiency and the SF one can get the data efficiency taking the product of the two. The systematics should be given only for the SF. So I'd say that `applyMCEfficiency()` and `applyEfficiencyScaleFactor()` is all the info one needs. I am not sure why they give also `applyDataEfficiency ` : I guess only for convenience. 

If someone else has more insight, please chime in.

Cheers

Marco

**Comment by fscutti** [comment]
Hi @jdandoy,
I can look into the MuonEfficiencyCorrector update. What kind of crash do you have when using either applyMCEfficiency or applyDataEfficiency? Looks like we might need at least one of these two anayway.

Cheers,
Federico

**Comment by jdandoy** [comment]
@fscutti  The errors I get when using applyMCEfficiency are like
```
EfficiencyScaleFactor     ERROR   Could not find pt-dependant histogram for variation central and muon with pt=53916.8164, eta=-0.75 and phi=-2.99
EfficiencyScaleFactor     ERROR   Could not apply the Monte Carlo efficiency
MuonEfficiencyCorrecto... WARNING Problem in applyMCEfficiency
```

However, these errors don't seem to crash the code ( as I thought they did yesterday), so I'll add this back in.  However things are still probably wrong after the new update, so we need to take a close look at this code.  Can we push regardless and then work on this?

**Comment by fscutti** [comment]
Hi @jdandoy,
sooner or later we'll need to update, so yes I am in favor of pushing your preliminary changes. However, can you post somewhere your config for me to replicate this?

**Comment by jdandoy** [comment]
These errors come when running on the generic ttbar (410000) sample, with the following muon efficiency configuration:

```
    "m_name"                  : "muonEfficiencyCorrector",
    "m_debug"                 : False,
    "m_inContainerName"       : "Muons_Selected",
    "m_inputAlgoSystNames"    : "Muons_Selected_Syst",
    "m_systNameReco"          : "",
    "m_systNameIso"           : "",
    "m_systNameTrig"          : "",
    "m_systNameTTVA"          : "",
    "m_Years"                 : "2015,2016",
    "m_runNumber2015"         : 276329,
    "m_runNumber2016"         : 300345,
    "m_useRandomRunNumber"    : True,
    "m_outputSystNamesReco"   : "MuonEfficiencyCorrector_RecoSyst",
    "m_outputSystNamesIso"    : "MuonEfficiencyCorrector_IsoSyst",
    "m_outputSystNamesTrig"   : "MuonEfficiencyCorrector_TrigSyst",
    "m_outputSystNamesTTVA"   : "MuonEfficiencyCorrector_TTVASyst",
    "m_calibRelease"          : "160630_ICHEP",
    "m_WorkingPointReco"      : "Loose",
    "m_WorkingPointIso"       : "GradientLoose",
    "m_WorkingPointRecoTrig"  : "Loose",
    "m_WorkingPointIsoTrig"   : "GradientLoose",
    "m_WorkingPointTTVA"      : "TTVA",
    "m_MuTrigLegs"            : "HLT_mu26_imedium,HLT_mu50",
```

**Comment by jdandoy** [comment]
When do you think you can look over this @fscutti ?

**Comment by fscutti** [comment]
Hi @jdandoy, in ~10 hours. sorry for the delay.

**Comment by fscutti** [comment]
Hi @jdandoy,
I was having a look at the code and I also see the same error when trying to decorate the muon with the applyMCEfficiency or applyDataEfficiency. However, I notice we never saved these eff in the ntuple but just the SF for reco, iso and TTVA. On the other hand, the methods getDataEfficiency and getMCEfficiency for a "manual" decoration of the muon, don't seem to give any error message but don't provide meaningful efficiencies. 

As we always saved SF AND efficiencies only for the trigger and not for these additional corrections, I suggest we just discard those for the moment. I will investigate with the authors of the tool but this should not stop analyses for now. What do you think?

**Comment by jdandoy** [comment]
@fscutti I agree that I am not using these numbers, so as long as no one else does (by getting the auxdata in their algorithm) then I'm fine with removing these lines and washing our hands of it.
