### ISSUE TITLE
MuonEfficiencyCorrector is Broken in 2.4.22

### ISSUE THREAD

**Issue by jdandoy** [UCATLAS/xAODAnaHelpers#755]
This needs to be updated following changes listed [here](https://its.cern.ch/jira/browse/ATLASG-820).

**Comment by btcarlso** [comment]
If the muon efficiency corrector is being updated, can we also update the code to provide the per-event SF as described in #739 ?

**Comment by fscutti** [comment]
Hi @btcarlso,
can you provide a scenario where the info in the ntuple is insufficient as of now?

**Comment by kratsg** [comment]
Any updates on this?

**Comment by fscutti** [comment]
As all information we dump in the ntuple is sufficient to compute any per-event SF I'll close this one.
