### ISSUE TITLE
Introspection to read m_derivationName in BasicEventSelection

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#763]
Can we auto config m_derivationName based on the CutBookkeeperContainer content ?
I assume so. 
This would remove lots of crashes when chaning input files and forgetting to change config. 

Any downside ?

**Comment by kratsg** [comment]
Should be possible. We should use a variable separate from `m_derivationName` for that stuff. Or create a new one called "m_overrideDerivationName" so that if it's specified, it overrides whatever automated introspection seems to get.

**Comment by kratsg** [comment]
Thanks!
