### ISSUE TITLE
Use uncrustify to clean up C++ code

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#770]
This helps us get consistent formatting and style across the board: http://uncrustify.sourceforge.net/

One will need to figure out a way to automatically do this from time to time. Perhaps after every single pull request is merged in (every commit to master basically), uncrustify is run to generate a patch which is opened as a pull request back into master for testing.

**Comment by kratsg** [comment]
Idea: set up a server that listens for a webhook to trigger uncrustify. Then have that run through and generate a patch file like in the [following pre-commit-hook](https://github.com/githubbrowser/Pre-commit-hooks/blob/master/pre-commit-uncrustify). After that, if the patch file is non-empty, we need to somehow attach the patch or open a pull request on github with it -- with changes to be made.

Not clear how to do the second part yet.

**Comment by ntadej** [comment]
Personally, I use clang-format for the same purpose for my code. I think uncrustify should be analogous to use. I think that making some server infrastructure might be an overkill. What I did for some of my projects:
 - decide on formatting and commit the config file to the repo
 - run once through whole codebase and insure it still builds/works properly
 - make something that each developer can setup on their computer - then every commit should be OK
    - setup the editor to automatically run formatting on save
    - create a pre-commit hook that is run for each developer locally

I know this involves getting other people to do something but in my experience, this is just a two step process in modern editors - install formatter and editor plugin + enable it.

**Comment by jbossios** [comment]
Closing since the idea was dropped (implemented but then reverted).
