### ISSUE TITLE
[Help Wanted] Is it possible to run PRW tool in 2.4.22+ without the PRW config files

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#775]
Dear all,

since the upgrade to 2.4.22: https://github.com/UCATLAS/xAODAnaHelpers/pull/754, we were under the impression that it is not possible to run the framework without PRW config files for each sample.

However, the TWiki page states that it is still possible to do that:
> A default configuration file is also provided, but is not recommended for use in any publication. It is available through the pathresolver, at the path: dev/PileupReweighting/mc15c_v2_defaults.NotRecommended.prw.root

instinctively, we tried to insert this path to the PRW tool like shown below and the framework successfully ran through the MC sample. Is this the correct way of using the "default" channel now? Is anybody else doing this?

```
#"m_PU_default_channel"         : 410000,
"m_PRWFileNames"               : "dev/PileupReweighting/mc15c_v2_defaults.NotRecommended.prw.root",
```

Best,
Miha

**Comment by kratsg** [comment]
@jmrolsson would know

**Comment by mswiatlo** [comment]
This ought to work.

On Jan 18, 2017, at 2:47 PM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:


@jmrolsson<https://github.com/jmrolsson> would know

**Comment by MihaMuskinja** [comment]
Hi @kratsg , it works, this can be closed. Thanks!
