### ISSUE TITLE
MetaData Crash and Burn

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/xAODAnaHelpers#80]
Hey Guys,

This line in fileExecute

https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BasicEventSelection.cxx#L303

uses the m_histEventCount histogram but that histogram is not initialized until histInitialize
which is called after fileExecute.  How does this not crash for you?

Gabriel

**Comment by mmilesi** [comment]
Hi Gabriel,

From this morning, we started using a new tag of EL, where the order of
call of histinitialize and fileexecute is inverted.

Check it out by running the python patch script for 2.3.12

Marco

**Comment by gfacini** [comment]
Hi Marco,

Thanks! Do we have anywhere it written how to check out the package and what scripts needs to be run for it to work?  Maybe in the Readme?

Cheers,
Gabriel

**Comment by kratsg** [comment]
@mmilesi -- I would suggest updating the README to contain current instructions with:

- current release used
- how to checkout
- grab packages if needed

**Comment by gfacini** [comment]
I updated the Readme
