### ISSUE TITLE
Update the b-tagging efficiency tool

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#807]
The b-tagging tool needs to be updated to 2017 Moriond recommendations: https://twiki.cern.ch/twiki/bin/view/AtlasProtected/BTagCalib2015#Recommendation_February_2017 .

Namely, the CDI file needs to be replaced with the new one (or is this configurable in the user code?):
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BJetEfficiencyCorrector.cxx#L55

**Comment by kkrizka** [comment]
You can configure the CDI file via an attribute. You need to set
`m_corrFileName = "xAODBTaggingEfficiency/13TeV/2016-20_7-13TeV-MC15-CDI-2017-01-31_v1.root"`

**Comment by MihaMuskinja** [comment]
Thanks! Will do.

**Comment by kratsg** [comment]
We should probably defer to user configuration.
