### ISSUE TITLE
All `m_debug` output should use `Debug()` and not `Info()`

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#82]

**Comment by johnda102** [comment]
What do we need to include to get Debug() ?

 member function ‘virtual EL::StatusCode BJetEfficiencyCorrector::execute()’:
/share/home/johnda/Analysis/xAODAnaHelpersDev/xAODAnaHelpers/Root/BJetEfficiencyCorrector.cxx:298:55: error: ‘Debug’ was not declared in this scope
  Debug( "execute", "New Jet eta = %f",  jet_itr->eta());

**Comment by kratsg** [comment]
@johnda102 Good question -- I assumed TObject had it: https://root.cern.ch/root/html/TObject.html

This is where `Info` and `Error` come from.

**Comment by johnda102** [comment]
ok then I close it.
 (Checkout the new pic!)

**Comment by kratsg** [comment]
We still want to implement this! Just differently. I'm going to see what PATHelp says. 

Nice pic :horse:

**Comment by kratsg** [comment]
In fact, this is what will happen. In `Algorithm.h` we will implement a `Debug()` function that takes in a variable number of arguments and auto-checks for `m_debug` as well

http://www.cplusplus.com/reference/cstdio/vsprintf/

```
#include <cstdio>

void Error (char* location, char * format, ...)
{
  char buffer[256];
  va_list args;
  va_start (args, format);
  vsnprintf (buffer, 255, format, args);


  //do something with the error

  va_end (args);
}
```

but something a bit more clever, etc.

**Comment by kratsg** [comment]
@johnda102 

> Hi Rolf,
>
>I didn't know about this feature of Boost, it's not a bad idea to keep in mind. But...
>
>Giordon, I myself want to set up my own analysis code as follows:
> - Create the EL::Algorithm classes with relatively little code. These classes inherit from TObject, and hence, should just use ROOT's messaging. I would just avoid debug and verbose printouts in there completely.
> - The algorithms would call on external classes to do most of their work. Classes that inherit either from asg::AsgTool, or asg::AsgMessaging.
>
>https://svnweb.cern.ch/trac/atlasoff/browser/Control/AthToolSupport/AsgTools/trunk/AsgTools/AsgTool.h
>https://svnweb.cern.ch/trac/atlasoff/browser/Control/AthToolSupport/AsgTools/trunk/AsgTools/AsgMessaging.h
>
>The first one allows you to write a dual-use tool in case your code should be easily usable from Athena as well, and the second one is more for the case where the code doesn't need to be dual-use, but you want to be able to write lines like:
>
>```
>ATH_MSG_DEBUG( "A debug message" );
>ATH_MSG_VERBOSE( "A verbose message" );
>```

**Comment by kratsg** [comment]
this is not going to be worth adding.
