### ISSUE TITLE
More memory leaks

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#824]
Hi @kratsg ,

unfortunately, our jobs are still failing due to excess memory usage. I looked for some more leaks, this time only in "execute()" step of the framework:

- https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/HelpTreeBase.cxx#L290

m_muonInfoSwitch is never deleted.
I suggest to add "delete m_muonInfoSwitch" in HelpTreeBase::~HelpTreeBase().

- https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetCalibrator.cxx#L460

This is never deleted I believe. I'm not even sure if this object is used at all.
I suggest to possibly delete lines 460 and 461.

- https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L647

These are still leaking as m_store->record( sysVariationNamesPID, m_outputSystNamesPID ) is still encapsulated in an "if" sentence:
```
  // Do it only if a tool with *this* name hasn't already been used, and has been previously initialised
  //
  if ( !m_corrFileNamePID.empty() && !isToolAlreadyUsed(m_pidEffSF_tool_name) ) {
```
I suggest to move each of them in the corresponding IF sentence as they are not used anywhere else.

**Comment by MihaMuskinja** [comment]
@johnda102 , @kratsg 

unfortunately still crashing :(

http://aipanda054.cern.ch//media/filebrowser/d37fb366-7268-4595-880b-e1bd775cf297/panda/tarball_PandaJob_3265275261_ANALY_UIO/memory_monitor_output.txt

4GB ram.

**Comment by kratsg** [comment]
I'm not sure what else is leaking memory. I looked through and don't see anything missing.

**Comment by fscutti** [comment]
Hi @MihaMuskinja, can you link here the most up to date log file as given by xAH for a case with the leak? Also, could you run the TreeAlgo, calibration and selection algorithms with  "m_verbose" : True?

**Comment by MihaMuskinja** [comment]
Hi @fscutti . Just to explain how we are running the framework: we have 4 types of systematics:

- electron calibration
- electron efficiency
- muon calibration
- muon efficiency

calibration systematics result in a separate TTree for each sys and efficiency systematics are added into the scale-factor std::vector.

In my latest jobs I turned off both muon calibration and muon efficiency systematics and the jobs are still failing. Example job:  http://bigpanda.cern.ch/job?pandaid=3266609864

logfile ends with:
```
BasicEventSelection::e... INFO    Entry number = 28000
BasicEventSelection::e... INFO    Entry number = 29000
 out particle not valid 
 out particle not valid 
 out particle not valid 
 out particle not valid 
Caught exception while executing algorithm:
std::bad_alloc
Finished executing root
Wed Mar  8 05:24:40 CET 2017
```

IMO it is problematic that efficiency systematics are ran also for each calibration sys while they are needed only in the nominal configuration.

**Comment by kratsg** [comment]
What is the ` out particle not valid ` line from? And if you turn off the electron stuff, it still crashes? I think you need to run the efficiency systematics for each calibration systematic to get an uncertainty on the systematic still.

**Comment by MihaMuskinja** [comment]
Hi @kratsg ,

this is from our user code: https://github.com/SameSignDiLepton/SSDiLepAnalysis/blob/b107acace86114910e2f10b5e7f26187ae687882/Root/TruthMatchAlgo.cxx#L613 it could probably be suppressed.

About the calib/eff systematics: we are using HistFitter for the statistical analysis and we only need up/down histograms for each sys uncertainty. HistFitter is actually not able to handle two variations at once (e.g. Sagita bias + trigger eff). Could you please point out a case where one would need eff systematics on top of calibration systematics or a tool that can handle this? Furthermore, all of the eff systematics were calculated with the nominal calibration and I'm not sure if it is actually valid to use them both at once.

**Comment by MihaMuskinja** [comment]
Turning off all efficiency systematics while keeping the calibration systematics seems to solve the problem:

calib+eff: http://bigpanda.cern.ch/task/10914299/  (fails)
only calib: http://bigpanda.cern.ch/task/10915993/  (does not fail)

However, this could now be something else than a leak although the error in the first job is:

> pilot, 1212: Payload ran out of memory trans, 220: Proot: An exception occurred in the user analysis code

logfile ends with bad_alloc which could also indicate a bad pointer?
```
BasicEventSelection::e... INFO    Entry number = 28000
BasicEventSelection::e... INFO    Entry number = 29000
 out particle not valid 
 out particle not valid 
 out particle not valid 
 out particle not valid 
Caught exception while executing algorithm:
std::bad_alloc
Finished executing root
```

**Comment by kratsg** [comment]
Bad alloc means running out of memory. Might need to ask on pathelp

**Comment by MihaMuskinja** [comment]
Hi @kratsg ,

the jobs go through with calibration sys only without any efficiency systematics. Is it possible to run the jobs with efficiency systematics only for the nominal calibration? I would like to avoid submitting the jobs twice.

**Comment by kratsg** [comment]
You can add another algorithm in your chain to run this at the same time and save these outputs in a different name.

**Comment by btamadio** [comment]
I am having the same issue with grid jobs failing due to memory usage:
http://bigpanda.cern.ch/task/10936241/
http://aipanda037.cern.ch:25080/cache/jedilog/10936241

**Comment by fscutti** [comment]
Hi @btamadio, are you using electrons and/or muons? What is your configuration and have you updated to the last xAH version?

**Comment by MihaMuskinja** [comment]
Hi @btamadio, this looks like a problem with the sites. It could be that all of the sites containing this dataset are blacklisted atm:

> mc15_13TeV:mc15_13TeV.361028.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ8W.merge.DAOD_EXOT3.e3569_s2576_s2132_r7772_r7676_p2688_tid08910095_00

 is unavailable at any site

**Comment by btamadio** [comment]
@MihaMuskinja @fscutti I ran the jobs without systematics, and they completed with no errors.

**Comment by fscutti** [comment]
Hi @btamadio, we are currently running some tests to see if these memory leaks go away with the very latest version of xAH. In this version systematic uncertainties for muon efficiencies are only considered in the nominal tree and not in the systematically altered ones. If you ran with calibrations systematics and efficiency ones with the latest configuration and see these leaks I would worry. Otherwise, I suggest you update xAH and try a new test. For clarity, can you point us to your configuration file?

**Comment by MihaMuskinja** [comment]
Hi @fscutti, @btamadio, @kratsg, @johnda102

I ran a large production of jobs with systematics with the newest version of xAH and in some cases the issue remains:

examples:
http://bigpanda.cern.ch/jobs/?jeditaskid=11004343&jobstatus=failed&display_limit=100
http://bigpanda.cern.ch/jobs/?jeditaskid=11004322&jobstatus=failed&display_limit=100
http://bigpanda.cern.ch/jobs/?jeditaskid=11004326&jobstatus=failed&display_limit=100

Error is always

> pilot, 1212: Payload ran out of memory trans, 220: Proot: An exception occurred in the user analysis code

And the logfile ends with

> BasicEventSelection::e... INFO    Entry number = 30000
> BasicEventSelection::e... INFO    Entry number = 31000
> Caught exception while executing algorithm:
> std::bad_alloc
> Finished executing root
> Tue Mar 21 17:41:08 CET 2017

> BasicEventSelection::e... INFO    Entry number = 29000
> BasicEventSelection::e... INFO    Entry number = 30000
> Caught exception while executing algorithm:
> std::bad_alloc
> Finished executing root
> Tue Mar 21 12:24:25 UTC 2017

What can we do to solve this issue?  It would probably help to do the same as in https://github.com/UCATLAS/xAODAnaHelpers/pull/832 for ElectronEffCorrector.

**Comment by kratsg** [comment]
> What can we do to solve this issue? It would probably help to do the same as in #832 for ElectronEffCorrector.

Yes. I think so.



> Another solution would be to cap the number of max events per job. At the moment we have one job per sub-file. Is it possible to set the max event limit?

Yes. This should be possible, but might need to ask on PATHelp which option, because I believe others have complained about this before that it wasn't working.

**Comment by fscutti** [comment]
Hi @MihaMuskinja and @kratsg, uniforming the muon end electron correctors was already in the pipeline. I'll start working on that asap.

**Comment by kratsg** [comment]
@fscutti poking on this, are we done?

**Comment by MihaMuskinja** [comment]
Hi @kratsg @ntadej ,

we are now running ntuples with even more systematics than before and so far there are no failures related to memory leaks. However, we rely on electron SF systematics not being run for each calibration systematic and have this cherry picked: https://github.com/UCATLAS/xAODAnaHelpers/pull/856 . I believe that Tadej is upgrading the elecron Eff code to work without deep copies...

**Comment by kratsg** [comment]
Ok, thanks! We'll close this when all the fixes are in.
