### ISSUE TITLE
Name of the JVT tool needs to be set (m_JVT_tool_name)

### ISSUE THREAD

**Issue by MihaMuskinja** [UCATLAS/xAODAnaHelpers#827]
Hi @kkrizka , @kratsg ,

I think that the m_JVT_tool_name string must be set as it is "" by default. This is done e.g. for electronEffTool in initialize:
```
m_TrigEffSF_tool_name = "ElectronEfficiencyCorrectionTool_effSF_Trig_" + m_WorkingPointTrigTrig + "_" + m_WorkingPointIDTrig;
RETURN_CHECK("ElectronEfficiencyCorrector::initialize()", checkToolStore<AsgElectronEfficiencyCorrectionTool>(m_TrigEffSF_tool_name), "" );

```
The problem is that the SFs are not calculated if the name is not set due to this "if" sentence:
```
if ( !isToolAlreadyUsed(m_JVT_tool_name) ) {
```

**Comment by MihaMuskinja** [comment]
Adding the three lines below helps, but then the SF computation crashes for me..
```
  m_JVT_tool_name = "JetJvtEfficiency_effSF_" + m_name;
  RETURN_CHECK("ElectronEfficiencyCorrector::initialize()", checkToolStore<CP::IJetJvtEfficiency>(m_JVT_tool_name), "" );
  m_JVT_tool_handle.setTypeAndName("CP::JetJvtEfficiency/" + m_JVT_tool_name);
```

Error:
```
JetSelector::executeSe... INFO    --------------------------------------
JetSelector::executeSe... INFO    Applying JVT SF
JetSelector::executeSe... INFO    ===>>>
JetSelector::executeSe... INFO     
JetSelector::executeSe... INFO    Jet 2, pt = 194.42 GeV, |eta| = 1.80
JetSelector::executeSe... INFO     
JetSelector::executeSe... INFO    JVT SF decoration: JetJvtEfficiency_JVTSyst_JVT_Medium
JetSelector::executeSe... INFO     
JetSelector::executeSe... INFO    Systematic: 
JetSelector::executeSe... INFO     
JetSelector::executeSe... INFO    JVT SF:
JetSelector::executeSe... INFO    	 1.000000 (from getEfficiencyScaleFactor())
JetSelector::executeSe... INFO    --------------------------------------
JetSelector::executeSe... INFO    Applying JVT SF
--------------------
An exception was caught!
Traceback (most recent call last):
  File "/afs/cern.ch/work/g/gorisek/miha/analysisFramework/RootCoreBin/bin/x86_64-slc6-gcc49-opt/xAH_run.py", line 597, in <module>
    driver.submit(job, args.submit_dir)
Exception: void EL::Driver::submit(const EL::Job& job, const string& location) =>
    SG::ExcBadAuxVar: Attempt to retrieve nonexistent aux data item `::isJvtHS' (101). (C++ exception)
worker finished:
Real time 0:00:17, CP time 14.770

========================================
```

**Comment by MihaMuskinja** [comment]
Answer from jet-wg : 

> Hi Miha,
> You need to have the isJvtHS decoration, which that method uses,
> 
> to do this, you need to do this beforehand,
> 
> 142       const xAOD::JetContainer *truthJets = nullptr;
> 143       if( evtStore()->retrieve(truthJets, "AntiKt4TruthJets").isFailure()) {
> 144           ATH_MSG_WARNING("Unable to retrieve AntiKt4TruthJets container");
> 145       }
> 146       if(tagTruth(jets,truthJets).isFailure()) {
> 147         ATH_MSG_WARNING("Unable to match truthJets to jets in tagTruth() method");
> 148       }
> 
> 
> or alternatively use this method for the whole jet container,
> https://svnweb.cern.ch/trac/atlasoff/browser/Reconstruction/Jet/JetJvtEfficiency/tags/JetJvtEfficiency-00-00-13/Root/JetJvtEfficiency.cxx#L140
> 
> Best,
> Mariyan

Can we do this in xAH?

**Comment by kkrizka** [comment]
Hi @MihaMuskinja ,

I'm a bit confused, why is the manual determination of PU vs HS jets needed? The [JVTCalibration](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JVTCalibration#JetJvtEfficiency_Tool_Usage) twiki claims:

> The tool internally access AntiKt4TruthJets to do the HS-PU matching.

**Comment by MihaMuskinja** [comment]
Hi @kkrizka ,

this is true only for the "global SF mode":

> This assumes that the jet container passed to the tool contains signal jets after Overlap Removal (if your analysis applies OR) but before applying JVT. N.B. The tool internally access AntiKt4TruthJets to do the HS-PU matching. The container must be available in your derivation. 

We are not passing the entire jet container to the tool but rather single jets. It would not make sense to loop over the entire truth jet container for each jet. We also got an official answer that we should add these decorations by hand

**Comment by MihaMuskinja** [comment]
It also says this on the TWiki page:

> The key difference with respect to the method described in the previous section is that you need to take care of selecting HS jets in your analysis code prior to retrieving efficiency and inefficiency scale factors.

**Comment by kkrizka** [comment]
Seems like I should have read the whole twiki. Thanks!

**Comment by MihaMuskinja** [comment]
Hey @kkrizka, it doesn't actually say to decorate jets with this name. It is a bit strange that they have to be decorated with an exact name. I think the nominal use is to filter HS jets in the user code and than turn off truth filter in the JVT tool. Anyway, both cases are equal.

**Comment by MihaMuskinja** [comment]
Hi @kkrizka , @kratsg,

this currently crashes for data, as there is no truth jet containers in data. I will submit a PR..
