### ISSUE TITLE
Subset of Trigger Decisions in Ntuple

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#86]
Hi All, 

   I just pulled the head and it looks like the functionality to save a subset of passing triggers has been removed.  Is this by design ? Or am I misreading ?  

   Seems like this functionality would be very nice in keeping the output small.  (esp bc the decisions are saved as vector<string>)

**Comment by kratsg** [comment]
When did it exist? What file?

**Comment by johnda102** [comment]
HelpTreeBase.cxx

```
 auto chainGroup = m_trigDecTool->getChainGroup( m_triggerSelection );
    for (auto &trigName : chainGroup->getListOfTriggers()) {
      auto trigChain = m_trigDecTool->getChainGroup( trigName );
      // Only save the trigger if it passed.                                                                                                             
      if (trigChain->isPassed()) {
        m_passTriggers.push_back   ( trigName );
      }
    }
```

**Comment by kratsg** [comment]
It looks like @gfacini removed it here: https://github.com/UCATLAS/xAODAnaHelpers/commit/3b00fc4b13600850bb8a61bf0d3afdf23ceb5585#diff-536048c8c92cb3373780d12a4b75a621L307

**Comment by johnda102** [comment]
Nevermind.  I see the functionality moved to BasicEventSelection. 

CLOSED

**Comment by gfacini** [comment]
Hi,
There was some difficulty in having more than one trigger tool created so this was the easiest solution on the given timescale.  Please let me know if you find it inadequate.
Gabriel

**Comment by johnda102** [comment]
I think (if I understand correctly) we did loose one degree-of-freedom that we might want. 

Previously we could cut on one triggerGroup (eg: L1_J50)  and save the decisions for another (eg: L1_.*) 
Now these are constrained to be the same

**Comment by gfacini** [comment]
Yes, you understand correctly.  Do you think this is a huge lose?  For trigger efficiency measurements this should be fine since you need a series of subsequently tighter triggers.  Maybe you have a use case where this is choice makes a huge difference?  We can add an additional cut!

**Comment by johnda102** [comment]
I think its fine for now.
