### ISSUE TITLE
No duplicated tools being made

### ISSUE THREAD

**Issue by kratsg** [UCATLAS/xAODAnaHelpers#88]
AsgTools released an update that allows for us to check if a tool already exists. This helps cut down on memory leaks. SUSYTools has implemented it here:

https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/SUSYPhys/SUSYTools/trunk/Root/SUSYToolsInit.cxx#L29

``` c++
    if( asg::ToolStore::contains<JetCalibrationTool>( "JetCalibTool" ) ) {
      m_jetCalibTool = asg::ToolStore::get<JetCalibrationTool>("JetCalibTool");
    } else {
        ....
```

**Comment by gfacini** [comment]
This would be useful to get the trigger config and trigger decision tool in HelpTreeBase instead of passing information through EventInfo

**Comment by kratsg** [comment]
@gfacini It would definitely be. The best way to do that is to allow for a "tool name" configuration option or just simply a boolean and set the tool name to be a global identifier like `xAH_TriggerConfig` and `xAH_TDT` to keep it uniform and obvious.

**Comment by mmilesi** [comment]
@gfacini , @kratsg  this is also super useful for doing trigger object matching (see #110 ) as the trigger matching tools need the TrigDecisionTool as a parameter at configuration.

**Comment by kratsg** [comment]
This is now superseded by AnaToolHandles. I've detailed this procedure here: http://xaodanahelpers.readthedocs.io/en/latest/Development.html#adding-and-initializing-tools.

The short of it is 

```c++
  m_JetCalibrationTool_handle.setName("JetCalibrationTool_" + m_name);
  ATH_MSG_DEBUG("Trying to initialize " << m_JetCalibrationToolHandle.typeAndName());
  if( !m_JetCalibrationTool_handle.isUserConfigured() ){
    ANA_CHECK( m_JetCalibrationTool_handle.setProperty("JetCollection",m_jetAlgo));
    //... other setProperty() calls and other logic can be in here for tool configuration
    ANA_CHECK( m_JetCalibrationTool_handle.setProperty("OutputLevel", msg().level()));
  }
  ANA_CHECK( m_JetCalibrationTool_handle.retrieve());
  ATH_MSG_DEBUG("Successfully initialized " << m_JetCalibrationToolHandle.typeAndName());
```

where the `isUserConfigured()` will check if a tool of that type+name has been created before or not. If it has not been created before, we can set properties on them. Regardless of whether we set properties or not, the `retrieve()` is a "create or get" meaning it will either create the tool if it does not exist, or just get the existing instance of the tool.
