### ISSUE TITLE
Typo w/ jet constituents

### ISSUE THREAD

**Issue by mattleblanc** [UCATLAS/xAODAnaHelpers#891]
A tiny bug was just pointed out to me in the jet constituents code --

https://github.com/UCATLAS/xAODAnaHelpers/blob/f14adc3284ec611e873f5db0aa8e416e45c872cc/Root/JetContainer.cxx#L1335

`pt` is filled instead of `phi` here.

I'll fix it this afternoon when I get a chance and make sure this is the only place it occurs ... just making a note of it here to keep track.

**Comment by kratsg** [comment]
Introduced in this commit: https://github.com/UCATLAS/xAODAnaHelpers/blame/38dd8179e19cd38a2ef80cbd9b4fe8d86e69b26d/Root/JetContainer.cxx#L1335 . Good catch. That's not easy to catch at all!

**Comment by mattleblanc** [comment]
Bob Kowalewski here at UVic caught it -- he's definitely got better eyes than I do.
