### ISSUE TITLE
 asg::ToolStore::contains not picking up tools set by tool handle

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#897]
on master 

added following lines to BasicEventSector after retrieving the trigDecTool

 std::cout << "Name is " << m_trigDecTool_handle.typeAndName() << std::endl;;
  std::cout << "asg check " << asg::ToolStore::contains<Trig::TrigDecisionTool>( "" )<<  std::endl;
  std::cout << "asg check1 " << asg::ToolStore::contains<Trig::TrigDecisionTool>( "Trig::TrigDecisionTool" )<<  std::endl;
  std::cout << "asg check2 " << asg::ToolStore::contains<Trig::TrigDecisionTool>( "Trig::TrigDecisionTool/Trig::TrigDecisionTool" )<<  std::endl;

the name of the tool created by the handle seems not to be picked up on the toolstore.

**Comment by kratsg** [comment]
```
std::cout << "Name is " << m_trigDecTool_handle.typeAndName() << std::endl;;
std::cout << "asg check " << asg::ToolStore::contains<Trig::TrigDecisionTool>( "ToolSvc." )<< std::endl;
std::cout << "asg check1 " << asg::ToolStore::contains<Trig::TrigDecisionTool>( "ToolSvc.Trig::TrigDecisionTool" )<< std::endl;
std::cout << "asg check2 " << asg::ToolStore::contains<Trig::TrigDecisionTool>( "ToolSvc.Trig::TrigDecisionTool/Trig::TrigDecisionTool" )<< std::endl;
```

Try this instead.
