### ISSUE TITLE
MuonEfficiencyCorrector.cxx  pileup tool handle inconsistent with basiceventselctor 

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#898]
Not sure whats happening here

Tried removing the line
m_pileup_tool_handle.setTypeAndName("CP::PileupReweightingTool");                                                                                          

also doenst work

**Comment by johnda102** [comment]
This is still failing for me in master


From BasicEventSelectionI see:

> basicEventSel.retrieve...INFO    Trying to initialize CP::PileupReweightingTool/CP::PileupReweightingTool
> ...
> basicEventSel.retrieve...INFO    Successfully initialized CP::PileupReweightingTool/CP::PileupReweightingTool

In MuonCalibrator I get:

> Muons.retrieve<xAOD::E...FATAL   /share/home/johnda/Analysis/TestxAHhh4b/xAODAnaHelpers/Root/MuonCalibrator.cxx:137 (virtual EL::StatusCode MuonCalibrator::initialize()): A configured  must have been previously created! Are you creating one in xAH::BasicEventSelection?
> EventLoop:/build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/EventLoop/Root/Worker.cxx:44:exception: Algorithm::initialize returned StatusCode::FAILURE

Looks like the declare statements are different in 
MuonCalibrator.h
BasicEventSelection.h

Do these need to be identical ?

**Comment by kratsg** [comment]
> Looks like the declare statements are different in
> MuonCalibrator.h
> BasicEventSelection.h

Yes. I must have missed that. The type isn't set in MuonCalibrator for some reason! I'll add a fix.

**Comment by kratsg** [comment]
> Muons.retrieve<xAOD::E...FATAL /share/home/johnda/Analysis/TestxAHhh4b/xAODAnaHelpers/Root/MuonCalibrator.cxx:137 (virtual EL::StatusCode MuonCalibrator::initialize()): A configured must have been previously created! Are you creating one in xAH::BasicEventSelection?

Note that this message tells all. "A configured <> must have been" -- means it wasn't recognizing that the type/name was set at all!
