### ISSUE TITLE
xAH job submission utils

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#94]
Spoke briefly with Gabe and Jeff about this. 

Every mother's son using xAH is asking me how to submit to the grid using xAH.  DiJet/Multijets have this setup nicely but this common submission code is duplicated in the individual derived analysis packages instead of in the xAH core.  To avoid duplication, I  suggest creating a header file in xAH where the common tasks are implemented as functions that can be called by the analysis level packages, which would then be shared by various user packages. 

So the end will be something like 
> cat MyPkg/util/runMyPkg.cxx

setupJob(...) //  Defined in in xAH

MyAlg* m_alg1 = new MyAlg(...) // Defined in MyPkg
job.AddAlg(m_alg1)
// .... Add a bunch more algs maybe some from xAH...

submitJob(...) //  defined in xAH

**Comment by kratsg** [comment]
I've had folks successfully submit to grid using `xAH_run.py --grid` option. So I'm not 100% sure what the suggestion is, just an example script that people can copy and use?

**Comment by gfacini** [comment]
@johnda102 @kratsg 
I believe the idea is to have a common thing to build the output container name etc and
all that other junk that is needed to submit a job but looking at xAH_run.py there is already
a lot there.  Maybe @johnda102 or @jdandoy  you can test that script and see if it is sufficient
and/or suggest improvements/additions?
Gabriel

**Comment by kratsg** [comment]
An example of testing it can be done with this package: https://github.com/UCATLAS/xAODPerfTools which depends on xAH. I am going to be testing grid submission myself, so there will be some commits to it soon that allow folks to use dataset names rather than local root files.
