### ISSUE TITLE
Update documentation for HelperFunctions::isAvailable

### ISSUE THREAD

**Issue by kpachal** [UCATLAS/xAODAnaHelpers#949]
Hi there, the documentation for the HelperFunctions::isAvailable function is out of date. It specifies:
```
      Example Usage:
      const xAOD::JetContainer* jets(0);
      // look for "AntiKt10LCTopoJets" in both TEvent and TStore
      HelperFunctions::isAvailable("AntiKt10LCTopoJets", m_event, m_store)
      // look for "AntiKt10LCTopoJets" in only TStore
      HelperFunctions::isAvailable("AntiKt10LCTopoJets", 0, m_store)
      // look for "AntiKt10LCTopoJets" in only TEvent, enable verbose output
      HelperFunctions::retrieve("AntiKt10LCTopoJets", m_event, 0, true)
```
when this in fact needs to be more like 
`isAvailable<xAOD::JetContainer>("....", .....)
`
Thanks to Giordon for a helpful email exchange -- this is now working fine in my code! But it would be great to see the documentation updated to match.

Thanks!
Kate

**Comment by kratsg** [comment]
Forgot to fix this, whoops.
