### ISSUE TITLE
Error when using 2.4.34

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#977]
I'm using the master (checked out today) with 2.4.34 and I'm getting the following error:

[^[[1m2017-08-01 20:54:25,229^[[0m][^[[1;37mINFO^[[0m   ]  Welcome to xAODAnaHelpers. Don't forget to read the documentation: https://xaodanahelpers.readthedocs.io/en/latest/. (^[[1mlogging.py^[[0m:9)
[^[[1m2017-08-01 20:54:25,233^[[0m][^[[1;37mINFO^[[0m   ]  Loading up your analysis dictionaries now, give us a second. (^[[1m__init__.py^[[0m:23)
Traceback (most recent call last):
  File "/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/v_2/RootCoreBin/bin/x86_64-slc6-gcc49-opt/xAH_run.py", line 17, in <module>
    import xAODAnaHelpers
  File "/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/v_2/RootCoreBin/python/xAODAnaHelpers/__init__.py", line 24, in <module>
    ROOT.EL.Algorithm()
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/6.04.16-x86_64-slc6-gcc49-opt/lib/ROOT.py", line 447, in __getattr2
    raise AttributeError( name )
AttributeError: EL

This is my JSON:

[
  { "class": "BasicEventSelection",
    "configs": {
      "m_name": "BasicEventSel",
      "m_truthLevelOnly": false,
      "m_applyGRLCut": true,
      "m_GRLxml": "$ROOTCOREBIN/data/xAODAnaHelpers/data15_13TeV.periodAllYear_DetStatus-v79-repro20-02_DQDefects-00-02-02_PHYS_StandardGRL_All_Good_25ns.xml",
      "m_triggerSelection": "HLT_j360 | HLT_j260 | HLT_j200 | HLT_j175 | HLT_j150 | HLT_j110 | HLT_j85 | HLT_j60 | HLT_j55 | HLT_j45 | HLT_j35 | HLT_j25 | HLT_j15",
      "m_applyTriggerCut": true,
      "m_storeTrigDecisions": true,
      "m_applyEventCleaningCut": true,
      "m_applyCoreFlagsCut": true,
      "m_doPUreweighting": false,
      "m_applyPrimaryVertexCut": true,
      "m_vertexContainerName": "PrimaryVertices",
      "m_PVNTrack": 2,
      "m_checkDuplicatesData": true,
      "m_derivationName": "JETM9Kernel"
    }
  },

  { "class": "JetCalibrator",
    "configs": {
      "m_name": "JetCalib",
      "m_calibConfigData": "JES_MC15Prerecommendation_Rscan_Aug2015.config",
      "m_calibSequence": "JetArea_Residual_Origin_EtaJES_Insitu",
      "m_sort": true,
      "m_doCleaning": true,
      "m_redoJVT": true,
      "m_jetCleanCutLevel": "LooseBad",
      "m_saveAllCleanDecisions": true,
      "m_jetCleanUgly": false,
      "m_inContainerName": "AntiKt6LCTopoJets",
      "m_outContainerName": "AntiKt6LCTopoJets_Nominal",
      "m_jetAlgo": "AntiKt6LCTopo",
      "m_outputAlgo": "AntiKt6LCTopoJets_Nominal_Algo",
      "m_JESUncertConfig": "",
      "m_runSysts": false,
      "m_systName": "",
      "m_JERUncertConfig": ""
    }
  },

  { "class": "JetSelector",
     "configs": {
      "m_name": "JetSel",
      "m_inContainerName": "AntiKt6LCTopoJets_Nominal",
      "m_inputAlgo": "AntiKt6LCTopoJets_Nominal_Algo",
      "m_decorateSelectedObjects": true,
      "m_createSelectedContainer": true,
      "m_outContainerName": "AntiKt6LCTopoJets_Signal",
      "m_outputAlgo":  "AntiKt6LCTopoJets_Signal_Algo",
      "m_cleanJets": false,
      "m_pT_min": 30e3,
      "m_useCutFlow": true
    }
  },

  { "class": "TreeAlgo",
     "configs": {
      "m_name": "Tree",
      "m_jetContainerName": "AntiKt6LCTopoJets_Signal",
      "m_jetDetailStr": "kinematic rapidity energy trackPV clean scales",
      "m_trigDetailStr": "passTriggers",
      "m_evtDetailStr": "pileup"
    }
  }

]

Any idea what could be the problem?

Best,
Jona

**Comment by kratsg** [comment]
Hi Jona,

Yes, this is a bug. I will need to fix it.

Giordon

**Comment by kratsg** [comment]
The error is pretty much my fault in terms of logic -- in RootCore, dictionaries need to be imported/loaded manually.. in CMake -- it's automatically done.

**Comment by jbossios** [comment]
I see. Thank you for having a look at this!

Best,
Jona

**Comment by kratsg** [comment]
It's merged in now, so feel free to pull and it should be fine (no need to recompile).

**Comment by jbossios** [comment]
Thanks. I'm having the following error now:

An exception was caught! (^[[1mxAH_run.py^[[0m:566)
Traceback (most recent call last):
  File "/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/bin/x86_64-slc6-gcc49-opt/xAH_run.py", line 252, in <module>
    logger.info("Loading up your analysis dictionaries now, give us a second.")
NameError: name 'logger' is not defined

**Comment by kratsg** [comment]
> An exception was caught! (^[[1mxAH_run.py^[[0m:566)
> Traceback (most recent call last):
> File "/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/bin/x86_64-slc6-gcc49-opt/xAH_run.py", line 252, in 
> logger.info("Loading up your analysis dictionaries now, give us a second.")
> NameError: name 'logger' is not defined

Strange that I didn't catch it. Should definitely be fixed by now.

**Comment by jbossios** [comment]
It works fine now. Thank you for the fast fix!
