### ISSUE TITLE
Error Compilation in 2.4.34

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#980]
Hi 

I can not compile xAH with 2.4.34, I see the following error:
/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/xAODAnaHelpers/Root/Algorithm.cxx: In member function ‘StatusCode xAH::Algorithm::algInitialize()’:
/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/xAODAnaHelpers/Root/Algorithm.cxx:28:19: error: ‘name’ was not declared in this scope
     m_name = name();
                   ^
/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/xAODAnaHelpers/Root/Algorithm.cxx:28:19: note: suggested alternatives:
In file included from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/xAODJet/versions/Jet_v1.h:23:0,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/xAODJet/Jet.h:7,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/xAODJet/JetContainer.h:7,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/xAODAnaHelpers/xAODAnaHelpers/HelperFunctions.h:16,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/xAODAnaHelpers/Root/Algorithm.cxx:7:
/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/xAODJet/JetContainerInfo.h:85:17: note:   ‘xAOD::JetTransform::name’
     std::string name(Type t);
                 ^
In file included from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/AsgTools/MsgStreamMacros.h:8:0,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/AsgTools/Check.h:8,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/AsgTools/StatusCode.h:8,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/xAODAnaHelpers/xAODAnaHelpers/Algorithm.h:16,
                 from /afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/xAODAnaHelpers/Root/Algorithm.cxx:1:
/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/include/AsgTools/MsgLevel.h:47:23: note:   ‘MSG::name’
    const std::string& name( Level lvl );
                       ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-tautological-undefined-compare"
make: *** [/afs/cern.ch/work/j/jbossios/public/SM/Rscan_TestingInsitu/July2017/SM-IJXS-Dijets/SendJobs/RootCoreBin/obj/x86_64-slc6-gcc49-opt/xAODAnaHelpers/obj/Algorithm.o] Error 1
make: *** Waiting for unfinished jobs....
RootCore: Error failed to compile package xAODAnaHelpers

Setup:
setupATLAS
lsetup "rcSetup Base,2.4.34"
rc find_packages
rc compile

I'm using the master (downloaded minutes ago) in lxplus.

Best,
Jona

**Comment by kratsg** [comment]
@jbossios , not sure since we have this compiling in 2.4.33 right now:
 (https://github.com/UCATLAS/xAODAnaHelpers/pull/979) with documentation mentioning 2.4.33 (https://xaodanahelpers.readthedocs.io/en/master/Installing.html#compiling). Can you try with 2.4.33 first and see if this is fine? If so, I can start poking at differences between 2.4.33 and 2.4.34 after I check the segfault in the other issue.

**Comment by kratsg** [comment]
@jbossios - I just checked this: https://gist.github.com/kratsg/4c7b3549ec1b5a574e4a5a9641d096c7 

I have no problems compiling. What other packages are you checking out?

**Comment by jbossios** [comment]
Hi 

I tried again from scratch and now works fine for me, sorry for the noise.
