### ISSUE TITLE
EventLoop revert in 2.4.35 breaks xAH

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#986]
EventLoop revert in 2.4.35 breaks xAH for RootCore 2.4.X. This change is the issue: https://github.com/UCATLAS/xAODAnaHelpers/commit/e674439139d19cb8eb9e8cc940819172b044c1e3#diff-03acc6d941b78ce8004dc83c003bb1e1R27

**Comment by kratsg** [comment]
You should be reverting EventLoopGrid -- not EventLoop?

**Comment by ntadej** [comment]
No, I think the base EventLoop is the issue. I already revert EventLoopGrid due to submissions issue which does not affect xAH's Algorithm class.

**Comment by kratsg** [comment]
Wait, are you saying EventLoop was reverted in 2.4.35? Because the code we have in here is based on 2.4.33 -- not 2.4.35. Can you check if it's broken in 2.4.36?

**Comment by ntadej** [comment]
I was running 2.4.36. On twiki it still says "in validation" for EventLoop change in 2.4.35, but it's suspicious that it's failing for on that line after updating to the latest version.
https://twiki.cern.ch/twiki/bin/view/AtlasProtected/AnalysisBaseReleaseNotes24#ReleaseNotes35

**Comment by kratsg** [comment]
Please double-check the version of EventLoop (https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/D3PDTools/EventLoop/tags/EventLoop-00-01-65/EventLoop/Algorithm.h#L250) and this change was added 3 months ago: https://svnweb.cern.ch/trac/atlasoff/changeset/804871

**Comment by ntadej** [comment]
So it seems that in 2.4.35 and 2.4.36:
 - they forgot to revert EventLoopGrid as reported on mailing list (still at EventLoopGrid-00-00-54)
 - they reverted EventLoop to EventLoop-00-01-53, probably this was a mixup

**Comment by kratsg** [comment]
@AvivCukierman seems to be hit with this problem as well.

**Comment by ntadej** [comment]
They should revert the wrong change and fix everything in 2.4.37 which was built today. I will try tomorrow and report back.

**Comment by kratsg** [comment]
If 2.4.37 works, we can then submit a PR to bump that version for r20.

**Comment by AvivCukierman** [comment]
Seemed to work with AB 2.4.33, EL-00-01-55, and xAH-00-04-00.

**Comment by ntadej** [comment]
I can confirm everything works fine with 2.4.37. `EventLoopGrid` was reverted to version that last worked with 2.4.X. Also `EventLoop` is now also back on newer versions required by xAH. I think it's safe to bump the version in xAH.
