### ISSUE TITLE
Adding properties from newer releases more carefully

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#987]
Probably properties from newer releases should not be applied to the tool if `false` or set to default value. In this way, xAH change will not break use of one or two older analysis releases.

For example, #985 only works with 2.4.35 or later, but we are forced to stay at 2.4.33 due to JetJvtEfficiency issues.

**Comment by kratsg** [comment]
@ntadej can you elaborate? I'm a little lost on what breaks in 2.4.33.

**Comment by ntadej** [comment]
Sorry for the confusion. `DEVmode` option has only be added in 2.4.35, so that's why I made #989 for `JetCalibrator` backwards compatibility.

There were some changes in JetJvtEfficiency tool with systematics that I'm still investigating how to fix in xAH. fJVT systematics were separated but are now returned also for JVT. That's why I'm staying with 2.4.33 at the moment.

In the future this might happen again, a new analysis release would introduce a new flag, but someone would still want to keep using an older release. Also we want to keep 20.7 and 21.2 working in parallel and some options might only be available in the latter. I'm just saying that for simple changes, we should have some checks not to break backwards compatibility with a past version or two.

**Comment by kratsg** [comment]
Rel 20 and Rel 21 compatibility will be made on a best effort. When the scrutiny effort is done, rel 20 will most likely be left unsupported by xAH.

**Comment by ntadej** [comment]
Ok. Thank you for your input. Probably, when issues arise, I can always open a PR for backwards compatibility fix.
