### ISSUE TITLE
Muon quality inconsistency

### ISSUE THREAD

**Issue by ntadej** [UCATLAS/xAODAnaHelpers#995]
Muon quality is written out "strictly" - Medium quality muon is marked only as Medium and not also as Loose and VeryLoose. This is not consistent with electrons where all branches are always inclusive.

I can fix muon selector but this is a breaking change so maybe it needs to be discussed.

**Comment by kratsg** [comment]
I think this should be made inclusive and in this case, a breaking change is fine.

**Comment by alexandertuna** [comment]
Co-sign. Inclusive means less code to write for downstream users.
