### ISSUE TITLE
Electron trigger scale factor can't be retrieved unless electron trigger efficiency is also retrieved?

### ISSUE THREAD

**Issue by alexandertuna** [UCATLAS/xAODAnaHelpers#998]
c.f.: 
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/ElectronEfficiencyCorrector.cxx#L325

`m_WorkingPointTrigTrig` is an empty string unless `m_corrFileNameTrigMCEff` is supplied. If `m_WorkingPointTrigTrig` is an empty string, the downstream decorator will be pissed, and I can't access the scale factor even further downstream. But if I only care about a scale factor, and not the efficiency, then I have no reason to supply `m_corrFileNameTrigMCEff`.

Am I reading the code correctly? Is there a reason `m_corrFileNameTrigMCEff` is required here, instead of `m_corrFileNameTrig`? The file names are identical except one is "efficiencySF..." and the other is "efficiency...".

**Comment by alexandertuna** [comment]
@ntadej : did you notice this in the refactoring of ElectronEfficiencyCorrector?

**Comment by alexandertuna** [comment]
cc @MihaMuskinja, who I think added this in https://github.com/UCATLAS/xAODAnaHelpers/commit/99624483f00488fd532ee5f9067cc449479a436b ?

**Comment by ntadej** [comment]
@alexandertuna I haven't really touched that part of the code. I've fixed the typo now.

**Comment by alexandertuna** [comment]
The PR looks good. :shipit:

https://github.com/UCATLAS/xAODAnaHelpers/pull/999
